Repository spectrocloud/librarium, pull requests merged in 2020-12, with the labels that each got.

#247 Aws iam perm update
  packages/docs/content/04-clusters.md
Labels: ok-to-test, size/M

#254 Update 01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: ok-to-test, size/XS

#258 Update 15-faq.md
  packages/docs/content/15-faq.md
Labels: ok-to-test, size/XS

#253 Faq trblshtng 2
  packages/docs/content/02-getting-started.md
  packages/docs/content/03-cluster-profiles/2-task-update-profile.md
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/00-kubernetes.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
  packages/docs/content/14-troubleshooting.md
  packages/docs/content/15-faq.md
Labels: ok-to-test, size/L

#260 1.5.7 changes
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/15-faq.md
Labels: ok-to-test, size/S

#259 update capa 0.6.3 aws iam permsissions
  packages/docs/content/04-clusters.md
Labels: ok-to-test, size/XS

#261 Added detail for secure passwords and cert
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: ok-to-test, size/XS

#263 Rel 1.5.7
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/S

#264 Rel notes page meta desc edit
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/S

#267 Cli version
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: ok-to-test, size/S

#268 Rel notes 1.6
  packages/docs/content/06-integrations/00-kubernetes.md
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/M

#269 Rel notes 1.6 edit
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/XS

#270 Pack constraints
  packages/docs/content/06-integrations/01-pack-constraints.md
Labels: ok-to-test, size/XL

#271 Update 00-calico.md
  packages/docs/content/06-integrations/00-calico.md
Labels: ok-to-test, size/XS

#272 Pack constraints edits
  packages/docs/content/06-integrations/01-pack-constraints.md
Labels: ok-to-test, size/L

#273 Repositioned a warning box that was common to all types
  packages/docs/content/06-integrations/01-pack-constraints.md
Labels: ok-to-test, size/S

#262 spectre -> spectro fix
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: needs-ok-to-test, size/XS

#274 Corrected Portworx and Calico version numbers
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/XS

#275 Rel notes 1.6 tooltip
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/00-external-dns.md
  packages/docs/content/06-integrations/00-portworx.md
  packages/docs/content/06-integrations/01-pack-constraints.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/docs/content/13-release-notes.md
  packages/docs/content/14-troubleshooting.md
Labels: ok-to-test, size/L

#276 fixed menu icons
  packages/docs/content/14-troubleshooting.md
  packages/docs/content/15-faq.md
Labels: needs-ok-to-test, size/M

#277 1.6 docs
  packages/api/content/v1/api.json
Labels: ok-to-test, size/XXL

#278 Release 1.6.0 changes
  CHANGES
Labels: size/XS

#279 Getting started edits
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
  packages/docs/content/14-troubleshooting.md
Labels: ok-to-test, size/M

#280 Update 1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
Labels: ok-to-test, size/XS

#281 1.6.4 rel notes
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/XS

#282 Trblshtng hd pix
  packages/docs/content/14-troubleshooting.md
  packages/docs/content/pdb_kubectl_describe_nodes_hd.png
  packages/docs/content/pdb_kubectl_error_hd.png
  packages/docs/content/pdb_node_cordoned_hd.png
  packages/docs/content/pdb_ui_error_hd.png
Labels: ok-to-test
