Repository spectrocloud/librarium, pull requests merged in 2020-10, with the labels that each got.

#206 Update 00-prometheus-operator.md
  packages/docs/content/06-integrations/00-prometheus-operator.md
Labels: size/XS

#207 Outcold Solutions monitoring pack doc
  packages/docs/content/06-integrations/00-collectord.md
Labels: size/M

#208 Docs on splunk agent
  CHANGES
Labels: size/XS

#211 Default SSL cert for ingress
  packages/docs/content/06-integrations/00-nginx.md
Labels: size/S

#213 Update CHANGES
  CHANGES
Labels: size/XS

#210 On prem docs
  packages/docs/content/00-index.mdx
  packages/docs/content/04-clusters.md
  packages/docs/content/12-enterprise-version.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  packages/docs/content/12-enterprise-version/03-enterprise-administration.md
  packages/docs/content/13-release-notes.md
  packages/docs/content/vmware_arch_oct_2020.png
Labels: size/L

#214 On prem admin docs
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  packages/docs/content/12-enterprise-version/03-enterprise-administration.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
  packages/docs/content/12-enterprise-version/on_prem_system_console.png
Labels: size/L

#215 On prem tabs
  packages/docs/content/00-index.mdx
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
Labels: size/M

#216 Doc 48
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#217 Doc 65
  packages/docs/content/02-getting-started.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#220 BET-1445 - updated the api json doc
  packages/api/content/v1/api.json
Labels: size/XXL

#221 Pr220
  packages/api/content/v1/api.json
Labels: size/XS

#222 Update 12-enterprise-version.md
  packages/docs/content/12-enterprise-version.md
Labels: size/S

#223 Update 01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: size/L

#224 Update 02-deploying-an-enterprise-cluster.md
  packages/docs/content/12-enterprise-version/02-deploying-an-enterprise-cluster.md
Labels: size/M

#226 On prem edits
  packages/docs/content/00-index.mdx
Labels: size/M

#225 Update 03-system-console-dashboard.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
Labels: size/M

#228 On prem links verify
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
Labels: size/S

#229 Update 03-system-console-dashboard.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
Labels: size/XS

#230 Update 01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: size/XS

#231 On prem links verify
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  packages/docs/content/13-release-notes.md
Labels: size/L

#232 Update 03-system-console-dashboard.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
Labels: size/XS

#233 Mihai/fall icons
  packages/docs/content/12-enterprise-version.md
  packages/shared/src/components/styles/SidebarIcon.js
Labels: size/XS

#227 Mihai/deprecated tag
  packages/api/content/v1/api.json
  packages/api/src/components/CodeHighlight.js
  packages/api/src/components/Swagger.js
  packages/api/src/templates/docs.js
  packages/shared/src/components/common/DeprecatedTag.js
Labels: size/M

#234 V1.5 cli url update
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: size/XS

#236 Release 1.5.0
  CHANGES
Labels: size/XS

#237 V1.5.0 docs
  packages/api/content/v1/api.json
Labels: size/XXL

#238 Rel notes known bugs update
  packages/docs/content/13-release-notes.md
Labels: size/S

#240 Api endpoint chg
  CHANGES
  prow/OWNERS
Labels: size/S

#242 Tenant api chg
  CHANGES
Labels: size/XS

#245 Testing new prow setup
  README.md
Labels: ok-to-test, size/XS

#246 Testing postsubmit job
  README.md
Labels: needs-ok-to-test, ok-to-test, size/XS
