Repository spectrocloud/librarium, pull requests merged in 2020-09, with the labels that each got.

#170 Vmware prereq
  packages/docs/content/04-clusters.md
Labels: size/S

#172 Update 04-clusters.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#161 Add metadescriptions and robots
  packages/api/config.js
  packages/api/content/v1/01-auth.md
  packages/api/content/v1/03-audits.md
  packages/api/content/v1/05-cloudaccounts.md
  packages/api/content/v1/07-cloudconfig.md
  packages/api/content/v1/09-clouds.md
  packages/api/content/v1/10-clusters.md
  packages/api/content/v1/11-clusterprofiles.md
  packages/api/content/v1/15-dashboard.md
  packages/api/content/v1/19-events.md
  packages/api/content/v1/21-files.md
  packages/api/content/v1/27-metrics.md
  packages/api/content/v1/31-notifications.md
  packages/api/content/v1/33-overlords.md
  packages/api/content/v1/35-packs.md
  packages/api/content/v1/39-projects.md
  packages/api/content/v1/41-registries.md
  packages/api/content/v1/43-roles.md
  packages/api/content/v1/45-services.md
  packages/api/content/v1/49-teams.md
  packages/api/content/v1/51-tenants.md
  packages/api/content/v1/53-users.md
  packages/docs/config.js
  packages/glossary/config.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/config.js
  packages/website/static/robots.txt
Labels: size/M

#174 Deploy latest
  CHANGES
Labels: size/XS

#175 Vmware prereq typo
  packages/docs/content/04-clusters.md
Labels: size/XS

#177 Update changelog
  CHANGES
Labels: size/XS

#179 Added tooltip
  README.md
  packages/shared/src/components/ui/Tooltip.js
Labels: size/M

#181 Update 1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/S

#182 Update 2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS

#183 Typo Clear 1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#184 Portworx integration content
  packages/docs/content/06-integrations/00-portworx.md
Labels: size/M

#186 Update 04-clusters.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#185 Tooltip
  packages/docs/content/02-getting-started.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
Labels: size/S

#188 Cliv1.1 to v1.2
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/S

#189 Api diagram
  packages/api/content/2-samples.md
  packages/api/content/v1/api.json
Labels: size/L

#190 Socks removal
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
Labels: size/S

#191 Update 02-getting-started.md
  packages/docs/content/02-getting-started.md
Labels: size/XS

#192 Release build 1.2.0
  CHANGES
Labels: size/XS

#194 Typo sever
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#195 Api diagram edit
  packages/api/content/2-samples.md
Labels: size/S

#196 Api diagram edit
  packages/api/content/2-samples.md
Labels: size/XS

#198 Updated logo-url
  packages/docs/content/06-integrations/00-portworx.md
Labels: size/XS

#199 Doc 59
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/M

#197 Responsiveness
  packages/api/src/components/Swagger.js
  packages/api/src/templates/docs.js
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/src/templates/docs.js
  packages/glossary/content/a/accent.md
  packages/glossary/content/a/annotation.md
  packages/glossary/content/a/api.md
  packages/glossary/content/a/apple.md
  packages/glossary/content/a/do-not-index.md
  packages/glossary/content/b/bundle.md
  packages/glossary/content/c/cluster.md
  packages/glossary/src/templates/docs.js
  packages/shared/src/components/Next.js
  packages/shared/src/components/NextPrevious.js
  packages/shared/src/components/Previous.js
  packages/shared/src/components/TableOfContents.js
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/common/MainHeader.js
  packages/shared/src/components/common/QuickSetup.js
  packages/shared/src/components/index.js
  packages/shared/src/components/styles/Docs.js
  packages/shared/src/components/styles/PageNavigationButtons.js
  packages/shared/src/components/styles/Sidebar.js
  packages/shared/src/layouts/Default/Header.js
  packages/shared/src/layouts/Default/index.js
  packages/shared/src/layouts/Default/search/index.js
  packages/shared/src/layouts/Default/search/input.js
  packages/shared/src/layouts/Default/sidebar/index.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/gatsby-config.js
  packages/website/gatsby-node.js
  packages/website/src/pages/glossary.js
Labels: size/XXL

#201 Whitelist
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#202 Whitelist
  packages/docs/content/04-clusters.md
Labels: size/S

#200 More responsive fixes
  packages/shared/src/components/Box.js
  packages/shared/src/components/Intro.js
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/common/QuickSetup.js
  packages/shared/src/layouts/Default/index.js
Labels: size/S

#203 Release
  CHANGES
Labels: size/XS

#204 Rel 1.2
  packages/docs/content/12-release-notes.md
Labels: size/XS
