Repository spectrocloud/librarium, pull requests merged in 2020-08, with the labels that each got.

#134 Use custom secrets for alertmanager
  packages/docs/content/06-integrations/prometheus-operator.md
Labels: size/M

#136 Pack url update
  packages/docs/content/06-integrations/citrixipam.md
  packages/docs/content/06-integrations/csi.md
  packages/docs/content/06-integrations/kubernetesdashboard.md
  packages/docs/content/06-integrations/permissionmanager.md
  packages/docs/content/06-integrations/prometheusoperator.md
Labels: size/XS

#137 Pack url update
  packages/docs/content/06-integrations/00-calico.md
  packages/docs/content/06-integrations/00-centos.md
  packages/docs/content/06-integrations/00-citrix-ipam.md
  packages/docs/content/06-integrations/00-csi.md
  packages/docs/content/06-integrations/00-dex.md
  packages/docs/content/06-integrations/00-external-dns.md
  packages/docs/content/06-integrations/00-falco.md
  packages/docs/content/06-integrations/00-fluentbit.md
  packages/docs/content/06-integrations/00-istio.md
  packages/docs/content/06-integrations/00-kibana.md
  packages/docs/content/06-integrations/00-kong.md
  packages/docs/content/06-integrations/00-kubernetes-dashboard.md
  packages/docs/content/06-integrations/00-kubernetes.md
  packages/docs/content/06-integrations/00-kubevious.md
  packages/docs/content/06-integrations/00-metallb.md
  packages/docs/content/06-integrations/00-nginx.md
  packages/docs/content/06-integrations/00-permission-manager.md
  packages/docs/content/06-integrations/00-prometheus-operator.md
  packages/docs/content/06-integrations/00-ubuntu.md
  packages/docs/content/06-integrations/00-vault.md
Labels: size/L

#138 Cust reg pre req
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#139 Fix permission
  packages/docs/content/02-getting-started.md
Labels: size/XS

#135 Add support for Alert Manager secret manager
  CHANGES
Labels: size/XS

#140 Url repair
  packages/docs/content/02-getting-started.md
  packages/docs/content/06-integrations/00-prometheus-operator.md
  packages/docs/content/07-projects.md
Labels: size/L

#141 Delete duplicated files
  packages/docs/content/06-integrations/citrixipam.md
  packages/docs/content/06-integrations/csi.md
  packages/docs/content/06-integrations/kubernetesdashboard.md
  packages/docs/content/06-integrations/permissionmanager.md
  packages/docs/content/06-integrations/prometheusoperator.md
Labels: bug, size/L

#143 Gcp
  packages/docs/content/00-index.mdx
  packages/docs/content/04-clusters.md
  packages/docs/content/gcp_cluster_architecture.png
Labels: size/M

#144 Gttng strtd tabs
  packages/docs/content/02-getting-started.md
Labels: size/XS

#145 Update 04-clusters.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#146 Frst vmwr clstr chngs
  packages/docs/content/02-getting-started.md
Labels: size/XS

#151 Update 02-getting-started.md
  packages/docs/content/02-getting-started.md
Labels: size/S

#152 Update 02-getting-started.md (4 digit to 5 digit)
  packages/docs/content/02-getting-started.md
Labels: size/XS

#153 Update 04-clusters.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#154 Update 04-clusters.md
  packages/docs/content/04-clusters.md
Labels: size/XS

#150 Improve SEO
  packages/shared/src/layouts/Default/search/input.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/src/pages/integrations.js
Labels: size/M

#157 Vmware ipam
  package 2.json
  packages/docs/content/04-clusters.md
Labels: size/M

#158 Rel notes 1.1
  packages/docs/content/12-release-notes.md
Labels: size/S

#162 Build
  CHANGES
Labels: size/XS

#163 Rel notes 1.1
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/12-release-notes.md
Labels: size/XS

#164 Update s3 links from 1.0.0 to 1.1.0
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS

#165 Rel notes 1.1
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
Labels: size/S

#160 Point of interest
  README.md
  packages/shared/src/components/common/PointOfInterest.js
  packages/shared/src/layouts/Default/Header.js
Labels: size/L

#166 Grammarly
  packages/docs/content/00-index.mdx
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/content/02-getting-started.md
  packages/docs/content/03-cluster-profiles.md
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/2-task-update-profile.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/00-calico.md
  packages/docs/content/06-integrations/00-citrix-ipam.md
  packages/docs/content/06-integrations/00-dex.md
  packages/docs/content/06-integrations/00-external-dns.md
  packages/docs/content/06-integrations/00-falco.md
  packages/docs/content/06-integrations/00-istio.md
  packages/docs/content/06-integrations/00-kibana.md
  packages/docs/content/06-integrations/00-kong.md
  packages/docs/content/06-integrations/00-kubernetes-dashboard.md
  packages/docs/content/06-integrations/00-kubernetes.md
  packages/docs/content/06-integrations/00-kubevious.md
  packages/docs/content/06-integrations/00-metallb.md
  packages/docs/content/06-integrations/00-nginx.md
  packages/docs/content/06-integrations/00-permission-manager.md
  packages/docs/content/06-integrations/00-prometheus-operator.md
  packages/docs/content/06-integrations/00-vault.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/08-user-management/2-rbac.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-release-notes.md
  packages/website/src/pages/integrations.js
Labels: size/L

#167 Bound tooltip to the points of interest cointainer
  packages/shared/src/components/common/PointOfInterest.js
Labels: size/XS

#168 Dashboard point of interest
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
  packages/docs/content/08-user-management.md
  packages/docs/content/default_dashboard.png
  packages/docs/content/default_dashboard_new_1.png
  packages/docs/content/default_dashboard_new_2.png
Labels: size/M

#169 Dashboard point of interest
  packages/docs/content/02-getting-started.md
Labels: size/M
