Repository spectrocloud/librarium, pull requests merged in 2020-07, with the labels that each got.

#110 Update 1-introduction.md
  packages/api/content/1-introduction.md
Labels: size/S

#108 Update 1-what-is.md
  packages/docs/content/01-introduction/1-what-is.md
Labels: size/S

#109 Update 2-concept-overviews.md
  packages/docs/content/01-introduction/2-concept-overviews.md
Labels: size/S

#114 Terminology Uniformity. Tina comments. Releases. MD Syntax cleanup.
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/content/02-getting-started/2-azure-your-first-cluster.md
  packages/docs/content/02-getting-started/3-vmware-your-first-cluster.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-aws-clusters.md
  packages/docs/content/04-clusters/2-azure-clusters.md
  packages/docs/content/04-clusters/3-vmware-clusters.md
  packages/docs/content/06-integrations/calico.md
  packages/docs/content/06-integrations/citrix-ipam.md
  packages/docs/content/06-integrations/dex.md
  packages/docs/content/06-integrations/falco.md
  packages/docs/content/06-integrations/fluentbit.md
  packages/docs/content/06-integrations/istio.md
  packages/docs/content/06-integrations/kibana.md
  packages/docs/content/06-integrations/kong.md
  packages/docs/content/06-integrations/kubernetes-dashboard.md
  packages/docs/content/06-integrations/kubernetes.md
  packages/docs/content/06-integrations/kubevious.md
  packages/docs/content/06-integrations/metallb.md
  packages/docs/content/06-integrations/nginx.md
  packages/docs/content/06-integrations/permission-manager.md
  packages/docs/content/06-integrations/prometheus-operator.md
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/06-integrations/vault.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/5-add-custom-packs-manifests.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-release-notes.md
Labels: size/L

#112 Mihai/api docs refactor
  packages/api/src/components/Swagger.js
  packages/api/src/templates/docs.js
Labels: size/L

#113 Mihai/tabs
  README.md
  packages/shared/src/components/styles/Tabs.js
Labels: size/M

#117 Added tabs to 'Getting started - 1st cluster'; 'cluster profiles'; 'c…
  packages/docs/content/02-getting-started.md
  packages/docs/content/02-getting-started/1-aws-your-first-cluster.md
  packages/docs/content/02-getting-started/2-azure-your-first-cluster.md
  packages/docs/content/02-getting-started/3-vmware-your-first-cluster.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-aws-clusters.md
  packages/docs/content/04-clusters/2-azure-clusters.md
  packages/docs/content/04-clusters/3-vmware-clusters.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/docs/content/09-registries-and-packs/5-add-custom-packs-manifests.md
  packages/docs/content/aws_cluster_architecture.png
  packages/docs/content/azure_cluster_architecture.png
  packages/docs/content/vmware_cluster_architecture.png
Labels: size/XXL

#118 Ingress support for Packs
  packages/docs/content/06-integrations/dex.md
  packages/docs/content/06-integrations/kibana.md
  packages/docs/content/06-integrations/kubernetes-dashboard.md
  packages/docs/content/06-integrations/kubevious.md
  packages/docs/content/06-integrations/permission-manager.md
  packages/docs/content/06-integrations/prometheus-operator.md
  packages/docs/content/06-integrations/vault.md
Labels: size/M

#119 making Deepak's changes to AWS Minimum Permissions.
  packages/docs/content/04-clusters.md
Labels: size/S

#120 Ingress changes for Dex and ExternalDNS doc
  packages/docs/content/06-integrations/dex.md
  packages/docs/content/06-integrations/externaldns.md
  packages/docs/content/06-integrations/vault.md
Labels: size/M

#121 Updates to Custom Registry and CLI references.
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/M

#122 Spectro CLI ref login doc change
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS

#123 ExternalDNS example
  packages/docs/content/06-integrations/externaldns.md
Labels: size/L

#125 Homepage content
  package-lock.json
  packages/api/src/templates/docs.js
  packages/docs/content/00-index.mdx
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/src/templates/docs.js
  packages/shared/src/assets/blue-hero-background.png
  packages/shared/src/assets/clouds/aws.png
  packages/shared/src/assets/clouds/azure.png
  packages/shared/src/assets/clouds/bare_metal.png
  packages/shared/src/assets/clouds/google_cloud.png
  packages/shared/src/assets/clouds/vmware.png
  packages/shared/src/assets/icons/clusters.svg
  packages/shared/src/assets/icons/mesh.svg
  packages/shared/src/components/Intro.js
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/common/DocUpdatesSection.js
  packages/shared/src/components/common/MainHeader.js
  packages/shared/src/components/common/QuickSetup.js
  packages/shared/src/components/ui/Button.js
  packages/shared/src/createApp.js
  packages/shared/src/graphql/index.js
  packages/shared/src/layouts/Default/index.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/gatsby-node.js
Labels: size/XXL

#126 Fix code-block component and refactor all code usage
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/externaldns.md
  packages/docs/content/06-integrations/kubernetes-dashboard.md
  packages/docs/content/06-integrations/kubernetes.md
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/06-integrations/vault.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/shared/src/mdx/components/codeBlock.js
  packages/shared/src/mdx/components/index.js
Labels: size/L

#128 Add suport for default tab
  README.md
  packages/docs/content/00-index.mdx
  packages/docs/content/02-getting-started.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/styles/Tabs.js
  packages/shared/src/components/ui/Tabs.js
  packages/shared/src/layouts/Default/sidebar/index.js
  packages/shared/src/utils/location.js
  packages/website/gatsby-node.js
Labels: size/L

#129 Homepage content
  packages/docs/content/00-index.mdx
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/12-release-notes.md
  packages/shared/src/components/Intro.js
  packages/shared/src/components/common/QuickSetup.js
Labels: size/L

#131 Rel build
  prow/functions.sh
  prow/release_build.sh
Labels: size/S

#130 Homepage content
  packages/docs/content/00-index.mdx
  packages/docs/content/02-getting-started.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/admin_dashboard.png
  packages/docs/content/default_dashboard.png
Labels: size/M

#133 Osx cli v updt
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS
