Repository spectrocloud/librarium, pull requests merged in 2020-06, with the labels that each got.

#56 Mihai/fixes3
  packages/docs/src/components/Integrations/index.js
  packages/shared/src/components/styles/Docs.js
Labels: size/S

#57 Ga content
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/content/02-getting-started.md
  packages/docs/content/02-getting-started/1-aws-your-first-cluster.md
  packages/docs/content/02-getting-started/2-azure-your-first-cluster.md
  packages/docs/content/02-getting-started/3-vmware-your-first-cluster.md
  packages/docs/content/03-cluster-profiles.md
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-aws-clusters.md
  packages/docs/content/04-clusters/2-azure-clusters.md
  packages/docs/content/04-clusters/3-vmware-clusters.md
  packages/docs/content/06-integrations/calico.md
  packages/docs/content/06-integrations/centos.md
  packages/docs/content/06-integrations/citrix-ipam.md
  packages/docs/content/06-integrations/dex.md
  packages/docs/content/06-integrations/falco.md
  packages/docs/content/06-integrations/kibana.md
  packages/docs/content/06-integrations/kubernetes-dashboard.md
  packages/docs/content/06-integrations/kubernetes.md
  packages/docs/content/06-integrations/kubevious.md
  packages/docs/content/06-integrations/metallb.md
  packages/docs/content/06-integrations/network-pack-cni.md
  packages/docs/content/06-integrations/nginx.md
  packages/docs/content/06-integrations/prometheus-operator.md
  packages/docs/content/06-integrations/prometheus.md
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/06-integrations/ubuntu.md
  packages/docs/content/06-integrations/vault.md
  packages/docs/content/08-user-management.md
  packages/docs/content/08-user-management/1-okta.md
  packages/docs/content/08-user-management/2-azure-ad.md
  packages/docs/content/08-user-management/3-keycloak.md
  packages/docs/content/08-user-management/4-onelogin.md
  packages/docs/content/08-user-management/5-msft-adfs.md
  packages/docs/content/08-user-management/7-about-roles-and-permissions.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/3-adding-custom-packs-using-helm-charts.md
  packages/docs/content/09-registries-and-packs/4-add-custom-packs-manifests.md
  packages/docs/content/09-registries-and-packs/5-spectro-cli-reference.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-release-notes.md
Labels: size/XXL

#64 Mihai/fixes5
  packages/docs/content/00-index.mdx
  packages/docs/src/templates/docs.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/gatsby-node.js
Labels: size/M

#54 update creating-vmware-clusters
  packages/docs/content/04-clusters/3-vmware-clusters.md
Labels: size/XS

#65 Mihai/fixes6
  packages/api/content/0-index.mdx
  packages/api/content/1-introduction.md
  packages/api/src/templates/docs.js
Labels: size/XS

#66 Mihai/Toc-scroll-fix
  packages/shared/src/components/styles/Docs.js
Labels: size/XS

#69 Hide homepage and redirect to introduction
  packages/docs/content/00-index.mdx
  packages/docs/content/01-introduction.md
  packages/website/gatsby-node.js
Labels: size/M

#67 Post-submit job
  prow/functions.sh
  prow/postsubmit.sh
Labels: size/S

#74 DOC-46 - Added pre requisites to custom registry steps
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/S

#75 Ga content
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management/6-rbac.md
  packages/docs/content/08-user-management/7-about-roles-and-permissions.md
Labels: size/L

#76 API endpoints integration update
  packages/api/content/v1/05-cloudaccounts.md
  packages/api/content/v1/13-crypto.md
  packages/api/content/v1/17-errlogs.md
  packages/api/content/v1/23-health.md
  packages/api/content/v1/25-jobs.md
  packages/api/content/v1/29-nats.md
  packages/api/content/v1/37-plans.md
  packages/api/src/components/ApiSidebar.js
  packages/api/src/templates/docs.js
Labels: size/M

#78 Ga content
  packages/api/content/1-introduction.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-custom-packs-using-helm-charts.md
  packages/docs/content/09-registries-and-packs/5-add-custom-packs-manifests.md
Labels: size/M

#79 Audit fix
  package-lock.json
  packages/docs/package-lock.json
  packages/docs/package.json
  packages/shared/package.json
Labels: size/XXL

#80 Comment out s3 sync for now
  prow/functions.sh
  prow/postsubmit.sh
  prow/presubmit.sh
Labels: size/S

#81 Update aws cloud account permissions
  packages/docs/content/04-clusters/1-aws-clusters.md
Labels: size/XS

#82 Sync on merge
  prow/functions.sh
  prow/postsubmit.sh
Labels: size/S

#85 Cool
  packages/docs/content/02-getting-started/1-aws-your-first-cluster.md
Labels: size/XS

#87 Instance Type Change
  packages/docs/content/02-getting-started/2-azure-your-first-cluster.md
Labels: size/S

#88 Update 02-getting-started.md
  packages/docs/content/02-getting-started.md
Labels: ok-to-test, size/XS

#86 Add NTP configuration
  packages/docs/content/04-clusters/3-vmware-clusters.md
Labels: size/XS

#89 Change home and remove api intro
  packages/api/content/0-index.mdx
  packages/api/content/1-introduction.md
  packages/api/content/1-introduction/1-what-is.md
  packages/api/content/1-introduction/2-concept-overviews.md
  packages/docs/content/01-introduction.md
  packages/shared/src/components/Intro.js
  packages/shared/src/layouts/Default/Header.js
  packages/website/gatsby-node.js
Labels: size/L

#84 Update 3-vmware-your-first-cluster.md
  packages/docs/content/02-getting-started/3-vmware-your-first-cluster.md
Labels: size/S

#90 Run with 8G mem
  .npmrc
  prow/functions.sh
Labels: size/XS

#91 Remove Prometheus integration
  packages/docs/content/06-integrations/prometheus.md
Labels: size/S

#92 Added verification step to custom registry setup
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS

#93 Ga content
  packages/api/content/1-introduction.md
Labels: size/M

#94 Algolia params
  prow/functions.sh
Labels: size/XS

#73 Add search
  packages/api/config.js
  packages/docs/config.js
  packages/glossary/config.js
  packages/shared/src/createApp.js
  packages/shared/src/layouts/Default/Header.js
  packages/shared/src/layouts/Default/layout.css
  packages/shared/src/layouts/Default/search/hitComps.js
  packages/shared/src/layouts/Default/search/index.js
  packages/shared/src/layouts/Default/search/input.js
  packages/shared/src/layouts/Docs/index.js
  packages/website/config.js
  packages/website/gatsby-config.js
  packages/website/src/utils/algolia.js
Labels: size/L

#95 Mihai/api response update
  packages/api/content/v1/01-auth.md
  packages/api/content/v1/03-audits.md
  packages/api/content/v1/05-cloudaccounts.md
  packages/api/content/v1/07-cloudconfig.md
  packages/api/content/v1/09-clouds.md
  packages/api/content/v1/10-clusters.md
  packages/api/content/v1/11-clusterprofiles.md
  packages/api/content/v1/15-dashboard.md
  packages/api/content/v1/19-events.md
  packages/api/content/v1/21-files.md
  packages/api/content/v1/27-metrics.md
  packages/api/content/v1/31-notifications.md
  packages/api/content/v1/33-overlords.md
  packages/api/content/v1/35-packs.md
  packages/api/content/v1/39-projects.md
  packages/api/content/v1/41-registries.md
  packages/api/content/v1/43-roles.md
  packages/api/content/v1/45-services.md
  packages/api/content/v1/49-teams.md
  packages/api/content/v1/51-tenants.md
  packages/api/content/v1/53-users.md
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/components/Swagger.js
  packages/api/src/templates/docs.js
  packages/shared/src/components/styles/Docs.js
Labels: size/XXL

#96 Ga content
  packages/docs/content/06-integrations/calico.md
  packages/docs/content/06-integrations/network-pack-cni.md
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/08-user-management.md
  packages/docs/content/08-user-management/1-okta.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/08-user-management/2-azure-ad.md
  packages/docs/content/08-user-management/2-rbac.md
  packages/docs/content/08-user-management/3-keycloak.md
  packages/docs/content/08-user-management/4-onelogin.md
  packages/docs/content/08-user-management/5-msft-adfs.md
  packages/docs/content/08-user-management/check_mark_64_e1.png
  packages/docs/content/08-user-management/check_mark_64_o.png
  packages/docs/content/08-user-management/copy_icon1.svg
  packages/docs/content/08-user-management/hubble_rbac_scope.png
  packages/docs/content/08-user-management/permissions.png
  packages/docs/content/08-user-management/permissions_inherited.png
  packages/docs/content/08-user-management/scenario.png
Labels: size/L

#97 Fixes
  packages/api/config.js
  packages/api/content/0-index.md
  packages/api/content/0-index.mdx
  packages/glossary/config.js
  packages/shared/src/components/Intro.js
  packages/website/gatsby-node.js
Labels: size/M

#98 Ga content
  packages/docs/content/01-introduction.md
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/content/01-introduction/cluster_profile_new.png
  packages/docs/content/02-getting-started.md
  packages/docs/content/02-getting-started/1-aws-your-first-cluster.md
  packages/docs/content/02-getting-started/2-azure-your-first-cluster.md
  packages/docs/content/02-getting-started/3-vmware-your-first-cluster.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/03-cluster-profiles/dev_profile_new.png
  packages/docs/content/03-cluster-profiles/dev_profile_new_2.png
  packages/docs/content/03-cluster-profiles/prod_profile_new.png
  packages/docs/content/03-cluster-profiles/prod_profile_new_2.png
Labels: size/L

#99 Updated the updated images for cluster profiles/examples.
  packages/docs/content/03-cluster-profiles/3-examples.md
Labels: size/XS

#100 Updated the updated images for cluster profiles/examples.
  packages/docs/content/03-cluster-profiles/3-examples.md
Labels: size/XS

#101 Updated the updated images for cluster profiles/examples. Added VMwar…
  packages/api/package-lock.json
  packages/docs/content/01-introduction/cluster_profile_new 2.png
  packages/docs/content/03-cluster-profiles/dev_profile_new 2.png
  packages/docs/content/03-cluster-profiles/dev_profile_new_2 2.png
  packages/docs/content/03-cluster-profiles/prod_profile_new 2.png
  packages/docs/content/03-cluster-profiles/prod_profile_new_2 2.png
  packages/docs/content/04-clusters/3-vmware-clusters.md
Labels: size/XL

#103 Azure doc update
  packages/docs/content/04-clusters/2-azure-clusters.md
Labels: size/XS

#102 Mihai/fixes
  packages/api/content/0-index.md
  packages/api/content/1-introduction.md
  packages/api/src/components/CodeHighlight.js
  packages/api/src/components/Swagger.js
  packages/api/src/templates/docs.js
  packages/website/gatsby-node.js
Labels: size/L

#106 Codrin/fixes
  packages/api/src/components/CodeHighlight.js
  packages/api/src/components/Swagger.js
  packages/shared/src/components/styles/Docs.js
  packages/website/gatsby-config.js
Labels: size/S

#111 Integrations logoUrl updated. VMware EXSi 6.5 Update 3 & EXSi 6.7 Upd…
  packages/docs/content/04-clusters/3-vmware-clusters.md
  packages/docs/content/06-integrations/citrix-ipam.md
  packages/docs/content/06-integrations/dex.md
  packages/docs/content/06-integrations/falco.md
  packages/docs/content/06-integrations/fluentbit.md
  packages/docs/content/06-integrations/istio.md
  packages/docs/content/06-integrations/kibana.md
  packages/docs/content/06-integrations/kong.md
  packages/docs/content/06-integrations/kubernetes-dashboard.md
  packages/docs/content/06-integrations/kubernetes.md
  packages/docs/content/06-integrations/kubevious.md
  packages/docs/content/06-integrations/metallb.md
  packages/docs/content/06-integrations/nginx.md
  packages/docs/content/06-integrations/permission-manager.md
  packages/docs/content/06-integrations/prometheus-operator.md
  packages/docs/content/06-integrations/storage-pack-csi.md
  packages/docs/content/06-integrations/vault.md
  packages/docs/content/08-user-management.md
Labels: size/M
