Repository spectrocloud/librarium, pull requests merged in 2021-05, with the labels that each got.

#337 update AWS Cloud Account Permissions
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: ok-to-test, size/XL

#338 new-cluster-page-changes
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: ok-to-test, size/XS

#339 Sts 4 policies
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: approved, ok-to-test, size/L

#340 Update 1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/S

#341 1.9.0 Document Updates
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/13-release-notes.md
Labels: approved, ok-to-test, size/XL

#342 1.9.0-document-updates
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/13-release-notes.md
Labels: approved, needs-ok-to-test, size/XS

#343 Release 1.9 push
  CHANGES
Labels: size/XS

#344 Update 1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: ok-to-test, size/XS

#345 1.9.0 doc updates
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/eks_cluster_architecture.png
Labels: approved, ok-to-test, size/XS

#349 AWS/ EKS Notes
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/14-troubleshooting/01-orchestration-spectrocloud.md
  packages/docs/content/14-troubleshooting/02-Network-Communications-and-Ports.md
Labels: needs-ok-to-test, ok-to-test, size/M

#350 Eks chg push
  CHANGES
Labels: size/XS

#352 k8s-pack-integrations-update1.9
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: needs-ok-to-test, ok-to-test, size/XS

#355 On-Prem System Requirements
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: approved, needs-ok-to-test, size/L

#357 Change addon type string
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
Labels: ok-to-test, size/XS

#358 Change structure, flow etc
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/L

#359 Requirement Document Updates
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: needs-ok-to-test, ok-to-test, size/M

#360 System requirements
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/L

#361 Fix format
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XS

#363 Requirement Document Updates
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: ok-to-test, size/L

#364 Update 00-on-prem-system-requirements.md
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XS

#369 new permissions
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/S

#365 EKS and SAAS Image Update
  packages/docs/content/04-clusters/eks_cluster_architecture.png
  packages/docs/content/14-troubleshooting/saas_networks_ports.png
Labels: approved, needs-ok-to-test, ok-to-test, size/XS
