Repository spectrocloud/librarium, pull requests merged in 2021-10, with the labels that each got.

#460 bet-3033
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
Labels: size/S, needs-ok-to-test, ok-to-test

#469 Maas gateway 1.0.9
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/12-enterprise-version/06-monitoring.md
Labels: size/M, needs-ok-to-test, ok-to-test

#459 new-integrations-added
  packages/docs/content/06-integrations/00-aws-ebs.md
  packages/docs/content/06-integrations/00-azure-disk.md
  packages/docs/content/06-integrations/00-certmanager.md
  packages/docs/content/06-integrations/00-csi.md
  packages/docs/content/06-integrations/00-gce.md
  packages/docs/content/06-integrations/00-heartbeat.md
  packages/docs/content/06-integrations/00-kubehunter.md
  packages/docs/content/06-integrations/00-kubewatch.md
  packages/docs/content/06-integrations/00-nfs-subdir-external.md
  packages/docs/content/06-integrations/00-oidc-eks.md
  packages/docs/content/06-integrations/00-openstack-cinder.md
  packages/docs/content/06-integrations/00-portworx.md
  packages/docs/content/06-integrations/00-prismacloud.md
  packages/docs/content/06-integrations/00-rook-ceph.md
  packages/docs/content/06-integrations/00-splunk.md
  packages/docs/content/06-integrations/00-vsphere-csi.md
  packages/docs/content/06-integrations/00-vsphere-volume.md
Labels: size/XL, needs-ok-to-test, ok-to-test

#467 Air gap repo
  packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md
  packages/docs/content/12-enterprise-version/05-air-gap-repo.md
Labels: size/L, ok-to-test

#450 getting-started
  packages/docs/content/00-release-notes.md
  packages/docs/content/02-getting-started.md
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/00-kubernetes.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/10-audit-logs.md
Labels: size/M, needs-ok-to-test, ok-to-test

#465 maas-gateway-update
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: size/M, ok-to-test

#470 vmware privilages update
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
Labels: size/L, ok-to-test

#476 Cluster refactor
  packages/docs/content/04-clusters/3-cluster-management.md
  packages/docs/content/04-clusters/3-cluster-management/1-scaling.md
  packages/docs/content/04-clusters/3-cluster-management/2-cluster-updates.md
  packages/docs/content/04-clusters/3-cluster-management/3-os-patching.md
  packages/docs/content/04-clusters/3-cluster-management/4-compliance-scan.md
  packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md
  packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md
  packages/docs/content/04-clusters/3-cluster-management/7-workloads.md
Labels: size/L

#473 Helm Registry
  packages/docs/content/09-registries-and-packs/6-helm-charts.md
Labels: size/M, needs-ok-to-test, ok-to-test

#471 1.14-frp
  packages/docs/content/06-integrations/00-frp.md
Labels: size/M, ok-to-test

#462 1.14-feature
  packages/docs/content/04-clusters.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-enterprise-version/04-enterprise-cluster-management.md
Labels: size/L, ok-to-test

#479 Latest changes to stage
  CHANGES
Labels: size/XS, ok-to-test

#478 v1alpha1 to v1 path migration fix
  package-lock.json
  packages/api/content/1-introduction.md
  packages/api/content/2-samples.md
  packages/api/content/v1/01-auth.md
  packages/api/content/v1/03-audits.md
  packages/api/content/v1/05-cloudaccounts.md
  packages/api/content/v1/07-cloudconfig.md
  packages/api/content/v1/09-clouds.md
  packages/api/content/v1/10-clusters.md
  packages/api/content/v1/11-clusterprofiles.md
  packages/api/content/v1/15-dashboard.md
  packages/api/content/v1/16-system.md
  packages/api/content/v1/19-events.md
  packages/api/content/v1/21-files.md
  packages/api/content/v1/27-metrics.md
  packages/api/content/v1/31-notifications.md
  packages/api/content/v1/33-overlords.md
  packages/api/content/v1/35-packs.md
  packages/api/content/v1/39-projects.md
  packages/api/content/v1/41-registries.md
  packages/api/content/v1/43-roles.md
  packages/api/content/v1/49-teams.md
  packages/api/content/v1/50-tenants.md
  packages/api/content/v1/53-users.md
  packages/api/content/v1/54-workspaces.md
  packages/api/content/v1/api.json
  packages/api/package-lock.json
Labels: size/XXL, needs-ok-to-test, ok-to-test

#480 doc-revisit-11-oct
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/03-cluster-profiles/development.png
  packages/docs/content/03-cluster-profiles/production.png
  packages/docs/content/04-clusters/1-new-clusters/03-aws.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/07-openstack.md
  packages/docs/content/04-clusters/3-cluster-management/0-reconfigure.md
  packages/docs/content/04-clusters/3-cluster-management/1-cluster-updates.md
  packages/docs/content/04-clusters/3-cluster-management/2-health-alerts.md
  packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md
  packages/docs/content/04-clusters/3-cluster-management/7-workloads.md
  packages/docs/content/04-clusters/3-cluster-management/conformance.png
  packages/docs/content/04-clusters/3-cluster-management/kcs.png
  packages/docs/content/04-clusters/3-cluster-management/kpt.png
  packages/docs/content/06-integrations/00-frp.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/05-air-gap-repo.md
Labels: size/L, needs-ok-to-test, ok-to-test

#484 Update 0-reconfigure.md
  packages/docs/content/04-clusters/3-cluster-management/0-reconfigure.md
Labels: size/XS

#487 Introduction to Spectro Cloud
  package-lock.json
  packages/api/package-lock.json
  packages/docs/content/00-index.mdx
  packages/docs/content/01-introduction.md
  packages/docs/content/01-introduction/1-what-is-sc.png
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/2-architecture-overview.md
  packages/docs/content/01-introduction/2-what-is-sc.png
  packages/shared/src/assets/clouds/aws.png
  packages/shared/src/assets/clouds/azure.png
  packages/shared/src/assets/clouds/bare_metal.png
  packages/shared/src/assets/clouds/google_cloud.png
  packages/shared/src/assets/clouds/maas.png
  packages/shared/src/assets/clouds/openshift.png
  packages/shared/src/assets/clouds/openstack.png
  packages/shared/src/assets/clouds/vmware.png
  packages/shared/src/components/Intro.js
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/common/MainHeader.js
Labels: size/XXL, ok-to-test

#486 air-gapped-spell-check
  packages/docs/content/12-enterprise-version/05-air-gap-repo.md
Labels: size/M, ok-to-test

#491 Introduction image updates
  packages/docs/content/01-introduction/2-architecture-overview.md
  packages/docs/content/01-introduction/2-intro.png
  packages/docs/content/01-introduction/2-what-is-sc.png
  packages/docs/content/01-introduction/3-intro.png
  packages/docs/content/01-introduction/4-intro.png
  packages/docs/content/01-introduction/5-intro.png
  packages/docs/content/01-introduction/dfd_on_prem_vmware.png
  packages/docs/content/01-introduction/dfd_saas_to_aws.png
  packages/docs/content/01-introduction/dfd_saas_to_vmware.png
Labels: size/XS, needs-ok-to-test, ok-to-test

#492 Intro image updates
  packages/docs/content/01-introduction/1-what-is-sc.png
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/22-intro.png
Labels: size/XS, ok-to-test
