Repository spectrocloud/librarium, pull requests merged in 2021-07, with the labels that each got.

#397 Release 1.11 packs and cli updates
  packages/docs/content/06-integrations/01-pack-constraints.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: ok-to-test, size/S

#395 1.11-OpenStack
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/openstack_cluster_architecture.png
Labels: ok-to-test, size/L

#398 schema-constraint-readonly
  packages/docs/content/06-integrations/01-pack-constraints.md
Labels: needs-ok-to-test, ok-to-test, size/S

#399 OpenStack-Updates
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: needs-ok-to-test, ok-to-test, size/L

#402 Release Notes and FAQ Updates
  packages/docs/content/00-release-notes.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/06-integrations/00-EKS-D.md
  packages/docs/content/16-faq.md
Labels: needs-ok-to-test, ok-to-test, size/XL

#400 correction in Azure Cluster creation
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: needs-ok-to-test, ok-to-test, size/XS

#404 Create 3 - Architecture Overview.md
  packages/docs/content/01-introduction/3 - Architecture Overview.md
Labels: size/M

#405 Create 16-glossary.md
  packages/docs/content/16-glossary.md
Labels: size/M

#407 rename file
  packages/docs/content/01-introduction/3-architecture-overview.md
Labels: size/XS

#406 Update 16-glossary.md
  packages/docs/content/16-glossary.md
Labels: size/XS

#412 add auto-reconf
  prow/functions.sh
Labels: approved, ok-to-test, size/XS

#414 1.12.0 Doc Update
  packages/docs/content/00-release-notes.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/aks_cluster_architecture.png
Labels: needs-ok-to-test, ok-to-test, size/M

#410 Update 16-glossary-all.md
  packages/docs/content/16-glossary-all.md
Labels: size/S

#413 Spectro release 1.12 CLI/Pack Updates
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: ok-to-test, size/S

#416 OIDC based SSO
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: needs-ok-to-test, ok-to-test, size/L

#418 Generic Cluster Import
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/2-brownfield-clusters.md
Labels: ok-to-test, size/S

#420 Openstack Troubleshooting Removed
  packages/docs/content/01-introduction/3-architecture-overview.md
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/2-task-update-profile.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: ok-to-test, size/S
