Repository spectrocloud/librarium, pull requests merged in 2021-02, with the labels that each got.

#292 Changes for 1.7
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/2-brownfield-clusters.md
  packages/docs/content/04-clusters/aws_cluster_architecture.png
  packages/docs/content/04-clusters/azure_cluster_architecture.png
  packages/docs/content/04-clusters/gcp_cluster_architecture.png
  packages/docs/content/04-clusters/vmware_arch_oct_2020.png
  packages/docs/content/04-clusters/vmware_cluster_architecture.png
Labels: size/XXL

#293 Fix cluster docs
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/2-brownfield-clusters.md
Labels: size/L

#295 Cli ver chg
  packages/docs/content/09-registries-and-packs.md
Labels: size/XS

#297 1.7 api docs
  packages/api/content/v1/api.json
Labels: needs-ok-to-test, size/XXL

#296 Changes 1.7.0
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: ok-to-test, size/XS

#298 Rel 170 push
  CHANGES
Labels: size/XS

#301 1.7 release notes Updated
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/S
