Repository spectrocloud/librarium, pull requests merged in 2021-06, with the labels that each got.

#370 1.10 Major Doc Updates
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/L

#371 Update 13-release-notes.md
  packages/docs/content/13-release-notes.md
Labels: size/S

#372 Fargate Profile Review - Update 1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/S

#373 OSPatchingPolicy 4-cluster-features.md
  packages/docs/content/04-clusters/4-cluster-features.md
Labels: size/S

#375 review-backup-restore-4-cluster-features.md
  packages/docs/content/04-clusters/4-cluster-features.md
Labels: size/L

#376 Permissions 1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/S

#377 ReleaseNoteUpdate 13-release-notes.md
  packages/docs/content/13-release-notes.md
Labels: size/M

#379 CloudPermissions 13-release-notes.md
  packages/docs/content/13-release-notes.md
Labels: size/M

#367 1.10 MacrosVariables
  packages/docs/content/06-integrations/01-pack-constraints.md
Labels: approved, needs-ok-to-test, ok-to-test, size/XS

#381 1.10-Doc-Updates
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/4-cluster-features.md
Labels: needs-ok-to-test, ok-to-test, size/L

#382 Changes for Backup Restores
  packages/docs/content/04-clusters/4-cluster-features.md
Labels: needs-ok-to-test, ok-to-test, size/S

#383 1.10 doc update policies 01
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/M

#384 Release Notes 1.10
  CHANGES
Labels: ok-to-test, size/XS

#385 1.10-doc-updates-05
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/M

#387 ReleaseNodes-DescribeIdentity-Provider 13-release-notes.md
  packages/docs/content/13-release-notes.md
Labels: size/XS

#389 PermissionChange-EKS-Identity
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/XS

#390 EKS-Permissions-Identify
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/XS

#391 1.10-Minor changes
  packages/docs/content/13-release-notes.md
Labels: ok-to-test, size/XS

#393 Doc spell checks
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/14-troubleshooting/01-orchestration-spectrocloud.md
Labels: needs-ok-to-test, ok-to-test, size/M

#394 cluster-logs-updates
  packages/docs/content/04-clusters.md
  packages/docs/content/14-troubleshooting.md
Labels: needs-ok-to-test, ok-to-test, size/M

#396 Release-note-1.11-new
  packages/docs/content/13-release-notes.md
Labels: needs-ok-to-test, ok-to-test, size/S
