Repository spectrocloud/librarium, pull requests merged in 2021-11, with the labels that each got.

#505 Codrin/hero
  package-lock.json
  package.json
  packages/api/package-lock.json
  packages/docs/content/01-introduction.md
  packages/shared/src/assets/hero.png
  packages/shared/src/assets/icons/workspaces.svg
  packages/shared/src/components/Intro.js
  packages/shared/src/components/common/MainHeader.js
  packages/shared/src/components/styles/SidebarIcon.js
  packages/website/gatsby-config.js
  packages/website/gatsby-node.js
  packages/website/package-lock.json
  packages/website/package.json
Labels: size/XXL

#506 workspace-icon
  packages/docs/content/05-workspace.md
  packages/docs/content/10-audit-logs.md
Labels: size/M, needs-ok-to-test, ok-to-test

#489 Update 04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
Labels: size/S, needs-ok-to-test, ok-to-test

#508 formula-update-cloud-cost
  packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#496 added support for video
  packages/shared/src/mdx/components/index.js
Labels: size/M, ok-to-test

#511 vsphere-zone-tagging
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
Labels: size/S, ok-to-test

#512 cluster-profile-creation-video-added
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/aws-full-profile.mp4
Labels: size/XS, needs-ok-to-test

#509 downloads-updtes-04
  packages/docs/content/05-workspace.md
  packages/docs/content/16-spectro-downloads.md
  packages/docs/content/17-glossary-all.md
Labels: size/S, needs-ok-to-test, ok-to-test

#504 release-notes-2.0.0
  packages/docs/content/00-release-notes.md
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: size/S, ok-to-test

#494 Bet-2722 : AAD Configuration for AKS
  packages/docs/content/04-clusters/1-new-clusters/02-aks.md
Labels: size/S, ok-to-test

#507 bet-3355
  packages/docs/content/04-clusters/1-new-clusters/05-gcp.md
Labels: size/M, needs-ok-to-test, ok-to-test

#513 video-removed
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/aws-full-profile.mp4
Labels: size/XS, ok-to-test

#518 added plugin support for videos
  package-lock.json
  packages/api/package-lock.json
  packages/shared/src/mdx/components/index.js
  packages/website/gatsby-config.js
  packages/website/package.json
Labels: size/XXL, needs-ok-to-test

#514 Update 06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
Labels: size/M, needs-ok-to-test, ok-to-test

#516 Update to correct git command that creates a branch
  README.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#515 Fixed typos and some terms.
  packages/docs/content/02-getting-started.md
  packages/docs/content/03-cluster-profiles.md
  packages/docs/content/04-clusters.md
  packages/docs/content/05-workspace.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-enterprise-version.md
  packages/docs/content/14-troubleshooting.md
  packages/docs/content/16-spectro-downloads.md
  packages/docs/content/17-glossary-all.md
Labels: size/M, needs-ok-to-test, ok-to-test

#519 Release 2.0.0
  CHANGES
Labels: ok-to-test

#520 cluster-profile-video-test
  packages/docs/content/03-cluster-profiles/1-task-define-profile.md
  packages/docs/content/03-cluster-profiles/aws-full-profile.mp4
Labels: size/XS, needs-ok-to-test, ok-to-test

#521 spell-check-01
  packages/docs/content/00-release-notes.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters/01-azure.md
  packages/docs/content/04-clusters/1-new-clusters/02-aks.md
  packages/docs/content/04-clusters/1-new-clusters/03-aws.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/07-openstack.md
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
  packages/docs/content/04-clusters/2-brownfield-clusters.md
  packages/docs/content/04-clusters/3-cluster-management/0-reconfigure.md
  packages/docs/content/04-clusters/3-cluster-management/1-cluster-updates.md
  packages/docs/content/04-clusters/3-cluster-management/2-health-alerts.md
  packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md
  packages/docs/content/04-clusters/3-cluster-management/4-os-patching.md
  packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/08-user-management/2-rbac.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/6-helm-charts.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
  packages/docs/content/12-enterprise-version/03-system-console-dashboard.md
  packages/docs/content/12-enterprise-version/04-enterprise-cluster-management.md
Labels: size/L, ok-to-test

#522 small-update-01
  packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#294 Portworx content updates about using secrets for credentials and the new presets option
  packages/docs/content/06-integrations/00-portworx.md
Labels: size/M, ok-to-test

#523 Prod push 210
  CHANGES
Labels: size/XS

#525 2.1.0-release-docs
  packages/docs/content/00-release-notes.md
  packages/docs/content/08-user-management.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/5-pack-constraints.md
  packages/docs/content/09-registries-and-packs/6-oci-registry.md
Labels: size/M, ok-to-test

#527 WOrkspace Review and release note edits
  packages/docs/content/00-release-notes.md
  packages/docs/content/05-workspace.md
  packages/docs/content/05-workspace/1-adding-a-new-workspace.md
  packages/docs/content/05-workspace/2-workload-visibility.md
Labels: size/L

#529 Update 00-release-notes.md
  packages/docs/content/00-release-notes.md
Labels: size/S

#524 18-nov-2021
  packages/docs/content/03-cluster-profiles.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/07-openstack.md
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
  packages/docs/content/04-clusters/3-cluster-management/0-reconfigure.md
  packages/docs/content/04-clusters/3-cluster-management/2-health-alerts.md
  packages/docs/content/04-clusters/3-cluster-management/4-os-patching.md
  packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md
  packages/docs/content/04-clusters/cluster_conditions.png
  packages/docs/content/04-clusters/cluster_services.png
  packages/docs/content/05-workspace.md
  packages/docs/content/09-registries-and-packs/6-oci-registry.md
  packages/docs/content/10-audit-logs.md
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/L, ok-to-test

#530 Fixed typos.
  packages/docs/content/00-release-notes.md
Labels: size/XS, needs-ok-to-test

#531 Release 2.1.0 to Prod
  CHANGES
Labels: ok-to-test

#535 cluster-profile-video-updated
  packages/docs/content/03-cluster-profiles/aws-full-profile.mp4
Labels: size/XS, needs-ok-to-test, ok-to-test

#536 k8s-packs-2.1.0
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#538 pack-update-01
  packages/docs/content/06-integrations/00-EKS-D.md
  packages/docs/content/06-integrations/eksd-cluster-profile.png
  packages/docs/content/06-integrations/eksd-cluster.png
Labels: size/M, needs-ok-to-test, ok-to-test

#537 2.1-k8s-1.20.12
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#533 2.1-rel-updates-01
  packages/docs/content/08-user-management.md
Labels: size/S, ok-to-test

#539 all-cluster-deployment-videos-added
  packages/docs/content/04-clusters/1-new-clusters/01-azure.md
  packages/docs/content/04-clusters/1-new-clusters/02-aks.md
  packages/docs/content/04-clusters/1-new-clusters/03-aws.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/05-gcp.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/07-openstack.md
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/aks.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/aws.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/azure.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/eks.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/google-cloud.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/maas.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/openstack.mp4
  packages/docs/content/04-clusters/1-new-clusters/cluster-creation-videos/vmware.mp4
Labels: size/M, ok-to-test

#534 Review - OCI registry
  packages/docs/content/09-registries-and-packs/6-oci-registry.md
Labels: size/M
