Repository spectrocloud/librarium, pull requests merged in 2021-09, with the labels that each got.

#444 typo fixes
  packages/docs/content/01-introduction/2-architecture-overview.md
  packages/docs/content/02-getting-started.md
  packages/docs/content/03-cluster-profiles.md
  packages/docs/content/03-cluster-profiles/2-task-update-profile.md
  packages/docs/content/03-cluster-profiles/3-examples.md
  packages/docs/content/04-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/2-brownfield-clusters.md
  packages/docs/content/04-clusters/3-cluster-updates.md
  packages/docs/content/06-integrations.mdx
  packages/docs/content/06-integrations/00-external-dns.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
  packages/docs/content/08-user-management/1-saml-sso.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
  packages/docs/content/16-glossary-all.md
Labels: size/L, needs-ok-to-test

#447 Update AWS SSO Sample URL
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: size/XS, needs-ok-to-test

#452 small fix
  packages/shared/src/components/common/QuickSetup.js
  packages/shared/src/layouts/Default/sidebar/treeNode.js
Labels: size/XS, needs-ok-to-test

#453 tabs-pages-01
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters/01-aks.md
  packages/docs/content/04-clusters/1-new-clusters/02-aws.md
  packages/docs/content/04-clusters/1-new-clusters/03-azure.md
  packages/docs/content/04-clusters/1-new-clusters/04-eks.md
  packages/docs/content/04-clusters/1-new-clusters/05-gcp.md
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
  packages/docs/content/04-clusters/1-new-clusters/07-openstack.md
  packages/docs/content/04-clusters/1-new-clusters/08-vmware.md
  packages/docs/content/04-clusters/1-new-clusters/aks_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/aws_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/azure_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/eks_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/gcp_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/maas_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/openstack_cluster_architecture.png
  packages/docs/content/04-clusters/1-new-clusters/vmware_arch_oct_2020.png
  packages/docs/content/04-clusters/1-new-clusters/vmware_cluster_architecture.png
  packages/docs/content/04-clusters/3-cluster-management.md
  packages/docs/content/04-clusters/3-cluster-management/1-scaling.md
  packages/docs/content/04-clusters/3-cluster-management/2-cluster-updates.md
  packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md
  packages/docs/content/04-clusters/3-cluster-management/4-os-patching.md
  packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md
Labels: size/XXL, needs-ok-to-test

#458 eks-d-new
  packages/docs/content/06-integrations/00-EKS-D.md
  packages/docs/content/06-integrations/eksd-cluster-profile.png
  packages/docs/content/06-integrations/eksd-cluster.png
Labels: size/M, needs-ok-to-test

#463 Introduction to Spectro Cloud
  packages/docs/content/01-introduction.md
  packages/docs/content/01-introduction/1-what-is-sc.png
  packages/docs/content/01-introduction/1-what-is.md
  packages/docs/content/01-introduction/2-architecture-overview.md
  packages/docs/content/01-introduction/2-what-is-sc.png
Labels: size/M, needs-ok-to-test, ok-to-test
