Repository spectrocloud/librarium, pull requests merged in 2021-01, with the labels that each got.

#284 Fix typo in aws permissions
  packages/docs/content/04-clusters.md
Labels: size/XS

#285 Remove cmd prompt
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
  packages/docs/content/09-registries-and-packs/3-add-custom-packs.md
  packages/docs/content/09-registries-and-packs/4-adding-add-on-packs.md
Labels: size/M

#283 Correcting typos
  packages/docs/content/02-getting-started.md
Labels: needs-ok-to-test, size/XS

#286 Fix wget cmds
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS

#287 add missing IAM permissions for hubble
  packages/docs/content/04-clusters.md
Labels: needs-ok-to-test, size/S

#290 add gcp min permissions
  packages/docs/content/04-clusters.md
Labels: size/M

#291 Update 03-cluster-profiles.md
  packages/docs/content/03-cluster-profiles.md
Labels: size/S
