Repository spectrocloud/librarium, pull requests merged in 2021-04, with the labels that each got.

#322 Minor typos fixed
  CHANGES
Labels: ok-to-test, size/XS

#323 cluster-updates-grammar-check
  packages/docs/content/04-clusters/3-cluster-updates.md
Labels: approved, ok-to-test, size/XS

#325 Spell grammar updates
  packages/docs/content/01-introduction/2-concept-overviews.md
  packages/docs/content/02-getting-started.md
Labels: approved, ok-to-test, size/XS

#328 operating-system
  packages/docs/content/06-integrations/00-centos.md
  packages/docs/content/06-integrations/00-ubuntu.md
Labels: approved, ok-to-test, size/M

#330 Troubleshoot page n/w ports image updated
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/14-troubleshooting/network_communication_ports.png
Labels: approved, ok-to-test, size/M

#327 small icon fix index page
  packages/docs/content/00-index.mdx
Labels: ok-to-test, size/XS

#332 Added zoom to images
  package-lock.json
  packages/website/gatsby-config.js
  packages/website/package-lock.json
  packages/website/package.json
Labels: ok-to-test, size/XL

#336 small fixes
  packages/shared/src/components/common/PointOfInterest.js
  packages/shared/src/components/styles/Sidebar.js
  packages/shared/src/components/ui/Tooltip.js
  packages/website/gatsby-config.js
Labels: needs-ok-to-test, size/XS

#334 1.9 Features
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/3-cluster-updates.md
  packages/docs/content/04-clusters/4-cluster-features.md
  packages/docs/content/14-troubleshooting/network_communication_ports.png
Labels: approved, ok-to-test, size/M
