Repository spectrocloud/librarium, pull requests merged in 2021-08, with the labels that each got.

#421 PCG install instructions
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/L

#424 VMWare -> AKS cluster descriptor
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: needs-ok-to-test, ok-to-test, size/XS

#422 Compliance page updated
  packages/docs/content/00-release-notes.md
  packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md
  packages/docs/content/15-compliance.md
  packages/docs/content/aws-tech-partner.png
  packages/docs/content/crn.png
  packages/docs/content/ema.png
  packages/docs/content/harshicorp.png
  packages/docs/content/pci-dss.png
  packages/docs/content/soc2.png
  packages/docs/content/terraform.png
Labels: size/M, needs-ok-to-test, ok-to-test

#423 Open Stack Updates
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/M, needs-ok-to-test, ok-to-test

#425 1.12-updates-aks-oidc
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#428 Update 00-release-notes.md
  packages/docs/content/00-release-notes.md
Labels: size/S

#429 Update 1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/M

#430 Update 1-saml-sso.md
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: size/S

#431 Identity Provider Info
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: size/L, ok-to-test

#433 Update 1-saml-sso.md
  packages/docs/content/08-user-management/1-saml-sso.md
Labels: size/S

#432 adding-custom-registry updated
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS, ok-to-test

#434 Release 1.12 Changes
  CHANGES
Labels: size/XS

#435 1.13.0 Release Docs
  packages/docs/content/00-release-notes.md
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/09-registries-and-packs.md
  packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
  packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XXL, ok-to-test

#427 design changes - introduction layout
  packages/api/config.js
  packages/api/src/components/ApiSidebar.js
  packages/docs/config.js
  packages/docs/content/00-index.mdx
  packages/docs/content/01-introduction.md
  packages/docs/src/components/Integrations/CategorySelector.js
  packages/docs/src/components/Integrations/Search.js
  packages/docs/src/components/Integrations/index.js
  packages/shared/src/assets/clouds/aws.png
  packages/shared/src/assets/clouds/azure.png
  packages/shared/src/assets/clouds/google_cloud.png
  packages/shared/src/assets/clouds/vmware.png
  packages/shared/src/assets/hero.png
  packages/shared/src/assets/logo_landscape_for_white.png
  packages/shared/src/components/Box.js
  packages/shared/src/components/Intro.js
  packages/shared/src/components/Logo.js
  packages/shared/src/components/Next.js
  packages/shared/src/components/Previous.js
  packages/shared/src/components/TableOfContents.js
  packages/shared/src/components/common/CloudsSection.js
  packages/shared/src/components/common/DocUpdatesSection.js
  packages/shared/src/components/common/MainHeader.js
  packages/shared/src/components/common/QuickSetup.js
  packages/shared/src/components/styles/Docs.js
  packages/shared/src/components/styles/PageNavigationButtons.js
  packages/shared/src/components/styles/Sidebar.js
  packages/shared/src/components/ui/Button.js
  packages/shared/src/components/ui/Tabs.js
  packages/shared/src/layouts/Default/Header.js
  packages/shared/src/layouts/Default/index.js
  packages/shared/src/layouts/Default/layout.css
  packages/shared/src/layouts/Default/search/hitComps.js
  packages/shared/src/layouts/Default/search/index.js
  packages/shared/src/layouts/Default/search/input.js
  packages/shared/src/layouts/Default/sidebar/index.js
  packages/shared/src/layouts/Default/sidebar/treeNode.js
  packages/shared/src/mdx/components/index.js
  packages/shared/src/theme/index.js
  packages/website/gatsby-config.js
  packages/website/src/pages/404.js
Labels: size/XXL, ok-to-test

#439 Update 15-compliance.md
  packages/docs/content/15-compliance.md
Labels: size/M

#440 small redesign fixes
  packages/shared/src/components/styles/Docs.js
  packages/shared/src/layouts/Default/layout.css
  packages/shared/src/layouts/Default/sidebar/treeNode.js
  packages/website/gatsby-config.js
Labels: size/M, needs-ok-to-test

#443 pack-constraints-page-moved-01
  packages/docs/content/04-clusters.md
  packages/docs/content/06-integrations/00-calico.md
  packages/docs/content/06-integrations/00-citrix-ipam.md
  packages/docs/content/06-integrations/00-collectord.md
  packages/docs/content/06-integrations/00-dex.md
  packages/docs/content/06-integrations/00-external-dns.md
  packages/docs/content/06-integrations/00-falco.md
  packages/docs/content/06-integrations/00-istio.md
  packages/docs/content/06-integrations/00-kong.md
  packages/docs/content/06-integrations/00-kubernetes-dashboard.md
  packages/docs/content/06-integrations/00-kubevious.md
  packages/docs/content/06-integrations/00-metallb.md
  packages/docs/content/06-integrations/00-nginx.md
  packages/docs/content/06-integrations/00-permission-manager.md
  packages/docs/content/06-integrations/00-prometheus-operator.md
  packages/docs/content/06-integrations/00-vault.md
  packages/docs/content/09-registries-and-packs/5-pack-constraints.md
Labels: size/L, ok-to-test

#446 bug-doc-77
  packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#445 pack preset update
  packages/docs/content/09-registries-and-packs/5-pack-constraints.md
  packages/docs/content/16-glossary-all.md
Labels: size/L, ok-to-test

#442 centered search
  packages/shared/src/layouts/Default/search/index.js
  packages/shared/src/layouts/Default/search/input.js
Labels: size/M, needs-ok-to-test
