Repository spectrocloud/librarium, pull requests merged in 2022-09, with the labels that each got.

#859 Adding pre-requisite to Workspace Management
  content/docs/05-workspace/1-adding-a-new-workspace.md
Labels: size/XS, ok-to-test

#858 2.8-HF-associate-oidc-provider
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/S, needs-ok-to-test, ok-to-test

#851 BET-6194 Links not displayed in document boxes
  README.md
Labels: size/S, needs-ok-to-test

#861 DOC-254-RKE2-Kubernetes
  content/docs/06-integrations/00-rke2.md
  content/docs/06-integrations/rke2-cluster-profile.png
  package-lock.json
Labels: size/XXL, ok-to-test

#862 Doc -275-Edge-Update
  content/docs/04-clusters/1-new-clusters/05-edge.md
  content/docs/04-clusters/1-new-clusters/native-edge.png
Labels: size/M, ok-to-test

#854 DOC-251-Nested-Cluster
  content/docs/04-clusters/4-nested-clusters.md
  content/docs/04-clusters/4-nested-clusters/create-host-cluster.png
  content/docs/04-clusters/4-nested-clusters/deploy-nested-cluster.png
  content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/4-nested-clusters/record-details.png
Labels: size/L, ok-to-test

#866 Revert "DOC-254-RKE2-Kubernetes (#861)"
  content/docs/06-integrations/00-rke2.md
  content/docs/06-integrations/rke2-cluster-profile.png
  package-lock.json
Labels: size/XXL, ok-to-test

#867 Doc-254-Restore-RKE
  content/docs/06-integrations/00-rke2.md
  content/docs/06-integrations/rke2-cluster-profile.png
Labels: size/S, ok-to-test

#865 updates and fixes for portworx 2.11.2
  content/docs/06-integrations/00-portworx_operator.md
Labels: size/XL, needs-ok-to-test, ok-to-test

#847 2.8-Enhancement-OS-Patch-monitoring
  content/docs/04-clusters/3-cluster-management/04-os-patching.md
Labels: size/S, needs-ok-to-test, ok-to-test

#844 release2.8-profile-import-export
  content/docs/03-cluster-profiles/3-cluster-profile-import-export.md
  content/docs/03-cluster-profiles/4-examples.md
  content/docs/03.5-system-profile.md
Labels: size/L, ok-to-test

#856 release-2.8-Webctl
  content/docs/04-clusters/3-cluster-management.md
  content/docs/04-clusters/3-cluster-management/12-palette-webctl.md
Labels: size/L, ok-to-test

#868 eks-troubleshoot
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#864 add-iam-policy-node-level
  content/docs/04-clusters/1-new-clusters/01-aws.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#863 2.8-enhancement-set-resource-limit
  content/docs/08-user-management/3-palette-resource-limits.md
Labels: size/S, needs-ok-to-test, ok-to-test

#857 2.8-Release-cluster-lock
  content/docs/04-clusters/3-cluster-management/13-palette-lock-cluster.md
Labels: size/M, ok-to-test

#845 2.8 Release Feature : google-idp
  content/docs/08-user-management/4-saml-sso.md
Labels: size/S, needs-ok-to-test, ok-to-test

#860 2.8-hf-regex
  content/docs/05-workspace.md
Labels: size/S, ok-to-test

#869 iam-policy-select
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/L, ok-to-test

#870 RKE2-Updates
  content/docs/06-integrations/00-rke2.md
Labels: size/M, ok-to-test

#873 2.8-release-notes
  content/docs/00-release-notes.md
Labels: size/M

#804 Doc-213-Ubuntu-v20-cc-eal-disabled
  content/docs/06-integrations/00-ubuntu.md
Labels: size/M, ok-to-test

#872 iam-policy-descptn
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/M, ok-to-test

#874 AWS-Nested-Clusters
  content/docs/04-clusters/1.5-nested-clusters.md
  content/docs/04-clusters/2-nested-clusters/create-host-cluster.png
  content/docs/04-clusters/2-nested-clusters/deploy-nested-cluster.png
  content/docs/04-clusters/2-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/2-nested-clusters/record-details.png
Labels: size/M, ok-to-test

#831 DOC-229-Ubuntu-K3s-pack
  content/docs/06-integrations/00-ubuntu-k3s.md
Labels: size/M, ok-to-test

#825 Doc-226-cni-multus
  content/docs/06-integrations/00-multus-cni.md
Labels: size/M, ok-to-test

#876 Update 05-backup-restore.md
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
Labels: size/XS

#880 minio-pem-203
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
Labels: size/S, needs-ok-to-test, ok-to-test

#877 2.8-hf-azure-diable-prop
  content/docs/04-clusters/1-new-clusters/03-azure.md
  content/docs/04-clusters/1-new-clusters/04-aks.md
Labels: size/M, ok-to-test

#879 2.8-release-cli-registries
  content/docs/00-release-notes.md
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/16-component.md
Labels: size/S, ok-to-test

#881 2.8 Production Push
  CHANGES
Labels: size/XS

#882 Update 16-component.md
  content/docs/16-component.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#884 quick-fix-2.8
  content/docs/00-release-notes.md
  content/docs/04-clusters/3-cluster-management/13-palette-lock-cluster.md
Labels: size/M, needs-ok-to-test, ok-to-test

#883 Update nested-cluster-quickstart.md
  content/docs/04-clusters/1.5-nested-clusters.md
  content/docs/04-clusters/2-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/2-nested-clusters/record-details.png
Labels: size/L, ok-to-test

#887 rearranging
  content/docs/04-clusters/04-nested-clusters.md
  content/docs/04-clusters/04-nested-clusters/create-host-cluster.png
  content/docs/04-clusters/04-nested-clusters/deploy-nested-cluster.png
  content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/04-nested-clusters/record-details.png
Labels: size/XS, needs-ok-to-test, ok-to-test

#818 Doc 225 generic vm libvirt v1.0.0
  content/docs/06-integrations/00-generic-vm-libvirt.md
Labels: size/L, ok-to-test

#893 links-update-02
  content/docs/00-index.mdx
  content/docs/00-release-notes.md
  content/docs/02-getting-started/04-onboarding-workflow.md
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/02-eks.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/04-aks.md
  content/docs/04-clusters/01-public-cloud/06-tke.md
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
  content/docs/05-workspace/1-adding-a-new-workspace.md
  content/docs/06-integrations/00-rke2.md
Labels: size/M, ok-to-test

#890 tf-0.9.1-release
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#891 vsphere-csi-compatibility-matrix
  content/docs/06-integrations/00-vsphere-csi.md
Labels: size/S, needs-ok-to-test, ok-to-test

#896 Palette 2.8 API collection
  content/api/palette-apis.json
Labels: size/XXL, needs-ok-to-test, ok-to-test

#888 DOC-302-Importing-a-Brownfield-Cluster
  content/docs/04-clusters/05-brownfield-clusters.md
Labels: size/M, ok-to-test

#898 DOC-339-on-prem
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/S, ok-to-test

#885 SSO-and-AzureAD
  content/docs/08-user-management/4-saml-sso.md
  content/docs/08-user-management/azure-app-registration.png
  content/docs/08-user-management/client-config.png
  content/docs/08-user-management/enterprise-app-registration.png
  content/docs/08-user-management/kubeadmconfig.png
  content/docs/08-user-management/notable-variables.png
Labels: size/L, ok-to-test

#900 Doc-226-Azure-minor-edits
  content/docs/08-user-management/4-saml-sso.md
Labels: size/XS, size/S, ok-to-test

#899 To resolve for stale pr
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/02-eks.md
Labels: size/XL, needs-ok-to-test, ok-to-test

#889 New tutorial for Terraform and practicing with CKS
  content/docs/18-knowledgebase.md
  content/docs/18-knowledgebase/00-how-to.md
  content/docs/18-knowledgebase/00-how-to/00-how-to.md
  content/docs/18-knowledgebase/01-tutorials.md
  content/docs/18-knowledgebase/01-tutorials/1-terraform-tutorial.md
  content/docs/18-knowledgebase/01-tutorials/2-cks-tutorial.md
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-bastion-host.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-cleanup.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-instance-ip.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-instance-summary.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-preview-stack.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/cks-workshop.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/my-cks-cloud-account.png
  content/docs/18-knowledgebase/01-tutorials/cks-tutorial-images/my-cks-workshop-basic.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/newly-created-cluster.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/terraform-finished-install.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-apply.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-create-missing-resources.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-destroy-complete.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-destroy.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-execution-plan.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-finished-installing.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-initialized.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-initializing.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-kubeflow.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-provision-plan.png
  content/docs/18-knowledgebase/01-tutorials/tf-tutorial-images/tf-provisioned-cluster.png
Labels: size/XL, ok-to-test
