Repository spectrocloud/librarium, pull requests merged in 2022-06, with the labels that each got.

#723 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#727 Replace-image-03-cluster-profile-file
  content/docs/03-cluster-profiles.md
  content/docs/03-cluster-profiles/cluster_profile_azure.png
Labels: size/M, needs-ok-to-test, ok-to-test

#730 terraform-0.7.2
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#735 prod-push-jun22
  CHANGES
Labels: size/XS, ok-to-test

#718 cilium-network-pack
  content/docs/06-integrations/00-cilium.md
Labels: size/M, ok-to-test

#737 On-Prem configuration Updates
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/S, ok-to-test

#724 Roles and Perms Matrix
  content/docs/08-user-management/4-roles-permissions-and-project-scope.md
  content/docs/08-user-management/5-roles-permissions-and-tenant-scope.md
Labels: size/XL, ok-to-test

#734 kube-bench v.0.6.8
  content/docs/06-integrations/00-kubebench.md
Labels: size/M, ok-to-test

#740 Updated-DOC-175-00-On-Prem
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/L, ok-to-test

#743 Roles-and-Perms-without-links
  content/docs/08-user-management/4-roles-permissions-and-project-scope.md
  content/docs/08-user-management/5-roles-permissions-and-tenant-scope.md
Labels: size/S, ok-to-test

#744 On-Prem removed artifact
  content/docs/06-integrations/00-kubebench.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XS, ok-to-test

#742 Doc-140-New-AWS-EFS
  content/docs/06-integrations/00-aws-efs.md
Labels: size/L, ok-to-test

#745 added logo and nav
  content/docs/06-integrations/00-aws-efs.md
  content/docs/06-integrations/00-kubebench.md
Labels: size/XS, ok-to-test

#746 NoNav
  content/docs/06-integrations/00-aws-efs.md
  content/docs/06-integrations/00-kubebench.md
Labels: size/S, ok-to-test

#750 Roles&perms&on prem updates
  content/docs/08-user-management/4-roles-permissions-and-project-scope.md
  content/docs/08-user-management/4-roles-permissions-and-tenant-scope.md
  content/docs/08-user-management/5-roles-permissions-and-project-scope.md
  content/docs/08-user-management/5-roles-permissions-and-tenant-scope.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XXL, ok-to-test

#753 Prod Push Jun 18
  CHANGES
Labels: size/XS

#739 cluster-creation-video-updates
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/04-aks.md
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/aks.mp4
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/aws.mp4
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/azure.mp4
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/eks.mp4
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/google-cloud.mp4
  content/docs/04-clusters/1-new-clusters/cluster-creation-videos/openstack.mp4
Labels: size/M, needs-ok-to-test, ok-to-test

#751 on-prem-installer-2.6-rel
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#755 Doc-179-Openstack_Cinder_CSI_1.22_1.23
  content/docs/06-integrations/00-openstack-cinder.md
Labels: size/S, ok-to-test

#759 DOC-194
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/M, ok-to-test

#757 small-correction
  content/docs/04-clusters/3-cluster-management/02-health-alerts.md
Labels: size/M, ok-to-test

#760 Appzi feedback
  content/docs/01-introduction/2-architecture-overview.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#761 prod-push-june22
  CHANGES
Labels: size/XS, ok-to-test

#762 vds-permission
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/M, needs-ok-to-test, ok-to-test

#763 minor-fix
  content/docs/08-user-management/2-palette-rbac.md
Labels: size/XS, needs-ok-to-test, ok-to-test
