Repository spectrocloud/librarium, pull requests merged in 2022-11, with the labels that each got.

#960 3.0.x api changes
  content/api/palette-apis.json
  content/api/v1/api.json
Labels: size/XXL, needs-ok-to-test, ok-to-test

#961 doc-390
  content/docs/04.5-devx.md
  content/docs/04.5-devx/03-cluster-groups.md
  content/docs/04.5-devx/04-resource-quota.md
  content/docs/04.5-devx/07-sandbox-clusters.md
Labels: size/M, needs-ok-to-test, ok-to-test

#963 docs: added more context pertatining to the certificate field
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: documentation, size/XS, ok-to-test

#957 macro-app-profile
  content/docs/04.5-devx/05-app-profile.md
Labels: size/M, ok-to-test

#966 chore: push to production
  CHANGES
Labels: documentation, size/XS, ok-to-test

#968 Add FIPS cert
  content/docs/15-compliance.md
Labels: size/S, ok-to-test

#969 Production release
  CHANGES
Labels: documentation, size/XS, ok-to-test

#970 Update 02-native.md
  content/docs/04-clusters/03-edge/02-native.md
Labels: size/M, ok-to-test

#975 Added links for level 3 Headings
  src/shared/components/styles/Docs.js
  src/shared/mdx/components/index.js
Labels: size/L, needs-ok-to-test

#973 docs: production release
  CHANGES
Labels: size/XS, needs-ok-to-test, ok-to-test

#978 docs: restructuring of the terraform provider section
  content/docs/13-terraform.md
  content/docs/13-terraform/01-resources.md
  content/docs/13-terraform/02-datasources.md
  src/shared/utils/redirects.js
Labels: documentation, size/XL, ok-to-test

#979 Add scan for local env
  Makefile
  package-lock.json
  package.json
Labels: size/XXL, needs-ok-to-test, ok-to-test

#977 quick-fix
  content/docs/06-integrations/00-generic-vm-libvirt.md
  content/docs/06-integrations/00-generic-vm-vsphere.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#980 Prod 11 11
  CHANGES
Labels: documentation, size/XS, ok-to-test

#971 chore: added solution for checking broken links locally
  .gitignore
  Makefile
  README.md
  package-lock.json
  package.json
Labels: enhancement, size/XXL, ok-to-test, dependencies

#897 csi-parameter-removed
  content/docs/06-integrations/00-vsphere-csi.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#981 Add Postman collection
  content/api/3-postman-collection.md
  content/api/URL-as-a-link.png
Labels: size/M, ok-to-test

#983 Tf update
  content/docs/13-terraform.md
Labels: documentation, size/XS, ok-to-test

#987 Add Postman Collection date
  CHANGES
Labels: documentation, size/XS, ok-to-test

#909 logo-remove-shpcg
  content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#982 DO NOT MERGE - resource-color-bar
  content/docs/04.5-devx/07-palette-virtual-clusters.md
  content/docs/04.5-devx/color-tracking.png
Labels: size/M, ok-to-test

#989 rearrange-read-me
  README.md
Labels: size/M, ok-to-test

#994 Postman fix
  content/api/3-postman-collection.md
Labels: size/XS, ok-to-test

#995 Edge docs remedy
  content/docs/04-clusters/03-edge.md
  content/docs/04-clusters/03-edge/01-virtualized.md
Labels: size/M, ok-to-test

#993 docs: information
  content/docs/04.5-devx/05-app-profile.md
  content/docs/04.5-devx/05-app-profile/00-create-app-profile.md
  content/docs/04.5-devx/05-app-profile/03-app-profile-cloning.md
  content/docs/04.5-devx/05-app-profile/03-app-profile-macros.md
  content/docs/04.5-devx/05-app-profile/04-app-profile-cloning.md
  content/docs/04.5-devx/05-app-profile/05-versioning-app-profile.md
Labels: size/L, ok-to-test

#1000 Devx 24n
  content/docs/04.5-devx/05-app-profile/00-create-app-profile.md
  content/docs/04.5-devx/05-app-profile/04-app-profile-cloning.md
  content/docs/04.5-devx/05-app-profile/05-versioning-app-profile.md
Labels: size/M, needs-ok-to-test, ok-to-test

#841 Replaced video syntax + added video plugin
  content/docs/03-cluster-profiles/1-task-define-profile.md
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/02-eks.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/04-aks.md
  content/docs/04-clusters/01-public-cloud/05-gcp.md
  content/docs/04-clusters/02-data-center/01-maas.md
  content/docs/04-clusters/02-data-center/02-openstack.md
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/04-clusters/05-brownfield-clusters.md
  gatsby-config.js
  package-lock.json
  package.json
  src/shared/mdx/components/index.js
Labels: size/XL, ok-to-test

#990 Glossary additions
  content/docs/17-glossary-all.md
Labels: documentation, size/S

#1006 3.0.x API changes (Azure, CoxEdge changes)
  content/api/palette-apis.json
  content/api/v1/api.json
Labels: size/XXL, ok-to-test

#1005 cilium-tetragon
  content/docs/06-integrations/00-cilium-tetragon.md
  content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md
Labels: size/L, needs-ok-to-test, ok-to-test

#1004 Video readme
  README.md
  content/docs/06-integrations/00-cilium-tetragon.md
Labels: documentation, size/S, ok-to-test

#1007 Update new Virtual Cluster limits
  content/docs/04.5-devx/07-palette-virtual-clusters.md
Labels: documentation, size/XS, ok-to-test

#992 Doc 411 debug for cluster creation getting stuck
  content/docs/14-troubleshooting/04-cluster-deployment.md
Labels: size/L

#1002 Doc 410
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/04.5-devx/05-app-profile/02-container-deployment.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/M, ok-to-test

#1001 Container Deployment Update
  content/docs/04.5-devx/05-app-profile/02-container-deployment.md
Labels: size/M, ok-to-test

#650 verto markup schemas
  src/shared/utils/markupSchemas.js
  src/templates/api.js
  src/templates/docs.js
Labels: size/M, ok-to-test

#1010 docs: terraform related changes and minor header fix
  content/docs/13-terraform.md
  content/docs/14-troubleshooting/04-cluster-deployment.md
Labels: size/XS, ok-to-test
