Repository spectrocloud/librarium, pull requests merged in 2022-08, with the labels that each got.

#813 Remove robots for Production push
  prow/functions.sh
Labels: size/XS, approved, needs-ok-to-test, ok-to-test

#820 terraform-update-0.8.8
  content/docs/13-terraform.md
Labels: size/M, needs-ok-to-test, ok-to-test

#821 sample-NameOverride
  content/docs/03-cluster-profiles/1-task-define-profile.md
Labels: size/S, ok-to-test

#824 BET-5982: Added 'iam:ListPolicies' in Deployment Policy
  content/docs/04-clusters/1-new-clusters/01-aws.md
Labels: size/XS

#822 :memo: Update Docs: Fix Grammatical Issues
  content/docs/01-introduction/1-what-is.md
Labels: size/M, ok-to-test

#809 Doc-178-Portworx-Vsphere-2.9-2.10
  content/docs/06-integrations/00-portworx.md
Labels: size/L, ok-to-test

#796 [WIP] update aks nodepool configurates
  content/docs/04-clusters/1-new-clusters/04-aks.md
Labels: size/L, ok-to-test

#829 Doc 192 portworx aws 2.9 & 2.10
  content/docs/06-integrations/00-portworx.md
Labels: size/L, needs-ok-to-test, ok-to-test

#814 S3 Permission Update
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
  content/docs/05-workspace/2-workload-features.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#811 api-rate-limit
  content/docs/08-user-management/3-palette-resource-limits.md
Labels: size/XS, ok-to-test

#803 Workspace Visibility
  content/docs/05-workspace/2-workload-features.md
Labels: size/XS, ok-to-test

#828 few-updates
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/M, ok-to-test

#832 Update 11-vmware.md
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#835 vds-permission
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#836 Prod push aug18
  CHANGES
Labels: size/XS, ok-to-test

#838 add portworx_operator docs
  content/docs/06-integrations/00-portworx_operator.md
Labels: size/XL, ok-to-test

#826 Changed disruptive video plugin
  content/docs/03-cluster-profiles/1-task-define-profile.md
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
  content/docs/04-clusters/1-new-clusters/03-azure.md
  content/docs/04-clusters/1-new-clusters/04-aks.md
  content/docs/04-clusters/1-new-clusters/06-gcp.md
  content/docs/04-clusters/1-new-clusters/07-maas.md
  content/docs/04-clusters/1-new-clusters/08-openstack.md
  content/docs/04-clusters/1-new-clusters/11-vmware.md
  content/docs/04-clusters/2-brownfield-clusters.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: size/XXL, needs-ok-to-test

#800 adding docker support
  Dockerfile
  Makefile
  scripts/entry.sh
Labels: size/M, needs-ok-to-test

#833 azure-oci-registry
  content/docs/09-registries-and-packs/6-oci-registry.md
Labels: size/M, needs-ok-to-test, ok-to-test

#837 tf-minor-rlse-8.9
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#812 version-update-pcks
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-azure-disk.md
  content/docs/06-integrations/00-nginx.md
  content/docs/06-integrations/00-prometheus-operator.md
Labels: size/M, ok-to-test

#842 doc-245
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#850 gke-autopilot
  content/docs/04-clusters/2-brownfield-clusters.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#846 2.8 Hot Fix EBS-K8s-Permissions
  content/docs/06-integrations/00-aws-ebs.md
Labels: size/L, ok-to-test

#830 istio-version-update
  content/docs/06-integrations/00-istio.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#853 Update 01-aws.md
  content/docs/04-clusters/1-new-clusters/01-aws.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#849 2.8 api docs
  content/api/v1/api.json
Labels: size/XXL, needs-ok-to-test, ok-to-test

#852 quick-fix
  content/docs/04-clusters/1-new-clusters/11-vmware.md
  content/docs/06-integrations/00-kubernetes.md
Labels: size/XS, ok-to-test

#855 terraform-rel-0.9.0
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#819 Doc-134-KubeVirt-0.51.0-and-0.55.0
  content/docs/06-integrations/00-kubevirt.md
Labels: size/M, ok-to-test
