Repository spectrocloud/librarium, pull requests merged in 2022-10, with the labels that each got.

#827 DOC-218-external-secrets-operator
  content/docs/06-integrations/00-external-secrets-operator.md
Labels: size/M, ok-to-test

#895 azure-self-hosted-pcg
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md
  content/docs/04-clusters/01-public-cloud/04-aks.md
Labels: size/L, ok-to-test

#903 link-updates
  content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md
Labels: size/S, needs-ok-to-test, ok-to-test

#904 Update 1-gateways.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md
  content/docs/04-clusters/01-public-cloud/04-aks.md
Labels: size/S, needs-ok-to-test, ok-to-test

#905 Revert "To resolve for stale pr"
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/02-eks.md
Labels: size/L

#907 prod push 5thOct
  CHANGES
Labels: size/XS, ok-to-test

#908 How-to-dim-until ready
  content/docs/18-knowledgebase/00-how-to.md
  content/docs/18-knowledgebase/00-how-to/00-how-to.md
  content/docs/18-knowledgebase/01-tutorials/2-cks-tutorial.md
Labels: size/XS, ok-to-test

#901 aws-autoscaler
  content/docs/06-integrations/00-aws-autoscaler.md
Labels: size/M, needs-ok-to-test, ok-to-test

#817 Doc-222-generic-vm-vsphere-v1.0.0
  content/docs/06-integrations/00-generic-vm-vsphere.md
Labels: size/L, ok-to-test

#912 gke-nested-cluster-info
  content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
Labels: size/XS, ok-to-test

#902 project-id-introduction
  content/api/1-introduction.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#915 DOC-333-SAML-SSO-and-Azure-AD
  content/docs/08-user-management/4-saml-sso.md
  content/docs/08-user-management/oidc-azure-images/azure-app-registration.png
  content/docs/08-user-management/oidc-azure-images/client-config.png
  content/docs/08-user-management/oidc-azure-images/enterprise-app-registration.png
  content/docs/08-user-management/oidc-azure-images/kubeadmconfig.png
  content/docs/08-user-management/oidc-azure-images/notable-variables.png
  content/docs/08-user-management/saml-azure-images/saml-azure-assign-users-and-groups.png
  content/docs/08-user-management/saml-azure-images/saml-azure-assigned-user-groups.png
  content/docs/08-user-management/saml-azure-images/saml-azure-basic-saml-config.png
  content/docs/08-user-management/saml-azure-images/saml-azure-config-identifier.png
  content/docs/08-user-management/saml-azure-images/saml-azure-default-ad-users.png
  content/docs/08-user-management/saml-azure-images/saml-azure-enterprise-all-app.png
  content/docs/08-user-management/saml-azure-images/saml-azure-federation-metadata-xml.png
  content/docs/08-user-management/saml-azure-images/saml-azure-identifier-entryid.png
  content/docs/08-user-management/saml-azure-images/saml-azure-logout-url.png
  content/docs/08-user-management/saml-azure-images/saml-azure-name.png
  content/docs/08-user-management/saml-azure-images/saml-azure-project-viewer.png
  content/docs/08-user-management/saml-azure-images/saml-azure-reply-url.png
  content/docs/08-user-management/saml-azure-images/saml-azure-saml-select.png
  content/docs/08-user-management/saml-azure-images/saml-azure-sign-on-url.png
  content/docs/08-user-management/saml-azure-images/saml-azure-team-create.png
  content/docs/08-user-management/saml-azure-images/saml-azure-users-and-group-assign.png
  content/docs/08-user-management/saml-azure-images/saml-group-example.png
Labels: size/L, size/XL, ok-to-test

#916 Release-3.0-Dev-Engine
  content/docs/04-clusters/04-nested-clusters.md
  content/docs/04-clusters/04-sandbox-clusters.md
  content/docs/04-clusters/04-sandbox-clusters/create-host-cluster.png
  content/docs/04-clusters/04-sandbox-clusters/deploy-nested-cluster.png
  content/docs/04-clusters/04-sandbox-clusters/record-details.png
  content/docs/04-clusters/04-sandbox-clusters/sandbox-cluster-quickstart.md
  content/docs/04.5-devx.md
  content/docs/04.5-devx/01-dev-land-explore.md
  content/docs/04.5-devx/02-enterprise-user.md
  content/docs/04.5-devx/03-cluster-groups.md
  content/docs/04.5-devx/04-resource-quota.md
  content/docs/04.5-devx/05-app-profile.md
  content/docs/04.5-devx/06-apps.md
  content/docs/04.5-devx/07-sandbox-clusters.md
  content/docs/04.5-devx/08-registries.md
  content/docs/04.5-devx/09-manage-dev-engine.md
  content/docs/04.5-devx/dev-enterprise.png
  content/docs/04.5-devx/devx-start.png
Labels: size/XL, ok-to-test

#919 Release 3.0.0 edge documentation
  content/docs/04-clusters/03-edge.md
  content/docs/04-clusters/03-edge/01-virtualized.md
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/04-clusters/03-edge/02-native/01-native-day2.md
  content/docs/04-clusters/03-edge/native-edge.png
  content/docs/04-clusters/03-edge/virtualized-edge.png
  content/docs/17-glossary-all.md
Labels: size/XXL, ok-to-test

#894 tf-0.10.0
  content/docs/13-terraform.md
Labels: size/M, ok-to-test

#922 Remove beta in edge
  content/docs/04-clusters/03-edge.md
Labels: size/M, ok-to-test

#929 fix registrationURL
  content/docs/04-clusters/03-edge/02-native.md
Labels: size/XS

#926 rel-3.0-maxpodlimit-aks
  content/docs/04-clusters/01-public-cloud/04-aks.md
Labels: size/S, ok-to-test

#923 3.0-Feature-reverse-proxy-dashboard
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
  content/docs/05-workspace.md
  content/docs/05-workspace/2-workload-features.md
  content/docs/18-knowledgebase/00-how-to.md
  content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md
Labels: size/L, needs-ok-to-test, ok-to-test

#920 3.0.0-noc-ui
  content/docs/04-clusters/06-cluster-management/14-noc-ui.md
Labels: size/M, needs-ok-to-test, ok-to-test

#921 3.0-azure-bkup
  content/docs/04-clusters/06-cluster-management/05-backup-restore.md
  content/docs/05-workspace/2-workload-features.md
Labels: size/L, ok-to-test

#934 Update 03-edge.md
  content/docs/04-clusters/03-edge.md
Labels: size/S

#925 DOC-375 Palette 3.0 API docs update
  content/api/palette-apis.json
  content/api/v1/02-appDeployments.md
  content/api/v1/18-pcg.md
  content/api/v1/20-appProfiles.md
  content/api/v1/22-clustergroups.md
  content/api/v1/api.json
Labels: size/XXL, ok-to-test

#930 terraform-10.1
  content/docs/13-terraform.md
Labels: size/M, ok-to-test

#935 Update 02-native.md
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/04-clusters/03-edge/02-native/01-native-day2.md
  content/docs/04-clusters/03-edge/native-edge-deployment-lifecycle.png
Labels: size/XXL

#932 cli-registries-update
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/16-component.md
Labels: size/S, ok-to-test

#924 rel-3.0-auto-remediation
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/13-palette-lock-cluster.md
Labels: size/M, ok-to-test

#936 tkt-plt-95
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/13-terraform.md
Labels: size/M, needs-ok-to-test, ok-to-test

#933 3.0-release-notes
  content/docs/00-release-notes.md
Labels: size/M, ok-to-test

#938 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#937 3.0-pack-updates
  content/docs/04.5-devx.md
  content/docs/06-integrations/00-aws-autoscaler.md
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-calico.md
  content/docs/06-integrations/00-certmanager.md
  content/docs/06-integrations/00-dex.md
  content/docs/06-integrations/00-external-dns.md
  content/docs/06-integrations/00-fluentbit.md
  content/docs/06-integrations/00-frp.md
  content/docs/06-integrations/00-generic-vm-libvirt.md
  content/docs/06-integrations/00-generic-vm-vsphere.md
  content/docs/06-integrations/00-istio.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/06-integrations/00-metallb.md
  content/docs/06-integrations/00-opa-gatekeeper.md
Labels: size/M, ok-to-test

#939 prod-push-25th-oct-2022
  CHANGES
Labels: size/XS, ok-to-test

#942 docs: minor suggetions to 3.0.0 releases
  README.md
  content/docs/00-release-notes.md
Labels: documentation, size/S, needs-ok-to-test, ok-to-test

#943 docs: removed duplicate yaml entry
  content/docs/06-integrations/00-external-secrets-operator.md
Labels: bug, documentation, size/M, ok-to-test

#945 docs: clarified language and added screenshot
  content/docs/04.5-devx.md
  content/docs/palette_console-user_menu-mode_highlighted.png
Labels: documentation, size/M, ok-to-test

#946 terraform-update
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#947 Prod push 27oct22
  CHANGES
Labels: size/XS, ok-to-test

#949 Prod push 27oct22 2nd time
  CHANGES
Labels: size/XS, ok-to-test

#951 pic
  content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/04-sandbox-clusters/sandbox-cluster-quickstart.md
Labels: size/XS, ok-to-test

#944 updates-pde
  content/docs/00-release-notes.md
  content/docs/04-clusters/04-sandbox-clusters.md
  content/docs/04-clusters/04-sandbox-clusters/sandbox-cluster-quickstart.md
  content/docs/04.5-devx/03-cluster-groups.md
  content/docs/04.5-devx/05-app-profile.md
  content/docs/04.5-devx/07-sandbox-clusters.md
Labels: size/M, ok-to-test

#955 docs: added documentation about redirects to the README
  README.md
Labels: documentation, size/S, ok-to-test

#954 ci: added steps for local docker development that support arm
  .dockerignore
  Dockerfile
  Makefile
  README.md
  scripts/entry.sh
Labels: size/M, ok-to-test

#952 DOC-380: Redirecting nested-clusters to sandbox-clusters
  README.md
  content/docs/04-clusters/04-nested-clusters.md
  content/docs/04-clusters/04-nested-clusters/create-host-cluster.png
  content/docs/04-clusters/04-nested-clusters/deploy-nested-cluster.png
  content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
  content/docs/04-clusters/04-nested-clusters/record-details.png
  gatsby-node.js
  src/shared/utils/redirects.js
Labels: size/L, ok-to-test

#956 doc-386
  content/api/v1/02-appDeployments.md
  content/api/v1/20-appProfiles.md
  content/api/v1/22-clustergroups.md
Labels: size/S, ok-to-test

#958 docs: push to production
  CHANGES
Labels: size/XS, ok-to-test
