Repository spectrocloud/librarium, pull requests merged in 2022-05, with the labels that each got.

#687 dates-added-to-clous-permissions
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
  content/docs/04-clusters/1-new-clusters/06-gcp.md
  content/docs/04-clusters/1-new-clusters/08-openstack.md
  content/docs/04-clusters/1-new-clusters/10-tke.md
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/L, ok-to-test

#689 Update 02-free-cloud-credit.md
  content/docs/02-getting-started/02-free-cloud-credit.md
Labels: size/XS, ok-to-test

#679 BET-4028/ API doc link to Git edit not accessible
  config.js
  gatsby-config.js
  src/templates/api.js
Labels: size/S, ok-to-test

#587 Resolved task 1 and 2
  README.md
  content/docs/00-release-notes.md
  content/docs/03-cluster-profiles/2-task-update-profile.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/08-user-management/1-saml-sso.md
  src/shared/components/Box.js
  src/shared/components/common/Integrations/Search.js
  src/shared/components/styles/Docs.js
  src/shared/components/ui/Tabs.js
  src/shared/layouts/Default/index.js
  src/shared/layouts/Default/layout.css
  src/shared/layouts/Default/search/input.js
  src/shared/mdx/components/index.js
Labels: size/XL, ok-to-test

#692 Appzi and fullstory integration
  gatsby-ssr.js
Labels: size/M

#690 search results page
  content/docs/00-search.mdx
  src/shared/components/SearchResults.js
  src/shared/layouts/Default/Header.js
  src/shared/layouts/Default/search/index.js
  src/shared/layouts/Default/search/input.js
Labels: size/L, ok-to-test

#698 Cluster Notifications adding a note
  content/docs/04-clusters/3-cluster-management/01-cluster-updates.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#697 prometheus-scrape-matrics
  content/docs/06-integrations/00-prometheus-operator.md
Labels: size/L, ok-to-test

#700 rel-2.6-cluster-profile-versioning
  content/docs/03-cluster-profiles/1-task-define-profile.md
Labels: size/L, ok-to-test

#701 minor-updates
  content/docs/08-user-management.md
  content/docs/08-user-management/1-saml-sso.md
  content/docs/08-user-management/2-rbac.md
  content/docs/08-user-management/3-rbac.md
  content/docs/08-user-management/3-saml-sso.md
Labels: size/L, ok-to-test

#705 parameters-support-in-storageclass
  content/docs/06-integrations/00-aws-ebs.md
Labels: size/S, ok-to-test

#704 2.6-release-notes
  content/docs/00-release-notes.md
Labels: size/S, ok-to-test

#710 updates-01
  content/docs/03-cluster-profiles/1-task-define-profile.md
Labels: size/M, ok-to-test

#709 component-matrix-2.6
  content/docs/16-component.md
Labels: size/S, needs-ok-to-test, ok-to-test

#707 2.6-release-cli-and-registries
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/09-registries-and-packs/3-add-custom-packs.md
  content/docs/09-registries-and-packs/4-adding-add-on-packs.md
  content/docs/09-registries-and-packs/6-helm-charts.md
Labels: size/XXL, ok-to-test

#711 doc-159
  content/docs/00-release-notes.md
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/S, ok-to-test

#713 minor-edit
  content/docs/09-registries-and-packs/4-adding-add-on-packs.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#714 Codrin/link fixes
  prow/functions.sh
Labels: size/XS

#715 Fixes
  CHANGES
Labels: size/S

#716 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/S, ok-to-test

#717 pcg-image-update-2.6
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
Labels: size/S, needs-ok-to-test, ok-to-test

#722 rel-date-update
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#719 Correction
  README.md
Labels: size/XS
