Repository spectrocloud/librarium, pull requests merged in 2022-01, with the labels that each got.

#552 Release 2.2.0
  CHANGES
Labels: ok-to-test

#551 MaaS-MAAS
  packages/docs/content/04-clusters/1-new-clusters/06-maas.md
Labels: size/M, needs-ok-to-test, ok-to-test

#554 edge-cluster-doc
  packages/docs/content/04-clusters/1-new-clusters.md
  packages/docs/content/04-clusters/1-new-clusters/01-aws.md
  packages/docs/content/04-clusters/1-new-clusters/02-eks.md
  packages/docs/content/04-clusters/1-new-clusters/03-azure.md
  packages/docs/content/04-clusters/1-new-clusters/04-aks.md
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
  packages/docs/content/04-clusters/1-new-clusters/06-gcp.md
  packages/docs/content/04-clusters/1-new-clusters/07-maas.md
  packages/docs/content/04-clusters/1-new-clusters/08-openstack.md
  packages/docs/content/04-clusters/1-new-clusters/09-vmware.md
  packages/docs/content/04-clusters/1-new-clusters/containerized-edge.png
  packages/docs/content/04-clusters/1-new-clusters/virtualized-edge.png
Labels: size/L, ok-to-test

#556 Added command line option --custom-cacert
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
Labels: size/XS, needs-ok-to-test

#557 updated release notes 2.2
  packages/docs/content/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#558 command-line-update
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#561 tiny-change
  packages/docs/content/17-glossary-all.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#560 Reworded v2.2 release notes
  packages/docs/content/00-release-notes.md
Labels: size/S, needs-ok-to-test, ok-to-test

#562 Consistency edits
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
  packages/docs/content/04-clusters/1-new-clusters/07-maas.md
Labels: size/S, needs-ok-to-test, ok-to-test

#565 doc-link-updates
  packages/docs/content/02-getting-started.md
  packages/docs/content/07-projects.md
  packages/docs/content/08-user-management.md
  packages/docs/content/17-glossary-all.md
Labels: size/S, needs-ok-to-test, ok-to-test

#566 pcge-command-argument-update
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
Labels: size/XS, ok-to-test

#568 1.16-1.19-k8s
  packages/docs/content/06-integrations/00-kubernetes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#567 BET-3741
  packages/docs/content/06-integrations/00-metallb.md
Labels: size/M, ok-to-test

#564 Update Release notes for CSI Layer
  packages/docs/content/00-release-notes.md
Labels: size/XS, ok-to-test

#570 Edge changes to production
  CHANGES
Labels: size/XS, ok-to-test

#569 minor-updates-edge-lb
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
  packages/docs/content/06-integrations/00-metallb.md
Labels: size/S, ok-to-test

#572 edge-beta-01
  packages/docs/content/04-clusters/1-new-clusters.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#574 Push to Production
  CHANGES
Labels: size/XS, ok-to-test

#575 metal-lb-pack-update
  packages/docs/content/06-integrations/00-metallb.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#579 Hotfix 2.2.26
  packages/docs/content/00-release-notes.md
  packages/docs/content/09-registries-and-packs/6-helm-charts.md
Labels: size/S, ok-to-test

#580 helm-page-revisited
  packages/docs/content/00-release-notes.md
  packages/docs/content/09-registries-and-packs/6-helm-charts.md
Labels: size/M, ok-to-test

#581 Production push
  CHANGES
Labels: size/XS, ok-to-test

#583 downloads-updated
  packages/docs/content/15-compliance.md
  packages/docs/content/16-spectro-downloads.md
Labels: size/S, needs-ok-to-test, ok-to-test

#584 Instructions for picking the correct infra.
  packages/docs/content/04-clusters/1-new-clusters/05-edge.md
  packages/docs/content/06-integrations/00-rook-ceph.md
Labels: size/M

#585 Prod push jan21
  CHANGES
Labels: size/XS, ok-to-test
