Repository spectrocloud/librarium, pull requests merged in 2022-07, with the labels that each got.

#754 macros-update
  content/docs/04-clusters/3-cluster-management/10-macros.md
Labels: size/M, ok-to-test

#756 workspace-enhancements
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
  content/docs/05-workspace/1-adding-a-new-workspace.md
  content/docs/05-workspace/2-workload-features.md
  content/docs/05-workspace/2-workload-visibility.md
Labels: size/XL, ok-to-test

#776 Adding a note for dynamic DNS
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/XS, ok-to-test

#768 2.7-feature-pcg-migration
  content/docs/12-enterprise-version/04-enterprise-cluster-management.md
Labels: size/L, ok-to-test

#772 macros-update-2.7
  content/docs/09-registries-and-packs/5-pack-constraints.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#766 2.7 Release Feature-aks-autoscaler
  content/docs/04-clusters/1-new-clusters/04-aks.md
  content/docs/04-clusters/1-new-clusters/07-maas.md
Labels: size/S, needs-ok-to-test, ok-to-test

#774 role-binding-workload-visibility-2.7
  content/docs/04-clusters/3-cluster-management/07-workloads.md
Labels: size/S, needs-ok-to-test, ok-to-test

#769 2.7-feature-azure-cni-pack
  content/docs/06-integrations/00-azure-cni.md
Labels: size/M, ok-to-test

#771 Doc-196-Canonical-UA-I-embedding-Ubuntu-MAAS
  content/docs/06-integrations/00-ubuntu.md
Labels: size/L, ok-to-test

#765 Doc-200-ImportClusterReadOnly
  content/docs/04-clusters/2-brownfield-clusters.md
Labels: size/M, ok-to-test

#764 Doc-161-Orchestration-Palette
  content/docs/14-troubleshooting/01-orchestration-spectrocloud.md
  content/docs/14-troubleshooting/distributed_orchestration.png
  content/docs/14-troubleshooting/workload_cluster_provisioning.png
Labels: size/M, ok-to-test

#779 helm-chart-csi-cni
  content/docs/03-cluster-profiles.md
  content/docs/03-cluster-profiles/1-task-define-profile.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#782 Update Edge Descriptions
  content/docs/04-clusters/1-new-clusters/05-edge.md
Labels: size/S, ok-to-test

#731 DOC-167-Release-docs-2.7-04-clusters-file
  content/docs/04-clusters.md
Labels: size/L, ok-to-test

#781 pv-resource-update
  content/docs/05-workspace.md
  content/docs/05-workspace/1-adding-a-new-workspace.md
  content/docs/05-workspace/2-workload-features.md
Labels: size/M, ok-to-test

#777 Windows Worker Node settings
  content/docs/04-clusters/1-new-clusters/04-aks.md
Labels: size/L, ok-to-test

#780 Doc-206-Profile-Packs-status-in-cluster-profile
  content/docs/04-clusters/3-cluster-management.md
  content/docs/04-clusters/3-cluster-management/11-pack-monitoring.md
  content/docs/04-clusters/3-cluster-management/pack_status.png
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/4-adding-add-on-packs.md
  content/docs/12-enterprise-version/06-monitoring.md
Labels: size/L, ok-to-test

#784 2.7-release-notes
  content/docs/00-release-notes.md
Labels: size/S, ok-to-test

#786 AKS-Windows-worker-node
  content/docs/04-clusters/1-new-clusters/04-aks.md
Labels: size/XS, ok-to-test

#787 Doc 200 import cluster read only with delete and install agent and migration
  content/docs/04-clusters/2-brownfield-clusters.md
Labels: size/L, ok-to-test

#788 few-updates
  content/docs/04-clusters/2-brownfield-clusters.md
Labels: size/M, needs-ok-to-test, ok-to-test

#785 some-corrections
  content/docs/05-workspace.md
  content/docs/05-workspace/2-workload-features.md
  content/docs/06-integrations/00-azure-cni.md
Labels: size/S, ok-to-test

#789 2.7 palette resource limits
  content/docs/08-user-management/3-palette-resource-limits.md
  content/docs/08-user-management/4-saml-sso.md
Labels: size/M, ok-to-test

#792 2.7-artifacts
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/16-component.md
Labels: size/S, needs-ok-to-test, ok-to-test

#798 Changes to the EFS policy formatting
  content/docs/06-integrations/00-aws-efs.md
Labels: size/M, needs-ok-to-test, ok-to-test

#797 DOC-211-Kubevious-minor-edits
  content/docs/06-integrations/00-kubevious.md
Labels: size/S, ok-to-test

#799 2.7-edge-virtualized
  content/docs/04-clusters/1-new-clusters/05-edge.md
  content/docs/04-clusters/1-new-clusters/05-edge/01-virtualized.md
  content/docs/04-clusters/1-new-clusters/05-edge/02-native.md
  content/docs/04-clusters/1-new-clusters/native-edge.png
Labels: size/XL, ok-to-test

#802 tenant-macro
  content/docs/09-registries-and-packs/5-pack-constraints.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#806 edge-beta
  content/docs/04-clusters/1-new-clusters/05-edge.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#808 edge-review-updates
  content/docs/00-release-notes.md
  content/docs/04-clusters/1-new-clusters/05-edge.md
Labels: size/M, ok-to-test

#805 minio-bkup
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
  content/docs/05-workspace/2-workload-features.md
Labels: size/L, ok-to-test

#810 prod-push-july-22
  CHANGES
Labels: size/XS, ok-to-test
