Repository spectrocloud/librarium, pull requests merged in 2022-12, with the labels that each got.

#1013 Update 00-cilium-tetragon.md
  content/docs/06-integrations/00-cilium-tetragon.md
Labels: size/XS, needs-ok-to-test

#1011 azure-endpoint-revisit
  content/docs/04-clusters/01-public-cloud/03-azure.md
Labels: size/M, ok-to-test

#991 OWNERS for documentation content
  README.md
  content/OWNERS
  content/OWNER_ALIASES
Labels: size/S, ok-to-test

#1008 ci: change behavior for CI flow
  prow/functions.sh
  prow/presubmit.sh
Labels: documentation, size/XS, approved, ok-to-test

#1016 virt-edge-removed-temp
  content/docs/04-clusters/03-edge.md
  content/docs/04-clusters/03-edge/01-virtualized.md
  src/shared/utils/redirects.js
Labels: size/L, ok-to-test

#1018 chore: fix redirect
  src/shared/utils/redirects.js
Labels: size/XS, ok-to-test

#1019 update maas installer version
  content/docs/04-clusters/02-data-center/01-maas.md
Labels: size/XS

#1022 Fix typo
  content/docs/04.5-devx/08-registries/00-helm-registry.md
Labels: size/XS, ok-to-test

#1023 fix language
  content/docs/04.5-devx/08-registries/00-helm-registry.md
Labels: size/XS

#1024 docs: fixes DOC-277
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: size/XS

#1026 docs: DOC-419 architecture section
  content/docs/02.5-architecture.md
  content/docs/02.5-architecture/01-architecture-overview.md
  content/docs/02.5-architecture/03-orchestration-spectrocloud.md
  content/docs/02.5-architecture/04-networking-ports.md
  content/docs/02.5-architecture/05-palette-namespaces-podes.md
  content/docs/02.5-architecture/architecture_architecture-on-prem-detailed.png
  content/docs/02.5-architecture/architecture_architecture-overview_on-prem.png
  content/docs/02.5-architecture/architecture_architecture-overview_saas.png
  content/docs/02.5-architecture/architecture_networking-ports_network-diagram.png
  content/docs/02.5-architecture/architecture_networking-ports_saas-network-diagram.png
  content/docs/02.5-architecture/architecture_orchestartion-spectrocloud_distributed-flow.png
  content/docs/02.5-architecture/architecture_orchestartion-spectrocloud_provision-flow.png
  content/docs/14-troubleshooting.md
  content/docs/14-troubleshooting/02-kubernetes-tips.md
  content/docs/14-troubleshooting/03-SAAS-Network-Communications-and-Ports.md
  content/docs/14-troubleshooting/04-cluster-deployment.md
  content/docs/14-troubleshooting/06-nodes.md
  content/docs/14-troubleshooting/08-pack-issues.md
  content/docs/docs_architecture-overview_components-overview.png
  src/shared/utils/redirects.js
  vale.ini
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L

#911 Doc 336
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/02-eks.md
  content/docs/04-clusters/04-palette-virtual-clusters/palette-virtual-cluster-quickstart.md
Labels: size/M, ok-to-test

#1025 App profiles
  content/docs/04.5-devx/05-app-profile.md
  content/docs/04.5-devx/05-app-profile/00-create-app-profile.md
  content/docs/04.5-devx/05-app-profile/02-container-deployment.md
Labels: documentation, size/L, ok-to-test

#1028 Fixed Resource typo
  content/docs/04.5-devx/04-resource-quota.md
Labels: size/XS, ok-to-test

#1030 dashboard-link
  content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md
Labels: size/XS, ok-to-test

#1032 On Premise Deployment Document Updates
  content/docs/12-enterprise-version.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/L, ok-to-test

#1029 Add ephemeral storage and revise
  content/docs/04.5-devx/04-resource-quota.md
Labels: size/M, ok-to-test

#1015 Clarify deploying a virtual cluster
  content/docs/04-clusters/04-palette-virtual-clusters/00-add-virtual-cluster-to-host-cluster.md
  content/docs/04-clusters/04-palette-virtual-clusters/palette-virtual-cluster-quickstart.md
Labels: documentation, size/L, ok-to-test

#1034 docs: fix for command not rendering correctly
  content/docs/04-clusters/03-edge/02-native.md
Labels: size/M

#1033 Images dec 22
  content/docs/12-enterprise-version.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
  content/docs/16-spectro-downloads.md
  content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md
Labels: size/M, needs-ok-to-test, ok-to-test

#1039 Update 03-cluster-groups.md
  content/docs/04.5-devx/03-cluster-groups.md
Labels: documentation, size/XS, ok-to-test

#1036 Packs P1 docs
  .github/workflows/pull_request.yaml
  content/docs/06-integrations/00-argo-cd.md
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-cilium.md
  content/docs/06-integrations/00-gce.md
  content/docs/06-integrations/00-prometheus-operator.md
  content/docs/06-integrations/00-vsphere-csi.md
  content/docs/14-troubleshooting.md
  vale.ini
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L

#1037 Add OpenShift
  content/docs/04.5-devx/03-cluster-groups.md
  content/docs/04.5-devx/devx_cluster-groups_advanced-config.png
Labels: documentation, size/M, ok-to-test

#1042 ci: fixes accidental prod release
  prow/presubmit.sh
Labels: size/XS

#1043 dosc: update typo
  content/docs/10-audit-logs.md
Labels: size/XS, ok-to-test

#1044 docs: added missing redirects
  content/docs/04-clusters/04-palette-virtual-clusters.md
  content/docs/04.5-devx/07-palette-virtual-clusters/00-pause-restore-virtual-clusters.md
  prow/postsubmit.sh
  prow/release_build.sh
  src/shared/utils/redirects.js
Labels: size/S

#1045 Update 04-app-profile-cloning.md
  content/docs/04.5-devx/05-app-profile/04-app-profile-cloning.md
Labels: size/XS

#1046 Add helm registry mods and redirects
  content/docs/04.5-devx/08-registries/00-helm-registry.md
  content/docs/04.5-devx/08-registries/01-oci-registry.md
  content/docs/08-user-management.md
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/3-add-custom-packs.md
  content/docs/09-registries-and-packs/4-adding-add-on-packs.md
  content/docs/09-registries-and-packs/6-helm-charts.md
  src/shared/utils/redirects.js
Labels: documentation, size/L, ok-to-test

#1035 link-dash-board
  content/docs/06-integrations/00-kubernetes-dashboard.md
Labels: size/S, needs-ok-to-test, ok-to-test

#1048 Add cluster group auto update detail
  content/docs/04.5-devx/04-resource-quota.md
Labels: documentation, size/XS, ok-to-test

#1051 Update 1-editing-custom-registry-tag.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/XS, ok-to-test

#1038 Update 04-palette-virtual-clusters.md
  content/docs/04-clusters/04-palette-virtual-clusters.md
  src/shared/utils/redirects.js
Labels: documentation, size/XS, ok-to-test

#1055 Update 03-vmware.md
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: size/XS, ok-to-test

#1056 Add accepted and rejected words
  vale/styles/Vocab/Internal/accept.txt
  vale/styles/Vocab/Internal/reject.txt
Labels: documentation, size/S, ok-to-test

#1057 Packs 3 1
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-external-secrets-operator.md
  content/docs/06-integrations/00-longhorn.md
  content/docs/06-integrations/00-microk8s.md
  content/docs/06-integrations/00-minio-operator.md
  content/docs/06-integrations/00-mysql-operator.md
  content/docs/06-integrations/00-nginx.md
  content/docs/06-integrations/00-prometheus-operator.md
  content/docs/06-integrations/00-vault.md
Labels: documentation, size/L, ok-to-test, 3.1

#1060 Updated On premise Configuration
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XS, ok-to-test

#1050 AWS GovCloud
  content/docs/04-clusters/01-public-cloud.md
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/01-aws/02-architecture.md
  content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
  content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
  content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
  content/docs/04-clusters/01-public-cloud/01-aws/clusters_aws_architecture_aws_cluster_architecture.png
  content/docs/04-clusters/01-public-cloud/01-aws/clusters_aws_create-and-manage-aws-eks-cluster_architecture.png
  content/docs/04-clusters/01-public-cloud/02-eks.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md
  content/docs/04-clusters/01-public-cloud/03-azure/01-azure-cloud.md
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
  content/docs/04-clusters/01-public-cloud/03-azure/clusters_azure_architecture_aks-diagram.png
  content/docs/04-clusters/01-public-cloud/03-azure/clusters_azure_architecture_iaas-overview.png
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  content/docs/14-troubleshooting/06-nodes.md
  src/shared/utils/redirects.js
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XXL, ok-to-test, 3.1

#1053 os-patch-boot
  content/docs/04-clusters/06-cluster-management/04-os-patching.md
Labels: size/M, ok-to-test, 3.1

#1054 filter-map-view
  content/docs/04-clusters/06-cluster-management/14-noc-ui.md
Labels: size/M, ok-to-test, 3.1

#1061 Node pools & autoscaler
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/01-public-cloud/05-gcp.md
  content/docs/04-clusters/01-public-cloud/06-tke.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, ok-to-test, 3.1

#1062 Azure Storage
  content/docs/04-clusters/01-public-cloud.md
  content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/M, 3.1

#1065 cli-registries
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/S, ok-to-test, 3.1

#1066 Revert "cli-registries"
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/S

#1049 tencent-pcp-623
  content/docs/04-clusters/01-public-cloud/06-tke.md
Labels: size/L, needs-ok-to-test, ok-to-test, 3.1

#1068 docs: change to trigger redeploy
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/XS

#1063 fips-compliance
  content/docs/15-compliance.md
  content/docs/15-compliance/00-fips-compliance.md
  content/docs/docs_compliance_compliance_fips-logo.png
Labels: size/L, needs-ok-to-test, ok-to-test, 3.1

#1064 3.1-release-notes
  content/docs/00-release-notes.md
  content/docs/15-compliance.md
  content/docs/15-compliance/00-fips-compliance.md
  content/docs/docs_compliance_compliance_fips-logo.png
Labels: size/L, ok-to-test, 3.1

#1069 devx-profile-updates
  content/docs/04-clusters.md
  content/docs/04-clusters/cluster_health.png
  content/docs/04.5-devx/05-app-profile/05-versioning-app-profile.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/doc_cluster_clusters-cluster-heart-beat.png
Labels: size/L, needs-ok-to-test, ok-to-test, 3.1

#1070 DOC-439 - Release 3.1 API docs
  content/api/palette-apis.json
  content/api/v1/24-filters.md
  content/api/v1/api.json
Labels: size/XXL, ok-to-test, 3.1

#1059 cluster-tag-filter
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/16-cluster-tag-filter.md
  content/docs/04-clusters/06-cluster-management/16-cluster-tag-filter/00-create-add-filter.md
  content/docs/08-user-management/1.5-new-user.md
  content/docs/08-user-management/2-palette-rbac/3-resource-scope-roles-permissions.md
Labels: size/XL, needs-ok-to-test, ok-to-test, 3.1

#1058 docs: 3.1 release branch
  CHANGES
  content/api/palette-apis.json
  content/api/v1/24-filters.md
  content/api/v1/api.json
  content/docs/00-release-notes.md
  content/docs/04-clusters.md
  content/docs/04-clusters/01-public-cloud.md
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/01-aws/02-architecture.md
  content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
  content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
  content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
  content/docs/04-clusters/01-public-cloud/01-aws/clusters_aws_architecture_aws_cluster_architecture.png
  content/docs/04-clusters/01-public-cloud/01-aws/clusters_aws_create-and-manage-aws-eks-cluster_architecture.png
  content/docs/04-clusters/01-public-cloud/02-eks.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md
  content/docs/04-clusters/01-public-cloud/03-azure/01-azure-cloud.md
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
  content/docs/04-clusters/01-public-cloud/03-azure/clusters_azure_architecture_aks-diagram.png
  content/docs/04-clusters/01-public-cloud/03-azure/clusters_azure_architecture_iaas-overview.png
  content/docs/04-clusters/01-public-cloud/05-gcp.md
  content/docs/04-clusters/01-public-cloud/06-tke.md
  content/docs/04-clusters/02-data-center/01-maas.md
  content/docs/04-clusters/02-data-center/02-openstack.md
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/04-os-patching.md
  content/docs/04-clusters/06-cluster-management/14-noc-ui.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  content/docs/04-clusters/06-cluster-management/16-cluster-tag-filter.md
  content/docs/04-clusters/06-cluster-management/16-cluster-tag-filter/00-create-add-filter.md
  content/docs/04-clusters/cluster_health.png
  content/docs/04.5-devx/05-app-profile/05-versioning-app-profile.md
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-external-secrets-operator.md
  content/docs/06-integrations/00-longhorn.md
  content/docs/06-integrations/00-microk8s.md
  content/docs/06-integrations/00-minio-operator.md
  content/docs/06-integrations/00-mysql-operator.md
  content/docs/06-integrations/00-nginx.md
  content/docs/06-integrations/00-prometheus-operator.md
  content/docs/06-integrations/00-vault.md
  content/docs/08-user-management/1.5-new-user.md
  content/docs/08-user-management/2-palette-rbac/3-resource-scope-roles-permissions.md
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/14-troubleshooting/06-nodes.md
  content/docs/15-compliance.md
  content/docs/15-compliance/00-fips-compliance.md
  content/docs/doc_cluster_clusters-cluster-heart-beat.png
  content/docs/docs_compliance_compliance_fips-logo.png
  src/shared/utils/redirects.js
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XXL, 3.1

#1071 rel-date
  content/docs/00-release-notes.md
Labels: size/XS
