Repository spectrocloud/librarium, pull requests merged in 2022-04, with the labels that each got.

#642 Tf page revisit
  content/docs/06-integrations/00-kubernetes.md
  content/docs/13-terraform.md
Labels: size/M, ok-to-test

#643 palette-component-complexity-matrix
  content/docs/16-complexity.md
Labels: size/L, ok-to-test

#640 opa-gatekeeper
  content/docs/06-integrations/00-opa-gatekeeper.md
Labels: size/M, ok-to-test

#652 fixed google tag manager blocked script
  package-lock.json
  package.json
Labels: size/S, ok-to-test

#653 pcm-update
  content/docs/16-complexity.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#654 release-2.5-Onboarding-workflow
  content/docs/02-getting-started/00-onboarding-workflow.md
  content/docs/02-getting-started/user-experience.png
Labels: size/M, ok-to-test

#648 rel-2.5-cluster-force-delete
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
  content/docs/04-clusters/1-new-clusters/03-azure.md
  content/docs/04-clusters/1-new-clusters/04-aks.md
  content/docs/04-clusters/1-new-clusters/05-edge.md
  content/docs/04-clusters/1-new-clusters/06-gcp.md
  content/docs/04-clusters/1-new-clusters/07-maas.md
  content/docs/04-clusters/1-new-clusters/08-openstack.md
  content/docs/04-clusters/1-new-clusters/09-vmware.md
  content/docs/04-clusters/1-new-clusters/10-vmware.md
Labels: size/XXL, ok-to-test

#644 tenant-admin-update
  content/docs/02-getting-started.md
  content/docs/07-projects.md
  content/docs/08-user-management.md
  content/docs/08-user-management/1-saml-sso.md
  content/docs/08-user-management/2-rbac.md
  content/docs/08-user-management/2-saml-sso.md
  content/docs/08-user-management/3-rbac.md
Labels: size/L, ok-to-test

#656 additional DeleteNetworkInterface permission for eks
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
Labels: size/XS, ok-to-test

#647 release-2.5-macros
  content/docs/04-clusters/3-cluster-management/01-cluster-updates.md
  content/docs/04-clusters/3-cluster-management/02-health-alerts.md
  content/docs/04-clusters/3-cluster-management/03-compliance-scan.md
  content/docs/04-clusters/3-cluster-management/04-os-patching.md
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
  content/docs/04-clusters/3-cluster-management/06-cloud-cost.md
  content/docs/04-clusters/3-cluster-management/07-workloads.md
  content/docs/04-clusters/3-cluster-management/08-taints.md
  content/docs/04-clusters/3-cluster-management/09-cluster-rbac.md
  content/docs/04-clusters/3-cluster-management/10-macros.md
Labels: size/L, ok-to-test

#657 getting-started-reworked
  content/docs/02-getting-started.md
  content/docs/02-getting-started/01-palette-freemium.md
  content/docs/02-getting-started/02-free-cloud-credit.md
  content/docs/02-getting-started/03-dashboard.md
  content/docs/02-getting-started/04-onboarding-workflow.md
  content/docs/02-getting-started/admin-dashboard.png
  content/docs/02-getting-started/project-dashboard.png
  content/docs/admin-dashboard.png
  content/docs/project-dashboard.png
Labels: size/L, ok-to-test

#649 release-2.5-tencent-tke
  content/docs/04-clusters/1-new-clusters/10-tke.md
  content/docs/04-clusters/1-new-clusters/tencent-diagram.png
Labels: size/L, ok-to-test

#659 cli-registries-update-2.5
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
Labels: size/S, ok-to-test

#660 release-notes-2.5
  content/docs/00-release-notes.md
Labels: size/M, ok-to-test

#661 rel-2.5-gcp-bkup
  content/docs/04-clusters/3-cluster-management/05-backup-restore.md
Labels: size/XL, needs-ok-to-test, ok-to-test

#662 Update 14-troubleshooting.md
  content/docs/14-troubleshooting.md
Labels: size/XS, ok-to-test

#665 componet-matrix-fname-update
  content/docs/16-component.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#666 doc-137
  content/docs/13-terraform.md
Labels: size/M, ok-to-test

#664 Update 01-palette-freemium.md
  content/docs/02-getting-started/01-palette-freemium.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#668 Update 04-onboarding-workflow.md
  content/docs/02-getting-started/04-onboarding-workflow.md
Labels: size/S, ok-to-test

#669 getting-started-update
  content/docs/02-getting-started.md
Labels: size/S, needs-ok-to-test, ok-to-test

#663 2.5-updates
  content/docs/00-release-notes.md
  content/docs/04-clusters/1-new-clusters.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/06-integrations/00-ubuntu.md
  content/docs/16-component.md
Labels: size/M, ok-to-test

#670 TKE-permissions-updated
  content/docs/04-clusters/1-new-clusters/10-tke.md
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/L, ok-to-test

#672 Release notes updates
  content/docs/00-release-notes.md
  content/docs/13-terraform.md
Labels: size/S, needs-ok-to-test, ok-to-test

#673 :cfd-time-update
  content/docs/04-clusters/1-new-clusters/01-aws.md
  content/docs/04-clusters/1-new-clusters/02-eks.md
  content/docs/04-clusters/1-new-clusters/03-azure.md
  content/docs/04-clusters/1-new-clusters/04-aks.md
  content/docs/04-clusters/1-new-clusters/05-edge.md
  content/docs/04-clusters/1-new-clusters/06-gcp.md
  content/docs/04-clusters/1-new-clusters/07-maas.md
  content/docs/04-clusters/1-new-clusters/08-openstack.md
  content/docs/04-clusters/1-new-clusters/10-tke.md
  content/docs/04-clusters/1-new-clusters/11-vmware.md
Labels: size/M, needs-ok-to-test, ok-to-test

#671 terraform-provider-module-compatibility
  content/docs/13-terraform.md
Labels: size/XS, ok-to-test

#674 rel-note
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#675 Ubuntu updates
  content/docs/00-release-notes.md
  content/docs/06-integrations/00-ubuntu.md
Labels: size/S, needs-ok-to-test, ok-to-test

#677 pack-version-updates
  content/docs/06-integrations/00-calico.md
  content/docs/06-integrations/00-certmanager.md
  content/docs/06-integrations/00-falco.md
  content/docs/06-integrations/00-portworx.md
  content/docs/06-integrations/00-rook-ceph.md
Labels: size/M, needs-ok-to-test, ok-to-test

#680 Release 2.5.0
  CHANGES
Labels: size/XS

#681 Release 2.5 docs
  content/api/v1/api.json
Labels: size/XXL, ok-to-test

#683 Tke cluster profile
  content/docs/00-release-notes.md
  content/docs/04-clusters/1-new-clusters/10-tke.md
Labels: size/S, ok-to-test

#685 Update 05-edge.md
  content/docs/04-clusters/1-new-clusters/05-edge.md
Labels: size/XS, ok-to-test

#686 Prod push apr22
  CHANGES
Labels: size/XS, ok-to-test

#684 Update 05-workspace.md
  content/docs/05-workspace.md
Labels: size/XS, ok-to-test
