Repository spectrocloud/librarium, pull requests merged in 2023-03, with the labels that each got.

#1152 chore: fixed link issue
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
Labels: bug, ok-to-test

#1091 docs: PDE Tutorial
  .github/workflows/image_optimizer.yaml
  .gitleaksignore
  assets/docs/images/tutorials/deploy-app/devx_app_deploy-apps_cluster-2-deploy-app.png
  assets/docs/images/tutorials/deploy-app/devx_app_deploy-apps_scenario-1-overview.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-app_create-api-key.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-app_self-hosted-hello-universe.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_app-profile-creation.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_app-profiles.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_architecture-diagram.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_cluster-2-details-page.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_cluster-details-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_delete-apps-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_delete-cluster-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_hello-universe.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_postgres-service-create.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_toggle-app-mode.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_ui-api-display.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_virtual-cluster-list.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy_scenario-2-overview.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploys-apps_reverse-proxy-diagram.png
  assets/docs/images/tutorials/tf-tutorial-images/newly-created-cluster.png
  assets/docs/images/tutorials/tf-tutorial-images/terraform-finished-install.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-apply.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-create-missing-resources.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-destroy-complete.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-destroy.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-execution-plan.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-finished-installing.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-initialized.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-initializing.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-kubeflow.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-provision-plan.png
  assets/docs/images/tutorials/tf-tutorial-images/tf-provisioned-cluster.png
  content/docs/04.5-devx/05-app-profile/03-app-profile-macros.md
  content/docs/04.5-devx/05-app-profile/08-services/4-connectivity.md
  content/docs/04.5-devx/06-apps/05-deploy-app.md
  content/docs/04.5-devx/06-apps/05-logs.md
  content/docs/18-knowledgebase/01-tutorials/1-terraform-tutorial.md
Labels: size/XXL, tutorial

#1155 docs: fixed image shadow
  assets/docs/images/tutorials/deploy-app/devx_app_deploy-apps_cluster-2-deploy-app.png
  assets/docs/images/tutorials/deploy-app/devx_app_deploy-apps_scenario-1-overview.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-app_create-api-key.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-app_self-hosted-hello-universe.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_app-profile-creation.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_app-profiles.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_architecture-diagram.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_cluster-2-details-page.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_cluster-details-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_delete-apps-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_delete-cluster-view.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_hello-universe.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_postgres-service-create.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_toggle-app-mode.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_ui-api-display.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy-apps_virtual-cluster-list.png
  assets/docs/images/tutorials/deploy-app/devx_apps_deploy_scenario-2-overview.png
Labels: bug, size/XS, ok-to-test

#1156 docs: updated tutorial tag
  content/docs/04.5-devx/06-apps/05-deploy-app.md
Labels: size/XS

#1162 redirect fix
  content/docs/04.5-devx/05-app-profile/08-services.md
Labels: size/XS, ok-to-test

#1166 [Snyk] Upgrade @babel/plugin-proposal-export-default-from from 7.16.7 to 7.18.10
  package-lock.json
  package.json
Labels: size/M

#1163 [Snyk] Upgrade antd from 4.20.3 to 4.24.8
  package-lock.json
  package.json
Labels: size/XXL, dependencies

#1164 [Snyk] Upgrade react-instantsearch-dom from 6.24.2 to 6.39.0
  package-lock.json
  package.json
Labels: size/L, dependencies

#1167 ci: added PR template
  .github/pull_request_template.md
Labels: size/XS, CI/CD

#1114 Restructure MAAS doc
  assets/docs/images/clusters_maas_maas-dns-setup.png
  content/docs/04-clusters/01-public-cloud/05.5-cox-edge/20-create-cox-cluster.md
  content/docs/04-clusters/02-data-center.md
  content/docs/04-clusters/02-data-center/01-maas.md
  content/docs/04-clusters/02-data-center/01-maas/02-architecture.md
  content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
  content/docs/04-clusters/02-data-center/01-maas/10-register-manage-maas-cloud-accounts.md
  content/docs/04-clusters/02-data-center/01-maas/15-create-manage-maas-clusters.md
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
Labels: documentation, size/XXL

#1161 Update 00-spectro-k8s-dashboard.md
  assets/docs/images/clusters_cluster-management_cluster-rbac_cluster-creation-settings.png
  assets/docs/images/clusters_cluster-management_cluster-rbac_cluster-settings.png
  assets/docs/images/clusters_cluster-management_cluster-rbac_cluster-subject-group.png
  assets/docs/images/integrations_spectro-k8s-dashboard_diagram-flow-users.png
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
  content/docs/06-integrations/00-frp.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/00-spectro-k8s-dashboard.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, ok-to-test

#1172 docs: table update
  content/docs/02.5-architecture/04-networking-ports.md
Labels: size/S

#1157 docs: PEM-916 Documentation of Monitoring Packs
  assets/docs/images/integrations_prometheus-agent_cluster-detail-view-grafana.png
  assets/docs/images/integrations_prometheus-agent_cluster-detail-view.png
  assets/docs/images/integrations_prometheus-operator_operator-preset-view-expanded.png
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/01.9-monitoring.md
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/10-deploy-monitor-stack.md
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/20-deploy-agent.md
  content/docs/06-integrations/00-prometheus-agent.md
  content/docs/06-integrations/00-prometheus-operator.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XXL, ok-to-test

#1176 docs: updated network ports table
  content/docs/02.5-architecture/04-networking-ports.md
Labels: size/S, ok-to-test

#1177 Maintenance
  .gitleaksignore
Labels: size/M, ok-to-test

#1178 docs: more updates
  content/docs/02.5-architecture/04-networking-ports.md
Labels: size/XS, ok-to-test

#1179 docs: PDE Update
  assets/docs/images/palette_console-user_menu-mode_highlighted.png
  content/docs/04.5-devx.md
Labels: size/S, ok-to-test

#1182 docs: PEM-1296 removed web shell language
  assets/docs/images/clusters_cluster-management_palette-webctl_cluster-details-overview.png
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/12-palette-webctl.md
Labels: size/M, ok-to-test

#1184 DOC-733 Fixed Background Blur on images + Removed unnecessary box-shadow
  content/docs/03-cluster-profiles/4-examples.md
  gatsby-config.js
  src/shared/layouts/Default/layout.css
Labels: size/M, ok-to-test

#1181 DOC-741: Remove GitHub SBOM format
  content/docs/04-clusters/06-cluster-management/03-compliance-scan.md
Labels: size/S, ok-to-test

#1185 Release notes 3 3
  content/docs/00-release-notes.md
Labels: size/M, 3.3

#1188 Change Public Cloud Gateway to Private
  content/docs/00-release-notes.md
Labels: size/XS, ok-to-test

#1189 Tenry 5
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
Labels: size/XS, ok-to-test

#1186 DOC-734 Fix PointsOfInterest scroll
  src/shared/components/common/PointOfInterest.js
Labels: size/S

#1173 [Snyk] Upgrade prism-react-renderer from 1.3.1 to 1.3.5
  package-lock.json
  package.json
Labels: size/S

#1191 Updated Packages to latest version for Gatsby v3
  package-lock.json
  package.json
Labels: size/XXL, needs-ok-to-test

#1193 Quick 404 links fix
  content/docs/04-clusters/02-data-center/01-maas.md
Labels: size/XS, ok-to-test

#1149 feat: release for Palette 3.3
  .gitleaksignore
  README.md
  assets/docs/images/clusters_edge_cloud-init_boot-order-squence.png
  assets/docs/images/clusters_edge_cloud-init_cloud-init-stages-supported.png
  assets/docs/images/clusters_site-deployment_prepare-edge-configuration_install-flow-with-more-user-data.png
  assets/docs/images/clusters_site-deployment_prepare-edge-configuration_install-flow.png
  assets/docs/images/clusters_site_deployment_mode-profile_scope-selector.png
  assets/docs/images/scope-switcher.png
  content/api/v1/api.json
  content/docs/00-release-notes.md
  content/docs/04-clusters/03-edge.md
  content/docs/04-clusters/03-edge/01-architecture.md
  content/docs/04-clusters/03-edge/01.5-edge-native-lifecycle.md
  content/docs/04-clusters/03-edge/01.8-installer-image.md
  content/docs/04-clusters/03-edge/02-edge-configuration.md
  content/docs/04-clusters/03-edge/02-edge-configuration/30-cloud-init.md
  content/docs/04-clusters/03-edge/02-edge-configuration/35-installer-reference.md
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/04-clusters/03-edge/08-deployment.md
  content/docs/04-clusters/03-edge/08-deployment/02-native.md
  content/docs/04-clusters/03-edge/09-site-deployment.md
  content/docs/04-clusters/03-edge/09-site-deployment/01-model-profile.md
  content/docs/04-clusters/03-edge/09-site-deployment/02-prepare-edge-configuration.md
  content/docs/04-clusters/03-edge/09-site-deployment/025-prepare-content-bundle.md
  content/docs/04-clusters/03-edge/09-site-deployment/03-installer.md
  content/docs/04-clusters/03-edge/09-site-deployment/04-stage.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation/06-edge-host-registration.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation/07-cluster-deployment.md
  content/docs/04-clusters/03-edge/20-advanced.md
  content/docs/06-integrations/00-frp.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/13-terraform.md
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
  src/shared/utils/redirects.js
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XXL, 3.3

#1200 docs: updated URLs and release note date
  content/docs/00-release-notes.md
  content/docs/09-registries-and-packs.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
Labels: size/M

#1201 docs: markdown fix
  content/docs/04-clusters/03-edge/09-site-deployment/03-installer.md
Labels: size/XS

#1202 docs: updated release notes
  content/docs/00-release-notes.md
  content/docs/16-component.md
Labels: size/XS

#1195 docs: monitoring stack w/ HTTPS
  assets/docs/images/clusters_monitoring_deploy-monitor-stack_https-architecture.png
  assets/docs/images/clusters_monitoring_deploy-monitor-stack_loadbalancers.png
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/10-deploy-monitor-stack.md
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/20-deploy-agent.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L

#1203 Update 16-component.md
  content/docs/16-component.md
Labels: size/XS

#1190 Spectro Virtualization - VM Management
  content/docs/04.6-vm-management.md
  content/docs/04.6-vm-management/05-vm-packs-profiles.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/10-vm-dashboard.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/15-create-vm-dashboard-profile.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/16-enable-vm-dashboard.md
  content/docs/04.6-vm-management/10-create-manage-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/04-deploy-vm-from-template.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/05-update-vm-configuration.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/10-migrate-vm-to-different-node.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/15-take-snapshot-of-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/20-clone-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/10-standard-vm-operations.md
  content/docs/04.6-vm-management/10-create-manage-vm/15-create-vm-template.md
  content/docs/04.6-vm-management/15-vm-roles-permissions.md
Labels: documentation, size/XXL, ok-to-test

#1180 bulwark gitleaks pr validation action
  .github/workflows/gitleaks.yaml
Labels: size/XS, ok-to-test, CI/CD

#1204 docs: updated Edge prereqs
  content/docs/04-clusters/03-edge/01-architecture.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation.md
Labels: documentation, ok-to-test

#1206 Update 01-build-kairos-os.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/01-build-kairos-os.md
Labels: size/XS, ok-to-test

#1207 Update 01-build-kairos-os.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/01-build-kairos-os.md
Labels: size/XS, ok-to-test

#1160 Symbolic Linking
  content/docs/08-user-management/04-saml-sso/00-enable-saml.md
  content/docs/08-user-management/04-saml-sso/02-palette-sso-with-adfs.md
  content/docs/08-user-management/04-saml-sso/03-palette-sso-azure-ad.md
  content/docs/08-user-management/4-saml-sso.md
  content/docs/18-knowledgebase.md
  content/docs/18-knowledgebase/00-how-to.md
  content/docs/18-knowledgebase/01-tutorials.md
  content/docs/18-knowledgebase/01-tutorials/1-terraform-tutorial.md
  content/docs/18-knowledgebase/01-tutorials/10-dev-engine.md
  content/docs/18-knowledgebase/01-tutorials/10-dev-engine/05-deploy-app.md
  content/docs/18-knowledgebase/01-tutorials/2-cks-tutorial.md
  src/shared/utils/redirects.js
Labels: size/XXL, ok-to-test

#913 cloudanix
  content/docs/06-integrations/00-cloudanix.md
Labels: size/L, ok-to-test

#1209 CI Broken URLs
  .github/workflows/url-checks.yaml
  .gitignore
  Makefile
  README.md
  package.json
  scripts/url-checker.sh
Labels: documentation, size/L, CI/CD

#1158 Kubernetes pack update
  .github/workflows/gitleaks.yaml
  assets/docs/images/integrations_pack_diffs.png
  assets/docs/images/integrations_pack_line_diffs.png
  content/docs/03-cluster-profiles/2-task-update-profile.md
  content/docs/06-integrations/00-kubernetes.md
Labels: documentation, size/XL, ok-to-test

#1211 Broken URLs fixes
  content/api/3-postman-collection.md
  content/docs/00-index.mdx
  content/docs/00-release-notes.md
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
  content/docs/04-clusters/03-edge/02-edge-configuration.md
  content/docs/04-clusters/03-edge/09-site-deployment/01-model-profile.md
  content/docs/04-clusters/03-edge/09-site-deployment/04-stage.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation.md
  content/docs/04-clusters/20-cluster-groups/35-ingress-cluster-group.md
  content/docs/04.5-devx/05-app-profile.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/0-mongo-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/1-mysql.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/2-postgresql-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/3-redis-db.md
  content/docs/04.5-devx/08-registries.md
  content/docs/04.6-vm-management/10-create-manage-vm/10-standard-vm-operations.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/08-user-management/2-palette-rbac/3-resource-scope-roles-permissions.md
  content/docs/16-component.md
Labels: bug, size/M

#1212 ci: added CODEOWNERS
  CODEOWNERS
  content/OWNERS
  content/OWNER_ALIASES
Labels: size/S, CI/CD

#1213 docs: added Edge troubleshooting steps
  assets/docs/images/troubleshooting_edge_grub-menu.png
  content/docs/14-troubleshooting/06-nodes.md
  content/docs/14-troubleshooting/12-edge.mdx
Labels: documentation, size/M, ok-to-test

#1214 docs: more broken URL fixes
  content/docs/00-release-notes.md
  content/docs/02-getting-started.md
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
  content/docs/04-clusters/03-edge/08-deployment/02-native.md
  content/docs/04-clusters/20-cluster-groups/35-ingress-cluster-group.md
  content/docs/04.5-devx/05-app-profile/08-services.md
  content/docs/04.5-devx/05-app-profile/08-services/15-db-services.md
Labels: bug, size/L, ok-to-test

#1218 docs: added new CLI flag
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/01-build-kairos-os.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/02-build-content-bundle.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/04-build-images.md
Labels: size/M

#1219 Url fix
  content/docs/12-enterprise-version.md
  content/docs/16-spectro-downloads.md
Labels: documentation, size/M, ok-to-test

#1217 Doc 472/custom pack registry updates
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/7-advanced-configuration.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, ok-to-test

#1215 API Sample Refactor
  content/api/1-introduction.md
  content/api/2-samples.md
  content/api/2-samples.mdx
  content/api/3-postman-collection.md
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/01-public-cloud/05-gcp.md
  content/docs/04.5-devx/06-apps/05-deploy-app.md
Labels: documentation, size/XXL

#1222 docs: minor update
  content/api/2-samples.mdx
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/7-advanced-configuration.md
  src/shared/mdx/components/codeBlock.js
Labels: size/XS, ok-to-test

#1223 Update 2-samples.mdx
  content/api/2-samples.mdx
Labels: size/XS, ok-to-test
