Repository spectrocloud/librarium, pull requests merged in 2023-12, with the labels that each got.

#1828 docs: Deploy a Custom Pack - Update [Tutorial]
  docs/docs-content/registries-and-packs/deploy-pack.md
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_adding-a-custom-registry-tls_certificate.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_architecture-diagram.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry-edit.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry-sync.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_cluster-health.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_cluster-layers.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_cluster-metrics.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_default-scope.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_delete-cluster.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_delete-profile.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_generate-api-key.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-login.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-project.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-repository.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_ngrok-start.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_oci-registry-edit.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_oci-registry-sync.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_oci-registry.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_pack-describe.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_pack-push.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_profile-certsan.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_profile-layer.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_profile-values-yaml.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_registry-delete.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_registry-edit.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_registry-sync.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_success.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_tenant-admin.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_verify-cluster.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_verify-profile.png
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1

#1866 npmrc heap increase
  .npmrc
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1870 docs: minor update of the deploy-pack.md file
  docs/docs-content/registries-and-packs/deploy-pack.md
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1

#1818 docs: overlay support for dhcp networks
  docs/docs-content/clusters/edge/site-deployment/vxlan-overlay.md
  static/assets/docs/images/clusters_edge_site-installation_vxlan-overlay_architecture.png
Labels: 4.2

#1874 docs: image update pr feedback
  static/assets/docs/images/tutorials/palette-canvos/clusters_edge_palette-canvos_artifacts.png
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1873 Vertex passkeys
  docs/docs-content/enterprise-version/system-management/account-management/_category_.json
  docs/docs-content/enterprise-version/system-management/account-management/account-management.md
  docs/docs-content/enterprise-version/system-management/account-management/credentials.md
  docs/docs-content/enterprise-version/system-management/account-management/email.md
  docs/docs-content/enterprise-version/system-management/add-registry.md
  docs/docs-content/enterprise-version/system-management/backup-restore.md
  docs/docs-content/enterprise-version/system-management/reverse-proxy.md
  docs/docs-content/enterprise-version/system-management/smtp.md
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/enterprise-version/system-management/tenant-management.md
  docs/docs-content/vertex/system-management/account-management/_category_.json
  docs/docs-content/vertex/system-management/account-management/account-management.md
  docs/docs-content/vertex/system-management/account-management/credentials.md
  docs/docs-content/vertex/system-management/account-management/email.md
  docs/docs-content/vertex/system-management/add-registry.md
  docs/docs-content/vertex/system-management/enable-non-fips-settings/_category_.json
  docs/docs-content/vertex/system-management/smtp.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/system-management/system-management.md
  docs/docs-content/vertex/system-management/tenant-management.md
  static/assets/docs/images/vertex_account-management_credentials_add-passkey.png
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.2

#1880 docs: new airgap. packs
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1879 Palette CLI - docs
  docs/docs-content/palette-cli/commands/commands.md
  docs/docs-content/palette-cli/commands/docs.md
  docs/docs-content/palette-cli/commands/ec.md
  docs/docs-content/palette-cli/commands/pcg.md
  docs/docs-content/palette-cli/install-palette-cli.md
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
Labels: 4.2

#1829 Add ability to expose services with kube-vip as load balancer
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/networking/_category_.json
  docs/docs-content/clusters/edge/networking/kubevip.md
  docs/docs-content/clusters/edge/networking/networking.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  static/assets/docs/images/clusters_edge_site-installation_vxlan-overlay_architecture.png
Labels: 4.2

#1884 chore: center images and round image corners
  src/css/custom.scss
  src/css/table.scss
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1887 chore: center images and round image corners (#1884)
  src/css/custom.scss
  src/css/table.scss
Labels: enhancement

#1888 docs: update kubeconfig behavior PEM-4198
  docs/docs-content/clusters/cluster-management/kubeconfig.md
Labels: 4.2

#1893 Docker prune
  .github/workflows/container-prune.yaml
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1877 docs: local harbor registry
  docs/docs-content/clusters/edge/networking/kubevip.md
  docs/docs-content/clusters/edge/networking/local-registry.md
  docs/docs-content/clusters/edge/networking/networking.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/clusters/edge/site-deployment/stage.md
  docs/docs-content/integrations/harbor-edge.md
  static/assets/docs/images/clusters_edge_networking_local_harbor_architecture.png
Labels: 4.2

#1889 Refactor Registries
  docs/deprecated/registries-and-packs/helm-charts.md
  docs/deprecated/registries-and-packs/oci-registry.md
  docs/docs-content/clusters/edge/site-deployment/model-profile.md
  docs/docs-content/devx/manage-dev-engine/registries.md
  docs/docs-content/devx/services/services.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/registries/_category_.json
  docs/docs-content/registries-and-packs/registries/helm-charts.md
  docs/docs-content/registries-and-packs/registries/oci-registry/_category_.json
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-helm.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-packs.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-zarf.md
  docs/docs-content/registries-and-packs/registries/oci-registry/oci-registry.md
  docs/docs-content/registries-and-packs/registries/pack-registries.md
  docs/docs-content/registries-and-packs/registries/registries.md
  docs/docs-content/tenant-settings/add-registry.md
  redirects.js
Labels: 4.2

#1899 docs: added Azure regions and updated symbol DOC-958
  docs/docs-content/vertex/supported-platforms.md
Labels: 4.2

#1890 docs: add edge additions to vmo docs
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
Labels: 4.2

#1895 docs: add note about nic selection
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.2

#1904 Add notes about edge cluster update limitations
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1903 add missing doc subsection
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1909 Image signature final
  .github/workflows/container-prune.yaml
  .github/workflows/nightly-docker-build.yaml
  .gitignore
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
  static/cosign.pub
Labels: documentation, enhancement, CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1913 chore: added arigap binary
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1917 Update Portworx /w Operator docs
  .gitleaksignore
  docs/docs-content/integrations/ngrok.md
  docs/docs-content/integrations/portworx_operator.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1923 Image prune debug
  .github/workflows/container-prune.yaml
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1926 docs: PEM-4236
  docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/palette-cli/commands/pcg.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1929 docs: removed version PEM-4239
  docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1931 Update ngrok.md
  docs/docs-content/integrations/ngrok.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1838 OneLogin How-to
  docs/api-content/api-docs/v1/api.json
  docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_app-role.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_callbackurl.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_clientid-clientsecret.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_group-field.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_group-sec-policy.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_login-redirect-uris.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_login-screen.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_logout-uri.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_logout.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_mapping-role-group.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_new-team.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_oidc-app-name.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_oidc-full-palette.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_roles-full.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_search-oidc.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_team-member.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_uri-config.png
  static/assets/docs/images/oidc-onelogin-images/user-management_saml-sso_palette_sso_with_onelogin_user-auth-group.png
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1891 docs: update cert renewal behavior PCP-2142
  docs/docs-content/clusters/cluster-management/certificate-management.md
  docs/docs-content/troubleshooting/nodes.md
Labels: 4.2

#1857 Provide missing Autocale information
  docs/docs-content/clusters/cluster-management/remove-clusters.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/azure.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  static/assets/docs/images/clusters_publiccloud_azure_add-rule.png
  static/assets/docs/images/clusters_publiccloud_azure_custom-autoscale.png
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1947 docs: set toc_max_heading_level to default value 3 for all docs DOC-938
  README.md
  docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/release-notes.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docusaurus.config.js
Labels: enhancement, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1950 docs: updated Palette CLI install
  docs/docs-content/palette-cli/install-palette-cli.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1
