Repository spectrocloud/librarium, pull requests merged in 2023-10, with the labels that each got.

#1630 Update maintenance-policy.md
  docs/docs-content/integrations/maintenance-policy.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1635 chore: updated privacy settings experience
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1633 Document patch release 4.0.15 RNs
  docs/docs-content/clusters/public-cloud/azure/architecture.md
  docs/docs-content/release-notes.md
Labels: documentation, backport-version-4-0, auto-backport

#1640 Integration doc ngrok minor fix
  docs/docs-content/integrations/ngrok.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1634 DOC-884: Update Okta Documentation for SAML
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_attribute-statements.png
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_create-application.png
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_general-settings.png
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_metadata-url.png
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_palette-manage-sso-okta-metadata.png
  static/assets/docs/images/saml-okta-images/user-management_saml-sso_palette-sso-with-okta-saml_palette-manage-sso-okta-saml.png
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1650 chore: upgraded docusarus
  package-lock.json
  package.json
Labels: dependencies, backport-version-4-0, auto-backport, backport-version-3-4

#1653 Patch 4 0 19 and 4 0 17 release notes
  docs/docs-content/release-notes.md
Labels: documentation, backport-version-4-0, auto-backport

#1658 docs: added CLI download URL
  docs/docs-content/spectro-downloads.md
Labels: backport-version-4-0, auto-backport

#1655 docs: updated edge docs PE-2801
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
  static/assets/docs/images/tutorials/palette-canvos/clusters_edge_palette-canvos_edit_profile.png
Labels: 4.1

#1661 ci: updated labels
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/eslint-test.yaml
  .github/workflows/image_optimizer.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/version-branch-update.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1656 docs: maas node tags PCP-1930
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/eslint-test.yaml
  .github/workflows/image_optimizer.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/version-branch-update.yaml
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
Labels: 4.1

#1670 edgeforge: fix
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
Labels: backport-version-4-0, auto-backport

#1665 Distro virtual cluster
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  docs/docs-content/clusters/palette-virtual-clusters/palette-virtual-clusters.md
  static/assets/docs/images/clusters_cluster-groups_create-cluster-group_virtual-cluster-distro.png
Labels: 4.1

#1673 Replace tooltips on Palette Dashboard page and revise for simplicity
  Makefile
  README.md
  docs/docs-content/getting-started/dashboard.md
  static/assets/docs/images/admin-dashboard.png
  static/assets/docs/images/getting-started_dashboard_admin-dashboard.png
  static/assets/docs/images/getting-started_dashboard_project-dashboard.png
  static/assets/docs/images/project-dashboard.png
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1685 chore: added toc to the global scope
  src/theme/MDXComponents/MDXComponents.ts
Labels: enhancement

#1682 Vertex platform
  docs/docs-content/release-notes.md
  docs/docs-content/vertex/supported-platforms.md
  docs/docs-content/vertex/vertex.md
Labels: 4.1

#1689 docs: pack updates
  .gitleaksignore
  Makefile
  docs/docs-content/integrations/calico.md
  docs/docs-content/integrations/cilium.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/rke2.md
  docs/docs-content/release-notes.md
  docs/docs-content/vertex/fips/fips-compliant-components.md
Labels: 4.1

#1691 docs: airgap fix
  docs/docs-content/enterprise-version/install-palette/airgap/checklist.md
  docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/checklist.md
  docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport

#1690 docs: added content for PEM-3770
  .gitleaksignore
  docs/docs-content/release-notes.md
  docs/docs-content/troubleshooting/nodes.md
  docs/docs-content/troubleshooting/pcg.md
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md
Labels: 4.1

#1680 Doc allow non fips packs in vertex pem 3652
  docs/docs-content/enterprise-version/system-management/add-registry.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/tenant-settings/add-registry.md
  docs/docs-content/tenant-settings/tenant-settings.md
  docs/docs-content/vertex/system-management/add-registry.md
  docs/docs-content/vertex/system-management/enable-non-fips-settings/enable-non-fips-settings.md
  docs/docs-content/vertex/system-management/enable-non-fips-settings/use-non-fips-addon-packs.md
  docs/docs-content/vertex/system-management/system-management.md
  static/assets/docs/images/vertex_use-non-fips-settings_nonFips-packs.png
Labels: documentation, 4.1

#1699 docs: updated broken URL and added missing release note PCP-1888
  docs/api-content/api-docs/3-postman-collection.md
  docs/docs-content/clusters/public-cloud/azure/architecture.md
  docs/docs-content/release-notes.md
  docs/docs-content/vertex/supported-platforms.md
Labels: auto-backport, backport-version-4-1

#1701 chore: touched up the Makefile
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1707 CI Runner Changes
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
Labels: CI/CD

#1706 Document addition of namespace labels for pods needing elevated privileges
  docs/docs-content/troubleshooting/cluster-deployment.md
Labels: auto-backport, 4.1, backport-version-4-1

#1710 CI Proposal
  .backportrc.json
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  archiveVersions.json
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1717 ci: cherry-pick of version-4-0
  .backportrc.json
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  archiveVersions.json
Labels: CI/CD

#1719 ci: cherry-pick of version-3-4
  .backportrc.json
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  archiveVersions.json
Labels: CI/CD

#1718 ci: cherry-pick of version-4-1
  .backportrc.json
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  archiveVersions.json
Labels: CI/CD

#1720 ci: added missing condition for non-cron workflows
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1722 Self-Hosted guidance for nginx
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1726 docs:PE-2831 provision static IP
  docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
Labels: auto-backport, backport-version-4-1

#1727 docs: update container image
  docs/docs-content/registries-and-packs/deploy-pack.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1
