Repository spectrocloud/librarium, pull requests merged in 2023-04, with the labels that each got.

#1220 Helm installation method for Palette
  assets/docs/images/enterprise-version_deploying-palette-with-helm_aws-iam-role.png
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
  content/docs/09-registries-and-packs/3-add-custom-packs.md
  content/docs/12-enterprise-version.md
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/12-enterprise-version/04-system-console-dashboard.md
  content/docs/12-enterprise-version/05-enterprise-cluster-management.md
  content/docs/12-enterprise-version/06-air-gap-repo.md
  content/docs/12-enterprise-version/07-monitoring.md
Labels: size/L, ok-to-test

#1226 CockroachDB
  content/docs/04.5-devx/05-app-profile/08-services/15-db-services.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/0-mongo-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/1-mysql.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/10-cockroach-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/2-postgresql-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/3-redis-db.md
  content/docs/04.5-devx/05-app-profile/08-services/50-service-listings/4-vault.md
Labels: documentation, size/L

#1233 Update 35-installer-reference.md
  content/docs/04-clusters/03-edge/02-edge-configuration/35-installer-reference.md
Labels: size/XS, ok-to-test

#1234 Table Removal
  content/docs/02-getting-started/04-onboarding-workflow.md
Labels: size/M, ok-to-test

#1231 docs: adding more Helm context
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
Labels: size/M

#1235 docs: fixed broken URL in release notes
  content/docs/00-release-notes.md
Labels: size/XS, ok-to-test

#1238 [Snyk] Upgrade react-instantsearch-dom from 6.39.0 to 6.39.1
  package-lock.json
  package.json
Labels: size/M

#1237 Update 09-registries-and-packs.md
  content/docs/09-registries-and-packs.md
Labels: size/XS, ok-to-test

#1240 docs: updated IAM policies page with a warning
  content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
Labels: size/S, ok-to-test

#1244 chore: fixed broken urls and reported typo
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/19-kubernetes-knowlege-hub/00-how-to/02-how-to-retrieve-images-from-private-registry.md
Labels: size/XS, ok-to-test

#1248 Update 10-create-manage-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm.md
Labels: size/XS, ok-to-test

#1247 Update 15-vm-roles-permissions.md
  content/docs/04.6-vm-management/15-vm-roles-permissions.md
Labels: size/XS, ok-to-test

#1246 Pde self hosted
  content/docs/04.5-devx.md
Labels: size/S, 3.4

#1230 Palette self-hosted airgap refactor
  assets/docs/images/enterprise-version_air-gap-repo_overview-order-diagram.png
  content/docs/12-enterprise-version/01-deploying-the-platform-installer.md
  content/docs/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/12-enterprise-version/06-air-gap-repo.md
Labels: size/XL

#906 Add kube-api audit logging how-to
  content/docs/04.6-vm-management/10-create-manage-vm.md
  content/docs/04.6-vm-management/15-vm-roles-permissions.md
  content/docs/10-audit-logs/05-kube-api-audit-logging.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, needs-ok-to-test, 3.4

#1239 docs: Prometheus Cluster Metrics
  assets/docs/images/clusters_cluster-management_grafana_spectro_metrics.png
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/20-deploy-agent.md
  content/docs/06-integrations/00-prometheus-cluster-metrics.md
  content/docs/06-integrations/00-prometheus-operator.md
Labels: size/L

#1250 docs: added new macros for pack PEM-1603
  content/docs/09-registries-and-packs/5-pack-constraints.md
Labels: size/M, ok-to-test

#1252 docs: added warning about missing metrics PEM-1615
  content/docs/04-clusters/06-cluster-management/01.9-monitoring/20-deploy-agent.md
  content/docs/06-integrations/00-prometheus-cluster-metrics.md
Labels: size/S

#1255 docs: updated broken links
  content/docs/12-enterprise-version/06-air-gap-repo.md
Labels: size/XS, ok-to-test

#1241 Helm Chart Install Reference
  content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md
Labels: size/L

#1256 docs: doc-755 added public IP addresses
  content/docs/02.5-architecture/04.5-palette-public-ips.md
Labels: size/M, ok-to-test, 3.4

#1259 Update 16-spectro-downloads.md
  content/docs/16-spectro-downloads.md
Labels: documentation, size/XS, ok-to-test

#1260 docs: fixed Helm chart variable name
  content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md
Labels: documentation, size/XS, ok-to-test

#1261 Update 03-prepare-user-data.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/03-prepare-user-data.md
Labels: size/L, WIP, ok-to-test

#1262 docs: PEM-1632 added new macro variable
  content/docs/09-registries-and-packs/5-pack-constraints.md
Labels: size/XS, ok-to-test, 3.4

#1210 DOC-725 Nested API Tree
  content/api/v1/16-system.md
  content/api/v1/21-files.md
  content/docs/04-clusters/03-edge/04-edgeforge-workflow/03-prepare-user-data.md
  content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md
  content/docs/16-spectro-downloads.md
  gatsby-browser.js
  gatsby-ssr.js
  package-lock.json
  package.json
  src/shared/components/Intro.js
  src/shared/components/common/ApiSidebar.js
  src/shared/components/common/Swagger.js
  src/shared/layouts/Api/apiSideBarTree.js
  src/shared/layouts/Default/index.js
  src/shared/layouts/Default/sidebar/index.js
  src/shared/layouts/Default/sidebar/treeNode.js
  src/shared/layouts/Persistent/index.js
  src/shared/layouts/Persistent/provider.js
  src/shared/layouts/Persistent/reducer.js
  src/shared/utils/redirects.js
  src/templates/api.js
  src/templates/docs.js
Labels: size/L, needs-ok-to-test

#1264 PE-1563 Updating palette-edge-installer cli link
  content/docs/16-spectro-downloads.md
Labels: size/XS, ok-to-test
