Repository spectrocloud/librarium, pull requests merged in 2023-07, with the labels that each got.

#1407 docs: PE-1982 added macro to table
  content/docs/09-registries-and-packs/5-pack-constraints.md
Labels: 4.0

#1406 Doc OIDC for edge native clusters
  content/docs/06-integrations/00-kubernetes-edge.md
  content/docs/06-integrations/00-kubernetes.md
Labels: documentation

#1423 docs: updated Mendable component
  assets/spectrocloud-logo-black.svg
  src/shared/components/MendableAIWidget.js
Labels: enhancement

#1421 docs: added Palette CLI subcommand
  content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
  content/docs/04-clusters/02-data-center/02-openstack.md
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/12.5-palette-cli/10-install-palette-cli.md
  content/docs/12.5-palette-cli/20-commands.md
Labels: documentation, 4.0

#1420 VerteX CLI content
  content/docs/12.5-palette-cli/20-commands.md
Labels: 4.0

#1433 Edge - Dynamic Tags
  content/docs/04-clusters/03-edge/02-edge-configuration/35-installer-reference.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.0

#1425 docs: PEM-2364 kubeconfig documentatin
  .gitleaksignore
  assets/docs/images/clusters_cluster--management_kubeconfig_cluster-details-kubeconfig-files.png
  content/docs/04-clusters/06-cluster-management/11.5-kubeconfig.md
  content/docs/06-integrations/00-kubernetes-generic.md
  content/docs/06-integrations/00-kubernetes.md
Labels: 4.0

#1435 docs: update repository URL
  content/docs/03-cluster-profiles/10-byoos/10-image-builder.md
  content/docs/04-clusters/03-edge/02-edge-configuration/30-cloud-init.md
Labels: documentation

#1436 Update InfoBox in 10-image-builder.md
  content/docs/03-cluster-profiles/10-byoos/10-image-builder.md
Labels: documentation
