Repository spectrocloud/librarium, pull requests merged in 2023-09, with the labels that each got.

#1510 New CVE's - Security Bulletin
  docs/docs-content/security/security-bulletins/cve-index.md
  docs/docs-content/security/security-bulletins/cve-reports.md
Labels: backport-version-4-0, auto-backport

#1518 chore: fixed broken URLs
  .github/url-checks.yaml
  Makefile
  docs/CODEOWNERS
  docs/docs-content/enterprise-version/enterprise-version.md
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport

#1517 Refactor MetalLB with Docusaurus
  docs/docs-content/integrations/metallb.md
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, backport-version-4-0, auto-backport

#1508 Backup Refactor Wrap-up
  docs/docs-content/clusters/cluster-management/backup-restore.md
  docs/docs-content/clusters/cluster-management/backup-restore/_category_.json
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
  docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md
  docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
  docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
  static/assets/docs/images/clusters_cluster-management_backup-restore_add_aws_account.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_confirm-restore.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_ondemand-backup.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_restore.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_scheduled-backup.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_separate-cloud-accounts.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_verify-restore.png
  static/assets/docs/images/clusters_cluster-management_backup-restore_view-backup.png
  static/assets/docs/images/clusters_cluster-management_backup_restore_add-backup-location-dynamic_aws_create_role.png
  static/assets/docs/images/clusters_cluster-management_backup_restore_add-backup-location-dynamic_aws_create_role_summary.png
  vale/styles/Vocab/Internal/accept.txt
Labels: backport-version-4-0, auto-backport

#1522 docs: DOC-823 update to MinIO steps
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
  docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
Labels: backport-version-4-0, auto-backport

#1524 ci: updates to the backport flow
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/backport.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/version-branch-update.yaml
Labels: CI/CD, backport-version-4-0, auto-backport

#1533 Document 4.0.7 & 4.0.8 hotfixes in Release Notes
  docs/docs-content/release-notes.md
Labels: backport-version-4-0, auto-backport

#1527 Document serviceDomain parameter in k8s config: PCP-935
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes.md
Labels: documentation, backport-version-4-0, auto-backport

#1535 Fix Download cluster logs URL in troubleshooting.md
  docs/docs-content/troubleshooting/troubleshooting.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1540 Update Palette CLI download URI to 4.0.1
  .github/workflows/pull_request.yaml
  docs/docs-content/spectro-downloads.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1536 Helm update
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
  docs/docs-content/enterprise-version/air-gap-repo.md
  docs/docs-content/enterprise-version/helm-chart-install-reference.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: documentation, backport-version-4-0, auto-backport

#1543 Update registries-and-packs.md
  docs/docs-content/registries-and-packs/registries-and-packs.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1549 chore: removed note callout boxes
  .github/workflows/version-branch-update.yaml
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
  docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
  docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
  docs/docs-content/enterprise-version/on-prem-system-requirements.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1547 Document action needed in Palette if Vcntr pwd changes: doc-866
  docs/docs-content/clusters/data-center/vmware.md
Labels: documentation, backport-version-4-0, auto-backport

#1553 Update palette-public-ips.md
  docs/docs-content/architecture/palette-public-ips.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1555 Update add-roles-and-role-bindings.md
  docs/docs-content/vm-management/vm-packs-profiles/add-roles-and-role-bindings.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1528 Versioning
  .backportrc.json
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/eslint-test.yaml
  .github/workflows/image_optimizer.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/version-branch-update.yaml
  .gitignore
  .husky/pre-push
  Makefile
  README.md
  docusaurus.config.js
  netlify.toml
  package-lock.json
  package.json
  redirects.js
  scripts/check-branch.sh
  scripts/netlify.sh
  scripts/update_docusarus_config.js
  scripts/versions.sh
  versionsOverride.json
Labels: enhancement, CI/CD, backport-version-4-0, auto-backport, backport-version-3-4

#1563 docs: url updates
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/troubleshooting/nodes.md
  netlify.toml
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1567 docs: updated README and release concurrency
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  README.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1573 ci: adding missing commit
  docs/docs-content/spectro-downloads.md
  package-lock.json
  src/components/MendableAIWidget/MendableAIWidget.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1575 Change Mendable AI widget asset url
  src/components/MendableAIWidget/MendableAIWidget.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1578 ci: updated branch PR logic
  .github/workflows/version-branch-update.yaml
  scripts/netlify.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1548 Repave clarifications
  .github/workflows/backport.yaml
  .github/workflows/version-branch-update.yaml
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/glossary-all.md
  docs/docs-content/troubleshooting/nodes.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1562 Release Notes for 4.0.13 patch release
  docs/docs-content/release-notes.md
Labels: documentation, backport-version-4-0, auto-backport

#1579 Update maintenance-policy.md
  docs/docs-content/integrations/maintenance-policy.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1584 ci: update to the backport post-PRs CI/CD
  .github/workflows/release-preview.yaml
  .github/workflows/version-branch-update.yaml
  scripts/netlify.sh
  src/components/MendableAIWidget/MendableAIWidget.tsx
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4

#1590 ci: updates to CI workflow
  .github/workflows/release.yaml
  .github/workflows/version-branch-update.yaml
  docs/docs-content/audit-logs/audit-logs.md
  scripts/netlify.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1594 ci: updated backport PR netlify logic
  .github/workflows/version-branch-update.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1599 Fix sentence in deploy-virtual-cluster.md
  docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1602 Remove warning about active development - Update edge.md
  docs/docs-content/clusters/edge/edge.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1603 Tiny doc fixes for edge
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1606 ci: updated README and backport CI
  .dockerignore
  .github/workflows/version-branch-update.yaml
  Dockerfile
  Makefile
  README.md
Labels: bug, enhancement, CI/CD, backport-version-4-0, auto-backport, backport-version-3-4

#1607 docs: added missing API rate documentation
  docs/api-content/api-docs/1-introduction.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4

#1613 docs: Update install-manage-maas-pcg examples
  docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
Labels: backport-version-4-0, auto-backport

#1598 Cluster group and virtual cluster clarifications
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
Labels: do-not-merge/work-in-progress, backport-version-4-0, auto-backport, backport-version-3-4

#1526 Document OIDC options for Spectro VM Dashboard: PEM-2283
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/add-roles-and-role-bindings.md
  docs/docs-content/vm-management/vm-packs-profiles/configure_OIDC.md
  docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
  docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md
Labels: documentation, backport-version-4-0, auto-backport

#1617 docs: fix virtual cluster text that used double infobox
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1619 docs: update palette-cli version
  docs/docs-content/spectro-downloads.md
Labels: backport-version-4-0, auto-backport

#1622 docs: fix URL
  README.md
  docs/docs-content/registries-and-packs/deploy-pack.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1627 Api version dropdown
  .gitignore
  Makefile
  docusaurus.config.js
  scripts/update_docusarus_config.js
  scripts/versions.sh
  src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4
