Repository spectrocloud/librarium, pull requests merged in 2023-05, with the labels that each got.

#1273 docs: added reserved tags for Azure
  content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md
Labels: size/S, ok-to-test

#1274 Cloudanix
  content/docs/06-integrations/00-cloudanix.md
Labels: size/S, needs-ok-to-test

#1276 Cloudanix Update
  content/docs/06-integrations/00-cloudanix.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/M, ok-to-test

#1275 Added 2 security bulletins
  content/docs/09.5-security/20-security-bulletins.md
Labels: size/M, needs-ok-to-test

#1283 GitHub actions
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  content/docs/01-introduction/05-palette-modes.md
Labels: size/M, CI/CD

#1289 Update 09-cluster-rbac.md
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
Labels: size/XS

#1281 chore: removed pack PPD-1229
  content/docs/00-release-notes.md
  content/docs/06-integrations/00-minio.md
  src/shared/utils/redirects.js
Labels: size/M, needs-ok-to-test

#1285 Release Notes 3.4
  content/docs/00-release-notes.md
  content/docs/09-registries-and-packs/4.5-deploy-pack.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, needs-ok-to-test, 3.4

#1257 BYOOS (non-Edge)
  assets/docs/images/cluster-profiles_byoos_image-builder_kubernetes-layer-example.png
  assets/docs/images/cluster-profiles_byoos_image-builder_workflow-diagram.png
  assets/docs/images/clusters_byoos_image-builder_cluster-profile-byoos-yaml.png
  content/docs/03-cluster-profiles/01-task-define-profile.md
  content/docs/03-cluster-profiles/02-task-update-profile.md
  content/docs/03-cluster-profiles/03-cluster-profile-import-export.md
  content/docs/03-cluster-profiles/04-examples.md
  content/docs/03-cluster-profiles/10-byoos.md
  content/docs/03-cluster-profiles/10-byoos/10-image-builder.md
  content/docs/17-glossary-all.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, 3.4

#1284 GCP Refactor & GKE Documentation
  content/docs/00-release-notes.md
  content/docs/04-clusters/01-public-cloud/01-aws.md
  content/docs/04-clusters/01-public-cloud/01-aws/02-architecture.md
  content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
  content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
  content/docs/04-clusters/01-public-cloud/03-azure.md
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
  content/docs/04-clusters/01-public-cloud/05-gcp.md
  content/docs/04-clusters/01-public-cloud/05-gcp/05-architecture.md
  content/docs/04-clusters/01-public-cloud/05-gcp/10-add-gcp-accounts.md
  content/docs/04-clusters/01-public-cloud/05-gcp/20-create-gcp-iaas-cluster.md
  content/docs/04-clusters/01-public-cloud/05-gcp/30-create-gcp-gke-cluster.md
  content/docs/04-clusters/01-public-cloud/05-gcp/90-required-permissions.md
  content/docs/04-clusters/01-public-cloud/cloud-accounts/aws-credentials.mp4
  content/docs/04-clusters/01-public-cloud/cloud-accounts/aws-sts.mp4
  content/docs/04-clusters/01-public-cloud/cloud-accounts/google.mp4
  content/docs/04-clusters/06-cluster-management/40-remove-clusters.md
Labels: documentation, size/XXL, needs-ok-to-test, 3.4

#1292 ci: removed prow folder
  prow/OWNERS
  prow/functions.sh
  prow/postsubmit.sh
  prow/presubmit.sh
  prow/release_build.sh
  prow/svc.yaml
Labels: size/M, CI/CD

#1236 Vm management updates
  assets/docs/images/clusters_cluster-management_namespace-create.png
  assets/docs/images/clusters_cluster-management_ns-resource-quota.png
  content/docs/04-clusters/06-cluster-management/09.5-namespace-management.md
  content/docs/04-clusters/06-cluster-management/12-palette-webctl.md
  content/docs/04.6-vm-management.md
  content/docs/04.6-vm-management/05-vm-packs-profiles.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/10-vm-dashboard.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/15-create-vm-dashboard-profile.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/16-enable-vm-dashboard.md
  content/docs/04.6-vm-management/10-create-manage-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/04-deploy-vm-from-template.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/05-update-vm-configuration.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/10-migrate-vm-to-different-node.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/15-take-snapshot-of-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/20-clone-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/10-standard-vm-operations.md
  content/docs/04.6-vm-management/10-create-manage-vm/15-create-vm-template.md
  content/docs/04.6-vm-management/10-create-manage-vm/20-access-cluster-with-virtctl.md
  content/docs/04.6-vm-management/10-create-manage-vm/25-vm-oversubscription.md
  content/docs/04.6-vm-management/15-vm-roles-permissions.md
Labels: size/XL

#1293 PDE Updates
  .github/workflows/pull_request.yaml
  assets/docs/images/devx_app-profile_create-app-profile_app-layer-infoboxes.png
  assets/docs/images/devx_devx_cli-display.png
  assets/docs/images/devx_manage-dev-engine_sso_display-oidc-page.png
  assets/docs/images/devx_manage-dev-engine_sso_palette-login-view.png
  assets/docs/images/docs_devx_pde-dashboard-utilization.png
  content/docs/00-release-notes.md
  content/docs/01-introduction/05-palette-modes.md
  content/docs/04.5-devx.md
  content/docs/04.5-devx/02-enterprise-user.md
  content/docs/04.5-devx/05-app-profile/00-create-app-profile.md
  content/docs/04.5-devx/05-app-profile/02-container-deployment.md
  content/docs/04.5-devx/06-apps/05-deploy-app.md
  content/docs/04.5-devx/07-palette-virtual-clusters/00-pause-restore-virtual-clusters.md
  content/docs/04.5-devx/07-palette-virtual-clusters/05-resize-virtual-clusters.md
  content/docs/04.5-devx/09-manage-dev-engine.md
  content/docs/04.5-devx/09-manage-dev-engine/04-resource-quota.md
  content/docs/04.5-devx/09-manage-dev-engine/08-registries.md
  content/docs/04.5-devx/09-manage-dev-engine/30-sso.md
  content/docs/12.5-palette-cli.md
  content/docs/12.5-palette-cli/10-install-palette-cli.md
  content/docs/12.5-palette-cli/20-commands.md
  content/docs/14-troubleshooting/08-pack-issues.md
  content/docs/14-troubleshooting/10-palette-dev-engine.md
  content/docs/16-spectro-downloads.md
  content/docs/18-knowledgebase/01-tutorials/05-deploy-app.md
  src/shared/utils/redirects.js
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XL, 3.4

#1297 chore: fixed docker image issue
  .dockerignore
  Dockerfile
Labels: dependencies

#1272 docs: MaaS introduction enhancement
  content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
Labels: size/M

#1295 Image Swap
  assets/docs/images/clusters_cluster-management_image-swap_kubernetes-layer-yaml.png
  content/docs/00-release-notes.md
  content/docs/03-cluster-profiles/10-byoos/10-image-builder.md
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/50-image-swap.md
  content/docs/06-integrations/00-kubernetes.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, 3.4

#1243 [Snyk] Upgrade sharp from 0.30.5 to 0.32.0
  package-lock.json
  package.json
Labels: size/L

#1296 docs: Disable workloads Settting
  content/docs/00-release-notes.md
  content/docs/14-troubleshooting/06-nodes.md
Labels: size/M, 3.4

#1299 Update README.md
  README.md
Labels: size/XS

#1301 Update 05-workspace.md
  content/docs/05-workspace.md
Labels: size/XS

#1304 docs: updated download URLs
  content/docs/00-release-notes.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/12.5-palette-cli/10-install-palette-cli.md
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
Labels: size/L, 3.4

#1306 Update 04-site-user-data.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation/04-site-user-data.md
Labels: size/XS

#1307 docs: added upgrade notes DOC-773
  content/docs/00-release-notes.md
  content/docs/12-enterprise-version.md
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/12-enterprise-version/10-upgrade.md
  content/docs/14-troubleshooting/04-cluster-deployment.md
  content/docs/14-troubleshooting/06-nodes.md
  content/docs/14-troubleshooting/12-edge.mdx
  content/docs/14-troubleshooting/15-palette-upgrade.md
Labels: size/L, 3.4

#1305 Update 04-site-user-data.md
  content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation/04-site-user-data.md
Labels: size/XS

#1309 Remove tenant admin login, fix table alignment, style issue
  content/docs/04.6-vm-management/05-vm-packs-profiles/10-vm-dashboard.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/15-create-vm-dashboard-profile.md
  content/docs/04.6-vm-management/05-vm-packs-profiles/16-enable-vm-dashboard.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/04-deploy-vm-from-template.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/05-update-vm-configuration.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/10-migrate-vm-to-different-node.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/15-take-snapshot-of-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/05-standard-vm-operations/20-clone-vm.md
  content/docs/04.6-vm-management/10-create-manage-vm/10-standard-vm-operations.md
  content/docs/04.6-vm-management/10-create-manage-vm/15-create-vm-template.md
  content/docs/04.6-vm-management/10-create-manage-vm/20-access-cluster-with-virtctl.md
  content/docs/04.6-vm-management/15-vm-roles-permissions.md
Labels: documentation, size/M

#1311 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS

#1315 docs: fixed broken URL in PDE DOC-774
  content/docs/04-clusters/01-public-cloud/80-deploy-k8s-cluster.md
  content/docs/06-integrations/00-byoos.md
  content/docs/16-spectro-downloads.md
  content/docs/19-kubernetes-knowlege-hub/01-tutorials.md
  content/docs/19-kubernetes-knowlege-hub/01-tutorials/06-deploy-stateless-frontend-app.md
  src/shared/utils/redirects.js
Labels: bug

#1298 Pin semantic-release and add .gitattributes for WSL
  .gitattributes
  package-lock.json
  package.json
Labels: size/XXL

#1308 Cluster Certificate Management
  assets/docs/images/clusters_cluster-management_certificate-management_certificate-renew-page.png
  assets/docs/images/clusters_cluster-management_certificate-management_cluster-details-page.png
  assets/docs/images/clusters_cluster-management_certificate-management_control-plane-only-change.png
  content/docs/04-clusters/06-cluster-management.md
  content/docs/04-clusters/06-cluster-management/02.5-certificate-management.md
Labels: documentation, do-not-merge/work-in-progress, size/L

#1321 chore: added .vscode file to set standard editor config for vscode
  .gitignore
  .vscode/settings.json
Labels: enhancement

#1324 docs: added checksum values for downloads
  content/docs/16-spectro-downloads.md
Labels: documentation, enhancement

#1339 docs: PLT-491 PLT-492 deprecation and RKE2 cleanup
  assets/docs/images/rke2-cluster-profile.png
  content/deprecated/06-integrations/00-EKS-D.md
  content/docs/06-integrations/00-rke2.md
  content/docs/16-component.md
Labels: documentation, deprecation
