Repository spectrocloud/librarium, pull requests merged in 2023-08, with the labels that each got.

#1439 docs: VerteX install content
  assets/docs/images/vertex-successful-vm-deploy-and-urls1.png
  assets/docs/images/vertex_cluster-profile-k8s-fips.png
  assets/docs/images/vertex_cluster-profile-k8s-fips1.png
  assets/docs/images/vertex_enterprise-install-button.png
  assets/docs/images/vertex_enterprise-install-button1.png
  assets/docs/images/vertex_fips-status-icons_compliant.png
  assets/docs/images/vertex_fips-status-icons_icons-in-cluster-overview.png
  assets/docs/images/vertex_fips-status-icons_icons-in-profile-stack.png
  assets/docs/images/vertex_fips-status-icons_icons-on-profile-page.png
  assets/docs/images/vertex_fips-status-icons_not-compliant.png
  assets/docs/images/vertex_fips-status-icons_partial.png
  assets/docs/images/vertex_fips-status-icons_unknown.png
  assets/docs/images/vertex_install-on-kubernetes_install_system-console.png
  assets/docs/images/vertex_installation_install-on-vmware_dns-and-ip.png
  assets/docs/images/vertex_installation_install-on-vmware_goto-tenant-management.png
  assets/docs/images/vertex_installation_install-on-vmware_vertex-system-console.png
  assets/docs/images/vertex_migrate-to-enterprise.png
  assets/docs/images/vertex_migrate-to-enterprise1.png
  assets/docs/images/vertex_system-management_enable-non-fips-settings_scan-and-backup-tabs.png
  assets/docs/images/vertex_system-management_overview-system-console.png
  assets/docs/images/vertex_system-management_ssl-certifiacte-management_certificate-upload.png
  assets/docs/images/vertex_system-management_tenant-management_activate-tenant.png
  assets/docs/images/vertex_system-management_tenant-management_remove-tenant.png
  assets/docs/images/vertex_use-non-fips-settings_nonFips-addon-packs.png
  assets/docs/images/vertex_use-non-fips-settings_nonFips-cluster-import.png
  assets/docs/images/vertex_use-non-fips-settings_nonFips-features.png
  assets/docs/images/vertex_vertex-successful-vm-deploy-and-urls.png
  assets/docs/images/vertex_vertex-successful-vm-deploy-and-urls1.png
  assets/docs/images/vertex_virtual-machine-ip.png
  assets/docs/images/vertex_virtual-machine-ip1.png
  assets/docs/vertex_virtual-machine-ip1.png
  assets/tape/vertex-install.tape
  content/docs/12.5-vertex.md
  content/docs/12.5-vertex/02-install-palette-vertex.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/10-install.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/20-install-airgap.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/30-vmware-system-requirements.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/vertex-install.mp4
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/10-install.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/15-install-airgap.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/20-vertex-helm-ref.md
  content/docs/12.5-vertex/03-fips-status-icons.md
  content/docs/12.5-vertex/60-system-management.md
  content/docs/12.5-vertex/60-system-management/30-ssl-certificate-management.md
  content/docs/12.5-vertex/60-system-management/50-reverse-proxy.md
Labels: 4.0

#1447 docs: updated KMS required permissions
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
Labels: documentation

#1429 Pack maint policy now deprecation stages display
  assets/docs/images/integrations_deprecation-profile-stack-msg.png
  assets/docs/images/integrations_deprecation-stage.png
  assets/docs/images/palette_installation_install-on-vmware_goto-tenant-management.png
  assets/docs/images/palette_installation_install-on-vmware_palette-system-console.png
  content/docs/06-integrations/01-maintenance-policy.md
Labels: 4.0

#1456 Pack labels
  content/docs/03-cluster-profiles/01.5-create-add-on-profile.md
  content/docs/04-clusters/06-cluster-management/08-taints.md
Labels: 4.0

#1455 Vs code plugin extension doc
  content/docs/04.5-devx.md
Labels: 4.0

#1457 4.0 release notes
  content/docs/00-release-notes.md
  content/docs/04-clusters/02-data-center/02-openstack.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.0

#1459 Release Notes Update
  content/docs/00-release-notes.md
  content/docs/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  content/docs/12.5-palette-cli/20-commands.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/10-install.md
Labels: 4.0

#1462 Node Repave Configuration
  content/docs/00-release-notes.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  content/docs/17-glossary-all.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.0

#1470 Palette/Vertex sizing
  content/docs/12-enterprise-version/00-on-prem-system-requirements.md
  content/docs/12-enterprise-version/02-deploying-an-enterprise-cluster.md
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/12.5-vertex/02-install-palette-vertex.md
  content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/10-install.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/10-install.md
  content/docs/16-spectro-downloads.md
Labels: 4.0

#1473 Content for PEM-3207 - scans and node maintenance mode
  content/docs/04-clusters/06-cluster-management/03-compliance-scan.md
Labels: 4.0

#1472 gRPC and Proxy
  content/docs/02.5-architecture/04.1-grps-proxy.md
Labels: 4.0

#1478 Minor changes
  content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
  content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/10-install.md
  content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/20-vertex-helm-ref.md
Labels: 4.0

#1477 Upgrade notes for palette 4.0
  assets/docs/images/enterprise-version_ssl-certificate-upload.png
  assets/docs/images/enterprise-version_sys-console-update-palette-version.png
  assets/docs/images/enterprise-version_upgrade_ec-cluster-profile.png
  content/docs/12-enterprise-version/08-ssl-certificate-management.md
  content/docs/12-enterprise-version/10-upgrade.md
Labels: 4.0

#1480 Minor 4 0 changes
  .gitleaksignore
  content/docs/00-release-notes.md
  content/docs/04-clusters/06-cluster-management/15-node-pool.md
  content/docs/06-integrations/00-aws-ebs.md
  content/docs/06-integrations/00-calico.md
  content/docs/06-integrations/00-frp.md
  content/docs/06-integrations/00-kubernetes-edge.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/06-integrations/00-longhorn.md
  content/docs/06-integrations/00-rke2.md
  content/docs/06-integrations/00-vsphere-csi.md
  content/docs/06-integrations/01-maintenance-policy.md
Labels: 4.0

#1463 docs: Edge node drain
  .gitleaksignore
  assets/docs/images/clusters_site-deployment_model-profile_byoos-pack-yaml.png
  content/docs/00-release-notes.md
  content/docs/04-clusters/03-edge/09-site-deployment/01-model-profile.md
  content/docs/06-integrations/00-byoos.md
Labels: 4.0

#1482 Document prerequisite: PCP-1587, named port groups: PCP-1174
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: 4.0

#1471 Rke2 reported fips issues
  assets/docs/images/vertex_fips-status-icons_icons-in-cluster-overview.png
  content/docs/12.5-vertex/00-fips.md
  content/docs/12.5-vertex/00-fips/01-fips-compliant-components.md
  content/docs/12.5-vertex/00-fips/03-fips-status-icons.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.0

#1484 docs: updated pcg install examples and reference page
  content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
  content/docs/04-clusters/02-data-center/02-openstack.md
  content/docs/04-clusters/02-data-center/03-vmware.md
  content/docs/12.5-palette-cli/10-install-palette-cli.md
  content/docs/12.5-palette-cli/20-commands.md
Labels: documentation

#1487 ci: added backport capability
  .backportrc.json
  .github/workflows/backport.yaml
Labels: backport-version-3-4, auto-backport

#1488 chore: validate backport
  .backportrc.json
  .github/workflows/backport.yaml
Labels: backport-version-4-0, auto-backport

#1489 ci: added comments to Makefile
  Makefile
Labels: backport-version-4-0, auto-backport

#1491 docs: updated fips page
  content/docs/12.5-vertex/00-fips/01-fips-compliant-components.md
Labels: backport-version-4-0, auto-backport

#1493 Remove the 1st occurrence of the OVA PCG video
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: backport-version-4-0, auto-backport

#1496 docs: DOC-853 provide FIPS content
  content/docs/12.5-vertex/00-fips/01-fips-compliant-components.md
Labels: backport-version-4-0, auto-backport

#1499 ci: added logic for backport PRs
  .backportrc.json
  .github/workflows/version-branch-update.yaml
Labels: backport-version-4-0, backport-version-3-4, auto-backport

#1501 ci: added logic for backport PRs
  .github/workflows/pull_request.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/version-branch-update.yaml
  .gitignore
  README.md
  netlify.toml
  scripts/netlify.sh
Labels: backport-version-4-0, backport-version-3-4, auto-backport

#1503 ci: final fix to backport CI
  .github/workflows/version-branch-update.yaml
Labels: backport-version-4-0, auto-backport
