Repository spectrocloud/librarium, pull requests merged in 2023-11, with the labels that each got.

#1732 chore: fixing packs deprecated logic
  src/components/PacksTable/PackTable.test.tsx
  src/components/PacksTable/PacksTable.tsx
Labels: bug, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1738 chore: added correct field to display
  src/components/PacksTable/PacksTable.tsx
Labels: bug, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1743 Ci version updates
  .github/workflows/version-branch-update.yaml
  static/packs-data/packs_report.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1745 chore: updated netlify.sh script
  scripts/netlify.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1750 Update App Mode Table
  docs/docs-content/devx/devx.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1733 docs: clarify requirement to explicitly specify storage class for vault on rke2 (PAC-829)
  docs/docs-content/integrations/rke2.md
  docs/docs-content/integrations/vault.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1725 Palette PDE commands
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/commands.md
  docs/docs-content/palette-cli/commands/_category_.json
  docs/docs-content/palette-cli/commands/commands.md
  docs/docs-content/palette-cli/commands/ec.md
  docs/docs-content/palette-cli/commands/login.md
  docs/docs-content/palette-cli/commands/pcg.md
  docs/docs-content/palette-cli/commands/pde.md
  docs/docs-content/palette-cli/commands/project.md
  docs/docs-content/palette-cli/palette-cli.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: auto-backport, backport-version-4-1

#1759 docs: updated oras statement DOC-909
  docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1755 Release Notes for patch release 4.1.9
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-1

#1756 docs:update edge vmware with newer version of palette edge PE-3002
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
Labels: auto-backport, backport-version-4-1

#1767 EKS journey cherry-pick for version-3-4 (#1715)
  docs/docs-content/clusters/public-cloud/aws/add-aws-accounts.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/aws/enable-secrets-encryption-kms-key.md
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
  docs/docs-content/integrations/kubernetes-generic.md
Labels: 3.4

#1749 Document Verified Packs
  docs/docs-content/integrations/maintenance-policy.md
  docs/docs-content/integrations/verified_packs.md
  static/assets/docs/images/integrations_verified-packs-green-check.png
Labels: documentation, backport-version-4-0, auto-backport, backport-version-4-1

#1763 docs: more context about IAM policies for AWS
  docs/docs-content/clusters/public-cloud/aws/architecture.md
  docs/docs-content/clusters/public-cloud/aws/aws.md
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
Labels: backport-version-4-0, backport-version-3-4, backport-version-4-1

#1773 chore: packs page DOC-807
  docs/docs-content/integrations/ngrok.md
  docs/docs-content/integrations/trident.md
  vale/styles/Vocab/Internal/accept.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1774 Minor clarification for node affinity
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-1

#1779 docs: minor touches DOC-910 DOC-911
  docs/docs-content/clusters/cluster-groups/ingress-cluster-group.md
  docs/docs-content/clusters/clusters.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1721 Updates to cluster profiles
  docs/docs-content/profiles/cluster-profiles/cluster-profiles.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-helm-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-manifest-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-pack-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-infrastructure-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/duplicate-pack-in-profile.md
  docs/docs-content/profiles/cluster-profiles/export-import-cluster-profile.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/modify-cluster-profiles.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1787 Clarify private IP address description.
  docs/docs-content/clusters/public-cloud/aws/eks.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1793 Minor clarification of virtual private IPs
  docs/docs-content/clusters/public-cloud/aws/eks.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1800 fix: typo in pack monitoring
  docs/docs-content/clusters/cluster-management/pack-monitoring.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4

#1783 Palette validator
  docs/docs-content/palette-cli/commands/commands.md
  docs/docs-content/palette-cli/commands/validator.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.2

#1804 Change numbered steps spell-out to be numerals
  docs/docs-content/clusters/edge/site-deployment/stage.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1805 Correct a heading
  docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
Labels: documentation, backport-version-4-0, auto-backport, backport-version-4-1

#1803 ci: release branch PRs triggers
  .github/workflows/release-branch-pr.yaml
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1791 docs:add command to delete packer cache and merge the .packerenv and …
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
Labels: auto-backport, backport-version-4-1

#1816 docs: added maas PEM-3973
  docs/docs-content/vertex/supported-platforms.md
Labels: 4.2

#1792 docs: add k3s pack doc
  docs/docs-content/clusters/cluster-management/cluster-rbac.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-edge.md
  vale/styles/Vocab/Internal/accept.txt
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1819 Deprecated packs style
  src/components/PacksTable/PackTable.test.tsx
  src/components/PacksTable/PacksTable.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1797 docs: add minimal resource guidance for provisioning clusters on publ…
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
Labels: auto-backport, backport-version-4-1

#1830 Offline Docs
  .github/workflows/nightly-docker-build.yaml
  .github/workflows/release.yaml
  Caddyfile
  Dockerfile-offline
  docs/docs-content/vertex/install-palette-vertex/airgap/airgap.md
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1834 docs: update the tutorial image and docker run command
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
Labels: auto-backport, backport-version-4-1

#1833 Helm Chart Deployments
  Charts/Chart.yaml
  Charts/templates/deployment.yaml
  Charts/templates/job.yaml
  Charts/templates/namespace.yaml
  Charts/templates/service.yaml
  Charts/values.yaml
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1841 fix: port arg and updated spectrocloud-registry tag
  docs/docs-content/registries-and-packs/adding-a-custom-registry.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1826 docs: hostname validation
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: 4.2

#1845 docs: add warning about silent build failures
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
Labels: auto-backport, backport-version-4-1

#1848 docs: updated airgap binaries and ova list DOC-925
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1839 Keycloak How-to
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
  static/assets/docs/images/keycloak/user-management_palette-rback_keycloak_login.png
  static/assets/docs/images/keycloak/user-management_palette-rback_palette-rbac-model.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-01-keycloak-service.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-02-callback-url.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-03-create-client.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-04-palette-username.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-05-client-authentication.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-06-keycloak-callback.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-07-keycloak-credentials.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-08-palette-callback.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-09-palette-oidc-enabled.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-10-keycloak-admin.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-11-palette-sso.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-12-keycloak-sso.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-13-palette-logged-in.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-14-palette-groups.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-15-palette-project.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-16-palette-sso-admins.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-17-keycloak-user.png
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-18-keycloak-password.png
  vale/styles/Vocab/Internal/accept.txt
  vale/styles/Vocab/Internal/reject.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1847 Fix VMware PCG details
  docs/docs-content/clusters/data-center/vmware.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1

#1858 Update backup-restore.md
  docs/docs-content/enterprise-version/system-management/backup-restore.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1
