Repository spectrocloud/librarium, pull requests merged in 2023-01, with the labels that each got.

#1076 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test

#1074 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test

#1075 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test

#1077 Pvc redirect
  src/shared/utils/redirects.js
Labels: size/XS, ok-to-test

#1078 Release Notes - minor update
  content/docs/00-release-notes.md
Labels: size/XS, ok-to-test, 3.1

#1080 Update 00-release-notes.md
  content/docs/00-release-notes.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#1072 Add GCP (and more) to cloudTypes parameter desc
  content/docs/09-registries-and-packs/3-add-custom-packs.md
  content/docs/09-registries-and-packs/6-helm-charts.md
Labels: documentation, size/S, ok-to-test

#1081 Romain - fix typos on VMware and vSphere
  content/docs/00-release-notes.md
  content/docs/02.5-architecture/04-networking-ports.md
  content/docs/09-registries-and-packs/3-add-custom-packs.md
  vale/styles/Vocab/Internal/accept.txt
  vale/styles/Vocab/Internal/reject.txt
Labels: size/S, ok-to-test

#1082 pack-catagories
  content/docs/03-cluster-profiles/1-task-define-profile.md
Labels: size/XS, needs-ok-to-test, ok-to-test

#1088 Add icons-fix repeat Network-fix link
  content/docs/04-clusters/04-palette-virtual-clusters.md
  content/docs/06-integrations/00-calico.md
  content/docs/06-integrations/00-minio.md
  content/docs/06-integrations/00-multus-cni.md
  content/docs/06-integrations/00-mysql-operator.md
  src/shared/utils/redirects.js
Labels: documentation, size/M, ok-to-test

#1090 Definitions for PXK and PXK-E
  content/docs/04-clusters/03-edge/02-native.md
  content/docs/17-glossary-all.md
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, size/M, ok-to-test

#1095 docs: fixed incorrect JSON paylaods in API sample
  content/api/2-samples.md
Labels: size/S, ok-to-test

#1096 docs: added explanation for AWSEBSCSI policy to virtual clusters
  content/docs/04-clusters/04-palette-virtual-clusters/00-add-virtual-cluster-to-host-cluster.md
Labels: size/XS, ok-to-test

#1084 DOC-698 updating for 1.2
  .github/workflows/pull_request.yaml
  content/docs/04-clusters/06-cluster-management/20-kubernetes-dashboard.md
  content/docs/06-integrations/00-frp.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/docs_integrations_frp_cert-san-example.png
  content/docs/06-integrations/docs_integrations_frp_tls-san-example.png
  content/docs/06-integrations/frp-certsan.png
  prow/postsubmit.sh
  prow/presubmit.sh
  prow/release_build.sh
  src/shared/utils/redirects.js
Labels: size/L

#1099 docs: fixed azure video bug
  content/docs/04-clusters/01-public-cloud/03-azure/01-azure-cloud.md
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
  content/docs/04-clusters/01-public-cloud/03-azure/aks.mp4
  content/docs/04-clusters/01-public-cloud/03-azure/azure.mp4
Labels: bug, size/XS, ok-to-test

#1098 Update 04.5-devx.md
  content/docs/04.5-devx.md
Labels: size/XS, 3.2

#1094 Moving OIDC authentication in the Pre-Reqs
  content/OWNER_ALIASES
  content/docs/04-clusters/06-cluster-management/20-kubernetes-dashboard.md
Labels: size/S, ok-to-test

#1085 tag-update-permission
  content/docs/08-user-management/2-palette-rbac/1-tenant-scope-roles-permissions.md
  content/docs/08-user-management/2-palette-rbac/2-project-scope-roles-permissions.md
Labels: size/S, ok-to-test

#1092 doc-700
  content/docs/08-user-management/2-palette-rbac/1-tenant-scope-roles-permissions.md
  content/docs/08-user-management/2-palette-rbac/2-project-scope-roles-permissions.md
Labels: size/L, ok-to-test

#1101 docs: fixed issue related to redirect error
  content/docs/06-integrations/00-frp.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
Labels: bug, size/XS, ok-to-test
