Repository spectrocloud/librarium, pull requests merged in 2023-02, with the labels that each got.

#1100 Document changes to the sign-in experience
  content/docs/08-user-management/1-user-authentication.md
Labels: size/M, 3.2

#1104 Adding Tag OIDC permission for EKS as IAM policy
  content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
Labels: size/XS, ok-to-test

#1089 Ingress for Cluster Groups
  content/docs/04.5-devx/03-cluster-groups/35-ingress-cluster-group.md
Labels: documentation, size/L, ok-to-test

#1093 Update pack versions
  Makefile
  content/docs/06-integrations/00-aws-efs.md
  content/docs/06-integrations/00-azure-disk.md
  content/docs/06-integrations/00-calico.md
  content/docs/06-integrations/00-external-dns.md
  content/docs/06-integrations/00-external-secrets-operator.md
  content/docs/06-integrations/00-kong.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/00-longhorn.md
  content/docs/06-integrations/00-opa-gatekeeper.md
Labels: documentation, size/L, 3.2

#1105 AWS Resource Tags
  content/docs/04-clusters/01-public-cloud/01-aws/02-architecture.md
Labels: size/S, ok-to-test, 3.2

#1107 Project Force Deletion
  content/docs/07-projects.md
  content/docs/08-user-management/1.8-project-association.md
  vale.ini
Labels: size/L, 3.2

#1112 Revise pack overview doc
  content/docs/06-integrations.mdx
  content/docs/06-integrations/01-standalone-integrated-packs.md
Labels: documentation, size/M, 3.2

#1113 Document AWS Gov cloud STS authentication
  content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
Labels: size/S, ok-to-test, 3.2

#1115 docs: fixed url redirect
  content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
  content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
Labels: bug, size/XS, ok-to-test

#1116 fix: added note about sshkey support in Azure
  content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
Labels: documentation, size/S, ok-to-test

#1102 DOC-476: How-to - Palette SSO with Microsoft ADFS
  content/docs/04-clusters/06-cluster-management/20-kubernetes-dashboard.md
  content/docs/18-knowledgebase/00-how-to.md
  content/docs/18-knowledgebase/00-how-to/00-how-to.md
  content/docs/18-knowledgebase/00-how-to/02-palette-sso-with-adfs.md
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/01-add_application_group.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/02-name_application_group.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/03-get_client_identifier.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/04-copy_callback_url.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/05-paste_redirect_uri.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/06-copy_shared_secret.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/07-open_oidc_app.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/08-add_web_api.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/09a-base_url.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/09b-add_identifiers.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/10-select_policy.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/11-enable_scopes.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/12-reopen_webapi_app.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/13-add_transform_rule_1.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/14-ldap_as_claims.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/15-set_ldap_claims.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/16-add_transform_rule_2.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/17-groups_as_claims.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/18-set_group_claim.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/19-note_adfs_name.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/20-configure_palette_oidc.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/21-create_team.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/22-name_team.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/23-tenant_roles.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/24-add_tenant_role.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/25-user_logout.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/26-palette_login.png
  content/docs/18-knowledgebase/00-how-to/palette-sso-with-adfs-images/27-team_members.png
Labels: size/L, ok-to-test, contribution

#1118 docs: Fix Typo
  README.md
Labels: size/XS, ok-to-test

#1120 docs: PDE updates
  assets/docs/images/045-devx_resource-quota_evaluation-process.png
  assets/docs/images/045-devx_resource-quota_is-beehive-enabled.png
  assets/docs/images/clusters_cluster-groups_index-page.png
  content/docs/04-clusters/04-palette-virtual-clusters.md
  content/docs/04-clusters/04-palette-virtual-clusters/00-add-virtual-cluster-to-host-cluster.md
  content/docs/04-clusters/20-cluster-groups.md
  content/docs/04-clusters/20-cluster-groups/10-create-cluster-group.md
  content/docs/04-clusters/20-cluster-groups/35-ingress-cluster-group.md
  content/docs/04.5-devx/03-cluster-groups.md
  content/docs/04.5-devx/04-resource-quota.md
  content/docs/04.5-devx/06-apps/05-logs.md
  src/shared/utils/redirects.js
  vale.ini
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XL, ok-to-test, 3.2

#1125 DOC-295 - Improve docs custom pack registry
  content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
Labels: size/L, ok-to-test

#1127 docs: added image
  assets/docs/images/intergrations_standalone-integrated-pack_diagram-overview.png
  content/docs/06-integrations/01-standalone-integrated-packs.md
Labels: size/XS

#1126 docs: fix incorrect redirect URL
  content/docs/04-clusters/06-cluster-management/12-palette-webctl.md
Labels: size/S, ok-to-test

#1130 Improve redirect URIs
  content/docs/18-knowledgebase/00-how-to/02-palette-sso-with-adfs.md
Labels: size/XS, ok-to-test

#1133 Update AD FS How To
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-application-group.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-identifiers.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-tenant-role.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-transform-rule-1.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-transform-rule-2.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_add-web-api.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_base-url.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_configure-palette-oidc.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_copy-callback-url.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_copy-logout-url.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_copy-shared-secret.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_create-team.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_enable-scopes.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_get-client-identifier.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_groups-as-claims.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_ldap-as-claims.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_name-application-group.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_name-team.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_note-adfs-name.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_open-oidc-app.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_palette-login.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_paste-logout-uri.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_paste-redirect-uri.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_reopen-webapi-app.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_select-policy.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_set-group-claim.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_set-ldap-claims.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_team-members.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_tenant-roles.png
  assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_user-logout.png
  content/docs/18-knowledgebase/00-how-to/02-palette-sso-with-adfs.md
Labels: size/L, ok-to-test

#1108 PAD-74: Add SBOM scan documentation
  Makefile
  assets/docs/images/sbom_dependencies.png
  assets/docs/images/sbom_results.png
  assets/docs/images/sbom_scan.png
  assets/docs/images/sbom_vulnerabilities.png
  content/docs/04-clusters/06-cluster-management/03-compliance-scan.md
Labels: size/L, needs-ok-to-test, 3.2

#1132 Virtual clusters use cni csi of host cluster
  content/docs/04-clusters/04-palette-virtual-clusters.md
Labels: documentation, size/S, 3.2

#1131 Update 13-terraform.md
  content/docs/13-terraform.md
Labels: size/XS, ok-to-test

#1106 Add Spectro-K8s-dashboard
  content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
  content/docs/06-integrations.mdx
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/00-spectro-k8s-dashboard.md
  content/docs/06-integrations/01-standalone-integrated-packs.md
Labels: documentation, size/L

#1122 Update generic-vm-packs.md
  content/docs/06-integrations/00-generic-vm-libvirt.md
  content/docs/06-integrations/00-generic-vm-vsphere.md
Labels: size/S, ok-to-test

#1111 Create how to resize virtual clusters
  content/docs/04.5-devx/07-palette-virtual-clusters/05-resize-virtual-clusters.md
Labels: documentation, size/M, 3.2

#1134 Compatible Page Updates
  content/docs/09-registries-and-packs/2-spectro-cli-reference.md
  content/docs/16-component.md
Labels: size/L, ok-to-test, 3.2

#1135 docs: fixed incorrect name for edge hosts
  content/api/v1/12-edgehosts.md
Labels: size/XS, ok-to-test

#1136 quick update on project scope
  content/api/1-introduction.md
Labels: size/M, ok-to-test

#1138 Further language clean up
  content/api/1-introduction.md
Labels: size/S, ok-to-test

#1129 Edge auto register
  content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
  content/docs/04-clusters/03-edge.md
  content/docs/04-clusters/03-edge/01-architecture.md
  content/docs/04-clusters/03-edge/01.5-edge-native-lifecycle.md
  content/docs/04-clusters/03-edge/01.8-installer-image.md
  content/docs/04-clusters/03-edge/02-native.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/XL, 3.2

#1137 3.2 API docs
  content/api/1-introduction.md
  content/api/palette-apis.json
  content/api/v1/12-edgehosts.md
  content/api/v1/api.json
Labels: size/XXL, ok-to-test, 3.2

#1140 Cluster group volumes backup
  assets/docs/images/clusters_cluster-groups_cluster-group-backups_backup-overview.png
  content/docs/04-clusters/04-palette-virtual-clusters.md
  content/docs/04-clusters/04-palette-virtual-clusters/00-add-virtual-cluster-to-host-cluster.md
  content/docs/04-clusters/04-palette-virtual-clusters/02-deploy-virtual-cluster.md
  content/docs/04-clusters/06-cluster-management/05-backup-restore.md
  content/docs/04-clusters/20-cluster-groups.md
  content/docs/04-clusters/20-cluster-groups/25-cluster-group-backups.md
  content/docs/04.5-devx/05-app-profile/08-services/15-db-services.md
  vale/styles/Vocab/Internal/accept.txt
Labels: size/L, 3.2

#1128 Add 3.2 release notes
  content/docs/00-release-notes.md
Labels: size/M, ok-to-test, 3.2

#1139 Update 0-.ssh.md
  content/docs/04-clusters/06-cluster-management/0-.ssh.md
  content/docs/04-clusters/06-cluster-management/0-ssh-keys.md
  src/shared/utils/redirects.js
Labels: size/M, ok-to-test

#1144 Update MAAS/OpenStack PCG version
  content/docs/04-clusters/02-data-center/01-maas.md
  content/docs/16-component.md
  content/docs/16-spectro-downloads.md
Labels: size/S, ok-to-test, 3.2

#1145 docs: cleanup in the PDE section related to PPD-913
  content/docs/00-release-notes.md
  content/docs/04-clusters/20-cluster-groups.md
  content/docs/04.5-devx.md
  content/docs/04.5-devx/01-dev-land-explore.md
  content/docs/04.5-devx/02-enterprise-user.md
  src/shared/utils/redirects.js
Labels: size/L, ok-to-test, 3.2

#1146 ci: added gitleaks ci job
  .github/workflows/gitleaks.yaml
Labels: size/M, CI/CD

#1148 ci: adding semantic release
  .github/workflows/release.yaml
  .releaserc.yaml
  README.md
  package-lock.json
  package.json
Labels: size/XXL, ok-to-test, CI/CD

#1141 Antrea cni pack
  content/docs/06-integrations/00-antrea-cni.md
Labels: documentation, size/L

#1150 docs: DOC-730 added docs for stylus CLI
  content/docs/16-component.md
Labels: documentation, size/S, ok-to-test
