Repository spectrocloud/librarium, pull requests merged in 2023-06, with the labels that each got.

#1313 Packs-maintenance-policy
  content/docs/06-integrations.mdx
  content/docs/06-integrations/00-kubernetes.md
  content/docs/06-integrations/01-maintenance-policy.md
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation

#1343 K8s Pack Minor Updates
  content/docs/06-integrations/00-kubernetes.md
  content/docs/17-glossary-all.md
Labels: documentation

#1347 docs: fix IAM policy DOC-785
  content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
Labels: bug

#1014 Add Security section
  assets/docs/images/security_dev_lifecycle.png
  content/docs/02.5-architecture/01-architecture-overview.md
  content/docs/09.5-security.md
  content/docs/09.5-security/05-core-principles.md
  content/docs/09.5-security/08-lifecycle.md
  content/docs/09.5-security/10-lifecycle/12-secure-development.md
  content/docs/09.5-security/10-lifecycle/15-release-process.md
  content/docs/09.5-security/10-product-architecture.md
  content/docs/09.5-security/11-product-architecture/01-platform-security.md
  content/docs/09.5-security/11-product-architecture/02-data-encryption.md
  content/docs/09.5-security/11-product-architecture/03-saas-operation.md
  content/docs/09.5-security/11-product-architecture/04-self-hosted-operation.md
  content/docs/09.5-security/11-product-architecture/05-tenant-cluster.md
  content/docs/09.5-security/20-security-bulletins.md
  content/docs/09.5-security/20-security-bulletins/10-cve-reports.md
  content/docs/09.5-security/20-security-bulletins/20-index.md
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, do-not-merge/work-in-progress, size/XL, future release

#1373 docs: broken URL fixed
  content/docs/00-release-notes.md
  content/docs/09.5-security.md
  content/docs/09.5-security/11-product-architecture/03-saas-operation.md
Labels: bug

#1375 OIDC configuration
  content/deprecated/06-integrations/00-oidc-eks.md
  content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
  content/docs/06-integrations/00-kubernetes-dashboard.md
  content/docs/06-integrations/00-kubernetes-generic.md
  content/docs/06-integrations/00-kubernetes.md
  content/docs/06-integrations/00-spectro-k8s-dashboard.md
  src/shared/utils/redirects.js
Labels: documentation, 3.4

#1378 Add spectro-template, several grammar fixes
  content/docs/04-clusters/02-data-center/03-vmware.md
Labels: documentation, 3.4
