Repository spectrocloud/librarium, pull requests merged in 2024-02, with the labels that each got.

#2128 docs: Guide on approving cluster repave operations
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/user-management/authentication/api-key/create-api-key.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  static/assets/docs/images/clusters_cluster-management_node-pool_available-updates-modal.png
  static/assets/docs/images/clusters_cluster-management_node-pool_cluster-nodes-healthy.png
  static/assets/docs/images/clusters_cluster-management_node-pool_cluster-updates-highlight.png
Labels: auto-backport, backport-version-4-2

#2166 Update spectro-cli-reference.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
Labels: auto-backport, backport-version-4-2

#2168 docs: DOC-1054 typo fix
  docs/docs-content/vm-management/vm-management.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2174 Deprecate Cox Edge content and add an unlisted page for redirects
  docs/deprecated/clusters/public-cloud/cox-edge/_category_.json
  docs/deprecated/clusters/public-cloud/cox-edge/add-cox-edge-accounts.md
  docs/deprecated/clusters/public-cloud/cox-edge/cox-edge.md
  docs/deprecated/clusters/public-cloud/cox-edge/create-cox-cluster.md
  docs/deprecated/clusters/public-cloud/cox-edge/network-rules.md
  docs/docs-content/clusters/public-cloud/public-cloud.md
  docs/docs-content/unlisted/_category_.json
  docs/docs-content/unlisted/cox-edge-eol.md
  docs/docs-content/unlisted/unlisted.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2135 chore: upgrade to docusaurus 3.1.1
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/devx/services/service-listings/vault.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements.md
  docs/docs-content/glossary-all.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
  docs/docs-content/registries-and-packs/adding-a-custom-registry.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#1966 OIDC w/ Entra ID
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-25_def_project_admin.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-OIDCCallback.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-allgroups.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-ba_group.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-ba_tenantadmin.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-enable.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-groupsclaim.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-k8s_cluster_admins.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-oidcallback.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-overivew.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-palette-registration.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-paletteregisterapp.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-success.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-testgroups.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-token-configuration.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-twoclaims.png
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-twooptionalclaims.png
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2187 Upgrade Mendable component
  src/components/MendableAIWidget/MendableAIWidget.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2194 Backup and other fix
  docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
  docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
  docs/docs-content/integrations/ubuntu.md
  docs/docs-content/registries-and-packs/registries/registries.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2193 docs: add note that exiting proxy pod must be restarted for vmo
  docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2203 docs: DOC-1061
  docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
  docs/docs-content/profiles/cluster-profiles/export-import-cluster-profile.md
  static/assets/docs/images/profiles_cluster-profiles_export-import-cluster-profiles_export-highlight.png
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2202 Update site-installation.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-installation.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2141 docs: add instructions for first boot tui
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/site-deployment/initial-setup.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
  static/assets/docs/images/cluster_edge_site-deployment_installation_initial-setup_tui.png
Labels: 4.3

#2072 docs: document etcd backups
  docs/docs-content/clusters/cluster-groups/cluster-group-backups.md
  docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md
  docs/docs-content/clusters/cluster-management/backup-restore/enable-etcd-backup.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2216 docs: add podman to tutorials DOC-1010 DOC-1009
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2214 docs: add podman, update container image
  docs/docs-content/devx/apps/deploy-app.md
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2227 docs: release notes for patch 4.2.9 DOC-1070
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2235 Maintenance
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/integrations/frp.md
  docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2239 docs: DOC-1059 inclusive diagram
  .releaserc.yaml
  static/assets/docs/images/edge_edge-configuration_cloud-init_user-data.png
  static/assets/docs/images/native-edge-deployment-lifecycle.png
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#1918 VMO - Using DataVolumes guide
  docs/docs-content/vm-management/create-manage-vm/create-disk-templates.md
  docs/docs-content/vm-management/vm-management.md
  static/assets/docs/images/create-disk-templates-guide/vm-management_create-manage-vm_create-disk-templates_add-on-disk-template-profile.png
  static/assets/docs/images/create-disk-templates-guide/vm-management_create-manage-vm_create-disk-templates_create-vm-from-template.png
Labels: auto-backport, backport-version-4-2

#2246 Update Vale to accept PCGs, vCPU, and vCPUs
  vale/styles/Vocab/Internal/accept.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2251 docs: add release notes for pcp 2516
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2253 docs: Update release-notes callout
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2255 Small 4.2.12 releases nodes fixes
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2257 Update Palette CLI download link
  docs/docs-content/spectro-downloads.md
Labels: auto-backport, backport-version-4-2

#2075 PCG Section [Refactor]
  README.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/pcg/_category_.json
  docs/docs-content/clusters/pcg/architecture.md
  docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
  docs/docs-content/clusters/pcg/deploy-pcg/_category_.json
  docs/docs-content/clusters/pcg/deploy-pcg/deploy-pcg.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/manage-pcg/_category_.json
  docs/docs-content/clusters/pcg/manage-pcg/create-manage-node-pool.md
  docs/docs-content/clusters/pcg/manage-pcg/manage-pcg.md
  docs/docs-content/clusters/pcg/manage-pcg/remove-pcg.md
  docs/docs-content/clusters/pcg/manage-pcg/scale-pcg-nodes.md
  docs/docs-content/clusters/pcg/pcg.md
  src/components/IconMapper/dynamicFontAwesomeImports.js
  static/assets/docs/images/clusters_manage-pcg_scale-pcg-nodes_nodes-view.png
  static/assets/docs/images/clusters_pcg_architecture_overview_diagram.png
  static/assets/docs/images/clusters_pcg_architecture_system-pcg-ui.png
  static/assets/docs/images/clusters_pcg_deploy-pcg-k8s_kubectl-cmds-view.png
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2262 Pcg deprecation
  docs/deprecated/clusters/data-center/maas/install-manage-maas-pcg.md
  docs/docs-content/architecture/architecture-overview.md
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/data-center/maas/maas.md
  docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
  docs/docs-content/clusters/data-center/nutanix/install-pcg/install-pcg.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/palette-cli/commands/pcg.md
  docs/docs-content/security/product-architecture/saas-operation.md
  docs/docs-content/vm-management/vm-management.md
  redirects.js
  vale/styles/Vocab/Internal/reject.txt
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2268 chore: update pdf script
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2287 4.2.13 RL
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2263 PCG Updates
  Makefile
  docs/deprecated/troubleshooting/pcg.md
  docs/docs-content/clusters/clusters.md
  docs/docs-content/clusters/pcg/architecture.md
  docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/manage-pcg/create-manage-node-pool.md
  docs/docs-content/clusters/pcg/manage-pcg/manage-pcg.md
  docs/docs-content/clusters/pcg/manage-pcg/pcg-upgrade.md
  docs/docs-content/troubleshooting/pcg.md
  static/assets/docs/images/clusters_manage-pcg_pcg-upgrade_updates-button.png
  vale.ini
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2297 chore: add acronym rule to vale DOC-940
  vale/styles/spectrocloud/acronym.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2296 docs: PEM-4571 multi-account
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
  docs/docs-content/enterprise-version/system-management/account-management/account-management.md
  docs/docs-content/enterprise-version/system-management/account-management/credentials.md
  docs/docs-content/enterprise-version/system-management/account-management/email.md
  docs/docs-content/enterprise-version/system-management/account-management/manage-system-accounts.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/glossary-all.md
  docs/docs-content/vertex/system-management/account-management/account-management.md
  docs/docs-content/vertex/system-management/account-management/credentials.md
  docs/docs-content/vertex/system-management/account-management/email.md
  docs/docs-content/vertex/system-management/account-management/manage-system-accounts.md
  docs/docs-content/vertex/system-management/system-management.md
  static/assets/docs/images/vertex_account-management_manage-system-accounts_user-dashboard.png
Labels: 4.3

#2305 docs: Update azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2304 Password Blocklist
  docs/docs-content/enterprise-version/system-management/account-management/credentials.md
  docs/docs-content/enterprise-version/system-management/account-management/password-blocklist.md
  docs/docs-content/vertex/system-management/account-management/credentials.md
  docs/docs-content/vertex/system-management/account-management/password-blocklist.md
Labels: 4.3

#2310 Configure Robots
  Makefile
  scripts/generate_robots.sh
  scripts/versions.sh
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2315 Updated airgap diagrams
  docs/docs-content/enterprise-version/install-palette/airgap/airgap.md
  docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/airgap/airgap.md
  docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
  static/assets/docs/images/enterprise-version_air-gap-repo_overview-order-diagram-focus.png
  static/assets/docs/images/enterprise-version_air-gap-repo_overview-order-diagram.png
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2320 docs: update api-key-management.md
  docs/docs-content/tenant-settings/api-key-management.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2
