Repository spectrocloud/librarium, pull requests merged in 2024-01, with the labels that each got.

#1953 Update cilium-tetragon.md
  docs/docs-content/integrations/cilium-tetragon.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1954 Flannel Packs Page
  docs/docs-content/integrations/flannel-cni.md
  vale/styles/Vocab/Internal/accept.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1962 Azure account gov create
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/azure.md
  vale/styles/Vocab/Internal/accept.txt
Labels: 4.2

#1967 chore: updated Vale rule to standarize on README
  vale/styles/Vocab/Internal/accept.txt
  vale/styles/Vocab/Internal/reject.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#1971 docs: PEM-4272
  docs/docs-content/enterprise-version/system-management/account-management/credentials.md
  docs/docs-content/vertex/system-management/account-management/credentials.md
  static/assets/docs/images/vertex_account-management_credentials_browser-cache-token.png
  static/assets/enterprise-version-account-management_credentials_browser-cache-token.png
Labels: 4.2

#1963 Longhorn Manual Resolution
  docs/docs-content/integrations/longhorn.md
Labels: 4.2

#1972 docs: open source license
  docs/docs-content/legal-licenses.md
Labels: 4.2

#1973 docs: update new pack versions
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/rke2.md
Labels: 4.2

#1883 Document Nutanix
  docs/docs-content/clusters/data-center/data-center.md
  docs/docs-content/clusters/data-center/nutanix/add-nutanix-cloud-account.md
  docs/docs-content/clusters/data-center/nutanix/architecture.md
  docs/docs-content/clusters/data-center/nutanix/create-manage-nutanix-cluster.md
  docs/docs-content/clusters/data-center/nutanix/install-pcg/deploy-kubernetes-cluster-pcg.md
  docs/docs-content/clusters/data-center/nutanix/install-pcg/install-pcg.md
  docs/docs-content/clusters/data-center/nutanix/nutanix.md
  docs/docs-content/clusters/data-center/nutanix/register-nutanix-cloud.md
  docs/docs-content/glossary-all.md
  docs/docs-content/integrations/nutanix-csi.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-cluster-profiles.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-full-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-infrastructure-profile.md
  static/assets/docs/images/clusters_data-center_nutanix_architecture.png
  static/assets/docs/images/clusters_data-center_nutanix_workflow.png
  vale/styles/Vocab/Internal/accept.txt
Labels: documentation, 4.2

#1975 Collection of 4.2 items
  docs/docs-content/clusters/cluster-management/image-swap.md
  docs/docs-content/clusters/palette-virtual-clusters/palette-virtual-clusters.md
  docs/docs-content/devx/devx.md
  docs/docs-content/integrations/harbor-edge.md
  docs/docs-content/release-notes.md
Labels: 4.2

#1977 docs: date fix
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#1979 Ci bypass
  .github/workflows/release.yaml
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#1892 docs: update tutorial cluster profiles DOC-935
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_cluster_profile_view.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_clusters_creation_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_clusters_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_details.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_profile_cluster_profile_review.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_azure_create_cluster_details.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_cluster_profile_stack.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_profile_review.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_app.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_delete-cluster-button.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_manifest.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_manifest_blue_btn.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_service_url.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_update_available.png
  static/assets/docs/images/tutorials/deploy-clusters/deploy_app/clusters_public-cloud_deploy-k8s-cluster_update_details_compare.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_clusters_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_gcp_cluster_profile_stack_view.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_profile_details.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_profile_review.png
Labels: tutorial, backport-version-4-0, backport-version-3-4, backport-version-4-1, backport-version-4-2

#1912 docs: add deploy cluster profile updates tutorial DOC-921
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_add-service-tag.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_apply-frontend-filter.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_available-updates-dialog.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_completed-cluster-updates.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_deployed-FE-cluster.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_deployed-clusters-start-setup.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_hello-universe-with-api.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_hello-universe-without-api.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_new-version-overview.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_pending-update-clusters-view.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_profile-version-selection.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_profile-with-cluster.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_tf-available-updates-dialog.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_tf-profile-new-version.png
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_updates-available-button-cluster-overview.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_cluster_profile_view.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_clusters_creation_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_clusters_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_details.png
  static/assets/docs/images/tutorials/deploy-clusters/aws/clusters_public-cloud_deploy-k8s-cluster_profile_cluster_profile_review.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_azure_create_cluster_details.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_cluster_profile_stack.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/azure/clusters_public-cloud_deploy-k8s-cluster_profile_review.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_app.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_delete-cluster-button.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_manifest.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_manifest_blue_btn.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_service_url.png
  static/assets/docs/images/tutorials/deploy-clusters/clusters_public-cloud_deploy-k8s-cluster_update_available.png
  static/assets/docs/images/tutorials/deploy-clusters/deploy_app/clusters_public-cloud_deploy-k8s-cluster_update_details_compare.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_clusters_parameters.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_gcp_cluster_profile_stack_view.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_profile_details.png
  static/assets/docs/images/tutorials/deploy-clusters/gcp/clusters_public-cloud_deploy-k8s-cluster_profile_review.png
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#1990 docs: updated PCG per feedback DOC-998
  docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/palette-cli/commands/pcg.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#1994 docs: add release notes - DOC-1011
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#1914 chore: upgrade to docusarus v3
  .github/workflows/pull_request.yaml
  .gitignore
  apisidebar.js
  docs/api-content/api-docs/1-introduction.md
  docs/api-content/api-docs/v1/api.json
  docs/deprecated/registries-and-packs/oci-registry.md
  docs/docs-content/byoos/image-builder.md
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  docs/docs-content/clusters/cluster-groups/ingress-cluster-group.md
  docs/docs-content/clusters/cluster-management/image-swap.md
  docs/docs-content/clusters/clusters.md
  docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
  docs/docs-content/clusters/edge/site-deployment/model-profile.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/devx/palette-virtual-clusters/palette-virtual-clusters.md
  docs/docs-content/devx/services/db-services.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/enterprise-version/upgrade.md
  docs/docs-content/getting-started/dashboard.md
  docs/docs-content/integrations/generic-vm-vsphere.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/trident.md
  docs/docs-content/integrations/ubuntu.md
  docs/docs-content/palette-cli/commands/docs.md
  docs/docs-content/palette-cli/commands/login.md
  docs/docs-content/profiles/app-profiles/create-app-profiles/create-out-of-box-app-profile.md
  docs/docs-content/profiles/app-profiles/delete-app-profile.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
  docs/docs-content/registries-and-packs/adding-add-on-packs.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/registries/registries.md
  docs/docs-content/tenant-settings/api-key-management.md
  docs/docs-content/troubleshooting/cluster-deployment.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
  docs/docs-content/workspace/workload-features.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/PacksTable/PackTable.test.tsx
  src/components/PacksTable/PacksTable.tsx
  src/components/mdx/Video/Video.tsx
  src/components/mdx/index.js
  src/css/custom.scss
  src/theme/CodeBlock/Content/String.js
  src/theme/DocCard/index.js
  src/theme/DocSidebarItem/Category/index.js
  tsconfig.json
Labels: enhancement, javascript

#2006 Break Out OSS Page
  docs/docs-content/legal-licenses/_category_.json
  docs/docs-content/legal-licenses/legal-licenses.md
  docs/docs-content/legal-licenses/oss-licenses.md
  vale/styles/spectrocloud/spectrocloud.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2019 docs: removed PCG-E from glossary
  docs/docs-content/glossary-all.md
Labels: documentation, auto-backport, backport-version-4-1, backport-version-4-2

#2016 chore: fix issues with hideclipboard not working
  docs/docs-content/troubleshooting/palette-dev-engine.md
  src/theme/CodeBlock/Content/String.js
  src/theme/CodeBlock/CopyButton/index.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2017 chore: Add a custom admonition for Tech Preview content
  docs/docs-content/clusters/data-center/nutanix/nutanix.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/integrations/harbor-edge.md
  docs/docs-content/introduction/introduction.md
  docusaurus.config.js
  src/css/custom.scss
  src/css/dark-mode.scss
  src/css/light-mode.scss
  src/theme/Admonition/Icon/TechPreview.js
  src/theme/Admonition/Type/TechPreview.js
  src/theme/Admonition/Types.js
  src/theme/Admonition/index.js
Labels: auto-backport, backport-version-4-2

#2015 docs: Added a new topic on generating HAR files
  docs/docs-content/troubleshooting/generate-har-files.md
  docs/docs-content/troubleshooting/troubleshooting.md
  static/assets/docs/images/troubleshooting_generate-har-files_chrome-dev-tools-settings.png.png
  static/assets/docs/images/troubleshooting_generate-har-files_firefox-devtools.png
  static/assets/docs/images/troubleshooting_generate-har-files_safari-web-inspector.png
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2018 Update palette-canvos.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
Labels: auto-backport, backport-version-4-2

#2033 Generate HAR Files: Fix wording in Prerequisites
  docs/docs-content/troubleshooting/generate-har-files.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2013 Clarify Kubernetes Support Lifecycle
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes-support.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/maintenance-policy.md
  docs/docs-content/integrations/microk8s.md
  docs/docs-content/integrations/rke2.md
  static/assets/docs/images/integrations_kubernetes-support_support-cycle.png
  static/assets/docs/images/integrations_kubernetes-support_support-cycle_other.png
  vale/styles/spectrocloud/spectrocloud.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2051 Image Fix
  docs/docs-content/architecture/networking-ports.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2055 Add layer constraint info to pack-constraints.md
  docs/docs-content/clusters/public-cloud/gcp/add-gcp-accounts.md
  docs/docs-content/registries-and-packs/pack-constraints.md
  docs/docs-content/registries-and-packs/registries/helm-charts.md
  docs/docs-content/registries-and-packs/registries/registries.md
Labels: contribution, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2031 ISO 27001
  docs/docs-content/architecture/grps-proxy.md
  docs/docs-content/clusters/cluster-groups/cluster-group-backups.md
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
  docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md
  docs/docs-content/clusters/cluster-management/cluster-tag-filter/cluster-tag-filter.md
  docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
  docs/docs-content/clusters/cluster-management/monitoring/deploy-agent.md
  docs/docs-content/clusters/cluster-management/palette-webctl.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
  docs/docs-content/clusters/public-cloud/aws/aws.md
  docs/docs-content/clusters/public-cloud/azure/azure.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/compliance.md
  docs/docs-content/devx/devx.md
  docs/docs-content/devx/services/service-listings/vault.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/ubuntu.md
  docs/docs-content/introduction/introduction.md
  docs/docs-content/legal-licenses/compliance.md
  docs/docs-content/legal-licenses/legal-licenses.md
  docs/docs-content/legal-licenses/oss-licenses.md
  docs/docs-content/profiles/app-profiles/app-profile-output-vars.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/security/security.md
  docs/docs-content/troubleshooting/cluster-deployment.md
  docs/docs-content/user-management/palette-rbac/palette-rbac.md
  docs/docs-content/user-management/user-management.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/system-management/enable-non-fips-settings/enable-non-fips-settings.md
  docs/docs-content/workspace/workload-features.md
  docusaurus.config.js
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  static/assets/docs/images/legal-licenses_compliance_iso-27001.png
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2044 chore: add vale rule for product UI naming
  docs/docs-content/glossary-all.md
  vale/styles/spectrocloud/product-ui.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2059 Update palette-public-ips.md
  docs/docs-content/architecture/palette-public-ips.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#1999 New CVEs included
  docs/docs-content/security/security-bulletins/cve-index.md
  docs/docs-content/security/security-bulletins/cve-reports.md
  vale/styles/Vocab/Internal/accept.txt
Labels: auto-backport, backport-version-4-1, backport-version-4-2

#1878 Add Tailscale as Third Party Integration for Palette Edge
  .gitignore
  .vscode/settings.json
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/third-party-integrations/_category_.json
  docs/docs-content/clusters/edge/third-party-integrations/tailscale.md
  docs/docs-content/clusters/edge/third-party-integrations/third-party-integrations.md
  package-lock.json
  vale/styles/Vocab/Internal/accept.txt
Labels: auto-backport, backport-version-4-2

#2099 Revert "chore: add vale rule to avoid master and slave"
  vale/styles/spectrocloud/inclusive.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2106 chore: add vale rule for master/slave language
  .prettierignore
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/spectrocloud/inclusive.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2090 docs: revise freemium page mentions DOC-1036
  docs/deprecated/getting-started/palette-freemium.md
  docs/docs-content/devx/enterprise-user.md
  docs/docs-content/getting-started/getting-started.md
  docs/docs-content/introduction/introduction.md
  docs/docs-content/user-management/saml-sso/palette-sso-azure-ad.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2092 docs: add instructions for connecting edge host to wifi
  docs/docs-content/clusters/edge/networking/connect-wifi.md
  docs/docs-content/clusters/edge/networking/networking.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
  vale/styles/Vocab/Internal/accept.txt
Labels: auto-backport, backport-version-4-2

#2104 Document Prettier in README
  .prettierignore
  Makefile
  README.md
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2120 docs: add warning for private registry password
  docs/docs-content/clusters/edge/networking/local-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md
Labels: auto-backport, backport-version-4-2

#2089 Language Clean-up
  docs/docs-content/audit-logs/kube-api-audit-logging.md
  docs/docs-content/clusters/cluster-management/cloud-cost.md
  docs/docs-content/clusters/cluster-management/compliance-scan.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/cluster-management/reconfigure.md
  docs/docs-content/clusters/cluster-management/taints.md
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  docs/docs-content/clusters/clusters.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/data-center/nutanix/create-manage-nutanix-cluster.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/cox-edge/create-cox-cluster.md
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
  docs/docs-content/devx/apps/deploy-app.md
  docs/docs-content/enterprise-version/system-management/backup-restore.md
  docs/docs-content/glossary-all.md
  docs/docs-content/integrations/collectord.md
  docs/docs-content/integrations/kibana.md
  docs/docs-content/integrations/ubuntu.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/pack-constraints.md
  styleguide/spectro-cloud-style-guide.md
  vale/styles/spectrocloud/inclusive.yml
Labels: documentation, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2105 docs: release notes patch 4.2.7
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-2

#2003 Airgap refactor
  docs/docs-content/enterprise-version/install-palette/airgap/airgap.md
  docs/docs-content/enterprise-version/install-palette/airgap/checklist.md
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/integrations/metallb.md
  docs/docs-content/integrations/prometheus-operator.md
  docs/docs-content/legal-licenses/legal-licenses.md
  docs/docs-content/vertex/install-palette-vertex/airgap/airgap.md
  docs/docs-content/vertex/install-palette-vertex/airgap/checklist.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  static/assets/docs/images/vertex_airgap_vmware-vsphere-airgap-instructions_order-operations.png
  static/assets/docs/images/vertex_airgap_vmware-vsphere-airgap-instructions_ovf-wizard.png
  vale/styles/Vocab/Internal/accept.txt
Labels: auto-backport, backport-version-4-2

#2137 chore: added missing refactor page
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: auto-backport, backport-version-4-2

#2132 docs: change minimum disk size for Edge
  docs/docs-content/clusters/edge/architecture.md
Labels: auto-backport, backport-version-4-2

#2139 Helm install changes
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
Labels: auto-backport, backport-version-4-2

#2143 Add a Vale rule to check for admonitions of type `:::note`
  vale/styles/spectrocloud/admonitions.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2133 docs: add harbor, update screenshots
  docs/docs-content/registries-and-packs/deploy-pack.md
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_architecture-diagram.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry-edit.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry-sync.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_basic-oci-registry.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-login.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-project.png
  static/assets/docs/images/tutorials/deploy-pack/registries-and-packs_deploy-pack_harbor-repository.png
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2152 Helm install changes
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
Labels: auto-backport, backport-version-4-2
