Repository spectrocloud/librarium, pull requests merged in 2024-07, with the labels that each got.

#3183 chore: Fix a broken link
  docs/docs-content/integrations/portworx_operator.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3191 ci: update CI workflow for new release format
  .github/workflows/release-branch-pr.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3233 ci: migrate to Vale
  .github/workflows/pull_request.yaml
  .gitignore
  vale.ini
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/config/vocabularies/Internal/reject.txt
  vale/styles/spectrocloud/ableism.yml
  vale/styles/spectrocloud/acronym.yml
  vale/styles/spectrocloud/admonitions.yml
  vale/styles/spectrocloud/colon.yml
  vale/styles/spectrocloud/condescending.yml
  vale/styles/spectrocloud/direction.yml
  vale/styles/spectrocloud/file-type.yml
  vale/styles/spectrocloud/future.yml
  vale/styles/spectrocloud/gender.yml
  vale/styles/spectrocloud/headings-title.yml
  vale/styles/spectrocloud/inclusive.yml
  vale/styles/spectrocloud/longform.yml
  vale/styles/spectrocloud/oxford-comma.yml
  vale/styles/spectrocloud/plural-parantheses.yaml
  vale/styles/spectrocloud/product-ui.yml
  vale/styles/spectrocloud/spectrocloud.yml
  vale/styles/spectrocloud/we.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3198 chore: Change the spelling of Local UI
  docs/deprecated/clusters/edge/edgeforge-workflow/build-artifacts.md
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/host-management/access-console.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
  docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md
  docs/docs-content/clusters/edge/local-ui/host-management/diagnostic-tools.md
  docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
  docs/docs-content/clusters/edge/site-deployment/initial-setup.md
  docs/docs-content/getting-started/additional-capabilities.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3234 docs: edge management api 4.4.a
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.4.a

#3246 CVE-2024-6387 - Security Advisory
  docs/docs-content/security-bulletins/cve-index.md
  docs/docs-content/security-bulletins/cve-reports.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3252 Steps for deleting the incorrectly created `kubernetes` LB and public IP
  docs/docs-content/troubleshooting/cluster-deployment.md
  docs/docs-content/troubleshooting/edge.md
  docs/docs-content/troubleshooting/nodes.md
  docs/docs-content/troubleshooting/palette-dev-engine.md
  docs/docs-content/troubleshooting/pcg.md
  docs/docs-content/troubleshooting/troubleshooting.md
Labels: 4.4.a

#3255 Clean up markup and alignment in the Troubleshooting section
  docs/docs-content/troubleshooting/cluster-deployment.md
  docs/docs-content/troubleshooting/edge.md
  docs/docs-content/troubleshooting/nodes.md
  docs/docs-content/troubleshooting/palette-dev-engine.md
  docs/docs-content/troubleshooting/pcg.md
  docs/docs-content/troubleshooting/troubleshooting.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3179 4.4.7 - Notes
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3258 Document the `fullyPrivateAddressing` property and its limitations for Azure
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
Labels: 4.4.a

#2874 Document AKS features from 3.4
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/architecture.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3279 ci: fix missing env
  .github/workflows/nightly-docker-build.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3291 docs: PE-4678
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3290 Known issue for using custom CA with Azure AKS
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3294 docs: add video card known issue
  docs/docs-content/release-notes/known-issues.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3304 chore: Fix a broken intro card link
  docs/docs-content/tutorials/tutorials.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3253 docs: partial fixes DOC-1263
  README.md
  scripts/generate-partials.sh
  src/components/PartialsComponent/PartialsComponent.tsx
  src/components/SimpleCardGrid/SimpleCardGrid.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3300 docs: document edge host known issue - PE-4638
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3327 docs: update OSS licenses OPS-4804
  docs/docs-content/legal-licenses/oss-licenses.md
Labels: 4.4.a

#3254 docs: update edge-cli version
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
Labels: auto-backport, backport-version-4-4

#3212 docs: PEM-5064
  _partials/feature_flags/_feature_flags_overview.mdx
  docs/docs-content/enterprise-version/system-management/feature-flags.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/vertex/system-management/feature-flags.md
  docs/docs-content/vertex/system-management/system-management.md
  src/components/IconMapper/dynamicFontAwesomeImports.js
Labels: 4.4.a

#3243 docs: add parameter about preventing password change in local ui
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/local-ui/host-management/access-console.md
Labels: 4.4.a

#3339 docs: Update prereqs for the `fullyPrivateAddressing` parameter
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
Labels: 4.4.a

#3340 docs: add new known issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3320 Release Notes 4.4.a
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/pcg.md
Labels: 4.4.a

#3338 Document the steps for using custom CA
  docs/docs-content/user-management/saml-sso/palette-sso-with-custom-ca.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
  static/assets/docs/images/user-management_saml-sso_palette-sso-with-custom-ca_enter-cert.webp
Labels: 4.4.a

#3346 Convert the HTTPS/TLS admonition to a bullet
  docs/docs-content/user-management/saml-sso/palette-sso-with-custom-ca.md
Labels: 4.4.a

#3344 docs: add additional qualifier for network environments
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3345 Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements
  docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3337 Document the step for removing kind images after EC and PCG installation
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.4.a

#3362 Document the step for removing kind images after EC and PCG installation
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3369 docs: add additional args
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
Labels: auto-backport, backport-version-4-4

#3379 Add the Further Guidance admonition + link to the VMware PCG tutorial
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docusaurus.config.js
  src/css/custom.scss
  src/css/dark-mode.scss
  src/css/light-mode.scss
  src/theme/Admonition/Icon/FurtherGuidance.js
  src/theme/Admonition/Type/FurtherGuidance.js
  src/theme/Admonition/Types.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3387 chore: Update README for admonitions
  README.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3378 docs: PCP-3141
  docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
  docs/docs-content/clusters/pcg/manage-pcg/configure-proxy.md
  docs/docs-content/clusters/pcg/manage-pcg/manage-pcg.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/architecture.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.4.a

#3120 Security Bulletin Changes
  .gitignore
  .prettierignore
  docs/api-content/api-docs/edge-v1/emc-api.json
  docs/api-content/api-docs/v1/api.json
  docs/deprecated/registries-and-packs/cve-index.md
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2020-1971.md
  docs/docs-content/security-bulletins/reports/cve-2021-3449.md
  docs/docs-content/security-bulletins/reports/cve-2021-3711.md
  docs/docs-content/security-bulletins/reports/cve-2021-45079.md
  docs/docs-content/security-bulletins/reports/cve-2022-0778.md
  docs/docs-content/security-bulletins/reports/cve-2022-25883.md
  docs/docs-content/security-bulletins/reports/cve-2022-41723.md
  docs/docs-content/security-bulletins/reports/cve-2022-4450.md
  docs/docs-content/security-bulletins/reports/cve-2023-0215.md
  docs/docs-content/security-bulletins/reports/cve-2023-0286.md
  docs/docs-content/security-bulletins/reports/cve-2023-0464.md
  docs/docs-content/security-bulletins/reports/cve-2023-39325.md
  docs/docs-content/security-bulletins/reports/cve-2023-44487.md
  docs/docs-content/security-bulletins/reports/cve-2023-45142.md
  docs/docs-content/security-bulletins/reports/cve-2023-47108.md
  docs/docs-content/security-bulletins/reports/cve-2023-52425.md
  docs/docs-content/security-bulletins/reports/cve-2023-5528.md
  docs/docs-content/security-bulletins/reports/cve-2024-21626.md
  docs/docs-content/security-bulletins/reports/ghsa-m425-mq94-257g.md
  docs/docs-content/security-bulletins/reports/prisma-2022-0227.md
  docs/docs-content/security-bulletins/reports/reports.md
  docs/docs-content/security-bulletins/security-bulletins.md
  docs/docs-content/security/security.md
  docs/docs-content/unlisted/cve-reports.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3397 docs: PEM-5375
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: 4.4.a

#3399 Update ghsa-m425-mq94-257g.md
  docs/docs-content/security-bulletins/reports/ghsa-m425-mq94-257g.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3400 docs: add known issue
  docs/docs-content/release-notes/known-issues.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3415 docs: PE 4708 fix
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3396 docs: bump tutorials tag DOC-1303
  .prettierignore
  _partials/tutorials/_checkout_tutorial_tag.mdx
  _partials/tutorials/_download_tutorial_image_docker.mdx
  _partials/tutorials/_download_tutorial_image_podman.mdx
  _partials/tutorials/_run_tutorial_container_docker.mdx
  _partials/tutorials/_run_tutorial_container_podman.mdx
  _partials/tutorials/_stop_tutorial_container_docker.mdx
  _partials/tutorials/_stop_tutorial_container_podman.mdx
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/getting-started/terraform.md
  docs/docs-content/tutorials/cluster-deployment/pde/deploy-app.md
  docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md
  docs/docs-content/tutorials/profiles/deploy-pack.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3395 docs: refactor taints guide DOC-1272
  docs/docs-content/clusters/cluster-management/node-labels.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/cluster-management/taints.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
  static/assets/docs/images/clusters_cluster-management_node-labels_cluster-creation-labels.webp
  static/assets/docs/images/clusters_cluster-management_node-labels_kubeconfig-download.webp
  static/assets/docs/images/clusters_cluster-management_taints_cluster-creation-taints.webp
  static/assets/docs/images/clusters_cluster-management_taints_kubeconfig-download.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3394 Packs component eslint
  .eslintrc.js
  declarations.d.ts
  docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md
  docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
  package.json
  plugins/packs-integrations.js
  src/components/IconMapper/IconMapper.tsx
  src/components/Integrations/Packs/Packs.tsx
  src/components/PacksInformation/PacksInformation.tsx
  src/components/PacksReadme/PacksReadme.antd.css
  src/components/PacksReadme/PacksReadme.tsx
  src/components/PacksTable/PacksTable.tsx
  src/components/Technologies/AppPackList.tsx
  src/components/Technologies/CategorySelector/CustomLabel.tsx
  src/components/Technologies/CategorySelector/FilterSelect.tsx
  src/components/Technologies/CategorySelector/filterSelect.antd.css
  src/components/Technologies/PackCardIcon.tsx
  src/components/Technologies/PacksFilters.tsx
  src/components/Technologies/Technologies.test.tsx
  src/components/Technologies/Technologies.tsx
  src/components/Technologies/TechnologyCard.tsx
  src/components/Technologies/packsFilters.antd.css
  src/components/Technologies/technologies.antd.css
  src/constants/packs.ts
  src/declarations.d.ts
  src/types/index.d.ts
  static/scripts/constants.js
  tsconfig.eslint.json
Labels: enhancement, javascript, refactor

#3403 docs: update Edge tutorial user data
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3437 Update Palette CLI Binaries URLs
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.4.a

#3438 docs: DOC-1312
  docs/docs-content/clusters/public-cloud/azure/architecture.md
  docs/docs-content/release-notes/known-issues.md
Labels: 4.4.a

#3439 [version-4-3] Release Prep
  docs/docs-content/glossary-all.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
  static/assets/docs/images/cluster_profile_new.webp
  static/assets/docs/images/keycloak/user-management_saml-sso_keycloak-09-palette-oidc-enabled.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-oidcallback.webp
  static/assets/docs/images/oidc-okta-images/oidc-okta_copy-logout-url.webp
  static/assets/docs/images/palette-sso-with-adfs-images/how-to_palette-sso-with-adfs_copy-logout-url.webp
Labels: 4.3

#3441 chore: add missing azure arch commit
  docs/docs-content/clusters/public-cloud/azure/architecture.md
Labels: auto-backport, backport-version-4-4

#3443 ci: update linkinator config
  Makefile
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3450 chore: minor updates post 4-4-a release
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/signed-content.md
  docs/docs-content/clusters/public-cloud/azure/architecture.md
Labels: auto-backport, backport-version-4-4

#3040 docs: VMO refactor
  docs/docs-content/clusters/cluster-management/palette-webctl.md
  docs/docs-content/vm-management/architecture.md
  docs/docs-content/vm-management/create-manage-vm/_category_.json
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/_category_.json
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/access-cluster-with-virtctl.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/advanced-topics.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/create-disk-templates.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/create-vm-template.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/vm-oversubscription.md
  docs/docs-content/vm-management/create-manage-vm/clone-vm.md
  docs/docs-content/vm-management/create-manage-vm/create-manage-vm.md
  docs/docs-content/vm-management/create-manage-vm/deploy-vm-from-template.md
  docs/docs-content/vm-management/create-manage-vm/enable-cpu-hotplug.md
  docs/docs-content/vm-management/create-manage-vm/migrate-vm-to-different-node.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/_category_.json
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/clone-vm.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/standard-vm-operations.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/update-vm-configuration.md
  docs/docs-content/vm-management/create-manage-vm/take-snapshot-of-vm.md
  docs/docs-content/vm-management/create-manage-vm/update-vm-configuration.md
  docs/docs-content/vm-management/create-vmo-profile.md
  docs/docs-content/vm-management/environment-setup.md
  docs/docs-content/vm-management/rbac/_category_.json
  docs/docs-content/vm-management/rbac/add-roles-and-role-bindings.md
  docs/docs-content/vm-management/rbac/configure_OIDC.md
  docs/docs-content/vm-management/rbac/rbac.md
  docs/docs-content/vm-management/rbac/vm-roles-permissions.md
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/_category_.json
  docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md
  redirects.js
  static/assets/docs/images/docs_vm-mangement_vmo-diagram.webp
  static/assets/docs/images/vm-management_architecture_vmo-architecture.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_vm-yaml-editor.webp
  static/assets/docs/images/vm-mangement_vmo-diagram.webp
  styleguide/spectro-cloud-style-guide.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3458 chore: DOC-1316
  docusaurus.config.js
  plugins/packs-integrations.js
  static/packs-data/exclude_packs.json
Labels: enhancement

#3459 feat: document how to add group attributes
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  static/assets/docs/images/keycloak/user-management_oidc-sso-keycloak-19-keycloak-client-scopes.webp
  static/assets/docs/images/keycloak/user-management_oidc-sso-keycloak-20-keycloak-mapper.webp
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3469 docs: fix typo
  docs/docs-content/clusters/edge/edge-native-lifecycle.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3464 docs: DOC-1310
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3462 docs: remove vertex backup issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3481 docs: PEM-5475
  docs/docs-content/integrations/verified_packs.md
  docs/docs-content/vertex/fips/fips-status-icons.md
  static/assets/docs/images/integrations_verified-packs_add-pack.webp
Labels: 4.4.b

#3483 docs: DOC-1325
  _partials/self-hosted/_required-domains.mdx
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/enterprise-version/install-palette/install-palette.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3489 Remove Banner Msg
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-4

#3495 docs: update Tenant Project Admin operations order DOC-1327
  docs/docs-content/user-management/palette-rbac/tenant-scope-roles-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3463 docs: add AWS "Scale, Upgrade, and Secure Clusters" tutorial DOC-1306
  _partials/getting-started/_cluster_observability.mdx
  _partials/getting-started/_cluster_profile_import_aws.mdx
  docs/docs-content/getting-started/aws/aws.md
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/aws/scale-secure-cluster.md
  docs/docs-content/getting-started/azure/create-cluster-profile.md
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_add-taint.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_cluster-profile-created.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_never-scanned-cluster.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_scans-completed.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_scans-schedules.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/aws/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/getting-started_scale-secure-cluster_open-tutorial-project.webp
  static/assets/docs/images/getting-started/getting-started_scale-secure-cluster_select-team-roles.webp
  static/assets/docs/images/getting-started/getting-started_scale-secure-cluster_switch-tenant-admin-scope.webp
  static/assets/docs/images/getting-started/getting-started_scale-secure-cluster_taints-in-action.gif
Labels: do-not-merge/work-in-progress

#3482 Document Pack's Component
  README.md
Labels: documentation

#3502 docs: DOC-1326
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3509 chore: DOC-1325
  _partials/self-hosted/_required-domains.mdx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-4
