Repository spectrocloud/librarium, pull requests merged in 2024-12, with the labels that each got.

#4843 docs: Update install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4869 chore: added filter to exclude cves not ready for publication
  utils/cves/index.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4807 docs: proxy certificates for earthly builds
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/release-notes/annoucements.md
Labels: 4.5.b

#4859 docs: update cluster profile update guides PEM-6443
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
  static/assets/docs/images/clusters_cluster-management_cluster-updates_preview-profile-ver-changes.webp
  static/assets/docs/images/integrations_pack_diffs.webp
  static/assets/docs/images/profiles_cluster-profiles_modify-cluster-incoming-updates.webp
Labels: 4.5.b

#4281 docs: multi-node airgap documentation
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/delete-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/link-hosts.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/share-auth.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/initial-setup.md
  static/assets/docs/images/clusters_edge_localui_cluster-mgmt_link-hosts.webp
Labels: 4.5.b

#4878 chore: update filters
  src/components/CveReportsTable/CveReportsTable.tsx
  utils/cves/index.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4888 docs: include one infra layer requirement
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4897 docs: security pagination support
  utils/cves/index.js
Labels: enhancement, backport-version-4-0, auto-backport, backport-version-3-4, javascript, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4912 docs: adjust broken links on GS Introduction page
  docs/docs-content/getting-started/introduction.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4879 docs: PE-5671: `systemd-timesyncd` local host prerequisite for Local UI agent mode servers with NTP configs
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#4936 Fix CVE URL logic
  src/components/CveReportsTable/CveReportsTable.tsx
  utils/cves/index.js
  utils/helpers/urls.js
  utils/helpers/urls.test.ts
Labels: bug, enhancement, backport-version-4-0, auto-backport, backport-version-3-4, javascript, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4921 Self-Hosted Cloud Credentials
  _partials/self-hosted/_cloud-provider-config.mdx
  docs/docs-content/enterprise-version/system-management/change-cloud-config.md
  docs/docs-content/vertex/system-management/change-cloud-config.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4963 docs: updated payload
  _partials/self-hosted/_cloud-provider-config.mdx
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4972 docs: change node to host
  docs/docs-content/clusters/edge/local-ui/cluster-management/delete-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/link-hosts.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
Labels: 4.5.b

#4973 ci: fix GitHub action issue
  .github/workflows/packs-data.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4982 Update CLI flag cmd in tooltip
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#4985 docs: add ip tables as a prerequisite
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/deployment-modes/controller-mode.md
Labels: auto-backport, backport-version-4-5

#4967 docs: DOC-1500: "Too many open files" Troubleshooting
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/enterprise-version/upgrade/upgrade-notes.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/enterprise-install.md
  docs/docs-content/vertex/upgrade/upgrade-notes.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4986 docs: minor touch-up
  _partials/self-hosted/_cloud-provider-config.mdx
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4998 Edge API Update
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.5.b

#5003 docs: DOC-1505
  docs/docs-content/integrations/harbor-edge-native-config.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5002 docs: update OSS license pages DOC-1512
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: 4.5.b

#5011 docs: exclude deprecated files from broken url check DOC-1503
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5019 docs: replace cve-reports as skipped path DOC-1503
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4987 docs: Self hosted updates
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5034 docs: node drain edit
  docs/docs-content/clusters/edge/cluster-management/skip-draining.md
Labels: 4.5.b

#5035 PCP-1889: add disableLocalAccounts method and correct order of steps
  docs/docs-content/clusters/public-cloud/azure/aks.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4971 docs: change simple cards to use versioned link DOC-1502
  README.md
  docs/docs-content/getting-started/additional-capabilities/additional-capabilities.md
  docs/docs-content/getting-started/aws/aws.md
  docs/docs-content/getting-started/azure/azure.md
  docs/docs-content/getting-started/gcp/gcp.md
  docs/docs-content/getting-started/getting-started.md
  docs/docs-content/getting-started/introduction.md
  docs/docs-content/getting-started/vmware/vmware.md
  docs/docs-content/tutorials/tutorials.md
  scripts/find-unused-images.sh
  src/components/SimpleCardGrid/SimpleCardGrid.test.tsx
  src/components/SimpleCardGrid/SimpleCardGrid.tsx
  src/components/VersionedLink/VersionedLink.test.tsx
  src/components/VersionedLink/VersionedLink.tsx
  static/assets/docs/images/hide_copy_button.webp
  static/assets/docs/images/hide_copy_button_example.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5033 docs: DOC-1517 updated oop diagram
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vm-management/install-vmo-in-airgap.md
  static/assets/docs/images/vertex_airgap_vmware-vsphere-airgap-instructions_order-operations.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5055 Security Bulletin Fix
  utils/cves/index.js
  utils/helpers/affected-table.js
  utils/helpers/affected-table.test.js
  utils/helpers/cveHelpers.js
  utils/helpers/cveHelpers.test.js
Labels: bug, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5056 docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  _partials/self-hosted/_setup-steps.mdx
  docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/env-setup-vm.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/enterprise-version/install-palette/install-palette.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/env-setup-vm-vertex.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
Labels: auto-backport, backport-version-4-5

#5070 docs: add known issue PE-5748
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5074 docs: fix airgap spelling in known issues
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5076 docs: remove duplicate entry
  docs/docs-content/release-notes/annoucements.md
Labels: auto-backport, backport-version-4-5

#5079 docs: added missing k8s version for 4.5.15
  _partials/self-hosted/_kubernetes_palette_versions.mdx
Labels: auto-backport, backport-version-4-5

#5081 docs: add PE-5567 to release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5083 docs: slack notification for release to production (gh-action)
  .github/workflows/release.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5111 chore: upgrade docusaurus-theme-openapi-docs plugin
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests, backport-version-4-4, backport-version-4-5

#5103 docs: DOC-1529: Add PCP-3592 to release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5101 docs: enable AWS STS
  _partials/self-hosted/_aws-sts-config.mdx
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
  docs/docs-content/clusters/public-cloud/aws/add-aws-accounts.md
  docs/docs-content/enterprise-version/system-management/configure-aws-sts-account.md
  docs/docs-content/vertex/system-management/configure-aws-sts-account.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5064 docs: Workspace refactor
  docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md
  docs/docs-content/vm-management/rbac/vm-roles-permissions.md
  docs/docs-content/workspace/adding-a-new-workspace.md
  docs/docs-content/workspace/workload-features.md
  docs/docs-content/workspace/workspace-mgmt/backup-restore.md
  docs/docs-content/workspace/workspace-mgmt/configure-rbac.md
  docs/docs-content/workspace/workspace-mgmt/delete-workspace.md
  docs/docs-content/workspace/workspace-mgmt/resource-mgmt.md
  docs/docs-content/workspace/workspace-mgmt/restrict-images.md
  docs/docs-content/workspace/workspace-mgmt/workspace-mgmt.md
  docs/docs-content/workspace/workspace.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5135 docs: aws sts creds
  _partials/self-hosted/_aws-sts-config.mdx
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5121 docs: DOC-1531: 10 GB PVC Requirement for Palette & VerteX with External DBs
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5155 docs: fix up broken links DOC-1532
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5163 chore: DOC-1534 update deprecated packs documentation and enhance Pac…
  docs/docs-content/integrations/deprecated-packs.md
  src/components/PacksTable/PackTable.test.tsx
  src/components/PacksTable/PacksTable.module.scss
  src/components/PacksTable/PacksTable.tsx
  src/components/PacksTable/__mocks__/@docusaurus/theme-common.ts
  src/components/PacksTable/__mocks__/@theme/Admonition.tsx
  utils/helpers/affected-table.test.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5009 chore: DOC-1516 change to text/plain
  docusaurus.config.js
  static/scripts/fullstory.js
Labels: bug, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5178 docs: DOC-1548
  docs/docs-content/getting-started/aws/aws.md
  docs/docs-content/getting-started/azure/azure.md
  docs/docs-content/getting-started/gcp/gcp.md
  docs/docs-content/getting-started/vmware/vmware.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5186 docs: fix broken link
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5
