Repository spectrocloud/librarium, pull requests merged in 2024-05, with the labels that each got.

#2737 chore: fix css spacing issue and correct edge forge indentation
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  src/css/custom.scss
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests

#2749 docs: fixed broken URLs
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
  docs/docs-content/integrations/portworx_operator.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2729 Update profile variables docs
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_add-vars-to-yaml.webp
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_variable-preview.webp
Labels: 4.4

#2743 chore: nodejs upgrade
  .github/workflows/dependabot.yaml
  .github/workflows/eslint-test.yaml
  .github/workflows/nightly-docker-build.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/visual-comparison.yaml
  Dockerfile
  package.json
Labels: dependencies, CI/CD, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests

#2688 Known Issues Global Page
  docs/docs-content/release-notes/_category_.json
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/palette-upgrade.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#2778 Fix broken links found in productiong
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/integrations/portworx_operator.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2784 docs: fix userdata indentation
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#2713 docs: document Crossplane PAD-82
  docs/docs-content/automation/_category_.json
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/crossplane/_category_.json
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/automation/palette-cli/_category_.json
  docs/docs-content/automation/palette-cli/commands/_category_.json
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/docs.md
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/fips-validate.md
  docs/docs-content/automation/palette-cli/commands/login.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/commands/pde.md
  docs/docs-content/automation/palette-cli/commands/project.md
  docs/docs-content/automation/palette-cli/commands/validator.md
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/automation/terraform/_category_.json
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
  docs/docs-content/devx/devx.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/_category_.json
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/terraform.md
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2789 [version-4-2] backport document Crossplane PR 2713
  docs/docs-content/automation/_category_.json
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/crossplane/_category_.json
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/automation/palette-cli/_category_.json
  docs/docs-content/automation/palette-cli/commands/_category_.json
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/docs.md
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/login.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/commands/pde.md
  docs/docs-content/automation/palette-cli/commands/project.md
  docs/docs-content/automation/palette-cli/commands/validator.md
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/automation/terraform/_category_.json
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
  docs/docs-content/devx/devx.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/_category_.json
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/terraform.md
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.2

#2790 [version-4-1] backport document Crossplane PR 2713
  docs/docs-content/automation/_category_.json
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/crossplane/_category_.json
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/automation/palette-cli/_category_.json
  docs/docs-content/automation/palette-cli/commands/_category_.json
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/docs.md
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/login.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/commands/pde.md
  docs/docs-content/automation/palette-cli/commands/project.md
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/automation/terraform/_category_.json
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/devx/devx.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/_category_.json
  docs/docs-content/spectro-downloads.md
  docs/docs-content/terraform.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.1

#2791 [version-4-0] backport document Crossplane PR 2713
  docs/docs-content/automation/_category_.json
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/crossplane/_category_.json
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/automation/palette-cli/commands.md
  docs/docs-content/automation/palette-cli/commands/_category_.json
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/automation/terraform/_category_.json
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/devx/devx.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/_category_.json
  docs/docs-content/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/terraform.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.0

#2793 [version-3-4] backport document Crossplane PR 2713
  docs/docs-content/automation/_category_.json
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/crossplane/_category_.json
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/automation/palette-cli/_category_.json
  docs/docs-content/automation/palette-cli/commands.md
  docs/docs-content/automation/palette-cli/commands/_category_.json
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/automation/terraform/_category_.json
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/devx/devx.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/palette-cli/_category_.json
  docs/docs-content/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/terraform.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 3.4

#2703 docs: add edge CLI command updates
  docs/docs-content/clusters/edge/edgeforge-workflow/build-content-bundle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-artifacts.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
Labels: auto-backport, backport-version-4-3

#2800 docs: DOC-1177
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-custom-registries.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
Labels: auto-backport, backport-version-4-3

#2804 docs: add new hardware requirements backport
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/clusters/edge/hardware-requirements.md
Labels: auto-backport, backport-version-4-3

#2795 docs: update postman link 4.3
  docs/api-content/api-docs/3-postman-collection.md
Labels: auto-backport, backport-version-4-3

#2810 chore: Fix a broken link
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
Labels: auto-backport, backport-version-4-3

#2786 docs: add kubernetes version downgrade warning and hello-universe pack version DOC-1165 DOC-1174
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/integrations/hello-universe.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes-support.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/microk8s.md
  docs/docs-content/integrations/rke2.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2809 Update hardware-requirements.md
  docs/docs-content/clusters/edge/hardware-requirements.md
Labels: auto-backport, backport-version-4-3

#2682 Deprecated Packs Clarification
  docs/docs-content/integrations/maintenance-policy.md
  static/packs-data/packs_report.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2728 Rhel pxk fips
  docs/docs-content/byoos/image-builder.md
  docs/docs-content/byoos/usecases/vmware/rhel-pxk.md
  docs/docs-content/byoos/usecases/vmware/vmware.md
  docs/docs-content/integrations/byoos.md
  docs/docs-content/integrations/kubernetes.md
  static/assets/docs/images/byoos_vmware_rhewl-pxk_cluster-profile-non-fips.webp
  static/assets/docs/images/byoos_vmware_rhewl-pxk_cluster-profile.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2830 chore: fix tf code
  docs/docs-content/integrations/byoos.md
Labels: auto-backport, backport-version-4-3

#2773 docs: DOC-1166 image update
  docs/docs-content/architecture/networking-ports.md
  docs/docs-content/architecture/orchestration-spectrocloud.md
  static/assets/docs/images/architecture_orchestartion-spectrocloud_provision-flow.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2837 docs: update crossplane provider version
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2846 Airgap Support VM custom SSL Certs
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
Labels: auto-backport, backport-version-4-3

#2802 Cluster profile resource usage computation
  docs/docs-content/tenant-settings/add-registry.md
  docs/docs-content/tenant-settings/api-key-management.md
  docs/docs-content/tenant-settings/login-banner.md
  docs/docs-content/tenant-settings/palette-resource-limits.md
  docs/docs-content/tenant-settings/tenant-settings.md
  docs/docs-content/user-management/palette-resource-limits.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2845 docs: rename local mgmt api
  docs/api-content/api-docs/1-introduction.md
Labels: auto-backport, backport-version-4-3

#2875 chore: update validator URL
  docs/docs-content/automation/palette-cli/commands/validator.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#2878 docs: DOC-1188
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-3

#2880 chore: fix path release date
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-3

#2854 docs: make minor fixes to local ui docs
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
Labels: auto-backport, backport-version-4-3

#2884 docs: change fix build branch
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
Labels: auto-backport, backport-version-4-3

#2867 VerteX and RHEL
  .github/workflows/clean-up-report.yaml
  .github/workflows/release-branch-pr.yaml
  .gitignore
  README.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
  scripts/netlify.sh
  scripts/netlify_add_branch.sh
  scripts/netlify_remove_branch.sh
  static/assets/videos/vertex-install.mp4
  static/tape/vertex-install.tape
Labels: 4.4

#2888 ci: updated logic to enable Netlify previews for release branch PRs
  .github/workflows/clean-up-report.yaml
  .github/workflows/release-branch-pr.yaml
  scripts/netlify.sh
  scripts/netlify_add_branch.sh
  scripts/netlify_remove_branch.sh
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2896 docs: Update authorization-token.md
  README.md
  docs/docs-content/user-management/authentication/authorization-token.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2889 Known issue csi
  docs/docs-content/release-notes/known-issues.md
  scripts/netlify.sh
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#2887 docs: add PartialsComponent to handle Docusaurus Markdown Imports in librarium DOC-1189
  .gitignore
  Makefile
  README.md
  _partials/_partial_example.mdx
  docs/docs-content/getting-started/getting-started.md
  docusaurus.config.js
  package.json
  scripts/generate-partials.sh
  src/components/PartialsComponent/PartialsComponent.test.tsx
  src/components/PartialsComponent/PartialsComponent.tsx
  src/components/PartialsComponent/PartialsImporter.tsx
  src/components/PartialsComponent/index.ts
  src/components/VersionedLink/CheckVersion.tsx
  src/components/VersionedLink/VersionedLink.test.tsx
  src/components/VersionedLink/VersionedLink.tsx
  src/components/VersionedLink/index.ts
  src/theme/MDXComponents/MDXComponents.ts
  tsconfig.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2892 Airgap VMware upgrade: Add missing steps
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2886 docs: add missing fips cmd to user data
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
Labels: auto-backport, backport-version-4-3

#2911 Day-2 operations for profile variables
  _partials/index.ts
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
Labels: auto-backport, backport-version-4-3

#2776 docs: PEM-4569
  _partials/index.ts
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/clusters/public-cloud/tke.md
  docs/docs-content/integrations/kubebench.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/pack-constraints.md
Labels: 4.4

#2923 Update the self-hosted and VerteX upgrade matrices
  _partials/index.ts
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.4

#2922 Clarity on which system administrator role can register Nutanix cloud
  docs/docs-content/clusters/data-center/nutanix/register-nutanix-cloud.md
Labels: auto-backport, backport-version-4-3

#2928 Fix the markup and layout of pages in the VMO section
  docs/docs-content/clusters/cluster-management/palette-webctl.md
  docs/docs-content/integrations/kubevirt.md
  docs/docs-content/vm-management/create-manage-vm/access-cluster-with-virtctl.md
  docs/docs-content/vm-management/create-manage-vm/create-disk-templates.md
  docs/docs-content/vm-management/create-manage-vm/create-manage-vm.md
  docs/docs-content/vm-management/create-manage-vm/create-vm-template.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/clone-vm.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/deploy-vm-from-template.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/standard-vm-operations.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/take-snapshot-of-vm.md
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/update-vm-configuration.md
  docs/docs-content/vm-management/create-manage-vm/vm-oversubscription.md
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/add-roles-and-role-bindings.md
  docs/docs-content/vm-management/vm-packs-profiles/configure_OIDC.md
  docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
  docs/docs-content/vm-management/vm-roles-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2927 docs: add introduction to govcloud terraform support
  docs/docs-content/automation/terraform/terraform.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#2883 docs: cert renewal airgap
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
  docs/docs-content/clusters/edge/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/cluster-management/upgrade-behavior.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.4

#2925 docs: replace palette control plane with management plane in pcg diag…
  docs/docs-content/clusters/pcg/architecture.md
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  static/assets/docs/images/clusters_pcg_architecture_overview_diagram.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-diagram.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2936 docs: DOC-1190 update self-hosted instructions for login
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: auto-backport, backport-version-4-3

#2945 Document the KubeVirt CPU hotplug feature
  docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/enable-cpu-hotplug.md
  static/assets/docs/images/vm-management_create-manage-vm_standard-vm-operations_enable-cpu-hotplug_vm-yaml-editor.webp
Labels: 4.4

#2917 docs: local ui diagnostic tools
  _partials/index.ts
  docs/docs-content/clusters/edge/local-ui/host-management/diagnostic-tools.md
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.4

#2910 docs: add community packs page DOC-1187
  docs/docs-content/integrations/community_packs.md
  docs/docs-content/integrations/deprecated-packs.md
  docs/docs-content/integrations/verified_packs.md
  static/assets/docs/images/integrations_community-packs_add-community-pack.webp
  static/assets/docs/images/integrations_verified-packs_add-pack.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3
