Repository spectrocloud/librarium, pull requests merged in 2024-04, with the labels that each got.

#2535 Update installer-reference.md
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2557 xz-utils security advisory
  docs/docs-content/security-bulletins/cve-reports.md
Labels: auto-backport, backport-version-4-1, backport-version-4-2

#2568 ci: fix branch determination logic
  .github/workflows/visual-comparison.yaml
  tsconfig.eslint.json
  visuals/screenshot.api.spec.ts
  visuals/screenshot.docs.spec.ts
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, visual-tests

#2577 Revert "chore: bump semantic-release from 20.1.3 to 23.0.6"
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2589 docs: upgrade to docusaurus 3.2.1 DOC-1134
  package-lock.json
  package.json
  plugins/font-awesome.js
  plugins/packs-integrations.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, visual-tests

#2594 Fix Production Build Issue
  Makefile
  scripts/versions.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2582 docs: DOC-1133
  docs/docs-content/release-notes.md
  docs/docs-content/troubleshooting/palette-upgrade.md
  package-lock.json
  static/assets/docs/images/byoos_vmware_konvoy_cluster-profile-view.webp
  static/assets/docs/images/byoos_vmware_konvoy_iso-selection.webp
  static/assets/docs/images/cluster_edge_emc_theming.webp
  static/assets/docs/images/cluster_edge_site-deployment_installation_initial-setup_tui.webp
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_add-vars-to-yaml.webp
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_open-profile-variables.webp
  static/assets/docs/images/troubleshootig_palette-upgrade_nodes-healthy.webp
  static/assets/docs/images/vertex_account-management_manage-system-accounts_user-dashboard.webp
Labels: 4.3

#2602 Implement a Vale rule for the Oxford comma
  vale/styles/spectrocloud/oxford-comma.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2540 VMware Refactor
  docs/deprecated/clusters/data-center/vmware.md
  docs/docs-content/clusters/data-center/data-center.md
  docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
  docs/docs-content/clusters/data-center/vmware/_category_.json
  docs/docs-content/clusters/data-center/vmware/architecture.md
  docs/docs-content/clusters/data-center/vmware/create-manage-vmware-clusters.md
  docs/docs-content/clusters/data-center/vmware/permissions.md
  docs/docs-content/clusters/data-center/vmware/vmware.md
  docs/docs-content/clusters/pcg/manage-pcg/add-dns-mapping.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/integrations/cloudanix.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
  static/assets/docs/images/clusters_vmware_architecture_arch-overview.webp
  static/assets/docs/images/vmware_arch_oct_2020.webp
Labels: documentation, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2611 chore: add security section
  docs/docs-content/release-notes.md
Labels: 4.3

#2601 docs: add rook-ceph known issue
  docs/docs-content/integrations/rook-ceph.md
  docs/docs-content/release-notes.md
Labels: 4.3

#2614 docs: add Arm64 known issue
  docs/docs-content/release-notes.md
Labels: 4.3

#2617 docs: clarify arm64 support (#2616)
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/clusters/edge/edge.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2613 docs: updates to release notes
  docs/docs-content/clusters/cluster-management/compliance-scan.md
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/rke2.md
  docs/docs-content/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
Labels: 4.3

#2621 chore: add API values to algolia
  .github/workflows/aloglia_crawler.yaml
  Makefile
  docs/api-content/api-docs/2-samples.mdx
  docs/docs-content/registries-and-packs/deploy-pack.md
  docsearch.config.json
  scripts/url-checker.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2615 4.3 security advisories
  docs/docs-content/security-bulletins/cve-reports.md
Labels: 4.3

#2626 chore: updated alogilia behavior
  docsearch.config.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2631 chore: fix broken URLs
  Makefile
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
  docs/docs-content/devx/services/service-listings/mysql.md
  docs/docs-content/devx/services/service-listings/vault.md
  docs/docs-content/integrations/citrix-ipam.md
  docs/docs-content/integrations/cloudanix.md
  docs/docs-content/integrations/falco.md
  docs/docs-content/integrations/longhorn.md
  docs/docs-content/integrations/nutanix-csi.md
  docs/docs-content/integrations/portworx.md
  docs/docs-content/integrations/portworx_operator.md
  docs/docs-content/integrations/prometheus-operator.md
  docs/docs-content/integrations/vault.md
  docs/docs-content/vertex/system-management/enable-non-fips-settings/use-non-fips-addon-packs.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2639 docs: Update release-notes.md
  docs/docs-content/release-notes.md
Labels: auto-backport, backport-version-4-3

#2638 ci: fix URL logic
  .github/workflows/aloglia_crawler.yaml
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/devx/services/service-listings/vault.md
  docsearch.config.json
  scripts/url-checker.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2541 docs: add guide for uploading packs to oci registries
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci-basic.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci-ecr.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci.md
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/spectrocloud/longform.yml
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2303 Self-hosted Palette upgrade guides
  docs/docs-content/clusters/pcg/manage-pcg/pcg-upgrade.md
  docs/docs-content/enterprise-version/enterprise-version.md
  docs/docs-content/enterprise-version/upgrade/_category_.json
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/_category_.json
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-notes.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/_category_.json
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/troubleshooting/palette-upgrade.md
  docs/docs-content/vertex/system-management/system-management.md
  docs/docs-content/vertex/upgrade/_category_.json
  docs/docs-content/vertex/upgrade/upgrade-k8s/_category_.json
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/non-airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/_category_.json
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/vertex/upgrade/upgrade.md
  docs/docs-content/vertex/vertex.md
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_diff-checker.webp
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_non-airgap_copy_configurations.webp
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_non-airgap_update.webp
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_non-airgap_upgrade-preview.webp
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_non-airgap_upgraded.webp
  static/assets/docs/images/enterprise-version_upgrade-upgrade_vmware_palette-upgrade-preview.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2648 [version-4-2] docs: add guide for uploading packs to oci registries PR 2541
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci-basic.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci-ecr.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-pack-oci/add-pack-oci.md
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/spectrocloud/longform.yml
Labels: 4.2

#2651 [version-4-1] docs: add guide for uploading packs to oci registries PR 2541
  docs/docs-content/clusters/edge/site-deployment/model-profile.md
  docs/docs-content/devx/manage-dev-engine/registries.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/oci-registry/_category_.json
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci-basic.md
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci-ecr.md
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci.md
  docs/docs-content/registries-and-packs/oci-registry/oci-registry.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/spectrocloud/longform.yml
Labels: 4.1

#2653 [version-4-0] docs: add guide for uploading packs to oci registries PR 2541
  docs/docs-content/clusters/edge/site-deployment/model-profile.md
  docs/docs-content/devx/manage-dev-engine/registries.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/oci-registry/_category_.json
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci-basic.md
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci-ecr.md
  docs/docs-content/registries-and-packs/oci-registry/add-pack-oci/add-pack-oci.md
  docs/docs-content/registries-and-packs/oci-registry/oci-registry.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/spectrocloud/longform.yml
Labels: 4.0

#2657 docs: remove spectro-packs project requirement
  docs/docs-content/registries-and-packs/deploy-pack.md
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2662 Remove unnecessary prerequisite from VMware airgap guide
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2656 chore: DOC-1148 fix missing trailing slash
  docs/docs-content/clusters/cluster-management/backup-restore/enable-etcd-backup.md
  docs/docs-content/clusters/cluster-management/kubeconfig.md
  docs/docs-content/clusters/cluster-management/namespace-management.md
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-artifacts.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-private-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
  docs/docs-content/getting-started/terraform.md
  docs/docs-content/integrations/hello-universe.md
  docs/docs-content/integrations/k3s.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-infrastructure-profile.md
  docs/docs-content/security/product-architecture/tenant-cluster.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/user-management/palette-rbac/tenant-scope-roles-permissions.md
  docusaurus.config.js
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2353 docs: Deploy App Workloads with a PCG Tutorial - DOC-1004
  docs/docs-content/clusters/pcg/deploy-app-pcg.md
  docs/docs-content/clusters/pcg/pcg.md
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_cluster-delete.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_cluster-health.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_cluster-profile.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_cluster-provisioning.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_cluster-review.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_deploy-profile.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_hello-universe.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_metallb-pack.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-cli.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-delete.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-diagram.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-events.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_pcg-health.webp
  static/assets/docs/images/clusters_pcg_deploy-app-pcg_vmware-delete.webp
  static/assets/videos/palette-login.mp4
  static/assets/videos/palette-pcg.mp4
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2690 Update BackUp Instructions
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
  docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
Labels: backport-version-4-0, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2697 Docker fix
  .github/workflows/nightly-docker-build.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2708 ci: fix build issue
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-2, backport-version-4-3

#2716 chore: fixed an issue with missing .env
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2722 docs: update installer-reference.md
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3
