Repository spectrocloud/librarium, pull requests merged in 2024-03, with the labels that each got.

#2284 chore: add file type reference rule
  docs/docs-content/tenant-settings/api-key-management.md
  vale/styles/spectrocloud/file-type.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2335 Updated vale configuration
  .github/workflows/pull_request.yaml
  vale/styles/config/vocabularies/Internal/accept.txt
  vale/styles/config/vocabularies/Internal/reject.txt
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2319 Konvoy
  docs/docs-content/byoos/_category_ copy.json
  docs/docs-content/byoos/image-builder.md
  docs/docs-content/byoos/usecases/usecases.md
  docs/docs-content/byoos/usecases/vmware/_category_ copy.json
  docs/docs-content/byoos/usecases/vmware/konvoy.md
  docs/docs-content/byoos/usecases/vmware/vmware.md
  docs/docs-content/integrations/konvoy.md
  docs/docs-content/integrations/ngrok.md
  static/assets/docs/images/byoos_vmware_konvoy_cluster-profile-view.png
  static/assets/docs/images/byoos_vmware_konvoy_iso-selection.png
  static/packs-data/packs_report.json
Labels: 4.3

#2344 docs: removing link
  docs/docs-content/clusters/edge/edge.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2340 chore: document EMC API endpoints
  .gitignore
  apisidebar.js
  docs/api-content/api-docs/1-introduction.md
  docs/api-content/api-docs/edge-v1/emc-api.json
  docusaurus.config.js
  package.json
  utils/api-parser/index.js
Labels: 4.3

#2341 Update deploy-private-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md
Labels: auto-backport, backport-version-4-2

#2352 docs: document namespace-based image swap diabling
  docs/docs-content/clusters/edge/networking/local-registry.md
  docs/docs-content/integrations/harbor-edge.md
Labels: 4.3

#2350 docs: add warning spectro proxy not supporting airgap environments.
  docs/docs-content/integrations/frp.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2364 chore: updated vale rules
  vale.ini
  vale/styles/spectrocloud/condescending.yml
  vale/styles/spectrocloud/direction.yml
  vale/styles/spectrocloud/plural-parantheses.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2369 VerteX support for AKS
  docs/docs-content/vertex/supported-platforms.md
Labels: 4.3

#2370 Vale Rule Fix
  vale/styles/spectrocloud/condescending.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2377 Update the TechPreview component to also accept custom text
  src/css/custom.scss
  src/css/dark-mode.scss
  src/css/light-mode.scss
  src/theme/Admonition/Icon/TechPreview.js
  src/theme/Admonition/Type/TechPreview.js
Labels: auto-backport, backport-version-4-2

#2380 docs: move securty notices to a more visible spot
  docs/docs-content/introduction/introduction.md
  docs/docs-content/legal-licenses/legal-licenses.md
  docs/docs-content/security-bulletins/_category_.json
  docs/docs-content/security-bulletins/cve-index.md
  docs/docs-content/security-bulletins/cve-reports.md
  docs/docs-content/security-bulletins/security-bulletins.md
  docs/docs-content/security/security-bulletins/_category_.json
  docs/docs-content/security/security.md
  redirects.js
  src/components/IconMapper/dynamicFontAwesomeImports.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2384 FIPS Validate Command
  docs/docs-content/palette-cli/commands/commands.md
  docs/docs-content/palette-cli/commands/ec.md
  docs/docs-content/palette-cli/commands/fips-validate.md
  docs/docs-content/palette-cli/commands/pcg.md
  docs/docs-content/palette-cli/commands/pde.md
  docs/docs-content/palette-cli/commands/project.md
  docs/docs-content/palette-cli/commands/validator.md
  vale.ini
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.3

#2387 docs: add the command to bring up TUI before cluster deployment
  docs/docs-content/clusters/edge/site-deployment/initial-setup.md
Labels: 4.3

#2343 Cluster Profile Variables
  docs/docs-content/glossary-all.md
  docs/docs-content/profiles/app-profiles/clone-app-profile.md
  docs/docs-content/profiles/app-profiles/create-app-profiles/create-helm-app-profile.md
  docs/docs-content/profiles/app-profiles/create-app-profiles/create-manifest-app-profile.md
  docs/docs-content/profiles/app-profiles/modify-app-profiles/update-app-profile.md
  docs/docs-content/profiles/cluster-profiles/clone-cluster-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-helm-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-manifest-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-pack-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-full-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-infrastructure-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
  docs/docs-content/profiles/cluster-profiles/export-import-cluster-profile.md
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_add-vars-to-yaml.png
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_open-profile-variables.png
Labels: 4.3

#2388 docs: validator updates
  docs/docs-content/palette-cli/commands/validator.md
Labels: 4.3

#2392 docs: replace EMC with local ui
  apisidebar.js
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edge-management-console/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/edge-management-console/host-management/host-management.md
  docs/docs-content/clusters/edge/edge-management-console/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/edgeforge-workflow/build-content-bundle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/local-ui/_category_.json
  docs/docs-content/clusters/edge/local-ui/cluster-management/_category_.json
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/host-management/_category_.json
  docs/docs-content/clusters/edge/local-ui/host-management/access-console.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
  docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
  docs/docs-content/clusters/edge/site-deployment/initial-setup.md
  docs/docs-content/glossary-all.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
Labels: 4.3

#2399 Fix typo
  docs/docs-content/clusters/data-center/nutanix/install-pcg/deploy-kubernetes-cluster-pcg.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2391 chore: add vale rule - commands longform DOC-941
  vale/styles/spectrocloud/longform.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2406 Change EMC to local UI and fix all links
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
Labels: 4.3

#2405 Update cluster creation guides + Refactor Azure AKS
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/data-center/nutanix/create-manage-nutanix-cluster.md
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
  docs/docs-content/clusters/public-cloud/tke.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes.md
Labels: 4.3

#2398 docs: address PE-4011 and PE-3874
  docs/docs-content/clusters/edge/upgrade-behavior.md
Labels: 4.3

#2386 docs: add section for custom image registry options
  docs/docs-content/clusters/edge/edgeforge-workflow/build-content-bundle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/networking/networking.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-custom-registries.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-private-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
  docs/docs-content/clusters/edge/site-deployment/site-deployment.md
  docs/docs-content/integrations/harbor-edge.md
  docs/docs-content/release-notes.md
  redirects.js
  static/assets/docs/images/clusters_edge_emc_workflow.png
Labels: 4.3

#2412 docs: add rook ceph documentation
  docs/docs-content/integrations/rook-ceph.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2422 chore: remove PCG section in Azure
  docs/deprecated/clusters/public-cloud/azure/gateways.md
  docs/docs-content/clusters/public-cloud/azure/architecture.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2423 docs: Update the PXK and PXK-E packs docs
  .gitleaksignore
  docs/docs-content/integrations/k3s.md
  docs/docs-content/integrations/kubernetes-edge.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/rke2.md
Labels: 4.3

#2342 4.3 Release Notes
  README.md
  docs/docs-content/release-notes.md
  docusaurus.config.js
  src/components/Badges/TechnicalPreviewReleaseNote/TechnicalPreviewReleaseNote.module.scss
  src/components/Badges/TechnicalPreviewReleaseNote/TechnicalPreviewReleaseNote.test
  src/components/Badges/TechnicalPreviewReleaseNote/TechnicalPreviewReleaseNote.tsx
  src/components/Badges/TechnicalPreviewReleaseNote/index.tsx
  src/components/Badges/index.ts
  src/theme/MDXComponents/MDXComponents.ts
  static/img/tech-preview-dark.svg
  static/img/tech-preview-light.svg
  tsconfig.json
  vale/styles/config/vocabularies/Internal/accept.txt
Labels: 4.3

#2429 docs: Update kubeconfig.md
  docs/docs-content/clusters/cluster-management/kubeconfig.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2413 docs: change edge harbor hardware requirements
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edgeforge-workflow/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/integrations/harbor-edge.md
Labels: 4.3

#2428 Palette CLI Airgap auto detect
  .gitleaksignore
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.3

#2433 docs: add hello universe pack page, fix ngrok pack title
  docs/docs-content/integrations/hello-universe.md
  docs/docs-content/integrations/ngrok.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2441 chore: add vale rule to enforce colon usage
  docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
  vale/styles/spectrocloud/colon.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2442 chore: backport Colon usage 4 2
  docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
  vale/styles/spectrocloud/colon.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1

#2449 Disable Mendable model
  src/components/MendableAIWidget/MendableAIWidget.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2446 Explain what kCh is in Palette
  .github/workflows/image_optimizer.yaml
  docs/docs-content/glossary-all.md
  docs/docs-content/introduction/resource-usage-estimation.md
  static/assets/docs/images/introduction_resource-usage-estimation_diagram-kCh-calculation.webp
  static/assets/docs/images/introduction_resourse-usage-estimation_kCh-in-ui.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2438 Image Registry Config Override
  .github/workflows/image_optimizer.yaml
  docs/docs-content/clusters/pcg/manage-pcg/manage-pcg.md
  docs/docs-content/clusters/pcg/manage-pcg/registry-override.md
  docs/docs-content/enterprise-version/system-management/registry-override.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/vertex/system-management/registry-override.md
  docs/docs-content/vertex/system-management/system-management.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2466 chore: fixed incorrect image type
  docs/docs-content/integrations/hello-universe.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2452 Document the change previews for updating cluster profile versions
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  docs/docs-content/getting-started/update-k8s-cluster.md
  docs/docs-content/introduction/resource-usage-estimation.md
  static/assets/docs/images/clusters_cluster-management_cluster-updates_preview-profile-ver-changes.webp
Labels: auto-backport, backport-version-4-2

#2354 Extra capabilities
  docs/docs-content/getting-started/additional-capabilities.md
  docs/docs-content/getting-started/getting-started.md
  static/assets/docs/images/getting-started/getting-started_additional-capabilities_palette.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2472 docs: PEM-4073
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#2481 Update download URLs
  docs/docs-content/component.md
  docs/docs-content/palette-cli/install-palette-cli.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/spectro-downloads.md
Labels: 4.3

#2485 Doc 1120 - Update Open Source Licenses List
  docs/docs-content/legal-licenses/oss-licenses.md
Labels: 4.3

#2482 docs: add update cluster section
  docs/docs-content/clusters/data-center/nutanix/create-manage-nutanix-cluster.md
Labels: 4.3

#2486 docs: DOC-1127
  docs/docs-content/release-notes.md
  docs/docs-content/troubleshooting/pcg.md
Labels: 4.3

#2487 docs: add Getting Started callout to landing page DOC-1124
  docs/docs-content/introduction/introduction.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2492 Minor fixes 3 28
  docs/deprecated/integrations/splunk.md
  docs/docs-content/clusters/data-center/nutanix/register-nutanix-cloud.md
  docs/docs-content/devx/services/service-listings/cockroach-db.md
  docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/deploy-pack.md
  docs/docs-content/registries-and-packs/registries-and-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
Labels: auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2483 Tip for past release notes
  docs/docs-content/release-notes.md
  package-lock.json
  package.json
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.module.scss
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.test.tsx
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
  src/components/ReleaseNotesVersions/index.ts
  src/css/dark-mode.scss
  src/css/light-mode.scss
  src/theme/MDXComponents/MDXComponents.ts
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2514 chore: fixed react hook logic
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2519 Projects Refactor
  docs/deprecated/projects.md
  docs/docs-content/clusters/cluster-groups/cluster-groups.md
  docs/docs-content/clusters/cluster-management/ssh-keys.md
  docs/docs-content/getting-started/dashboard.md
  docs/docs-content/kubernetes-knowlege-hub/how-to/how-to-retrieve-images-from-private-registry.md
  docs/docs-content/kubernetes-knowlege-hub/how-to/how-to.md
  docs/docs-content/kubernetes-knowlege-hub/kubernetes-knowlege-hub.md
  docs/docs-content/kubernetes-knowlege-hub/tutorials/deploy-stateless-frontend-app.md
  docs/docs-content/kubernetes-knowlege-hub/tutorials/tutorials.md
  docs/docs-content/tenant-settings/projects/_category_.json
  docs/docs-content/tenant-settings/projects/create-manage-projects.md
  docs/docs-content/tenant-settings/projects/projects.md
  docs/docs-content/tenant-settings/tenant-settings.md
  docs/docs-content/user-management/project-association.md
  redirects.js
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
  static/assets/docs/images/tenant_settings-projects-dashboard.webp
  static/assets/docs/images/tenant_settings-projects-projects-project_id.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2520 fix: casing in siteNetwork.httpsProxy
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2

#2497 docs: add note to change Longhorn images to reference harbor
  docs/docs-content/integrations/longhorn.md
Labels: 4.3

#2529 chore: fixed logic
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2
