Repository spectrocloud/librarium, pull requests merged in 2024-11, with the labels that each got.

#4567 Docs Feedback
  docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
  docs/docs-content/workspace/adding-a-new-workspace.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4566 docs: update arg table
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#4584 docs: DOC-1457
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/palette-dev-engine.md
Labels: auto-backport, backport-version-4-5

#4558 docs: Azure Disk Encryption (PCP-3720 & PCP-3735)
  docs/docs-content/clusters/public-cloud/azure/azure-disk-encryption.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
Labels: 4.5.a

#4613 docs: fixes YAML issue
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4543 docs: add instructions for proxy
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#4583 Announcement Page
  docs/docs-content/release-notes/annoucements.md
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#4611 docs: document new filters UI PEM-6202
  docs/docs-content/clusters/cluster-management/cluster-management.md
  docs/docs-content/clusters/cluster-management/cluster-map-filters.md
  docs/docs-content/clusters/cluster-management/noc-ui.md
  redirects.js
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-all-filters.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-details.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-list-view.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-map-view.webp
Labels: 4.5.a

#4641 docs: virtual clusters on edge cluster groups known issue DOC-1473
  docs/docs-content/release-notes/known-issues.md
Labels: 4.5.a

#4631 docs: PE-5063
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/integrations/harbor-edge-native-config.md
Labels: 4.5.a

#4640 docs: PLT-1467 image pull secret
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: 4.5.a

#4489 DOC-1453
  docs/docs-content/audit-logs/monitor-with-datadog.md
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/release-notes/annoucements.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/cluster-deployment.md
Labels: 4.5.a

#4649 PAD-418 VDDK image for VMO migration
  .gitleaksignore
  docs/docs-content/automation/palette-cli/commands/vmo.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
Labels: 4.5.a

#4669 docs: add limitation on version skipping during upgrades
  docs/docs-content/clusters/cluster-management/cluster-updates.md
Labels: backport-version-4-0, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4678 docs: fix broken crossplane URL
  docs/docs-content/automation/automation.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4686 docs: added new known issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#4690 docs: update upgrade paths
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: auto-backport, backport-version-4-5

#4687 docs: add instructions for agent upgrade
  docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md
Labels: auto-backport, backport-version-4-5

#4694 added a new one and revised others
  docs/docs-content/security-bulletins/reports/cve-2016-1585.md
  docs/docs-content/security-bulletins/reports/cve-2018-20225.md
  docs/docs-content/security-bulletins/reports/cve-2023-47108.md
  docs/docs-content/security-bulletins/reports/cve-2024-10963.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-5

#4693 docs: docusaurus v3.6.1
  docs/docs-content/troubleshooting/troubleshooting.md
  docusaurus.config.js
  netlify.toml
  package-lock.json
  package.json
  src/css/custom.scss
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests, backport-version-4-4, backport-version-4-5

#4689 PCG Migrate
  docs/docs-content/clusters/pcg/architecture.md
  docs/docs-content/clusters/pcg/manage-pcg/migrate_pcg.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4696 docs: release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#4713 docs: add note about vddk secret namespace
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
Labels: auto-backport, backport-version-4-5

#4698 docs: add qualifier for hardware requirements
  docs/docs-content/clusters/edge/hardware-requirements.md
  docs/docs-content/deployment-modes/agent-mode/architecture.md
Labels: auto-backport, backport-version-4-5

#4719 Remove Ansible Roles in Pack Documentation
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/adding-add-on-packs.md
  docs/docs-content/registries-and-packs/registries-and-packs.md
  docs/docs-content/tutorials/profiles/deploy-pack.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4720 chore: add ngrok
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4738 docs: remove vercel link
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4717 docs: add known issue Pe 5556
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4734 docs: add release notes for release 4.5.11 DOC-1486
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#4758 docs: fix name of AWS IAM policy
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4767 docs: add clarification message
  docs/docs-content/release-notes/annoucements.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#4766 docs: update k8s version config for EdgeForge
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#4736 docs: add helm uninstall instructions
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/uninstall.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/uninstall.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4792 Self-Hosted Updates
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4799 Upgrade Docusaurus 3.6.3
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests, backport-version-4-4, backport-version-4-5

#4737 docs: VM Migration Assistant
  docs/docs-content/automation/palette-cli/commands/vmo.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/advanced-topics.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
  docs/docs-content/vm-management/create-manage-vm/migrate-vm-to-different-node.md
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-migration-assistant/_category_.json
  docs/docs-content/vm-management/vm-migration-assistant/additional-configuration.md
  docs/docs-content/vm-management/vm-migration-assistant/cancel-active-migration-plans.md
  docs/docs-content/vm-management/vm-migration-assistant/create-migration-plans.md
  docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
  docs/docs-content/vm-management/vm-migration-assistant/start-migration-plans.md
  docs/docs-content/vm-management/vm-migration-assistant/vm-migration-assistant.md
  package-lock.json
  package.json
  static/assets/docs/images/vm-management_vm-migration-assistant_additional-configuration_overview-metrics.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_additional-configuration_overview-settings.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_additional-configuration_plans-table.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_additional-configuration_providers-table.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_pipeline-details-cold.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_pipeline-details-warm.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_pipeline-status-cold.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_pipeline-status-warm.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_plan-ready.webp
  static/assets/docs/images/vm-management_vm-migration-assistant_migrate-vms-vmo-cluster_provider-ready.webp
  static/packs-data/packs_information.json
Labels: 4.5.b

#4810 docs: Update VM Migration Assistant pack parameters table
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
Labels: 4.5.b

#4809 docs: address getting started feedback
  _partials/_create-tenant-api-key.mdx
  docs/docs-content/getting-started/aws/aws.md
  docs/docs-content/getting-started/aws/create-cluster-profile.md
  docs/docs-content/getting-started/aws/deploy-k8s-cluster.md
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/aws/scale-secure-cluster.md
  docs/docs-content/getting-started/aws/update-k8s-cluster.md
  docs/docs-content/getting-started/azure/azure.md
  docs/docs-content/getting-started/azure/create-cluster-profile.md
  docs/docs-content/getting-started/azure/deploy-k8s-cluster.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/scale-secure-cluster.md
  docs/docs-content/getting-started/azure/update-k8s-cluster.md
  docs/docs-content/getting-started/gcp/create-cluster-profile.md
  docs/docs-content/getting-started/gcp/deploy-k8s-cluster.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/gcp.md
  docs/docs-content/getting-started/gcp/scale-secure-cluster.md
  docs/docs-content/getting-started/gcp/update-k8s-cluster.md
  docs/docs-content/getting-started/getting-started.md
  docs/docs-content/getting-started/introduction.md
  docs/docs-content/getting-started/vmware/create-cluster-profile.md
  docs/docs-content/getting-started/vmware/deploy-k8s-cluster.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  docs/docs-content/getting-started/vmware/vmware.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4818 docs: add message brokers section PEM-6141
  docs/docs-content/architecture/architecture-overview.md
Labels: 4.5.b

#4819 Updated hello-universe yaml in tutorial
  docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4827 docs: add feature gate to the vm clone guide DOC-1491
  docs/docs-content/vm-management/create-manage-vm/clone-vm.md
Labels: 4.5.b
