Repository spectrocloud/librarium, pull requests merged in 2024-08, with the labels that each got.

#3514 4.4.12 Release Notes
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3515 Remove Validator Palette CLI Command
  docs/deprecated/automation/palette-cli/commands/validator.md
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
  docs/docs-content/release-notes/release-notes.md
  redirects.js
Labels: 4.4.b

#3471 docs: document application proxy
  docs/docs-content/clusters/cluster-management/cluster-proxy.md
Labels: auto-backport, backport-version-4-4

#3537 docs: document VMO known issue and troubleshooting steps
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/troubleshooting.md
  docs/docs-content/troubleshooting/vmo-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3546 [version-4-2] docs: document VMO known issue and troubleshooting steps (#3537)
  .gitleaksignore
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/troubleshooting.md
  docs/docs-content/troubleshooting/vmo-issues.md
Labels: 4.2

#3549 docs: fix broken link and slow down linkinator job DOC-1329
  Makefile
  docs/deprecated/integrations/prometheus-operator.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3551 Update signed-content.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/signed-content.md
Labels: auto-backport, backport-version-4-4

#3568 docs: update prereq to initramfs
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3572 chore: Fix broken links
  docs/deprecated/clusters/edge/edgeforge-workflow/build-images.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3564 docs: Audit logs
  docs/docs-content/clusters/edge/local-ui/host-management/audit-logs.md
  docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
Labels: 4.4.b

#3583 docs: add airgap VMO profile creation PEM-5497
  docs/docs-content/vm-management/create-vmo-profile.md
Labels: do-not-merge/work-in-progress

#3562 docs: update edge api
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.4.b

#3588 Kubevirt resource not getting updated after updating the pack values in UI
  docs/docs-content/troubleshooting/vmo-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3585 docs: modify core dump
  docs/docs-content/clusters/edge/local-ui/host-management/download-core-dump.md
  docs/docs-content/clusters/edge/local-ui/host-management/download-files.md
Labels: 4.4.b

#3523 docs: OPS-4863
  docs/deprecated/integrations/konvoy.md
  docs/docs-content/byoos/byoos.md
  docs/docs-content/byoos/capi-image-builder/_category_.json
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/_category_ .json
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/build-image-vmware.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/rhel-capi.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/rocky-capi.md
  docs/docs-content/byoos/capi-image-builder/capi-image-builder.md
  docs/docs-content/byoos/capi-image-builder/comp-matrix-capi-builder.md
  docs/docs-content/byoos/capi-image-builder/config-reference.md
  docs/docs-content/byoos/image-builder/_category_.json
  docs/docs-content/byoos/image-builder/build-image-vmware/_category_ .json
  docs/docs-content/byoos/image-builder/build-image-vmware/build-image-vmware.md
  docs/docs-content/byoos/image-builder/build-image-vmware/konvoy.md
  docs/docs-content/byoos/image-builder/build-image-vmware/rhel-pxk.md
  docs/docs-content/byoos/image-builder/build-image.md
  docs/docs-content/byoos/image-builder/image-builder.md
  docs/docs-content/byoos/usecases/usecases.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
  redirects.js
Labels: 4.4.b

#3595 [4.4.b] Binaries References and Upgrade Path
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.4.b

#3547 docs: release notes 4.4.b
  docs/docs-content/component.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/nodes.md
Labels: 4.4.b

#3612 Updating CVEs from .12 to .14 and adding official summaries
  docs/docs-content/security-bulletins/reports/cve-2005-2541.md
  docs/docs-content/security-bulletins/reports/cve-2012-2663.md
  docs/docs-content/security-bulletins/reports/cve-2015-20107.md
  docs/docs-content/security-bulletins/reports/cve-2016-1585.md
  docs/docs-content/security-bulletins/reports/cve-2016-20013.md
  docs/docs-content/security-bulletins/reports/cve-2017-11164.md
  docs/docs-content/security-bulletins/reports/cve-2018-20225.md
  docs/docs-content/security-bulletins/reports/cve-2018-20657.md
  docs/docs-content/security-bulletins/reports/cve-2018-20796.md
  docs/docs-content/security-bulletins/reports/cve-2018-20839.md
  docs/docs-content/security-bulletins/reports/cve-2019-1010022.md
  docs/docs-content/security-bulletins/reports/cve-2019-12900.md
  docs/docs-content/security-bulletins/reports/cve-2019-17543.md
  docs/docs-content/security-bulletins/reports/cve-2019-19244.md
  docs/docs-content/security-bulletins/reports/cve-2019-9192.md
  docs/docs-content/security-bulletins/reports/cve-2019-9674.md
  docs/docs-content/security-bulletins/reports/cve-2019-9923.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/cve-2019-9937.md
  docs/docs-content/security-bulletins/reports/cve-2020-35512.md
  docs/docs-content/security-bulletins/reports/cve-2020-36325.md
  docs/docs-content/security-bulletins/reports/cve-2021-3737.md
  docs/docs-content/security-bulletins/reports/cve-2021-39537.md
  docs/docs-content/security-bulletins/reports/cve-2021-42694.md
  docs/docs-content/security-bulletins/reports/cve-2022-0391.md
  docs/docs-content/security-bulletins/reports/cve-2022-23990.md
  docs/docs-content/security-bulletins/reports/cve-2022-41409.md
  docs/docs-content/security-bulletins/reports/cve-2022-41723.md
  docs/docs-content/security-bulletins/reports/cve-2022-4899.md
  docs/docs-content/security-bulletins/reports/cve-2023-0464.md
  docs/docs-content/security-bulletins/reports/cve-2023-26604.md
  docs/docs-content/security-bulletins/reports/cve-2023-27534.md
  docs/docs-content/security-bulletins/reports/cve-2023-29499.md
  docs/docs-content/security-bulletins/reports/cve-2023-32636.md
  docs/docs-content/security-bulletins/reports/cve-2023-37920.md
  docs/docs-content/security-bulletins/reports/cve-2023-39325.md
  docs/docs-content/security-bulletins/reports/cve-2023-4156.md
  docs/docs-content/security-bulletins/reports/cve-2023-44487.md
  docs/docs-content/security-bulletins/reports/cve-2023-45142.md
  docs/docs-content/security-bulletins/reports/cve-2023-47108.md
  docs/docs-content/security-bulletins/reports/cve-2024-21626.md
  docs/docs-content/security-bulletins/reports/cve-2024-38428.md
  docs/docs-content/security-bulletins/reports/ghsa-m425-mq94-257g.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3603 docs: reduce linkinator config DOC-1346
  .github/workflows/url-checks.yaml
  Makefile
  scripts/url-checker.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3640 docs: remove space from broken URL check DOC-1346
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3626 docs: add a warning about deleting registered Edge hosts
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3648 Fix Production Issue with Packs List
  src/components/Technologies/PackCardIcon.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3641 Remove Invalid Azure Permission
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3669 chore: iconmapper error fix
  src/components/Technologies/PackCardIcon.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3676 Packs fix
  plugins/packs-integrations.js
Labels: bug, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3668 Session Timeout
  docs/docs-content/enterprise-version/system-management/account-management/credentials.md
  docs/docs-content/tenant-settings/session-timeout.md
  docs/docs-content/tenant-settings/tenant-settings.md
  docs/docs-content/vertex/system-management/account-management/credentials.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3613 Upgrade Docusaurus 3.5.2
  package-lock.json
  package.json
  plugins/packs-integrations.js
  src/theme/DocCard/index.js
  src/theme/DocSidebarItem/Category/index.js
  src/theme/DocSidebarItem/Link/index.js
  visuals/screenshot.api.spec.ts
  visuals/screenshot.docs.spec.ts
Labels: dependencies, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests, backport-version-4-4

#3691 Removed N/A cves 8-21-24
  docs/docs-content/security-bulletins/reports/cve-2020-1971.md
  docs/docs-content/security-bulletins/reports/cve-2021-3449.md
  docs/docs-content/security-bulletins/reports/cve-2021-3711.md
  docs/docs-content/security-bulletins/reports/cve-2021-45079.md
  docs/docs-content/security-bulletins/reports/cve-2022-0778.md
  docs/docs-content/security-bulletins/reports/cve-2022-4450.md
  docs/docs-content/security-bulletins/reports/cve-2023-0215.md
  docs/docs-content/security-bulletins/reports/cve-2023-0286.md
  docs/docs-content/security-bulletins/reports/cve-2023-52425.md
  docs/docs-content/security-bulletins/reports/cve-2023-5528.md
  docs/docs-content/security-bulletins/reports/cve-2024-0743.md
  docs/docs-content/security-bulletins/reports/prisma-2022-0227.md
  docs/docs-content/security-bulletins/reports/reports.md
  redirects.js
Labels: auto-backport, backport-version-4-4

#3693 8-22-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2022-25883.md
Labels: auto-backport, backport-version-4-4

#3701 docs: add grub screen description
  docs/docs-content/clusters/edge/site-deployment/site-installation/initial-setup.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3703 docs: 8-23-24 cve updates
  docs/docs-content/security-bulletins/reports/ghsa-74fp-r6jw-h4mp.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3702 Azure JSON Policies
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3712 chore: update README.md (admonitions)
  README.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3726 docs: clarify upgrade direction
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/non-airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
  docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3732 docs: remove vertex from self-hosted page
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3740 docs: minor backport to clarify bug fix
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3743 chore: automatic format prettier error
  .github/workflows/pull_request.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3738 Ato message
  README.md
  _partials/feature_flags/_feature_flags_overview.mdx
  _partials/self-hosted/_login-banner.mdx
  docs/docs-content/enterprise-version/system-management/login-banner.md
  docs/docs-content/enterprise-version/system-management/system-management.md
  docs/docs-content/tenant-settings/login-banner.md
  docs/docs-content/vertex/system-management/login-banner.md
  docs/docs-content/vertex/system-management/system-management.md
  src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
  src/components/PaletteVertexUrlMapper/index.ts
  src/theme/MDXComponents/MDXComponents.ts
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4
