Repository spectrocloud/librarium, pull requests merged in 2024-09, with the labels that each got.

#3771 9-2-24 cve status correction
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3742 docs: PCP-3421
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/cluster-management/taints.md
Labels: 4.4.c

#3739 docs: add limitation of renewal
  docs/docs-content/clusters/cluster-management/certificate-management.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3661 docs: profile basic information regarding external registry using pro…
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
Labels: auto-backport, backport-version-4-4

#3791 docs: PCP-3426
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3809 docs: PE-4831
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3810 9-5-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2021-46848.md
  docs/docs-content/security-bulletins/reports/cve-2024-0760.md
  docs/docs-content/security-bulletins/reports/cve-2024-1737.md
  docs/docs-content/security-bulletins/reports/cve-2024-1975.md
  docs/docs-content/security-bulletins/reports/cve-2024-45490.md
  docs/docs-content/security-bulletins/reports/cve-2024-45491.md
  docs/docs-content/security-bulletins/reports/cve-2024-45492.md
  docs/docs-content/security-bulletins/reports/cve-2024-6232.md
  docs/docs-content/security-bulletins/reports/cve-2024-7592.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3807 PLT-1377: centralize & correct vSphere privileges
  _partials/permissions/_vsphere-permissions.mdx
  docs/docs-content/clusters/data-center/vmware/permissions.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3821 docs: new securrity bulletin format
  docs/docs-content/security-bulletins/reports/cve-2023-49569.md
  docs/docs-content/security-bulletins/reports/cve-2024-45490.md
  docs/docs-content/security-bulletins/reports/cve-2024-45491.md
  docs/docs-content/security-bulletins/reports/cve-2024-45492.md
  docs/docs-content/security-bulletins/reports/cve-2024-6232.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3823 docs: PE-4316
  docs/docs-content/clusters/cluster-management/certificate-management.md
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
Labels: 4.4.c

#3833 docs: add known issues
  docs/docs-content/release-notes/known-issues.md
Labels: 4.4.c

#3840 docs: DOC-1372
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: backport-version-4-0, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3846 docs: alter yaml spacing in duplicate profile pack docs
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/duplicate-pack-in-profile.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3854 docs: update version and k8s distro
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
Labels: auto-backport, backport-version-4-4

#3832 docs: clarify QR code registration requirements
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
Labels: backport-version-4-4

#3863 docs: Edge mgmt api 4.4.c
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.4.c

#3764 docs: connected local UI
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/host-management/access-console.md
  docs/docs-content/clusters/edge/local-ui/host-management/audit-logs.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
  docs/docs-content/clusters/edge/local-ui/host-management/diagnostic-tools.md
  docs/docs-content/clusters/edge/local-ui/host-management/download-files.md
  docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
Labels: 4.4.c

#3839 Volume Snapshot Support
  docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md
  docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
  docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3865 docs: update oss licenses
  docs/docs-content/legal-licenses/oss-licenses.md
Labels: 4.4.c

#3873 docs: DOC-1375
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3855 docs: PEM-5694
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/create-vm-template.md
  docs/docs-content/vm-management/create-manage-vm/deploy-vm-from-template.md
  docs/docs-content/vm-management/create-manage-vm/enable-cpu-hotplug.md
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_details.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_flavor_box.webp
Labels: 4.4.c

#3879 docs: DOC-1369
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/automation.md
  docs/docs-content/troubleshooting/troubleshooting.md
  plugins/packs-integrations.js
  vale.ini
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3887 fix: move VM folder to spectro role, correct folder conditions
  _partials/permissions/_vsphere-permissions.mdx
  docs/docs-content/clusters/data-center/vmware/create-manage-vmware-clusters.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3886 docs: confirm cert renewal by looking at expiry date
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3864 Vmo mac address
  docs/docs-content/vm-management/architecture.md
  docs/docs-content/vm-management/create-manage-vm/enable-cpu-hotplug.md
Labels: 4.4.c

#3815 CAPI Image Builder - Airgap Workflow
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/_category_.json
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/_category_.json
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/airgap-build.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/build-image-vmware.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/_category_.json
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/non-airgap-build.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi.md
  docs/docs-content/byoos/capi-image-builder/comp-matrix-capi-builder.md
  docs/docs-content/byoos/capi-image-builder/config-reference.md
  redirects.js
Labels: 4.4.c

#3894 docs: DOC-1379
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3866 docs: add VM migration from vSphere to Palette VMO DOC-830
  docs/docs-content/automation/palette-cli/commands/vmo.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
  docs/docs-content/vm-management/vm-management.md
  static/assets/docs/images/migrate-vm-kubevirt-guide/vm-management_create-manage-vm_migrate-vm-kubevirt_start_migrated_vm.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3902 9-13-24 4.4.17 cve updates
  docs/docs-content/security-bulletins/reports/cve-2022-45061.md
  docs/docs-content/security-bulletins/reports/cve-2022-48560.md
  docs/docs-content/security-bulletins/reports/cve-2022-48565.md
  docs/docs-content/security-bulletins/reports/cve-2023-24329.md
  docs/docs-content/security-bulletins/reports/cve-2024-3651.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3872 docs: add cert renewal availability impact
  docs/docs-content/clusters/cluster-management/certificate-management.md
  docs/docs-content/clusters/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
Labels: 4.4.c

#3912 docs: cert disconnected known issue
  docs/docs-content/release-notes/known-issues.md
Labels: 4.4.c

#3910 docs: PLT-1393
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/vmo-issues.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3911 docs: add config patch to migration prereqs PLT-1392
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/advanced-topics.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3926 Small release notes fixes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3932 docs: fix missed mention of renewal
  docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
Labels: auto-backport, backport-version-4-4

#3934 docs: remove airgap instructions from non-airgap guides
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3938 [version-4-3] docs: remove airgap instructions from non-airgap guides (#3934)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.3

#3930 9-15-24 palette cve updates
  docs/docs-content/registries-and-packs/adding-add-on-packs.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/cve-2022-28357.md
  docs/docs-content/security-bulletins/reports/cve-2022-28948.md
  docs/docs-content/security-bulletins/reports/cve-2022-41724.md
  docs/docs-content/security-bulletins/reports/cve-2022-41725.md
  docs/docs-content/security-bulletins/reports/cve-2022-45061.md
  docs/docs-content/security-bulletins/reports/cve-2022-48560.md
  docs/docs-content/security-bulletins/reports/cve-2022-48565.md
  docs/docs-content/security-bulletins/reports/cve-2023-24329.md
  docs/docs-content/security-bulletins/reports/cve-2023-24534.md
  docs/docs-content/security-bulletins/reports/cve-2023-24536.md
  docs/docs-content/security-bulletins/reports/cve-2023-24537.md
  docs/docs-content/security-bulletins/reports/cve-2023-24538.md
  docs/docs-content/security-bulletins/reports/cve-2023-24539.md
  docs/docs-content/security-bulletins/reports/cve-2023-24540.md
  docs/docs-content/security-bulletins/reports/cve-2023-29400.md
  docs/docs-content/security-bulletins/reports/cve-2023-29403.md
  docs/docs-content/security-bulletins/reports/cve-2023-45287.md
  docs/docs-content/security-bulletins/reports/cve-2023-52356.md
  docs/docs-content/security-bulletins/reports/cve-2024-0743.md
  docs/docs-content/security-bulletins/reports/cve-2024-21626.md
  docs/docs-content/security-bulletins/reports/cve-2024-32002.md
  docs/docs-content/security-bulletins/reports/cve-2024-3651.md
  docs/docs-content/security-bulletins/reports/cve-2024-6232.md
  docs/docs-content/security-bulletins/reports/reports.md
  redirects.js
Labels: auto-backport, backport-version-4-4

#3939 [version-4-2] docs: remove airgap instructions from non-airgap guides (#3934)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.2

#3940 [version-4-1] docs: remove airgap instructions from non-airgap guides (#3934)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.1

#3941 [version-4-0] docs: remove airgap instructions from non-airgap guides (#3934)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.0

#3942 docs: add api breaking change
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3928 docs: fix broken links and adjust linkinator config DOC-1382
  .github/workflows/url-checks.yaml
  Makefile
  docs/docs-content/legal-licenses/oss-licenses.md
  docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
  linkinator/linkinator-ci.config.json
  linkinator/linkinator-rate-limit-ci.config.json
  linkinator/linkinator-rate-limit.config.json
  linkinator/linkinator.config.json
  scripts/url-checker.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3951 docs: document api breaking change/known issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3936 docs: add instruction about json file for k8s versions
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
Labels: auto-backport, backport-version-4-4

#3929 docs: DOC-1362
  docs/docs-content/automation/palette-sdk/palette-sdk.md
  docs/docs-content/user-management/authentication/api-key/api-key.md
  docs/docs-content/user-management/authentication/api-key/delete-api-key.md
  docs/docs-content/user-management/saml-sso/saml-sso.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3961 9-17-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2012-2663.md
  docs/docs-content/security-bulletins/reports/cve-2016-20013.md
  docs/docs-content/security-bulletins/reports/cve-2017-11164.md
  docs/docs-content/security-bulletins/reports/cve-2018-20657.md
  docs/docs-content/security-bulletins/reports/cve-2018-20796.md
  docs/docs-content/security-bulletins/reports/cve-2018-20839.md
  docs/docs-content/security-bulletins/reports/cve-2019-1010022.md
  docs/docs-content/security-bulletins/reports/cve-2019-12900.md
  docs/docs-content/security-bulletins/reports/cve-2019-9192.md
  docs/docs-content/security-bulletins/reports/cve-2020-36325.md
  docs/docs-content/security-bulletins/reports/cve-2021-39537.md
  docs/docs-content/security-bulletins/reports/cve-2021-42694.md
  docs/docs-content/security-bulletins/reports/cve-2021-46848.md
  docs/docs-content/security-bulletins/reports/cve-2022-0391.md
  docs/docs-content/security-bulletins/reports/cve-2022-41409.md
  docs/docs-content/security-bulletins/reports/cve-2022-41723.md
  docs/docs-content/security-bulletins/reports/cve-2022-4899.md
  docs/docs-content/security-bulletins/reports/cve-2023-0464.md
  docs/docs-content/security-bulletins/reports/cve-2023-26604.md
  docs/docs-content/security-bulletins/reports/cve-2023-37920.md
  docs/docs-content/security-bulletins/reports/cve-2023-39325.md
  docs/docs-content/security-bulletins/reports/cve-2023-45142.md
  docs/docs-content/security-bulletins/reports/cve-2023-47108.md
  docs/docs-content/security-bulletins/reports/cve-2024-0760.md
  docs/docs-content/security-bulletins/reports/cve-2024-1737.md
  docs/docs-content/security-bulletins/reports/cve-2024-1975.md
  docs/docs-content/security-bulletins/reports/cve-2024-21626.md
  docs/docs-content/security-bulletins/reports/cve-2024-24790.md
  docs/docs-content/security-bulletins/reports/cve-2024-37370.md
  docs/docs-content/security-bulletins/reports/cve-2024-37371.md
  docs/docs-content/security-bulletins/reports/cve-2024-38428.md
  docs/docs-content/security-bulletins/reports/cve-2024-45490.md
  docs/docs-content/security-bulletins/reports/cve-2024-45491.md
  docs/docs-content/security-bulletins/reports/cve-2024-45492.md
  docs/docs-content/security-bulletins/reports/cve-2024-6232.md
  docs/docs-content/security-bulletins/reports/cve-2024-7592.md
  docs/docs-content/security-bulletins/reports/ghsa-74fp-r6jw-h4mp.md
  docs/docs-content/security-bulletins/reports/ghsa-m425-mq94-257g.md
  docs/docs-content/security-bulletins/reports/reports.md
  docs/docs-content/security-bulletins/security-bulletins.md
Labels: auto-backport, backport-version-4-4

#3955 RL 4.4.19
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#3952 docs: remove oss-licenses from the url checking job DOC-1382
  Makefile
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3909 docs: add import and deploy OVA guide DOC-829
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/vmo.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/advanced-topics.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
  docs/docs-content/vm-management/vm-management.md
  static/assets/docs/images/deploy-import-ova-guide/vm-management_create-manage-vm_advanced-topics_deploy-import-ova_fix-boot-order-warning.webp
  static/assets/docs/images/deploy-import-ova-guide/vm-management_create-manage-vm_advanced-topics_deploy-import-ova_fix-serial-number-warning.webp
  static/assets/docs/images/deploy-import-ova-guide/vm-management_create-manage-vm_advanced-topics_deploy-import-ova_imported-vm-details.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3976 docs: update vertex/self-hosted upgrade paths table
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: auto-backport, backport-version-4-4

#3975 9-18-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2022-41724.md
  docs/docs-content/security-bulletins/reports/cve-2023-24536.md
  docs/docs-content/security-bulletins/reports/cve-2023-24537.md
  docs/docs-content/security-bulletins/reports/cve-2023-24538.md
  docs/docs-content/security-bulletins/reports/cve-2023-29403.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3979 chore: DOC-1388
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, api-format

#3987 chore: add nodejs
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3994 chore: final fix
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4001 chore: api label action
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3931 chore: dependencies
  package-lock.json
  package.json
Labels: backport-version-4-0, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, api-format

#4015 docs: add missing letter in namespace
  docs/docs-content/troubleshooting/enterprise-install.md
Labels: auto-backport, backport-version-4-4

#4018 docs: Update config-reference.md
  docs/docs-content/byoos/capi-image-builder/config-reference.md
Labels: auto-backport, backport-version-4-4

#4026 9-20-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2022-28948.md
  docs/docs-content/security-bulletins/reports/cve-2023-24534.md
  docs/docs-content/security-bulletins/reports/cve-2023-52356.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#3561 [Tutorial] Deploy an Edge Cluster on VirtualBox
  .gitleaksignore
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_byos-cluster-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-nodes.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-events.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-overview.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-hellouni.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-k8s.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-metallb.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_delete-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_diagram.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host-palette.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_hello-universe.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-config.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-network.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-reboot.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-remove-iso.webp
Labels: tutorial, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4032 [version-4-2] docs: [Tutorial] Deploy an Edge Cluster on VirtualBox (#3561)
  .gitleaksignore
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_byos-cluster-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-nodes.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-events.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-overview.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-hellouni.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-k8s.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-metallb.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_delete-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_diagram.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host-palette.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_hello-universe.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-config.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-network.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-reboot.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-remove-iso.webp
Labels: 4.2

#4033 [version-4-1] docs: [Tutorial] Deploy an Edge Cluster on VirtualBox (#3561)
  .gitleaksignore
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_byos-cluster-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-nodes.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-events.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-overview.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-hellouni.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-k8s.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-metallb.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_delete-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_diagram.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host-palette.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_hello-universe.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-config.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-network.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-reboot.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-remove-iso.webp
Labels: 4.1

#4034 [version-4-0] docs: [Tutorial] Deploy an Edge Cluster on VirtualBox (#3561)
  .gitleaksignore
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_byos-cluster-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-nodes.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-deployment-profile.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-events.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-overview.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-hellouni.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-k8s.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_cluster-profile-metallb.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_delete-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_diagram.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host-palette.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_edge-host.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_hello-universe.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-config.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-network.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-reboot.webp
  static/assets/docs/images/tutorials/edge-vbox/tutorials_edge-vbox_deploy-cluster-virtualbox_vm-remove-iso.webp
Labels: 4.0

#3841 Update compliance-scan.md
  docs/docs-content/clusters/cluster-management/compliance-scan.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4031 docs: clarify agent upgrade documentation
  docs/docs-content/clusters/cluster-management/platform-settings/pause-platform-upgrades.md
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4046 9-23-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2005-2541.md
  docs/docs-content/security-bulletins/reports/cve-2015-20107.md
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2016-1585.md
  docs/docs-content/security-bulletins/reports/cve-2018-20225.md
  docs/docs-content/security-bulletins/reports/cve-2019-19244.md
  docs/docs-content/security-bulletins/reports/cve-2019-9674.md
  docs/docs-content/security-bulletins/reports/cve-2019-9923.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/cve-2019-9937.md
  docs/docs-content/security-bulletins/reports/cve-2020-35512.md
  docs/docs-content/security-bulletins/reports/cve-2021-3737.md
  docs/docs-content/security-bulletins/reports/cve-2022-23990.md
  docs/docs-content/security-bulletins/reports/cve-2022-25883.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#4051 gRPC Transcoding
  docs/docs-content/architecture/grps-proxy.md
  docs/docs-content/security-bulletins/reports/cve-2005-2541.md
  docs/docs-content/security-bulletins/reports/cve-2015-20107.md
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2016-1585.md
  docs/docs-content/security-bulletins/reports/cve-2018-20225.md
  docs/docs-content/security-bulletins/reports/cve-2019-19244.md
  docs/docs-content/security-bulletins/reports/cve-2019-9674.md
  docs/docs-content/security-bulletins/reports/cve-2019-9923.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/cve-2019-9937.md
  docs/docs-content/security-bulletins/reports/cve-2020-35512.md
  docs/docs-content/security-bulletins/reports/cve-2021-3737.md
  docs/docs-content/security-bulletins/reports/cve-2022-23990.md
  docs/docs-content/security-bulletins/reports/cve-2022-25883.md
  docs/docs-content/security-bulletins/reports/reports.md
  static/assets/docs/images/architecture_grps-proxy_grpc-websocket.webp
Labels: auto-backport, backport-version-4-4

#4049 docs: add limitation for external registry + content bundle
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4053 docs: PLT-1397 clarify CDI upload proxy wording for ova import
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4050 docs: modify calico instructions for multi-nic case
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4047 docs: DOC-1385
  docs/docs-content/architecture/grps-proxy.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
  docs/docs-content/release-notes/release-notes.md
  static/assets/docs/images/architecture_grps-proxy_grpc-websocket.webp
Labels: auto-backport, backport-version-4-4

#4075 [4-4] docs: DOC-1385 - Release Notes (#4047)
  docs/docs-content/architecture/grps-proxy.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
  docs/docs-content/release-notes/release-notes.md
  static/assets/docs/images/architecture_grps-proxy_grpc-websocket.webp
Labels: 4.4

#4077 docs: revert release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#4079 docs: add 4.4.20 release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-4

#4081 Corrections cve updates
  docs/docs-content/security-bulletins/reports/cve-2005-2541.md
  docs/docs-content/security-bulletins/reports/cve-2015-20107.md
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2016-1585.md
  docs/docs-content/security-bulletins/reports/cve-2018-20225.md
  docs/docs-content/security-bulletins/reports/cve-2019-19244.md
  docs/docs-content/security-bulletins/reports/cve-2019-9674.md
  docs/docs-content/security-bulletins/reports/cve-2019-9923.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/cve-2019-9937.md
  docs/docs-content/security-bulletins/reports/cve-2020-35512.md
  docs/docs-content/security-bulletins/reports/cve-2021-3737.md
  docs/docs-content/security-bulletins/reports/cve-2022-23990.md
  docs/docs-content/security-bulletins/reports/cve-2022-25883.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-4

#4082 docs: DOC-1391
  docs/docs-content/devx/devx.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/security-bulletins/reports/cve-2015-8855.md
  docs/docs-content/security-bulletins/reports/cve-2019-9936.md
  docs/docs-content/security-bulletins/reports/reports.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
  scripts/compress-convert-images.sh
Labels: auto-backport, backport-version-4-4

#4076 docs: Getting Started VMware screenshots update
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4087 [version-4-3] docs: Getting Started VMware screenshots update (#4076)
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: 4.3

#4088 [version-4-2] docs: Getting Started VMware screenshots update (#4076)
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: 4.2

#4089 [version-4-0] docs: Getting Started VMware screenshots update (#4076)
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: 4.0

#4090 [version-4-1] docs: Getting Started VMware screenshots update (#4076)
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: 4.1

#4091 [version-3-4] docs: Getting Started VMware screenshots update (#4076)
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/update-k8s-cluster.md
  scripts/compress-convert-images.sh
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_clusters_parameters.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_new_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-k8s-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_create_cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_event_log.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster-tf_profile_review.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-with-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_profile-without-kubecost.webp
  static/assets/docs/images/getting-started/vmware/getting-started_deploy-manage-k8s-cluster_reconciliation.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_delete-cluster-button.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-upgrade-applied.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_kubernetes-versions.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_metallb-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_node-repaves.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_pack-presets.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_service_url.webp
  static/assets/docs/images/getting-started/vmware/getting-started_scale-secure-cluster_third-node-pool.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_add-service-tag.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_apply-frontend-filter.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_cluster-details.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_completed-cluster-updates.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_download-kubeconfig.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_new-version-overview.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_pending-update-clusters-view.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-version-selection.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_profile-with-cluster.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_select-kubecost-pack.webp
  static/assets/docs/images/getting-started/vmware/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
Labels: 3.4

#4096 docs: DOC-1409
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-4

#4066 docs: PLT-1405
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4120 docs: add ubuntu to known issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4121 docs: DOC-1410
  _partials/self-hosted/_required-domains.mdx
  docs/docs-content/architecture/palette-public-ips.md
Labels: 4.5

#4112 docs: PLT-1407
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
Labels: 4.5

#4095 chore: improve backports
  .github/workflows/backport.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4
