Repository spectrocloud/librarium, pull requests merged in 2024-10, with the labels that each got.

#4132 docs: PCP-3568
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-4

#4131 docs: update airgap self-hosted pages
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4119 OIDC userinfo
  docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
Labels: 4.5

#4149 [version-4-2] docs: update airgap self-hosted pages (#4131)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: 4.2

#4150 [version-4-1] docs: update airgap self-hosted pages (#4131)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: 4.1

#4151 [version-4-0] docs: update airgap self-hosted pages (#4131)
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: 4.0

#4152 chore: improve backport message
  .github/workflows/backport.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4138 Microk8s and Backup Failures
  docs/docs-content/integrations/kubernetes-microk8s.md
  docs/docs-content/release-notes/known-issues.md
Labels: 4.5

#4167 Fix link to VMO reference architecture
  docs/docs-content/vm-management/architecture.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4168 docs: update dockerfile
  Dockerfile
  Makefile
  README.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4181 OCI Helm Registries - Sync Supported
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-helm.md
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-packs.md
  docs/docs-content/registries-and-packs/registries/oci-registry/oci-registry.md
  docs/docs-content/registries-and-packs/registries/registries.md
Labels: 4.5

#4188 docs: add new pxk oss licenses page
  docs/docs-content/legal-licenses/compliance.md
  docs/docs-content/legal-licenses/legal-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses-index.md
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
  redirects.js
Labels: auto-backport, backport-version-4-4

#4189 Minor typo
  .github/workflows/backport.yaml
  src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4197 fix wording of pxk
  docs/deprecated/integrations/kubernetes.md
  docs/docs-content/glossary-all.md
  docs/docs-content/integrations/kubernetes.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4220 docs: remove free-tier mention
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
  docs/docs-content/clusters/edge/networking/connect-wifi.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4226 docs: fix api-label
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4216 docs: PEM-6014
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/modify-cluster-profiles.md
  docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
  static/assets/docs/images/byoos_vmware_rhewl-pxk_cluster-profile-non-fips.webp
  static/assets/docs/images/integrations_pack_diffs.webp
  static/assets/docs/images/profiles_cluster-profiles_modify-cluster-incoming-updates.webp
  static/assets/docs/images/profiles_cluster-profiles_modify-cluster-profiles_new-version-notifcation-changes-required.webp
  static/assets/docs/images/profiles_cluster-profiles_modify-cluster-profiles_new-version-notifcation.webp
Labels: 4.5

#4234 ci: fix api label job
  .github/workflows/api_format.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4233 docs: add Edge api 4.5.0
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.5, api-format

#4217 docs: add workaround for RKE2 Cilium known issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
Labels: 4.5

#4242 docs: DOC-1419
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
Labels: auto-backport, backport-version-4-4

#4250 docs: DOC-1421
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/getting-started/aws/setup.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-4

#4098 docs: disable webhook
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable.md
Labels: 4.5

#4140 docs: share local UI login
  docs/docs-content/clusters/edge/local-ui/cluster-management/share-auth.md
Labels: 4.5

#4258 docs: pxk-license
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#4159 docs: DOC-1408
  docs/docs-content/integrations/kubernetes-microk8s.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  static/packs-data/packs_information.json
Labels: 4.5

#4099 docs: agent mode / deployment modes
  docs/docs-content/deployment-modes/_category_.json
  docs/docs-content/deployment-modes/agent-mode/_category_.json
  docs/docs-content/deployment-modes/agent-mode/agent-mode.md
  docs/docs-content/deployment-modes/agent-mode/architecture.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/deployment-modes/agent-mode/manage-agent/localui-theming.md
  docs/docs-content/deployment-modes/agent-mode/manage-agent/manage-agent.md
  docs/docs-content/deployment-modes/appliance-mode.md
  docs/docs-content/deployment-modes/controller-mode.md
  docs/docs-content/deployment-modes/deployment-modes.md
  src/components/IconMapper/dynamicFontAwesomeImports.ts
  static/assets/docs/images/deployment-modes_agent-mode.webp
  static/assets/docs/images/deployment-modes_agent-mode_byos-pack.webp
  static/assets/docs/images/deployment-modes_appliance-mode.webp
  static/assets/docs/images/deployment-modes_controller-diagram.webp
  static/assets/docs/images/deployment-modes_main-diagram-loop.gif
Labels: 4.5

#4263 docs: fix extra return char
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#4268 docs: updated agent-mode
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#4270 docs: update spectro-downloads.md
  docs/docs-content/spectro-downloads.md
Labels: auto-backport, backport-version-4-5

#4293 chore: fix bug in packs plugin
  plugins/packs-integrations.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4292 10-16-24 cve corrections
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-5

#4282 docs: update 4.5 RN test
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#4304 docs: DOC-1425
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#4305 docs: update url mapper component
  README.md
  docs/docs-content/clusters/pcg/pcg.md
  src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4313 [version-3-4] docs: update url mapper component (#4305)
  README.md
  src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
Labels: 3.4

#4324 Version Branches Robots.txt Update
  .github/workflows/versions_robot.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4283 docs: add include-core-images-only option
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
Labels: auto-backport, backport-version-4-5

#4302 Rewrote MAAS custom endpoint docs
  docs/deprecated/integrations/kubernetes.md
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/integrations/kubernetes.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4342 Backports Message
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/api_format.yaml
  .github/workflows/backport.yaml
  .github/workflows/container-prune.yaml
  .github/workflows/packs-data.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/versions_robot.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4334 docs: update byos edge pack version
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#4352 docs: fix image tag
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#4355 Airgap Binaries
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
Labels: auto-backport, backport-version-4-5

#4351 docs: DOC-1430
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#4323 docs: change earthly command to installed earthly
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/signed-content.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4364 ci: add prettier to remove uneccessary triggers
  .github/workflows/versions_robot.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4372 Backport prettier update
  .github/workflows/versions_robot.yaml
  scripts/noindex_docusaurus_config.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4380 Robots Txt Fix
  .github/workflows/versions_robot.yaml
  docusaurus.config.js
  netlify.toml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4388 ci: remove package.json prepare
  netlify.toml
  package-lock.json
  package.json
Labels: dependencies, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4396 docs: update cve-2022-32190
  docs/docs-content/security-bulletins/reports/cve-2022-32190.md
Labels: auto-backport, backport-version-4-5

#3888 [DOC 1368] RHEL base binary options to be used in Airgap mode
  _partials/self-hosted/_setup-steps.mdx
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/config-reference.md
  docs/docs-content/enterprise-version/install-palette/airgap/airgap.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/airgap-install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/env-setup-vm.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/environment-setup.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/airgap-install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/env-setup-vm-vertex.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/environment-setup.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
  redirects.js
Labels: auto-backport, backport-version-4-4, 4.4.c, backport-version-4-5

#4401 customEndpointPort must be an integer
  docs/deprecated/integrations/kubernetes.md
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/integrations/kubernetes.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4411 Registry URLs Fixes
  .github/workflows/release-preview.yaml
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4429 docs: remove double slashes from image reference DOC-1232
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4409 docs: add clean up images job DOC-1232
  .github/workflows/clean-up-unused-images.yaml
  .gitignore
  Makefile
  scripts/find-unused-images.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4459 docs: adjust script to handle zero unused images DOC-1232
  .github/workflows/clean-up-unused-images.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#1961 DOC-806: adding revised Datadog integration doc
  docs/docs-content/audit-logs/monitor-with-datadog.md
  static/assets/docs/images/audit-logs_monitor-with-datadog_datadog-agent.webp
  static/assets/docs/images/audit-logs_monitor-with-datadog_datadog-logs.webp
  static/assets/docs/images/audit-logs_monitor-with-datadog_datadog-pack.webp
  static/assets/docs/images/audit-logs_monitor-with-datadog_datadog-ui.webp
  static/assets/docs/images/audit-logs_monitor-with-datadog_registry.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4473 doc: DOC-1178
  docs/docs-content/profiles/profile-customization.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4482 10-24-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2005-2541.md
  docs/docs-content/security-bulletins/reports/cve-2018-20657.md
  docs/docs-content/security-bulletins/reports/cve-2019-12900.md
  docs/docs-content/security-bulletins/reports/cve-2020-35512.md
  docs/docs-content/security-bulletins/reports/cve-2022-23990.md
  docs/docs-content/security-bulletins/reports/cve-2022-4899.md
  docs/docs-content/security-bulletins/reports/cve-2023-27534.md
  docs/docs-content/security-bulletins/reports/cve-2023-29499.md
  docs/docs-content/security-bulletins/reports/cve-2023-32636.md
  docs/docs-content/security-bulletins/reports/cve-2023-36632.md
  docs/docs-content/security-bulletins/reports/cve-2023-4156.md
  docs/docs-content/security-bulletins/reports/cve-2023-45853.md
  docs/docs-content/security-bulletins/reports/cve-2024-1485.md
  docs/docs-content/security-bulletins/reports/cve-2024-24790.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-5

#4486 docs: update edge managament api for 4.5.5
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: auto-backport, api-format, backport-version-4-5

#4490 docs: PE-5397 node log download
  docs/docs-content/troubleshooting/edge.md
Labels: auto-backport, backport-version-4-5

#4474 docs: add guidance to spectro-k8s-dashboard pack DOC-1442
  docs/docs-content/clusters/cluster-management/kubernetes-dashboard.md
  docs/docs-content/integrations/k8s-dashboard.md
  static/assets/docs/images/integrations_spectro-k8s-dashboard_dashboard-page.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4499 10-29-24 cve updates
  docs/docs-content/security-bulletins/reports/cve-2019-1010022.md
  docs/docs-content/security-bulletins/reports/cve-2021-39537.md
  docs/docs-content/security-bulletins/reports/cve-2021-46848.md
  docs/docs-content/security-bulletins/reports/cve-2023-24540.md
  docs/docs-content/security-bulletins/reports/cve-2023-37920.md
  docs/docs-content/security-bulletins/reports/cve-2024-1485.md
  docs/docs-content/security-bulletins/reports/cve-2024-21626.md
  docs/docs-content/security-bulletins/reports/cve-2024-24790.md
  docs/docs-content/security-bulletins/reports/cve-2024-37371.md
  docs/docs-content/security-bulletins/reports/cve-2024-45491.md
  docs/docs-content/security-bulletins/reports/reports.md
Labels: auto-backport, backport-version-4-5

#4500 docs: add base64 requirement
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4272 Azure Permissions Refactor
  docs/deprecated/clusters/public-cloud/azure/required-permissions.md
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4512 docs: add new images to Getting Started DOC-1333
  _partials/getting-started/_getting-started_create-cluster-profile_spacetastic-end.mdx
  _partials/getting-started/_getting-started_create-cluster-profile_spacetastic-intro.mdx
  _partials/getting-started/_getting-started_setup_spacetastic-end.mdx
  _partials/getting-started/_getting-started_setup_spacetastic-intro.mdx
  static/assets/docs/images/getting-started/getting-started_create-cluster-profile_profile-created.webp
  static/assets/docs/images/getting-started/getting-started_create-cluster-profile_system-dependencies.webp
  static/assets/docs/images/getting-started/getting-started_setup_getting-started-discovery.webp
  static/assets/docs/images/getting-started/getting-started_setup_palette-setup-complete.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4513 Some small fixes for Azure v2 docs
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4528 docs: add pack indentation known issue PEM-6218
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#4532 Resolved Known Issue - 10/31
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#4542 docs: small fix for Azure v2 docs
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#4530 Cluster Groups w/ Edge
  docs/docs-content/clusters/cluster-groups/cluster-groups.md
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  static/assets/docs/images/clusters_cluster-groups_index-page.webp
Labels: 4.5.a

#4551 docs: DOC-1458
  docs/docs-content/clusters/pcg/architecture.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5
