Repository spectrocloud/librarium, pull requests merged in 2024-06, with the labels that each got.

#2965 Fix broken links for ngrok
  docs/docs-content/integrations/metallb.md
  docs/docs-content/integrations/ngrok.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2966 docs: updated proxy domain table
  .github/workflows/pull_request.yaml
  docs/docs-content/architecture/palette-public-ips.md
  docs/docs-content/enterprise-version/install-palette/install-palette.md
  docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2805 docs: Update the MicroK8s page to reflect 4.4 changes
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: 4.4

#2977 docs: upgrade docusaurus to version 3.4.0
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, visual-tests

#2988 docs: PEM-3526
  docs/docs-content/clusters/imported-clusters/cluster-import.md
  docs/docs-content/clusters/imported-clusters/imported-clusters.md
  docs/docs-content/clusters/imported-clusters/migrate-full-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-2, backport-version-4-3

#2997 chore: fix netlify issue that caused master to build
  scripts/netlify.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-2, backport-version-4-3

#3002 Microk8s update
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3005 [version-4-2] backport Microk8s update PR 3002
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: 4.2

#3006 [version-4-1] backport Microk8s update PR 3002
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: 4.1

#3007 [version-4-0] backport Microk8s update PR 3002
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: 4.0

#3008 [version-3-4] backport Microk8s update PR 3002
  docs/docs-content/integrations/microk8s.md
  static/assets/docs/images/integrations_microk8s_cluster-profile-view.webp
Labels: 3.4

#3010 docs: Edge mgmt api 4 4
  apisidebar.js
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: 4.4

#2918 docs: add steps for new edge cli command
  docs/deprecated/clusters/edge/edgeforge-workflow/build-artifacts.md
  docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-artifacts.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/integrations/kubernetes-edge.md
  redirects.js
Labels: 4.4

#3011 Update security-bulletins.md
  docs/docs-content/security-bulletins/security-bulletins.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#2612 docs: document trusted boot
  _partials/index.ts
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/hardware-requirements.md
  docs/docs-content/clusters/edge/trusted-boot/deployment-day2/_category_.json
  docs/docs-content/clusters/edge/trusted-boot/deployment-day2/deployment-day2.md
  docs/docs-content/clusters/edge/trusted-boot/deployment-day2/install.md
  docs/docs-content/clusters/edge/trusted-boot/deployment-day2/upgrade-cluster.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/_category_.json
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/add-extra-content.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-iso.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/check-efi-limit.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/edgeforge.md
  docs/docs-content/clusters/edge/trusted-boot/keys/_category_.json
  docs/docs-content/clusters/edge/trusted-boot/keys/export-keys.md
  docs/docs-content/clusters/edge/trusted-boot/keys/generate-keys.md
  docs/docs-content/clusters/edge/trusted-boot/keys/key-management.md
  docs/docs-content/clusters/edge/trusted-boot/keys/keys.md
  docs/docs-content/clusters/edge/trusted-boot/trusted-boot.md
  package-lock.json
  scripts/netlify.sh
  static/assets/docs/images/cluster_edge_trusted-boot_boot-process.webp
  static/assets/docs/images/clusters_edge_trusted-boot_highlevel.webp
  static/assets/docs/images/clusters_edge_trusted-boot_key-management_key-relationship.webp
Labels: 4.4

#3023 chore: k8s report
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3029 Update the open-source licenses table
  docs/docs-content/legal-licenses/oss-licenses.md
Labels: 4.4

#3030 chore: vertex known issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#3033 docs: add stable IP requirements
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#3034 docs: highlight CIS hardening
  docs/docs-content/clusters/edge/architecture.md
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3045 docs: fix user data alignment issue
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#2873 4.4 Release Notes
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/edge.md
  docs/docs-content/troubleshooting/pack-issues.md
Labels: 4.4

#3053 vSphere Version 6 series support
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3052 Known Issues Publication
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#3063 Known Issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3

#3044 Minor Pack Updates
  docs/docs-content/component.md
  docs/docs-content/integrations/frp.md
  docs/docs-content/integrations/kubernetes-generic.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/integrations/ubuntu.md
Labels: 4.4

#3075 ci: update Vale
  .github/workflows/pull_request.yaml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3074 RKE2 Overlay Network Support
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
Labels: auto-backport, backport-version-4-3

#3082 docs: remove overlay limitation
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
Labels: auto-backport, backport-version-4-3

#3084 docs: Update colon.yml
  vale/styles/spectrocloud/colon.yml
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3090 docs: updated VMware permissions
  docs/docs-content/clusters/data-center/vmware/permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3062 docs: add note about contacting sales team for qr code registration app
  docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3101 docs: add vsphere supported versions table
  docs/docs-content/clusters/data-center/vmware/vmware.md
  docs/docs-content/vertex/supported-platforms.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3103 docs: new known issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/palette-dev-engine.md
Labels: 4.4

#3102 Update the Palette and Edge CLIs download information
  docs/docs-content/spectro-downloads.md
Labels: 4.4

#3106 [version-4-0] backport add vsphere supported versions table PR 3101
  docs/docs-content/clusters/data-center/vmware/vmware.md
Labels: 4.0

#3107 [version-4-1] backport add vsphere supported versions table PR 3101
  docs/docs-content/clusters/data-center/vmware/vmware.md
Labels: 4.1

#3109 Fix broken links found in production
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
  docs/docs-content/clusters/edge/trusted-boot/keys/generate-keys.md
Labels: auto-backport, backport-version-4-4

#3022 docs: refactor and update aws cluster autoscaler pack page
  docs/docs-content/integrations/aws-autoscaler.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3

#3114 [version-4-2] backport docs: refactor and update aws cluster autoscaler pack page PR 3022
  docs/docs-content/integrations/aws-autoscaler.md
Labels: 4.2

#3115 [version-4-1] backport docs: refactor and update aws cluster autoscaler pack page (#3022)
  docs/docs-content/integrations/aws-autoscaler.md
Labels: 4.1

#3116 [version-4-0] backport docs: refactor and update aws cluster autoscaler pack page (#3022)
  docs/docs-content/integrations/aws-autoscaler.md
Labels: 4.0

#3117 [version-3-4] backport docs: refactor and update aws cluster autoscaler pack page (#3022)
  docs/docs-content/integrations/aws-autoscaler.md
Labels: 3.4

#3118 [version-4-4] backport docs: refactor and update aws cluster autoscaler pack page (#3022)
  docs/docs-content/integrations/aws-autoscaler.md
Labels: 4.4

#3073 Update the VMO index page and document its architecture
  docs/api-content/api-docs/v1/api.json
  docs/docs-content/vm-management/architecture.md
  docs/docs-content/vm-management/create-manage-vm/_category_.json
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/create-disk-templates.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/vm-oversubscription.md
  docs/docs-content/vm-management/create-manage-vm/migrate-vm-to-different-node.md
  docs/docs-content/vm-management/create-manage-vmo-cluster.md
  docs/docs-content/vm-management/create-vmo-profile.md
  docs/docs-content/vm-management/rbac/_category_.json
  docs/docs-content/vm-management/rbac/rbac.md
  docs/docs-content/vm-management/vm-management.md
  docs/docs-content/vm-management/vm-packs-profiles/_category_.json
  docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md
  static/assets/docs/images/docs_vm-mangement_vmo-diagram.webp
  static/assets/docs/images/vm-mangement_architecture_arch-diagram.webp
  static/assets/docs/images/vm-mangement_vmo-diagram.webp
  styleguide/spectro-cloud-style-guide.md
Labels: refactor

#3122 docs: update tutorials container version
  docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3121 Update vxlan-overlay.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3129 docs: update cluster override behaviour DOC-1240
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  docs/docs-content/clusters/cluster-management/update-k8s-cluster.md
  docs/docs-content/getting-started/update-k8s-cluster.md
  static/assets/docs/images/getting-started/getting-started_update-k8s-cluster_available-updates-dialog.webp
  static/assets/docs/images/getting-started/getting-started_update-k8s-cluster_editor-changes.webp
  static/assets/docs/images/getting-started/getting-started_update-k8s-cluster_updates-available-button-cluster-overview.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_available-updates-dialog.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_editor-changes.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_updates-available-button-cluster-overview.webp
Labels: auto-backport, backport-version-4-4

#3131 chore: correct Postman URL
  docs/api-content/api-docs/3-postman-collection.md
Labels: auto-backport, backport-version-4-4

#3061 Self-Hosted Custom CA Update
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3138 Known Issue 6-21-2024
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3140 Update Alogolia
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  .github/workflows/visual-comparison.yaml
  README.md
  docusaurus.config.js
  src/components/MendableAIWidget/MendableAIWidget.tsx
  src/components/MendableAIWidget/index.ts
  src/theme/Root/Root.tsx
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3156 docs: feedback from Pedro
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3160 docs: add Sonobuoy known issue PCP-3093
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3165 docs: Add a note about MongoDB replication completion
  docs/docs-content/troubleshooting/palette-upgrade.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3164 docs: PLT-1264
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/enterprise-install.md
  docs/docs-content/troubleshooting/palette-upgrade.md
  docs/docs-content/vertex/upgrade/upgrade-notes.md
  docs/docs-content/vertex/upgrade/upgrade.md
  static/assets/docs/images/troubleshooting_enterprise_install_system-profile-pack.webp
Labels: auto-backport, backport-version-4-3, backport-version-4-4

#3171 docs: DOC-1261 cilium issue
  docs/docs-content/integrations/cilium.md
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4

#3176 EC Install Validate Flag
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.4.a
