Repository spectrocloud/librarium, pull requests merged in 2025-08, with the labels that each got.

#7572 docs: DOC-2059: MongoDB Self-Hosted Upgrade Troubleshooting
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/troubleshooting/palette-upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7581 docs: remove Spectro Addon Repo references DOC-2066
  docs/docs-content/integrations/cloudanix.mdx
  docs/docs-content/integrations/gatekeeper.mdx
  docs/docs-content/registries-and-packs/registries/registries.md
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
  docusaurus.config.js
Labels: notify-slack, 4.7.a

#7625 docs: update vmo diagram
  docs/docs-content/vm-management/architecture.md
  static/assets/docs/images/vm-management_architecture_vmo-architecture-new.webp
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7633 docs: add crossplane to release notes PLT-1868
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7635 docs: Remove Tech Preview for Harbor Edge-Native Config pack
  docs/docs-content/integrations/harbor-edge-native-config.mdx
Labels: notify-slack

#7645 docs: Fix broken URLs on 4th August 2025 (Part 1)
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7657 docs: add 4.7.8 release notes DOC-2080
  docs/docs-content/clusters/edge/networking/kubevip.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7685 docs: update release notes DOC-2080
  docs/docs-content/clusters/edge/networking/kubevip.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7701 docs: Remote shell preview exit
  docs/docs-content/clusters/edge/cluster-management/remote-shell.md
Labels: notify-slack, 4.7.a

#7708 docs: add isTwoNodeCluster to release notes DOC-2084
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7692 PCP-4774 - EKS worker node customisation
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/integrations/kubernetes-eks.mdx
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.a

#7592 doc-2075: Updating the notify-slack github action script to ping people during their working hours.
  .github/workflows/GHA-ready-for-review.yaml
Labels: github_actions, notify-slack

#7717 chore(sec): sec fix for GH comment
  .github/workflows/GHA-ready-for-review.yaml
Labels: auto-backport, backport-version-4-2, github_actions, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7725 DOC-2068 - Management Appliance default drive selection behaviour
  _partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
Labels: auto-backport, backport-version-4-7, notify-slack

#7721 docs: DOC-2086: Insecure Skip TLS Verify Not Applicable to VerteX
  _partials/self-hosted/_smtp.mdx
  docs/docs-content/enterprise-version/system-management/smtp.md
  docs/docs-content/vertex/system-management/smtp.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7716 docs: update release branch naming DOC-2085
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/visual-comparison.yaml
  .husky/pre-commit
  README.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7746 chore: Vale spellcheck fix
  .github/workflows/spellcheck-report.yaml
  .husky/pre-commit
  Makefile
  vale-spellcheck-ignore.txt
Labels: notify-slack

#7751 chore(ci): updated ./husky/pre-commit script from sh to bash
  .husky/pre-commit
  Makefile
  scripts/check_branch_name.sh
  scripts/sanitize-ignore-file.sh
Labels: CI/CD, auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7750 PEM-7798: auto cluster role bindings
  .husky/pre-commit
  Makefile
  docs/docs-content/clusters/cluster-management/platform-settings/cluster-auto-rbac.md
  docs/docs-content/clusters/cluster-management/platform-settings/cluster-auto-remediation.md
  docs/docs-content/clusters/cluster-management/platform-settings/platform-settings.md
  scripts/check_branch_name.sh
  scripts/sanitize-ignore-file.sh
  static/assets/docs/images/clusters_management-platform_settings-autorbac_binding_audit_logs.webp
Labels: backport-version-4-7, notify-slack, 4.7.a

#7755 docs: Add fs parameter requirement and example value
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7749 docs: add AI pack type DOC-2065
  docs/docs-content/integrations/maintenance-policy.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/pack-constraints.md
  src/components/IconMapper/IconMapper.tsx
  src/constants/packs.ts
  static/assets/packs/ai_layer.svg
Labels: notify-slack, 4.7.a

#7767 docs: Fix broken URLs found on 11th August 2025
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/devx/services/service-listings/redis-db.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7

#7764 docs: add documentation about api spec files to readme
  README.md
Labels: notify-slack

#7780 docs: add consoleBaseAddress guide PEM-8211 PEM-8232
  docs/docs-content/vm-management/configure-console-base-address.md
  docs/docs-content/vm-management/create-manage-vm/_category_.json
  docs/docs-content/vm-management/rbac/_category_.json
  docs/docs-content/vm-management/vm-migration-assistant/_category_.json
  static/assets/docs/images/vm-management_configure-console-base-address_connect-button.webp
Labels: notify-slack, 4.7.a

#7782 (docs-rel-4-7-a) PEM-7965: Documenting GPU quotas
  docs/docs-content/clusters/cluster-management/namespace-management.md
  docs/docs-content/workspace/workspace-mgmt/resource-mgmt.md
  static/assets/docs/images/clusters_cluster-management_namespace-create-new_4-7.webp
  static/assets/docs/images/clusters_cluster-management_namespace-create_4-7.webp
  static/assets/docs/images/clusters_cluster-management_ns-resource-quota_4-7.webp
  static/assets/docs/images/workspace-management_resource-management_4-7.webp
  static/assets/docs/images/workspace-management_workspace-over-quota_4-7.webp
  static/assets/docs/images/workspace-management_workspace-quota_4-7.webp
  static/assets/docs/images/workspace-management_workspace-within-quota_4-7.webp
Labels: notify-slack, 4.7.a

#7798 docs: add known issue PE-7313
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge/edge.md
Labels: notify-slack

#7801 docs: fix default drive selection for Management Appliance
  _partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
Labels: auto-backport, backport-version-4-7, notify-slack

#7802 Doc 2062 artifact studio enhancements
  docs/docs-content/downloads/artifact-studio.md
  static/assets/docs/images/downloads/downloads_artifact-studio-browse-packs-4-7-a.webp
  static/assets/docs/images/downloads/downloads_artifact-studio-build-bundle-4-7-a.webp
  static/assets/docs/images/downloads/downloads_artifact-studio-individual-packs-download-4-7-a.webp
  static/assets/docs/images/downloads/downloads_artifact-studio-search-and-filter-4-7-a.webp
Labels: notify-slack, 4.7.a

#7791 docs: DOC-2094: Remove Obsolete Self-Hosted k8s Airgap Image
  _partials/self-hosted/upgrade/_airgap-binary-execution.mdx
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7804 DOC-2024 - Management Appliance Upgrade Steps
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
  _partials/self-hosted/management-appliance/_upgrade-palette-prereqs.mdx
  _partials/self-hosted/management-appliance/_upgrade-palette-validate.mdx
  _partials/self-hosted/management-appliance/_upload-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-packs-validate.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-validate.mdx
  docs/docs-content/enterprise-version/install-palette/palette-management-appliance.md
  docs/docs-content/enterprise-version/upgrade/palette-management-appliance.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/install-palette-vertex/vertex-management-appliance.md
  docs/docs-content/vertex/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/vertex-management-appliance.md
  static/assets/docs/images/enterprise-version_install-palette_palette-management-appliance_palette-tenant-version.webp
Labels: notify-slack, 4.7.a

#7821 PCP-4774 - Additional examples for EKS node customization
  docs/docs-content/integrations/kubernetes-eks.mdx
Labels: notify-slack, 4.7.a

#7830 docs: Security Advisory 3: Self-Deleting Nodes with OwnerReference
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7766 docs: Add information about registryMappingRules usage by Registry Connect
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: auto-backport, backport-version-4-6, backport-version-4-7, notify-slack

#7818 docs: Add Cilium annotations known issue
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/release-notes/known-issues.md
Labels: notify-slack, 4.7.a

#7823 DOC-2098 - Karpenter Support Limitations
  docs/docs-content/clusters/public-cloud/aws/architecture.md
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.a

#7840 docs: PE-7335: Primary Registry Required for Local Multi-Node Edge Clusters
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-primary-registry.md
Labels: auto-backport, backport-version-4-6, backport-version-4-7, notify-slack

#7844 doc-2102: updated Operating Systems section to Ubuntu 22.04
  docs/docs-content/security/product-architecture/platform-security.md
Labels: documentation, backport-version-4-7, notify-slack

#7841 docs: DOC-2102: Remove NIC and vip_interface Requirements for Network Overlay Clusters
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/release-notes/known-issues.md
Labels: notify-slack, 4.7.a

#7846 docs: DOC-2093: Updating Incorrect VMO Initialism
  docs/docs-content/clusters/edge/hardware-requirements.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7878 docs: DOC-1926: 4.7.a Additional Airgap Cluster Profile Packs
  _partials/self-hosted/_airgap-cluster-profile-packs.mdx
  _partials/vertex/_airgap-cluster-profile-packs.mdx
Labels: auto-backport, backport-version-4-7, notify-slack

#7868 docs: DOC-2107: 4.7.15 Release Notes
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7875 DOC-2124 - Management Appliance - Palette CLI only for uploading bundles to external registries
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
  _partials/self-hosted/management-appliance/_upgrade-palette-prereqs.mdx
  _partials/self-hosted/management-appliance/_upload-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-packs-prereqs.mdx
  _partials/self-hosted/management-appliance/_upload-packs-validate.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-prereqs.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-validate.mdx
Labels: auto-backport, backport-version-4-7, notify-slack

#7891 doc-2125: adding links to Palette/VerteX appliances upload sections
  docs/docs-content/downloads/artifact-studio.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7890 DOC-2130 - Pause image deletion steps for VerteX Management Appliance upgrade
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
  docs/docs-content/vertex/upgrade/vertex-management-appliance.md
  static/assets/docs/images/enterprise-version_upgrade_palette-management-appliance_content-sync-error_4.7.3.webp
Labels: auto-backport, backport-version-4-7, notify-slack

#7887 docs: DOC-2107: Release Notes 4.7.15 - Terraform Addition
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7896 docs: August 25, 2025: URL Fixes
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
  docs/docs-content/byoos/image-builder/build-image-vmware/konvoy.md
  docs/docs-content/byoos/image-builder/build-image-vmware/rhel-pxk.md
  linkinator/linkinator-rate-limit-ci.config.json
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7910 DOC-2137 - Troubleshooting steps for stalled VerteX Management Appliance upgrade due to stuck Linstor satellite pods
  docs/docs-content/troubleshooting/enterprise-install.md
  docs/docs-content/vertex/upgrade/vertex-management-appliance.md
Labels: auto-backport, backport-version-4-7, notify-slack

#7916 docs: update secure boot warning on management appliance
  _partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
Labels: auto-backport, backport-version-4-7, notify-slack
