Repository spectrocloud/librarium, pull requests merged in 2025-06, with the labels that each got.

#7025 docs: fix typo in image
  docs/docs-content/architecture/networking-ports.md
  static/assets/docs/images/architecture_networking-ports_on_prem_network-diagram-grpc-new.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#7055 docs: patch release notes DOC-1951
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7081 docs: add patch release notes DOC-1960
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7080 docs: add TLS known issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#7086 docs: add instructions about ipxe provisioning
  docs/docs-content/clusters/edge/site-deployment/virtual-deployment/ipxe-boot.md
  docs/docs-content/clusters/edge/site-deployment/virtual-deployment/vm-edge-host.md
Labels: auto-backport, backport-version-4-6

#7091 docs: use k8s version arg and use the right canvos tag
  _partials/_canvos-version.mdx
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/signed-content.md
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-iso.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: auto-backport, backport-version-4-6

#7116 docs: Remove Shared Storage requirement from EC install
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#7083 docs: patch release notes DOC-1959
  _partials/_azure-cloud-account-setup.mdx
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7128 Revert "docs: patch release notes DOC-1959"
  _partials/_azure-cloud-account-setup.mdx
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7146 docs: fix spelling errors
  docs/docs-content/clusters/edge/site-deployment/virtual-deployment/ipxe-boot.md
  docs/docs-content/release-notes/release-notes.md
  vale-spellcheck-ignore.txt
Labels: auto-backport, backport-version-4-6

#7054 Doc 1688 tutorial cluster profiles
  README.md
  _partials/getting-started/_getting-started_deploy-cluster-tf_setup-local-environment.mdx
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/tutorials/cluster-management/update-maintain/cluster-profile-variables.md
  static/assets/docs/images/architecture_networking-ports_on_prem_network-diagram-grpc-new.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-add-variable-and-confirm-update.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-addon-deployment-update.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-create-variable.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-default-port-wordpress.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-default-wp-deploy.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-default-wp-port.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-download-kubeconfig-tf.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-download-kubeconfig.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-hello-universe-1-variable.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-http-port.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-inuse.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-replicacount.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-update-variables.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-validate-namespace.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-validate-overview-tf.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-validate-overview.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-validate-replica.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-variable-clipboard.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-variable-layer-inuse.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-variable-replica.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-variables/clusters_cluster-management_deploy-cluster-profile-variables-wordpress-default-page.webp
Labels: do-not-merge/work-in-progress, tutorial

#7181 [version-4-3] docs: apply suggestions from joi (#7176)
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2

#7175 docs: Specify that site user data ISO is not bootable
  docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#7190 doc-1988:initial draft; images to be added
  docs/docs-content/clusters/cluster-management/kubernetes-dashboard.md
  docs/docs-content/integrations/spectro-k8s-dashboard.mdx
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_add-role-binding.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_apply-profile.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_connect.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_select-dashboard-pack.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_select-kubernetes-pack.webp
Labels: documentation, auto-backport, backport-version-4-6

#7177 PCP-4711 Add IRSA constraint on EKS
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/troubleshooting/cluster-deployment.md
Labels: auto-backport, backport-version-4-6

#7193 docs: fix broken link
  docs/docs-content/clusters/cluster-management/kubernetes-dashboard.md
Labels: auto-backport, backport-version-4-6

#7156 docs: patch release notes DOC-1963
  _partials/_palette-kubernetes-versions.mdx
  _partials/self-hosted/_palette-vmware-kubernetes-versions.mdx
  _partials/vertex/_palette-vmware-kubernetes-versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/clusters/edge/cluster-management/skip-draining.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/deployment-modes/agent-mode/manage-agent/os-upgrades.md
  docs/docs-content/downloads/cli-tools.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7202 docs: DOC-1994: Adding Removed 4.6.40 Bug Fixes to 4.6.41
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#7210 docs: Resolve the Palette Optimized Canonical known issue
  docs/docs-content/clusters/edge/architecture/architecture.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge/edge.md
Labels: 4.7.0

#7230 docs: DOC-1990: Verified VM Migration Assistant Migration Combinations
  docs/docs-content/vm-management/vm-migration-assistant/create-migration-plans.md
  docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
  docs/docs-content/vm-management/vm-migration-assistant/start-migration-plans.md
  docs/docs-content/vm-management/vm-migration-assistant/vm-migration-assistant.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6
