Repository spectrocloud/librarium, pull requests merged in 2025-04, with the labels that each got.

#6275 doc: update to virtual clusters headings
  docs/docs-content/clusters/palette-virtual-clusters/palette-virtual-clusters.md
  docs/docs-content/devx/palette-virtual-clusters/palette-virtual-clusters.md
Labels: 4.6.b

#6286 docs: Version 4.6: Updated Release Notes + Security Advisory for 4.4 Nginx Patch
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-6

#6291 docs: add cross links for application proxy settings
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6295 docs: DOC-1745: Zarf OCI Registry Cleanup
  docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-zarf.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6296 docs: DOC-1789: Updating Stylus tagsFromFile and tagsFromScript Parameters
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6290 docs: DOC-1765: Removing Libvirt References
  docs/deprecated/integrations/generic-vm-libvirt.mdx
  docs/deprecated/integrations/ubuntu-libvirt.mdx
  docs/docs-content/clusters/imported-clusters/migrate-full-permissions.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  docs/docs-content/integrations/generic-vm-vsphere.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  redirects.js
  src/components/PacksTable/PacksTable.tsx
  static/packs-data/exclude_packs.json
  static/packs-data/packs_information.json
Labels: 4.6.b

#6314 docs: add TF provider release DOC-1804
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6323 docs: update the edge CLI version DOC-1801
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6313 docs: add warning for non editable labels on existing nodes
  docs/docs-content/clusters/cluster-management/node-labels.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6334 docs: exclude GTM and FullStory from being loaded locally DOC-1807
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6308 docs: DOC-1762: Single Quote Requirement in Cluster Profile Variables
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/delete-cluster-profile-variables.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/modify-cluster-profile-variables.md
  static/assets/docs/images/profiles_create-cluster-profiles_define-profile-variables_add-vars-to-yaml.webp
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6322 doc: update Edge installer reference tables with Type and Default values
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6276 Release Note for vCluster breaking change and announcement
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.b

#6368 docs: Nginix 4-8-25 Updates (Version 4.6)
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-6

#6375 docs: DOC-1811: Overlay PXK-E Support + Style Guide Adjustments
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6373 docs: change agent mode airgap install steps
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6416 doc: update VM CPU and Memory modal guidance
  docs/docs-content/vm-management/create-manage-vm/enable-cpu-hotplug.md
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_config-box.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_configuration.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_details.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_flavor_box.webp
  static/assets/docs/images/vm-management_create-manage-vm_enable-cpu-hotplug_vm-yaml-editor.webp
Labels: 4.6.b

#6420 docs: fix cd path
  docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md
  docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6428 docs: upload edge api file
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: api-format

#6010 docs: PE-6162 new CLI content command
  .gitleaksignore
  docs/deprecated/clusters/edge/edgeforge-workflow/build-artifacts.md
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/content.md
  docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
Labels: 4.6.b

#6431 doc: Microsoft Entra ID OIDC API permissions
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-25_def_project_admin.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-ba_tenantadmin.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-groupsclaim.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-palette-registration.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6391 docs: expand update a cluster DOC-1780
  docs/docs-content/clusters/cluster-management/cluster-updates.md
  static/assets/docs/images/clusters_management_updates_kubeconfig-download.webp
  static/assets/docs/images/clusters_management_updates_kubectl-api-hellouniverse-removed.webp
  static/assets/docs/images/clusters_management_updates_kubectl-api-hellouniverse.webp
  static/assets/docs/images/clusters_management_updates_kubectl-noapi-hellouniverse.webp
  static/assets/docs/images/clusters_management_updates_palette-api-hellouniverse.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6447 doc: fix indentation on Install Agent Host
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6418 docs: block ai bots in robots.txt DOC-1823
  scripts/ai_robots.txt
  scripts/generate_robots.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6459 docs: DOC-1762: Double Quote Cluster Profile Variable Exception
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6001 docs: BYOR
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edge-native-lifecycle.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-custom-registries.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-primary-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-private-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/migrate-edge-native-config.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
  static/assets/docs/images/clusters_edge_registries_primary-registry.webp
Labels: 4.6.b

#6469 docs: known issue PE-6530
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.b

#6470 docs: update supplemental packs pages DOC-1795
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
Labels: 4.6.b

#6377 Doc 1242 cp update
  docs/deprecated/clusters/public-cloud/deploy-k8s-cluster.md
  docs/deprecated/integrations/aws-cluster-autoscaler.md
  docs/deprecated/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md
  docs/deprecated/tutorials/cluster-management/update-maintain/tag-filter-clusters.md
  docs/deprecated/tutorials/cluster-management/update-maintain/update-k8s-cluster.md
  docs/docs-content/audit-logs/monitor-with-datadog.md
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/byoos/image-builder/build-image.md
  docs/docs-content/clusters/cluster-management/image-swap.md
  docs/docs-content/clusters/cluster-management/node-labels.md
  docs/docs-content/clusters/cluster-management/ssh/ssh-keys.md
  docs/docs-content/clusters/cluster-management/ssh/ssh-usernames.md
  docs/docs-content/clusters/cluster-management/taints.md
  docs/docs-content/clusters/data-center/nutanix/nutanix.md
  docs/docs-content/clusters/public-cloud/aws/aws.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/azure.md
  docs/docs-content/clusters/public-cloud/gcp/gcp.md
  docs/docs-content/clusters/public-cloud/public-cloud.md
  docs/docs-content/integrations/aws-cluster-autoscaler.mdx
  docs/docs-content/kubernetes-knowlege-hub/tutorials/deploy-stateless-frontend-app.md
  docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md
  docs/docs-content/tutorials/public-cloud/_category_.json
  docs/docs-content/tutorials/tutorials.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/create-disk-templates.md
  docs/docs-content/vm-management/create-vmo-profile.md
  docs/docs-content/vm-management/rbac/configure_OIDC.md
  redirects.js
  static/assets/docs/images/migrate-vm-kubevirt-guide/clusters_cluster-management_deploy-cluster-profile-updates_profile-override.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_add-kube-cost-pack-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_confirm-new-pack-version-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_create-new-profile-version-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_deployed-FE-cluster.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_deployed-profile-version.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_download-kube-config.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_hello-universe-without-api.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_kubcost-pack-details-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_kubecost-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_pending-update-clusters-view.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_profile-add-new-pack-ui.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_profile-override.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_profile-version-selection.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_reivew-updates-dialog.webp
  static/assets/docs/images/tutorials/deploy-cluster-profile-updates/clusters_cluster-management_deploy-cluster-profile-updates_updates-available-button-cluster-overview.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6473 docs: DOC-1790: 4.6.b OS Licenses
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: 4.6.b

#6417 docs: release notes 4.6.b DOC-1791 DOC-1794
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.b

#6479 docs: DOC-1832: Update cert-manager Version to 1.17
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/system-management/registry-override.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
Labels: 4.6.b

#6486 docs: DOC-1833: externalRegistries and registryMappingRules user-data Indentation
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6482 docs: PE-6539
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/migrate-edge-native-config.md
Labels: 4.6.b

#6494 docs: add SBOM known issue PCP-4370
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.b

#6458 docs: make release updates across the various pages DOC-1792
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/component.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
Labels: 4.6.b

#6495 docs: add upgrade paths DOC-1793
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.6.b

#6497 docs: add bug fixes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6499 docs: fix arrow angle
  static/assets/docs/images/clusters_edge_registries_primary-registry.webp
Labels: auto-backport, backport-version-4-6

#6502 docs: Add fields to Edge Installer Configuration Reference.
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6507 Add vip.skip parameter and update references to its documentation
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-edge-hosts.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6513 doc: adjust prettier-ignore to fix EKS header formatting
  docs/docs-content/clusters/public-cloud/aws/eks.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6501 docs: PCP-4359: CAPI Core Version Upgrade
  docs/docs-content/clusters/data-center/nutanix/register-nutanix-cloud.md
Labels: auto-backport, backport-version-4-6

#6529 docs: netmask specification
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6534 docs: DOC-1840: Additional Bug Fixes for 4.6.b Release Notes
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6538 docs: fix node labels modification limitation
  docs/docs-content/clusters/cluster-management/node-labels.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6547 docs: add extra information about Ubuntu Pro DOC-1843
  docs/docs-content/vertex/fips/fips-compliant-components.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6562 docs: DOC-1856: Correcting Earthly Script Command (FIPS)
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6573 docs: add missing backtick DOC-1749
  docs/docs-content/registries-and-packs/add-custom-packs.md
Labels: auto-backport, backport-version-4-6

#6561 docs: DOC-1859: Updating Security Development Lifecycle Graphic
  static/assets/docs/images/security_dev_lifecycle.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6593 doc: Additional IAM Permissions for GCP due to CAPG upgrade
  docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6595 Fix warning and formatting
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6603 docs: add consent screen
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6166 docs: add os advisories
  .gitignore
  Makefile
  docs/docs-content/security-bulletins/os-k8s/os-k8s.mdx
  package.json
  src/components/OsCveTable/OsCveTable.module.scss
  src/components/OsCveTable/OsCveTable.test.tsx
  src/components/OsCveTable/OsCveTable.tsx
  src/components/OsCveTable/__mocks__/@docusaurus/theme-common.ts
  src/components/OsCveTable/__mocks__/@theme/Admonition.tsx
  src/css/table.scss
  src/theme/MDXComponents/MDXComponents.ts
  utils/cves/index.js
  utils/helpers/cveHelpers.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6
