Repository spectrocloud/librarium, pull requests merged in 2025-02, with the labels that each got.

#5623 Document workaround for enabling Cilium pack with EKS clusters
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/troubleshooting/pack-issues.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5622 docs: release notes patch 4.5.21
  docs/docs-content/component.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
Labels: auto-backport, backport-version-4-5

#5631 docs: correct cilium parameter description
  docs/docs-content/troubleshooting/pack-issues.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5633 docs: add oci recommendation
  docs/docs-content/tutorials/profiles/deploy-pack.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5669 docs: add extra sentence, fix command
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5682 docs: DOC-1664: Removing Erroneous "EOF" from .arg File
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5661 docs: EKS cluster and EKS hybrid requirements
  docs/docs-content/clusters/public-cloud/aws/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
Labels: auto-backport, backport-version-4-5

#5683 docs: adjust release note to include control plane resize operations
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5689 docs: minor EKS description change
  docs/docs-content/clusters/public-cloud/aws/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
Labels: auto-backport, backport-version-4-5

#5647 docs: add os upgrades guide DOC-1533
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/deployment-modes/agent-mode/manage-agent/os-upgrades.md
Labels: auto-backport, backport-version-4-5

#5704 docs: Appliance Mode step for hybrid pool creation
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
Labels: auto-backport, backport-version-4-5

#5693 docs: update the release preview workflow to more specific branch matching
  .github/workflows/release-preview.yaml
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5707 docs: Ingress TLS configuration for VM Migration Assistant
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
Labels: 4.6

#5720 docs: add notes for patch 4.5.22 DOC-1692
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5598 Update webhook-disable.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#5722 docs: update 4.5.21 upgrade paths and helm paths
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: auto-backport, backport-version-4-5

#5726 docs: DOC-1634: Calico Memory Leak and Palette Workload Clusters
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5725 docs: DOC-1673: Update Open Source Licenses
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: 4.6

#5728 docs: PLT-1601: EC --validate Works in Airgap
  docs/docs-content/automation/palette-cli/commands/ec.md
Labels: auto-backport, backport-version-4-5

#5595 Two node
  docs/docs-content/clusters/edge/architecture/architecture.md
  docs/docs-content/clusters/edge/architecture/two-node.md
  docs/docs-content/clusters/edge/cluster-management/replace-failed-node.md
  docs/docs-content/clusters/edge/edge.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
  docs/docs-content/deployment-modes/appliance-mode.md
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
  static/assets/docs/images/clusters_edge_architecture_two-node-diagram.webp
  static/assets/docs/images/clusters_edge_architecture_two-node-failover.webp
  static/assets/docs/images/clusters_edge_architecture_two-node-split.webp
  static/assets/docs/images/clusters_edge_architecture_two-node-upgrade.webp
Labels: 4.6

#5734 docs: update kubernetes requirement page
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/enterprise-version/install-palette/install-palette.md
  docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
Labels: auto-backport, backport-version-4-5

#5692 docs: add release notes DOC-1663
  docs/docs-content/release-notes/annoucements.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6

#5733 docs: PEM-7013: Known Issue re: VMO Namespace Permission
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5752 docs: DOC-1658: Harbor Edge Native Resource Quotas
  docs/docs-content/integrations/harbor-edge-native-config.md
Labels: auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5731 EKS Hybrid documentation improvements (4.6.0)
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/_category_.json
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-edge-hosts.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-eks-cluster.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-environment.md
Labels: 4.6

#5719 docs: update palette cli and spectro cli
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/component.md
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
Labels: 4.6

#5758 docs: update upgrade path
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/component.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.6

#5759 docs: fix broken link to Getting Started
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables.md
Labels: auto-backport, backport-version-4-6

#5761 docs: fix broken MAAS doc links
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5769 docs: fix some steps in prepare EKS cluster
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-eks-cluster.md
Labels: auto-backport, backport-version-4-6

#5774 docs: known cert issue for two-node edge clusters
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#5775 docs: adjust release notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#5778 docs: move active issue to resolved DOC-1696
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#5781 docs: remove vmo pack from exclusion list
  static/packs-data/exclude_packs.json
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5735 docs: add harbor limitation for arm
  docs/docs-content/clusters/edge/architecture/two-node.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, 4.6

#5791 docs: update pcg k8s requirements table
  docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
  docs/docs-content/clusters/pcg/pcg.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#5794 docs: add patch 4.6.7 release notes DOC-1697
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#5805 Update generate-keys.md
  docs/docs-content/clusters/edge/trusted-boot/keys/generate-keys.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5772 docs: restyle the site according to new brand DOC-1587
  docusaurus.config.js
  sidebars.js
  src/components/CustomTable/CustomTable.module.scss
  src/components/CveReportsTable/CveReportsTable.tsx
  src/components/PacksReadme/PacksReadme.antd.css
  src/components/PacksReadme/PacksReadme.module.scss
  src/components/PointOfInterest/PointOfInterest.module.scss
  src/components/PointOfInterest/PointOfInterest.tsx
  src/components/SimpleCardGrid/SimpleCardGrid.module.scss
  src/components/Technologies/CategorySelector/CustomLabel.module.scss
  src/components/Technologies/CategorySelector/filterSelect.antd.css
  src/components/Technologies/Technologies.module.scss
  src/components/Technologies/TechnologyCard.tsx
  src/components/Technologies/technologies.antd.css
  src/components/Tooltip/Tooltip.tsx
  src/css/custom.scss
  src/css/dark-mode.scss
  src/css/font.scss
  src/css/light-mode.scss
  src/theme/DocCard/index.js
  static/fonts/PlusJakartaSans-Bold.ttf
  static/fonts/PlusJakartaSans-Light.ttf
  static/fonts/PlusJakartaSans-Medium.ttf
  static/fonts/PlusJakartaSans-Regular.ttf
  static/fonts/PlusJakartaSans-SemiBold.ttf
  static/fonts/Poppins-300.woff2
  static/fonts/Poppins-400.woff2
  static/fonts/Poppins-500.woff2
  static/fonts/Poppins-600.woff2
  static/fonts/Poppins-700.woff2
  static/img/favicon.png
  static/img/spectro-cloud-social-card.png
  static/img/spectrocloud-logo-dark.svg
  static/img/spectrocloud-logo-light.svg
  static/img/spectrocloud-social-card.png
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5832 chore: update cve filter
  utils/cves/index.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5736 docs: add private registry for PXKE
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5852 docs: fix newly broken MAAS doc links
  docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5806 docs: PEM-7032: Reclassifying the "Deleted" Filter as a Status
  docs/docs-content/clusters/cluster-management/cluster-map-filters.md
  docs/docs-content/clusters/clusters.md
Labels: 4.6.a

#4858 chore: add kapa branch
  .eslintignore
  .eslintrc.js
  .prettierignore
  docs/docs-content/release-notes/release-notes.md
  docusaurus.config.js
  static/img/spectrocloud-mark-light-bkgd-RGB.svg
  static/scripts/kapa-shortcut.js
  static/scripts/kapa-widget.bundle.js
  tsconfig.json
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5870 docs: add pxk-e non support
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#5878 docs: add edge upgrade a/b partition behavior
  docs/docs-content/clusters/edge/cluster-management/upgrade-behavior.md
  static/assets/docs/images/clusters_edge_cluster-management_upgrade-diagram.webp
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5883 docs: Removing known issue from PEM-6961
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.a

#5873 docs: parameterise release related file changes DOC-1651
  .prettierignore
  Makefile
  README.md
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/component.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/spectro-downloads.md
  scripts/release/generate-advanced-configuration.sh
  scripts/release/generate-compatibility-matrix.sh
  scripts/release/generate-downloads.sh
  scripts/release/generate-install-palette-cli.sh
  scripts/release/generate-kubernetes-palette-versions.sh
  scripts/release/generate-pcg-kubernetes-versions.sh
  scripts/release/generate-release-notes.sh
  scripts/release/generate-spectro-cli-reference.sh
  scripts/release/templates/compatibility-cli.md
  scripts/release/templates/compatibility-edge-cli.md
  scripts/release/templates/edge-cli.md
  scripts/release/templates/kubernetes-max-version.md
  scripts/release/templates/palette-cli-install-version.md
  scripts/release/templates/palette-cli.md
  scripts/release/templates/pcg-kubernetes-version.md
  scripts/release/templates/registry-reference-end.md
  scripts/release/templates/registry-reference-mid.md
  scripts/release/templates/release-notes-heading.md
  scripts/release/templates/release-notes.md
  scripts/release/templates/spectro-cli-install-linux.md
  scripts/release/templates/spectro-cli-install-osx.md
  scripts/release/templates/spectro-cli-install-version.md
  scripts/release/templates/vmware-kubernetes-version.md
  scripts/release/utilities.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5884 2-26-25 security-content-updates
  docs/docs-content/legal-licenses/compliance.md
  docs/docs-content/security/lifecycle/lifecycle.md
  docs/docs-content/security/lifecycle/secure-development.md
  docs/docs-content/security/security.md
  redirects.js
  static/assets/docs/images/docs_compliance_compliance_jpc-logo.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5885 docs: add release notes for patch 4.6.8
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#5901 docs: PE-6155: Resolved Known Issue re: Disconnected Edge Clusters and PKI Certificate Renewal
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.a

#5903 docs: fix admonition in prepare edge hosts
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-edge-hosts.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#5876 chore: add quick keyboard shortcut to open kapa
  .prettierignore
  docs/docs-content/release-notes/release-notes.md
  docusaurus.config.js
  static/scripts/kapa-shortcut.js
  static/scripts/kapa-widget.bundle.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6
