Repository spectrocloud/librarium, pull requests merged in 2025-09, with the labels that each got.

#7930 doc-2200: Appzi PR for Over-Commit Resources to Enhance VM Perf for memory
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/vm-oversubscription.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7952 docs: Add Edge breaking changes to release notes
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.b

#7953 Update S3 permissions list for EC backup
  docs/docs-content/enterprise-version/system-management/backup-restore.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7

#7978 docs: remove spectrocloud_macro TF resource PLT-1944
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.b

#7979 Provide kernel version details for PXK-E known issue
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge/edge.md
Labels: backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#7987 docs: Add regular TLS certificate example for Management Appliance
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-enablement.mdx
Labels: auto-backport, backport-version-4-7, notify-slack

#8001 docs: Fix user data header and indentation
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8010 docs: DOC-2202 + DOC-2214: Known Issues PE-7114 and PEM-8524
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8060 docs: add more developer portals and update redirected links DOC-2248
  docs/deprecated/integrations/external-secrets-operator.md
  docs/deprecated/integrations/vault.md
  docs/docs-content/automation/automation.md
  docs/docs-content/automation/terraform/terraform.md
  docs/docs-content/devx/services/service-listings/vault.md
  docs/docs-content/integrations/external-secrets-operator.mdx
  linkinator/linkinator-ci.config.json
  linkinator/linkinator-rate-limit-ci.config.json
  linkinator/linkinator-rate-limit.config.json
  linkinator/linkinator.config.json
  scripts/url-checker-developer-portals.sh
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8067 docs: add VMO additional details PEM-8088
  docs/docs-content/integrations/virtual-machine-orchestrator.mdx
  docs/docs-content/vm-management/create-manage-vm/create-manage-vm.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8076 docs: PLT-1948: Palette CLI Breaking Change
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.b

#8068 doc-2247: known issue EC2 cluster with imdv2 required
  docs/docs-content/release-notes/known-issues.md
  src/components/IconMapper/dynamicFontAwesomeImports.ts
Labels: auto-backport, backport-version-4-7, notify-slack

#8075 docs: add Zot password warning DOC-2213
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
Labels: notify-slack, 4.7.b

#8103 docs: PLT-1948: Palette CLI Breaking Change Updates (Ubuntu Pro)
  _partials/palette-cli/credentials-breaking-change.mdx
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/automation.md
Labels: notify-slack, 4.7.b

#8110 docs: Palette CLI --ubuntu-pro-token Flag
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/login.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/troubleshooting/automation.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7

#8039 docs: DOC-2135: Crossplane v2 Support
  _partials/crossplane/_cluster-profile-existing.mdx
  _partials/crossplane/_install-crossplane.mdx
  _partials/crossplane/_palette-crossplane-provider-version.mdx
  _partials/crossplane/_provider-palette-created.mdx
  _partials/crossplane/_provider-palette-yaml.mdx
  _partials/crossplane/_secret-cloud-yaml.mdx
  docs/docs-content/automation/crossplane/crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
Labels: notify-slack, 4.7.b

#8129 docs: Add Cilium agent mode Edge configuration
  docs/docs-content/integrations/cni-cilium-oss.mdx
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8130 docs: Add Cilium agent mode Edge configuration to release notes
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.b

#8128 docs: Document Calico version that fixes Edge compatibility issue
  docs/docs-content/integrations/cni-calico.mdx
  docs/docs-content/release-notes/release-notes.md
Labels: notify-slack, 4.7.b

#8160 docs: update configurations for new certificate DOC-2253
  docs/docs-content/legal-licenses/compliance.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8171 doc-2257: fix typo on edge arch page
  docs/docs-content/clusters/edge/architecture/architecture.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8020 docs: release notes for 4.7.b DOC-2109
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  static/packs-data/packs_information.json
Labels: notify-slack, 4.7.b

#8190 docs: DOC-2108: 4.7.b OS Licenses
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: notify-slack, 4.7.b

#8188 docs: DOC-2112: Airgap Binaries + OVAs
  _partials/self-hosted/_airgap-additional-ovas.mdx
  _partials/self-hosted/_airgap-cluster-profile-packs.mdx
  _partials/vertex/_airgap-additional-ovas.mdx
  _partials/vertex/_airgap-cluster-profile-packs.mdx
Labels: do-not-merge/work-in-progress, 4.7.b

#8191 docs: update paths DOC-2111
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.7.b

#8197 docs: add VMO cluster profile variables bug fix DOC-2217
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8196 docs: DOC-2258: Edge Host NVIDIA GPU nvidia-sim Prerequisite
  docs/docs-content/clusters/edge/site-deployment/edge-host-view.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8222 DOC-2251 - Unset AMI ID can cause cluster repaves for EKS
  docs/docs-content/clusters/public-cloud/aws/eks.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8226 docs: DOC-2267: Update Vertex Management Appliance Ubuntu Version
  docs/docs-content/vertex/install-palette-vertex/vertex-management-appliance.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8251 docs: DOC-2264: CAPI Airgap rpmrepo Clarification
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
Labels: auto-backport, backport-version-4-6, backport-version-4-7, notify-slack

#8250 docs: update usercentrics to Seers DOC-2262
  .github/workflows/nightly-docker-build.yaml
  .github/workflows/post_release.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  .github/workflows/visual-comparison.yaml
  docusaurus.config.js
  sidebars.js
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack, backport-version-4-1, backport-version-4-0, backport-version-3-4

#8230 docs: component updates week 39 DOC-2260 PAC-3230
  _partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
  _partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
  _partials/self-hosted/management-appliance/_upgrade-palette-prereqs.mdx
  _partials/self-hosted/management-appliance/_upload-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-packs-prereqs.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-enablement.mdx
  _partials/self-hosted/management-appliance/_upload-third-party-packs-prereqs.mdx
  docs/docs-content/downloads/artifact-studio.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8266 docs: DOC-2275: Updating Palette CLI and Agent Versions
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/deployment-modes/agent-mode/architecture.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8229 doc-2133: redoing MAAS LXD adjustments
  docs/docs-content/clusters/data-center/maas/architecture.md
  docs/docs-content/clusters/data-center/maas/create-manage-maas-lxd-clusters.md
  docs/docs-content/clusters/pcg/manage-pcg/create-manage-node-pool.md
  static/assets/docs/images/clusters_data-center_maas_arch-diagram-maas-lxd_mk.webp
  static/assets/docs/images/clusters_data-center_maas_arch-diagram-new-4-7-b.webp
  static/assets/docs/images/clusters_data-center_maas_profile-lxd-4-7-b.webp
  static/assets/docs/images/clusters_data-center_maas_profile-lxd-cloud-config_4-7-b.webp
  static/assets/docs/images/clusters_data-center_maas_profile-lxd-worker-4-7-b.webp
Labels: auto-backport, backport-version-4-7, notify-slack

#8228 docs: release notes for patch 4.7.21 DOC-2261 DOC-2273
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-7, notify-slack

#8264 docs: remove onclick and fix visual screenshots DOC-2262
  sidebars.js
  visuals/screenshot.css
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack, backport-version-4-1, backport-version-4-0, backport-version-3-4

#8252 docs: DOC-2196: Namespace Regex Rules + Cluster Profile Refactor
  _partials/profiles/_add-on-existing-intro.mdx
  _partials/profiles/_add-on-namespace.mdx
  _partials/profiles/_create-profile-enablement.mdx
  _partials/profiles/_create-profile-next-steps.mdx
  _partials/profiles/_create-profile-prerequisites.mdx
  docs/docs-content/clusters/public-cloud/azure/windows.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-addon-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-helm-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-manifest-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-pack-addon.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-full-profile.md
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-infrastructure-profile.md
  docs/docs-content/profiles/profile-customization.md
Labels: do-not-merge/work-in-progress, auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8268 DOC-2272: update azure disk encryption page
  docs/docs-content/clusters/public-cloud/azure/azure-disk-storage-sse.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  redirects.js
Labels: auto-backport, backport-version-4-5, backport-version-4-6, backport-version-4-7, notify-slack

#8300 docs: update ISO 27001 certification on compliance page DOC-2280
  docs/docs-content/legal-licenses/compliance.md
  static/assets/docs/images/legal-licenses_compliance_iso-27001.webp
Labels: auto-backport, backport-version-4-7, notify-slack
