Repository spectrocloud/librarium, pull requests merged in 2025-01, with the labels that each got.

#5200 docs: change pack information for Portworx DOC-1521
  static/packs-data/packs_information.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5209 [version-4-5] chore: bump typescript from 5.3.3 to 5.7.2 (#5194)
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4

#5220 Fix sample shell commands
  docs/api-content/api-docs/2-samples.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5228 docs: fix librarium container
  .dockerignore
  .prettierignore
  Dockerfile
  Makefile
  README.md
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5245 docs: fix broken links
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vm-management/vm-migration-assistant/create-migration-plans.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#5246 docs: update broadcom links and remove redundant prereq
  docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
Labels: auto-backport, backport-version-4-5

#5251 docs: DOC-1570
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5213 Palette CLI Encryption
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/ec.md
  docs/docs-content/automation/palette-cli/commands/import.md
  docs/docs-content/automation/palette-cli/commands/login.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/commands/pde.md
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
  docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
  docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: 4.5.c

#5250 chore: update make init command
  Makefile
  README.md
  utils/cves/requests.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5217 docs: PEM-6611: Cluster Profile Variables Updates
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
Labels: 4.5.c

#5289 docs: add note about including core content for scaleup
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
Labels: auto-backport, backport-version-4-5

#5310 docs: DOC-1574 Update palette-sso-with-entra-id.md
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5244 docs: Edge maas kch note
  docs/docs-content/introduction/resource-usage-estimation.md
  static/assets/docs/images/introduction_resource-usage_tenant-admin.webp
Labels: 4.5.c

#5100 docs: DOC-912: Add Maintenance Mode Documentation
  docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
  docs/docs-content/clusters/cluster-management/cluster-management.md
  docs/docs-content/clusters/cluster-management/compliance-scan.md
  docs/docs-content/clusters/cluster-management/maintenance-mode.md
  docs/docs-content/vm-management/architecture.md
  docs/docs-content/vm-management/create-manage-vm/migrate-vm-to-different-node.md
  static/assets/docs/images/clusters_cluster-management_maintenance_mode.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5208 docs: document image pull secrets templates
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Labels: 4.5.c

#4959 DOC-1454 - Amazon EKS Hybrid Nodes
  .gitleaksignore
  docs/docs-content/clusters/public-cloud/aws/add-aws-accounts.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/_category_.json
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/eks-hybrid-nodes.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  static/assets/docs/images/aws_eks-hybrid_architecture_eks-hybrid-architecture.webp
  static/assets/docs/images/aws_eks-hybrid_create-hybrid-node-pools_in-use-clusters.webp
  static/assets/docs/images/aws_eks-hybrid_create-hybrid-node-pools_running-hybrid-pool.webp
  static/assets/docs/images/aws_eks-hybrid_import-eks-cluster-enable-hybrid-mode_cluster-import-procedure.webp
  static/assets/docs/images/aws_eks-hybrid_import-eks-cluster-enable-hybrid-mode_enable-hybrid-mode.webp
Labels: future release, 4.5.c

#5091 DOC-887: SSH usernames
  docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
  docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
  docs/docs-content/clusters/cluster-management/ssh/_category_.json
  docs/docs-content/clusters/cluster-management/ssh/ssh-keys.md
  docs/docs-content/clusters/cluster-management/ssh/ssh-usernames.md
  docs/docs-content/clusters/cluster-management/ssh/ssh.md
  docs/docs-content/clusters/data-center/vmware/create-manage-vmware-clusters.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
  docs/docs-content/getting-started/azure/deploy-k8s-cluster.md
  docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md
  docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md
  docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5323 docs: change from provider images to edgeforge
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
Labels: 4.5.c

#5333 docs: OIDC option in VM Migration Assistant pack
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
Labels: 4.5.c

#5263 4.5.c Release Notes
  docs/docs-content/architecture/networking-ports.md
  docs/docs-content/release-notes/annoucements.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.5.c

#5336 docs: DOC-1580 deprecate Tencent cloud docs
  docs/api-content/api-docs/2-samples.md
  docs/deprecated/clusters/public-cloud/tke.md
  docs/deprecated/integrations/kubernetes-generic.md
  docs/deprecated/integrations/kubernetes-tke.md
  docs/deprecated/integrations/kubernetes.md
  docs/docs-content/clusters/public-cloud/public-cloud.md
  docs/docs-content/getting-started/introduction.md
  docs/docs-content/integrations/kubernetes-konvoy.md
  docs/docs-content/introduction/introduction.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/troubleshooting/nodes.md
  docs/docs-content/unlisted/cox-edge-eol.md
  static/assets/docs/images/tencent-diagram.webp
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5334 docs: tags filter replaces profiles & update screenshots
  docs/docs-content/clusters/cluster-management/cluster-map-filters.md
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-all-filters.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-details.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-list-view.webp
  static/assets/docs/images/clusters_cluster-management_cluster-map-filters_cluster-map-view.webp
Labels: 4.5.c

#5337 docs: improve info call out box
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
Labels: auto-backport, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5346 docs: mark EKS Hybrid as tech preview
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/eks-hybrid-nodes.md
Labels: 4.5.c

#5350 docs: add safeguard against undefined pack versions DOC-1583
  plugins/packs-integrations.js
  static/packs-data/exclude_packs.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5335 docs: Update to encryption
  docs/docs-content/automation/palette-cli/palette-cli.md
  docs/docs-content/troubleshooting/automation.md
Labels: 4.5.c

#5338 chore: fix tolowercase issue the disable_security_integrations env var
  utils/cves/requests.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5366 docs: add nil guards to render pack versions DOC-1583
  src/components/PacksReadme/PacksReadme.tsx
  src/constants/packs.ts
  static/packs-data/exclude_packs.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5378 chore: disable vmo pack
  static/packs-data/exclude_packs.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5387 docs: README update
  CHANGELOG.md
  README.md
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5377 docs: PEM-6276 updated DNS and certificate prereqs
  docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
  docs/docs-content/vertex/system-management/ssl-certificate-management.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5397 docs: DOC-1573: StorageClass requirement for self-hosted clusters
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5418 docs: DOC-1579
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-addon-profile.md
  docs/docs-content/profiles/profile-customization.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5218 docs: add docs for cluster adoption
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/local-to-central.md
  docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
  docs/docs-content/user-management/palette-rbac/permissions.md
  docs/docs-content/user-management/palette-rbac/project-scope-roles-permissions.md
  docs/docs-content/user-management/palette-rbac/tenant-scope-roles-permissions.md
  static/assets/docs/images/clusters_edge_local-ui_local-to-central.webp
Labels: 4.5.c

#5417 docs: DOC-1577: Add projectName prereq to Palette Agent
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#5219 docs: add note about version constraint for PXK-E 1.31.1
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5433 docs: update Edge mgmt api 4.5.c
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: api-format, 4.5.c

#5435 docs: PE-5925
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
Labels: 4.5.c

#5436 fix: spelling
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5439 docs: update oss licenses
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: 4.5.c

#5442 chore: upgrade to 3.7.0
  package-lock.json
  package.json
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5441 docs: PEM-6747: Adding Palette OIDC limitation re: VM Migration Assistant
  docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md
Labels: 4.5.c

#5451 CI/CD Error Catching
  .github/actions/build-cached-cves/action.yaml
  .github/actions/build-cached-packs/action.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  Makefile
  README.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5450 docs: known issue for VM Migration Unknown state
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/vmo-issues.md
  docs/docs-content/vm-management/vm-migration-assistant/additional-configuration.md
Labels: 4.5.c

#5434 docs: validate-auth command for Palette CLI
  docs/docs-content/automation/palette-cli/commands/commands.md
  docs/docs-content/automation/palette-cli/commands/validate-auth.md
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Labels: 4.5.c

#5431 docs: add warning about pausing platform upgrades
  docs/docs-content/clusters/cluster-management/platform-settings/pause-platform-upgrades.md
Labels: auto-backport, backport-version-4-5

#5460 Remove Dependency Duplication
  package-lock.json
  package.json
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5461 docs: VMO known issue update after engineering review
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/vmo-issues.md
  docs/docs-content/vm-management/vm-migration-assistant/additional-configuration.md
Labels: 4.5.c

#5463 Update custom-link.md
  docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5

#5474 docs: Azure validation example and environment variable requirements
  docs/docs-content/automation/palette-cli/commands/validate-auth.md
Labels: 4.5.c

#5438 docs: add constraint on removing multiple nodes
  docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
Labels: auto-backport, backport-version-4-5

#5481 docs: add extra VMO oidc configuration and refactor guide
  docs/docs-content/vm-management/rbac/configure_OIDC.md
  docs/docs-content/vm-management/rbac/rbac.md
Labels: 4.5.c

#5473 docs: PE-5817: FIPS Agent Mode + Rocky Linux SELinux Limitations
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/troubleshooting/edge.md
Labels: 4.5.c

#5485 docs: fix redis link and indentation
  docs/docs-content/devx/services/service-listings/redis-db.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5493 docs: remove tech preview banner from microk8s PCP-4016
  docs/docs-content/integrations/kubernetes-microk8s.md
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5494 docs: add PXK known issue PCP-4015
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5502 docs: known issue for Palette agent 4.5.14 and custom path in user-data
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
Labels: auto-backport, backport-version-4-5

#5505 docs: Kubernetes upgrade failure due to agent mode known issue
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5464 docs: adding starts with constraint for fetch version branches DOC-1600
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  scripts/versions.sh
Labels: backport-version-4-0, auto-backport, backport-version-3-4, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5379 Sunset version 3.4 documenation
  versionsOverride.json
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5521 docs: add OS Type option for AKS worker node pools
  docs/docs-content/clusters/public-cloud/azure/aks.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5528 docs: modify release notes for cl
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5428 Docs CI Documentation
  .github/actions/build-cached-cves/action.yaml
  .github/actions/build-cached-packs/action.yaml
  .github/dependabot.yml
  .github/workflows/aloglia_crawler.yaml
  .github/workflows/api_format.yaml
  .github/workflows/backport.yaml
  .github/workflows/clean-up-report.yaml
  .github/workflows/clean-up-unused-images.yaml
  .github/workflows/container-prune.yaml
  .github/workflows/dependabot.yaml
  .github/workflows/eslint-test.yaml
  .github/workflows/gitleaks.yaml
  .github/workflows/image_optimizer.yaml
  .github/workflows/nightly-docker-build.yaml
  .github/workflows/packs-data.yaml
  .github/workflows/post_release.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  .github/workflows/url-checks.yaml
  .github/workflows/versions_robot.yaml
  .github/workflows/visual-comparison.yaml
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5537 ci: DOC-1614
  .github/workflows/release-preview.yaml
  README.md
  docusaurus.config.js
  scripts/update_docusarus_config.js
Labels: CI/CD, backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5482 docs: add show last update time flag DOC-1605
  .github/workflows/dependabot.yaml
  .github/workflows/nightly-docker-build.yaml
  .github/workflows/post_release.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-branch-pr.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/screenshot_capture.yaml
  .github/workflows/visual-comparison.yaml
  Makefile
  README.md
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5538 chore: first test cluster scanner
  .github/workflows/cluster-scanner-librarium.yaml
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5554 docs: DOC-1617
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-5

#5551 docs: PPD-1502: Airgap Virtual Cluster Guide
  docs/docs-content/clusters/cluster-groups/create-cluster-group.md
  docs/docs-content/clusters/clusters.md
  docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
  docs/docs-content/clusters/palette-virtual-clusters/palette-virtual-clusters.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
  docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
Labels: auto-backport, backport-version-4-5

#5562 docs: PE-5993
  docs/docs-content/clusters/cluster-management/platform-settings/pause-platform-upgrades.md
  docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md
Labels: auto-backport, backport-version-4-5

#5566 docs: DOC-1621: semodule_package --outfile flag
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#5568 docs: PCP-4049: MicroK8s 1.28 > 1.29 Known Issue for MAAS and AWS Clusters
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6

#5564 docs: fix third-party references in self-hosted airgap guides
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
  docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5576 docs: added clarification related to agent-modfe
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5

#5586 Include us-docker domain in proxy requirements
  docs/docs-content/clusters/clusters.md
Labels: auto-backport, backport-version-4-5

#5585 Update installer-reference.md
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  static/assets/docs/images/clusters_edge_edge-configuration_installer-reference_registry-mapping.webp
Labels: auto-backport, backport-version-4-5

#5569 docs: add delete node pool section
  docs/docs-content/clusters/cluster-management/cluster-management.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/cluster-management/reconfigure.md
  redirects.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5

#5589 docs: DOC-1634: Known Memory Leak Issue re: Calico and EC/PCG Clusters
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5

#5605 docs: update cilium parameter descriptions and agent mode steps for EKS Hybrid Nodes
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
Labels: auto-backport, backport-version-4-5

#5607 docs: DOC-1650: Edge Binary Download Link Fix
  docs/docs-content/spectro-downloads.md
Labels: auto-backport, backport-version-4-5

#5609 docs: DOC-1646: Update API Rate Limit for v1/cloudconfig Resources
  docs/api-content/api-docs/1-introduction.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6

#5610 docs: DOC-1653: Changing VMware vSphere Local Operations Permission to Subcategory
  _partials/permissions/_vsphere-permissions.mdx
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5
