Repository spectrocloud/librarium, pull requests merged in 2025-05, with the labels that each got.

#6630 doc: check cloud credentials before force-deleting a cluster
  docs/docs-content/clusters/cluster-management/remove-clusters.md
Labels: 4.6.c

#6631 doc: Assign AMI to node pool for EKS clusters
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6613 docs: fix more spelling mistakes DOC-1746
  docs/docs-content/automation/palette-cli/commands/import.md
  docs/docs-content/automation/palette-cli/commands/pcg.md
  docs/docs-content/automation/palette-cli/commands/pde.md
  docs/docs-content/automation/palette-cli/commands/vmo.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi.md
  docs/docs-content/clusters/cluster-groups/cluster-groups.md
  docs/docs-content/clusters/cluster-management/monitoring/deploy-monitor-stack.md
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/edge/architecture/architecture.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/share-auth.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
  docs/docs-content/clusters/edge/trusted-boot/keys/export-keys.md
  docs/docs-content/clusters/palette-virtual-clusters/migrate-virtual-clusters.md
  docs/docs-content/clusters/pcg/manage-pcg/configure-proxy.md
  docs/docs-content/clusters/pcg/manage-pcg/create-manage-node-pool.md
  docs/docs-content/clusters/pcg/manage-pcg/migrate_pcg.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
  docs/docs-content/clusters/public-cloud/azure/azure-cloud.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
  docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
  docs/docs-content/getting-started/additional-capabilities/additional-capabilities.md
  docs/docs-content/integrations/kubernetes-support.md
  docs/docs-content/registries-and-packs/adding-a-custom-registry.md
  docs/docs-content/registries-and-packs/adding-add-on-packs.md
  docs/docs-content/registries-and-packs/advanced-configuration.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge.md
  docs/docs-content/troubleshooting/kubernetes-tips.md
  docs/docs-content/troubleshooting/nodes.md
  docs/docs-content/troubleshooting/palette-upgrade.md
  docs/docs-content/user-management/palette-rbac/palette-rbac.md
  docs/docs-content/vertex/fips/fips.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
  docs/docs-content/vm-management/architecture.md
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
  docs/docs-content/vm-management/create-manage-vm/migrate-vm-to-different-node.md
  docs/docs-content/workspace/adding-a-new-workspace.md
  docs/docs-content/workspace/workspace-mgmt/backup-restore.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6587 docs: add documentation for resetting through SSH
  docs/docs-content/clusters/edge/cluster-management/reset-host.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6641 docs: fix final spellcheck error DOC-1746
  docs/docs-content/clusters/palette-virtual-clusters/migrate-virtual-clusters.md
Labels: auto-backport, backport-version-4-6

#6654 docs: add VM tools to deploy import guide DOC-1847
  docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6535 docs: DOC-1842: 4.6.x Patch Note Updates
  docs/docs-content/clusters/edge/cluster-management/remote-shell.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6671 doc: update VMO and vCluster airgap binary versions
  _partials/_additional-deployment-options.mdx
  docs/docs-content/downloads/palette-vertex/additional-packs.md
  docs/docs-content/downloads/self-hosted-palette/additional-packs.md
Labels: auto-backport, backport-version-4-6

#6673 docs: remove useful bots from block list
  scripts/ai_robots.txt
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6670 docs: DOC-1844: add kubectl command
  docs/docs-content/getting-started/azure/update-k8s-cluster.md
  static/assets/docs/images/getting-started/azure/clusters_cluster-management_deploy-cluster-profile-updates_palette-refresh.webp
Labels: backport-version-4-0, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6681 docs: add GCP cluster deletion known issue PEM-7576
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#6590 docs: GA Local UI.
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/delete-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/link-hosts.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/local-to-central.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/host-management/access-console.md
  docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md
  docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md
  docs/docs-content/clusters/edge/local-ui/host-management/edit-user-data.md
  docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
  docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md
  docs/docs-content/clusters/edge/local-ui/host-management/theming.md
  docs/docs-content/clusters/edge/local-ui/local-ui.md
Labels: 4.6.c

#6701 docs: add spectrocloud_macros breaking change and deprecation PLT-1743
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6683 docs: add requirements of pack.content.images
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/adding-add-on-packs.md
Labels: auto-backport, backport-version-4-6

#6727 doc: add Description field to the Team entity
  docs/docs-content/user-management/users-and-teams/create-a-team.md
Labels: 4.6.c

#6729 docs: do not use Palette Edge CLI for upgrade to 4.6.16 or later
  docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md
Labels: 4.6.c

#6730 docs: add ssh prereq
  docs/docs-content/clusters/edge/cluster-management/remote-shell.md
Labels: 4.6.c

#6724 docs: add patch release for 4.6.25 DOC-1878
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6742 docs: Airgap support for VM Migration Assistant (pack URL pending)
  _partials/_additional-deployment-options.mdx
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6734 How to send group names to Palette with Entra
  docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-optionalclaims.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-token-configuration.webp
  static/assets/docs/images/oidc-entra-id-images/user-management_saml-sso_palette-sso-with-entra-id-twooptionalclaims.webp
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6745 docs: warn harbor edge-native config pack new clusters only
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6604 docs: DOC-1757: Self-Hosted Anonymous SMTP Configuration
  _partials/self-hosted/_smtp.mdx
Labels: 4.6.c

#6746 DOC-1857 - Different resource groups selectable for private API server LBs (Azure IaaS)
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6757 docs: correction to EKS Hybrid Network diagram
  static/assets/docs/images/eks-hybrid_prepare-environment_prepare-network_network-example.webp
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6758 PCP-4421 - GKE repave release note due to CAPG upgrade
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6781 docs: Edge troubleshooting scripts
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
  docs/docs-content/clusters/edge/networking/vxlan-overlay.md
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/edge/_category_.json
  docs/docs-content/troubleshooting/edge/collect-support-bundles.md
  docs/docs-content/troubleshooting/edge/edge.md
  docs/docs-content/troubleshooting/troubleshooting.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6803 docs: fix code snippet DOC-1883
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6813 Divide troubleshooting scripts commands
  docs/docs-content/troubleshooting/edge/collect-support-bundles.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6796 docs: doc-1841 profile variable workflow update
  docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/modify-cluster-profile-variables.md
  static/assets/docs/images/profiles_cluster-profiles_create-cluster-profiles_define-profile-variables_modify-cluster-profile-variable-override-updated.webp
  static/assets/docs/images/profiles_cluster-profiles_create-cluster-profiles_define-profile-variables_modify-cluster-profile-variable-review-update-changes-updated.webp
Labels: 4.6.c

#6821 Add the information about the embedded script
  docs/docs-content/troubleshooting/edge/collect-support-bundles.md
Labels: 4.6.c

#6632 docs: DOC-1849: Additional Whitelabel Config Options
  _partials/self-hosted/_customize-interface.mdx
  docs/docs-content/enterprise-version/system-management/customize-interface.md
  docs/docs-content/vertex/system-management/customize-interface.md
  static/assets/docs/images/enterprise-version_system-management_customize-interface.webp
Labels: 4.6.c

#6834 PCP-4502 - Breaking change for CAPI v1.9.4 due to unwanted node drain
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6835 DOC-1892 - Pause Agent Upgrades suggestion for potential repaves
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6826 docs: 4.6.c swagger
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: api-format

#6779 docs: DOC-1809: CAPI Image Builder Pre- and Post-Install Scripts
  _partials/capi-image-builder/_download-capi-image-builder-repository.mdx
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi.md
Labels: auto-backport, backport-version-4-6

#6837 docs: update release scripts DOC-1863
  Makefile
  docs/docs-content/downloads/cli-tools.md
  scripts/release/generate-compatibility-matrix.sh
  scripts/release/generate-downloads.sh
  scripts/release/generate-kubernetes-palette-versions.sh
  scripts/release/generate-spectro-cli-reference.sh
  scripts/release/templates/compatibility-cli.md
  scripts/release/templates/compatibility-edge-cli.md
  scripts/release/templates/edge-cli.md
  scripts/release/templates/palette-cli.md
  scripts/release/templates/vertex-vmware-kubernetes-version.md
  scripts/release/templates/vmware-kubernetes-version.md
  scripts/release/utilities.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6754 doc: add Canonical K8s pack
  docs/docs-content/clusters/edge/architecture/architecture.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/arg.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/deployment-modes/agent-mode/architecture.md
  static/packs-data/packs_information.json
Labels: 4.6.c

#6820 docs: make changes to collapse versions and fields
  utils/cves/index.js
  utils/helpers/affected-table.js
  utils/helpers/affected-table.test.js
  utils/helpers/cveHelpers.js
  utils/helpers/revision-history.js
  utils/helpers/revision-history.test.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6743 Updated reference for tagsFromScript
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6856 docs: remove console log
  utils/cves/index.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6133 Add guide for locating VM disks (VMO)
  docs/docs-content/vm-management/create-manage-vm/locate-vm-disks.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6760 docs: add 4.6.c release notes DOC-1868
  docs/docs-content/architecture/orchestration-spectrocloud.md
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6855 docs: update the list of addOn types DOC-1894
  docs/docs-content/registries-and-packs/add-custom-packs.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6884 docs: adjust cloud type in the case that packs have cloudProvider=all DOC-1888
  plugins/packs-integrations.js
  utils/helpers/affected-table.js
  utils/helpers/revision-history.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6893 docs: Known Issue re: Velero Restores and emptyDir Volumes
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#6885 chore: remove duplicate entries in OS CVE
  utils/helpers/cveHelpers.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6376 PEM-7063 Imported cluster limitations
  docs/docs-content/clusters/imported-clusters/cluster-import.md
  docs/docs-content/clusters/imported-clusters/imported-clusters.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6908 docs: PEM-7063 changes for EKS Hybrid docs
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6883 docs: 4.6.26 Release Notes
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6922 docs: add limitation for appliance studio
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
  docs/docs-content/deployment-modes/appliance-mode/appliance-studio.md
Labels: 4.6.c

#6849 DOCS: DOC-1848 cluster dashboard
  docs/docs-content/clusters/cluster-management/kubernetes-dashboard.md
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_apply-profile.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_connect.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_select-dashboard-pack.webp
  static/assets/docs/images/clusters_cluster-management_spectro-kubernetes-dashboard_success.webp
  static/assets/docs/images/tutorials/cluster-dashboard-upgrade/clusters_cluster-management_cluster-dashboard_cluster-profile-example.webp
  static/assets/docs/images/tutorials/cluster-dashboard-upgrade/clusters_cluster-management_cluster-dashboard_update-available.webp
Labels: 4.6.c

#6924 Update add-gcp-accounts.md
  docs/docs-content/clusters/public-cloud/gcp/add-gcp-accounts.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6934 docs: remove missed harbor edit
  docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
Labels: auto-backport, backport-version-4-6

#6716 docs: content upload command
  docs/docs-content/automation/palette-cli/commands/content.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
  docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
  docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
Labels: 4.6.c

#6932 docs: update aditional packs DOC-1872
  _partials/self-hosted/_airgap-cluster-profile-packs.mdx
  _partials/vertex/_airgap-cluster-profile-packs.mdx
Labels: 4.6.c

#6940 PCP-4572 Warning for use of dynamic IP allocation for private Azure IaaS cluster LBs
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
Labels: 4.6.c

#6937 docs: update release notes
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6933 docs: add known issue PPD-1532
  docs/docs-content/release-notes/known-issues.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6944 docs: DOC-1903: Expanding Velero emptyDir Known Issue Workaround
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#6938 Troubleshooting scripts adjustments
  docs/docs-content/troubleshooting/edge/collect-support-bundles.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6958 docs: add extra permission
  _partials/permissions/_aws-eks-controller-policy.mdx
Labels: 4.6.c

#6956 docs: Adjust the embedded script information
  docs/docs-content/troubleshooting/edge/collect-support-bundles.md
Labels: 4.6.c

#6966 docs: allow custom logos in Docs DOC-1886 DOC-1893
  Makefile
  docs/docs-content/downloads/offline-docs.md
  docusaurus.config.js
  scripts/start-docker.sh
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6962 docs: add additional packs
  _partials/self-hosted/_airgap-cluster-profile-packs.mdx
  _partials/vertex/_airgap-cluster-profile-packs.mdx
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6963 docs: Clarify high availability and node roles in Canonical Kubernetes
  docs/docs-content/clusters/edge/architecture/architecture.md
  docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
Labels: 4.6.c

#6979 docs: adjust Portworx breaking change wording and ordering of Breaking Changes
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#6980 DOC-1933 / DOC-1890 - Update GCP Required Permissions
  docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6985 docs: Release note for updated GCP permissions
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6945 docs: DOC-1901 add bug fixes and improvements
  docs/docs-content/release-notes/release-notes.md
Labels: 4.6.c

#7005 docs: Known issue for PXKE clusters and FIPS agent mode for custom paths
  docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#7006 docs: PCP-4627: Known Issue re: Azure Gov Clusters
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#7008 docs: DOC-1938: Resolved Known Issue re: GCP 1.31.x and 1.32.x PXK Support
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#7009 docs: document k3s known issue
  docs/docs-content/release-notes/known-issues.md
Labels: 4.6.c

#7010 docs: DOC-1937: Airgap Self-Hosted VMware Upgrade - IP Claim Known Issue + Workaround
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/troubleshooting/enterprise-install.md
Labels: 4.6.c

#7002 docs: update several release documents
  _partials/_additional-deployment-options.mdx
  _partials/_palette-kubernetes-versions.mdx
  _partials/self-hosted/_install-next-steps.mdx
  _partials/self-hosted/_palette-vmware-kubernetes-versions.mdx
  _partials/vertex/_palette-vmware-kubernetes-versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/downloads/cli-tools.md
  docs/docs-content/enterprise-version/activate-installation/activate-installation.md
  docs/docs-content/enterprise-version/upgrade/upgrade.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/troubleshooting/enterprise-install.md
  docs/docs-content/vertex/activate-installation/activate-installation.md
  docs/docs-content/vertex/upgrade/upgrade.md
Labels: 4.6.c
