Repository spectrocloud/librarium, pull requests merged in 2025-03, with the labels that each got.

#5922 docs: add limitation to VM Migration Assistant for OVAs
  docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#5914 chore: Image commithook edit
  scripts/compress-convert-images.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5951 chore: try kapa fix
  docusaurus.config.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5959 docs: bump free-solid-svg-icons to 6.7.2
  .github/workflows/eslint-test.yaml
  package-lock.json
  package.json
Labels: dependencies, backport-version-4-0, auto-backport, javascript, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5925 docs: PCP-4154: Autoscaler Cleanup for Backports (Excludes Azure IaaS)
  docs/docs-content/clusters/cluster-management/node-pool.md
  docs/docs-content/clusters/data-center/openstack.md
  docs/docs-content/clusters/data-center/vmware/create-manage-vmware-clusters.md
  docs/docs-content/clusters/public-cloud/aws/create-cluster.md
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/clusters/public-cloud/azure/aks.md
  docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md
  docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
  docs/docs-content/getting-started/aws/scale-secure-cluster.md
  docs/docs-content/getting-started/azure/scale-secure-cluster.md
  docs/docs-content/getting-started/gcp/scale-secure-cluster.md
  docs/docs-content/getting-started/vmware/scale-secure-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5715 docs: automate permissions update DOC 1613
  .github/workflows/permissions-update.yaml
  _partials/permissions/_aws-control-plane-policy.mdx
  _partials/permissions/_aws-controller-policy.mdx
  _partials/permissions/_aws-deployment-policy.mdx
  _partials/permissions/_aws-dynamic-permissions.mdx
  _partials/permissions/_aws-ebs-csi-driver-policy.mdx
  _partials/permissions/_aws-eks-controller-policy.mdx
  _partials/permissions/_aws-nodes-policy.mdx
  _partials/permissions/_aws-static-permissions.mdx
  _partials/permissions/_azure-aks-dynamic-rg-sub-role.mdx
  _partials/permissions/_azure-aks-dynamic-sub-role.mdx
  _partials/permissions/_azure-aks-static-rg-sub-role.mdx
  _partials/permissions/_azure-aks-static-sub-role.mdx
  _partials/permissions/_azure-aks-static-vnet-role.mdx
  _partials/permissions/_azure-iaas-dynamic-rg-sub-role.mdx
  _partials/permissions/_azure-iaas-static-rg-sub-role.mdx
  _partials/permissions/_azure-iaas-static-vnet-role.mdx
  docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
  docs/docs-content/clusters/public-cloud/azure/required-permissions.md
  scripts/permissions-map.json
  scripts/permissions-sync.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#5974 docs: DOC-1707: RHEL Credentials No Longer Needed for Airgap Envs with CAPI Version 4.6.0
  docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
  docs/docs-content/byoos/capi-image-builder/config-reference.md
Labels: auto-backport, backport-version-4-6

#5902 chore: prevent tutorial categories from being highlighted DOC-1587
  src/css/dark-mode.scss
  src/css/light-mode.scss
  src/theme/DocSidebarItem/Category/index.js
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6002 docs: remove duplicated PCG IP address section DOC-1702
  docs/docs-content/clusters/pcg/deploy-pcg/maas.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6000 fix: case sensitve uri argument ProjectUid
  docs/api-content/api-docs/2-samples.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6050 Fix gitleaks issues
  .gitleaksignore
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6071 docs: Add Edge mgmt API for 4.6.a
  docs/api-content/api-docs/edge-v1/emc-api.json
Labels: api-format, 4.6.a

#6064 docs: remove ansible references
  docs/docs-content/clusters/clusters.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  docs/docs-content/registries-and-packs/registries-and-packs.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6049 Remote shell
  docs/docs-content/clusters/edge/cluster-management/remote-shell.md
  docs/docs-content/user-management/palette-rbac/permissions.md
  docs/docs-content/user-management/palette-rbac/project-scope-roles-permissions.md
  docs/docs-content/user-management/palette-rbac/tenant-scope-roles-permissions.md
  static/assets/docs/images/clusters_edge_cluster-mgmt_remote-shell.webp
Labels: 4.6.a

#6040 docs: debug unused images pipeline
  .github/workflows/clean-up-unused-images.yaml
  scripts/find-unused-images.sh
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6108 docs: DOC-1747: Remove Remaining Tencent/TKE References
  docs/docs-content/clusters/cluster-management/platform-settings/cluster-auto-remediation.md
  docs/docs-content/clusters/imported-clusters/migrate-full-permissions.md
  docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
  docs/docs-content/clusters/public-cloud/public-cloud.md
  docs/docs-content/integrations/kubernetes.md
  docs/docs-content/registries-and-packs/add-custom-packs.md
  src/components/PacksTable/PacksTable.tsx
Labels: auto-backport, backport-version-4-6

#6079 docs: EKS Kubernetes pack additional details
  docs/docs-content/clusters/public-cloud/aws/eks.md
  docs/docs-content/integrations/kubernetes-eks.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6088 docs: DOC-1714: 4.6.a OS Licenses
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses-index.md
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: 4.6.a

#6123 docs: update flags in oras login commands
  docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
  docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
  docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6122 docs: PEM-7190: Troubleshooting to Remove nats-system Namespace
  docs/docs-content/troubleshooting/nodes.md
Labels: 4.6.a

#6132 docs: adjust STS pages DOC-1751
  _partials/self-hosted/_aws-sts-config.mdx
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6118 docs: Compatibility matrix 6 a
  _partials/self-hosted/_kubernetes_palette_versions.mdx
  docs/docs-content/automation/palette-cli/install-palette-cli.md
  docs/docs-content/clusters/pcg/pcg.md
  docs/docs-content/component.md
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
  docs/docs-content/release-notes/announcements.md
  docs/docs-content/release-notes/known-issues.md
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/spectro-downloads.md
Labels: 4.6.a

#6165 docs: DOC-1740: Self-Hosted SMTP Configuration Updates
  _partials/self-hosted/_smtp.mdx
  docs/docs-content/enterprise-version/system-management/smtp.md
  docs/docs-content/vertex/system-management/smtp.md
Labels: auto-backport, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6183 docs: add 1.32 to known issues
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-6

#6182 docs: virtual cluster guidance for cluster mode
  docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6170 docs: DOC-1756: Release Notes - 4.6 Patch
  docs/docs-content/release-notes/release-notes.md
Labels: auto-backport, backport-version-4-6

#6193 docs: add registry mapping rules known issue DOC-1763
  docs/docs-content/release-notes/known-issues.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6198 docs: DOC-1749: Updating OS Licenses for 4.6 Branch
  docs/docs-content/legal-licenses/oss-licenses-index/oss-licenses.md
  docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
Labels: auto-backport, backport-version-4-6

#6202 docs: update spectro cli version
  docs/docs-content/registries-and-packs/spectro-cli-reference.md
Labels: auto-backport, backport-version-4-6

#6207 docs: Edge Tutorial Updates
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
  docs/docs-content/tutorials/edge/deploy-cluster.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6222 docs: Removing Additional Earthly Link from VirtualBox Edge Tutorial
  docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6206 docs: modify hardware requirements
  docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
  docs/docs-content/clusters/edge/hardware-requirements.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6205 docs: add registry credentials to user data example
  docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6131 docs: add unique stage names for cloud init
  docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
  docs/docs-content/clusters/edge/edge-configuration/edge-configuration.md
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
Labels: auto-backport, backport-version-4-5, backport-version-4-6

#6235 docs: DOC-1773: Nginx Security Advisory
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
  docs/docs-content/security-bulletins/security-bulletins.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6241 docs: update cves links
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6245 docs: add direct links
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6253 docs: DOC-1782: Fixing Portworx Spelling
  docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
Labels: backport-version-4-0, auto-backport, backport-version-4-1, backport-version-4-2, backport-version-4-3, backport-version-4-4, backport-version-4-5, backport-version-4-6

#6250 docs: DOC-1770: 4.6.18 Release Notes
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-6

#6264 docs: 4.6 Nginx Security Updates
  docs/docs-content/release-notes/release-notes.md
  docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Labels: auto-backport, backport-version-4-6
